### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by steida** [firebase/firebaseui-web#1]
I guess it's planned, does it?

**Comment by TMSCH** [comment]
Hi Steida,

It is indeed on the roadmap! I will keep you updated through this thread.

**Comment by Folyd** [comment]
+1

**Comment by NeoLegends** [comment]
Any news?

**Comment by joshwcomeau** [comment]
This is super important! Without NPM distribution I can't really include it in a devtool I'm building, since I don't want to tell my users to have to add script/style tags to their HTML.

**Comment by orouz** [comment]
+1

**Comment by bojeil-google** [comment]
Quick update on the npm firebaseui-web: Now that the SDK has been open sourced, we are actively working on the npm package distribution for it. It will be coming soon.

**Comment by TMSCH** [comment]
npm support has been added: https://github.com/firebase/firebaseui-web#npm-module
