### ISSUE TITLE
Facebook provider does not contain all public_profile data

### ISSUE THREAD

**Issue by rossthedevigner** [firebase/firebaseui-web#100]
When I look at the documentation for the the data returned as part of the `public_profile` [Public Profile](https://developers.facebook.com/docs/facebook-login/permissions/#reference-public_profile) I don't see some of the following information: `gender`, `locale`, `timezone`, `age_range`.

Do I have to make a secondary request to get that data?

**Comment by bojeil-google** [comment]
Yeah, you can use the Facebook access token returned after sign-in to query this data from Facebook.

**Comment by rossthedevigner** [comment]
@bojeil-google That's what I figured, but wanted to make sure I wasn't missing something obvious. Thanks!

**Comment by choopage** [comment]
Hi @bojeil-google  and @rossthedevigner, how do we query this data from Facebook? Any documentation on this?

**Comment by bojeil-google** [comment]
This may be helpful: https://stackoverflow.com/questions/46572065/use-access-token-provided-by-firebase-facebook-auth-to-access-facebook-api
We also plan to expose `result.additionalUserInfo.profile` in FirebaseUI-web.
