### ISSUE TITLE
custom authentication provider support.

### ISSUE THREAD

**Issue by muhammadnasr** [firebase/firebaseui-web#101]
I wonder if Firebase custom authentication provider is supported or not?
I didn't find it in the example

**Comment by bojeil-google** [comment]
Hey @muhammadhassan,
Custom auth providers are not supported by firebaseui. They would require a lot of code customization per provider and backend server logic.
Check this repo for guidance on this: https://github.com/firebase/custom-auth-samples/tree/master/instagram
