### ISSUE TITLE
Will Google login soon not be supported?

### ISSUE THREAD

**Issue by simonness** [firebase/firebaseui-web#1016]
I recently received the following email from GoogleDevelopers-noreply@google.com:

> Hello Google Developer,
> 
> We're writing to let you know that we detected the use of an embedded webview in requests to Google's OAuth 2.0 authorization endpoint in the past 120 days associated with one or more of your OAuth client IDs listed in this email.
> 
> Any affected authorization endpoint requests will be blocked with a `disallowed_useragent` error starting **July 24, 2023**. Affected requests to our authorization endpoint will display a [user-facing warning message](https://notifications.google.com/g/p/APHC3co144T-A7-CkMzuFdQMuZuhhFK4D8orvAfF5m_J_lAJAS2ymsZT1Vp9G069u3SkcdUiKy1opBTLde3g8_9bDiZbpgm67rpomHb-VH_m8rOSkgztCz_Hb9d_57ZhkRbI3UEfRbEg7lEJhSIFSgWBDNdKlDT3_W8yvZ3mMww_2wPVwV7StdT6SAuzHnCttD2gK0iyttdxxF7ngZ9IHjcxXKUT3OJ4EObXbE2SWBOfHsVgCoBqi4E9QWuSektewnSWHrIbc0JvdrObYKvm54yBx1AAzMRJCjFj6_IMIUWGyTFudyRWAJNXDoUTD3IdymueYxBvWw) starting in May until **July 24, 2023**.
> 
> **What do you need to know?**
> Embedded webview libraries are highly customizable, which can expose Google's login and account authorization pages to potential "man-in-the-middle" attacks. [Google's OAuth 2.0 "Use secure browsers" policy](https://notifications.google.com/g/p/APHC3cqZpMHVFZmP76HurtCyEBfvS4GEQD_XAvSb1Y4UQIyiWv4dZCdOyQV5fBC5H9TH8dgG4NJNNb1o3gMTSLFwEdcRGfCNZs-DDyOLz2mWXyOC8Txwbg2n6WOj3o0uDKOu6N2p4iJG4etOvUl-0bz_XRAg-qcZgniwbdFua7sYs5j7XYUdxf7pn2da9MHVrjL37w5aZB2SfODsNhJSO8DO-VcdZc1gLbVAd7cCxAvxciyn7Qq1J3QVDA) helps us protect users from these and other types of attacks.
> 
> Examples of affected embedded webview libraries include `android.webkit.WebView` on Android and `WKWebView` on iOS or macOS.
> 
> **What do you need to do?**
> Review our June 2021 Google Developers blog post, [Security changes to Google's OAuth 2.0 authorization endpoint in embedded webviews](https://notifications.google.com/g/p/APHC3crQUk0A-rh6B_f3o7rM2WBI8EEHaySFT6YgKqQqwtmvqSExjv4eVzcLvgUjeEI9rdeTKdV0-ouGFeIXFW2oNCvGJZ9zfKHYZnB-lBQguq0W2sDcQpWUpCSwLbgjV7PP_bBhQyz15tQAzTk5ZlE71a9YlDp5yX7joxy4e7shiYvltolVEIM7zNgaCdNgHAyRFIicM8Avn3w9MTMaWriGMbJbZLxKPh0tZtxliSVLNqkNaZDs5uyLi96GtbfnQ3aGFZqkIsBIOT8uNeT-jUOdnBeC3nLD5bpz0WFRLG7U3NosETk), to determine potential next steps.
> Consider how enterprise and educational users might be impacted by embedded webviews in your app(s).
> If you are able to modify the authorization requests of your app, you can choose to [test your application for compatibility](https://notifications.google.com/g/p/APHC3cp6wZaXPyDlzH88PX60lFflqAFRa6ebSEW_HzO5y4UWKrOX-X3i1atvSUvzfEFf6cEFGiIku_Yf3NVsTjsrzKIr0lROvjUA6DxQvb70nic8I7SDEW2RdwyKSS7t5wwADaUV1c2XAJP-ct4t4bkdB1xD1Ku-_HpjJsIZNsLoq3tzwY4F1dwhVhyadhEQkV8nfXHfo2XIGJWc8fVM6EjmnKNnMYk37-3YprVtWNs6I1DnELPSvZOc_Ovgz6IuVp_DVgnz4DRNXbpO0EWL02WAcv3TzZENLipL1xdV8hexcH7WJh5KFpkFag) with our "Use secure browsers" policy after making the necessary changes.
>
> **Note:** Suppression of the user-facing warning message is not supported.

The project id quoted is the Firebase Auth Id used on my project, so presume it relates to the use of this library when using login with Google. Will this library be updated to take in account of these changes?

**Comment by brandonrich** [comment]
I got this same message. Even if the project is dead, I need to understand the scope and what to do. We do not knowingly use embedded webviews, and we have no native mobile app, so does this mean that firebaseui is somehow in violation of this policy? Or does it only mean one of our end users may be using an unsupported browser? How can I test today whether our use of firebaseui will fail in July, and does anyone think it is viable/necessary to implement login using the firebase library only?

**Comment by jobizzness** [comment]
If a user is browsing your website from say TikTok web view or Facebook. This might be a problem

**Comment by prameshj** [comment]
Firebase UI Web does not use webviews. I believe this issue occurs if an end user tries to access the login page from an embedded browser, like Android webView instead of using the browser app on their mobile device.

> does this mean that firebaseui is somehow in violation of this policy? Or does it only mean one of our end users may be using an unsupported browser? How can I test today whether our use of firebaseui will fail in July, and does anyone think it is viable/necessary to implement login using the firebase library only? 

FirebaseUI is not violating this policy, since this policy depends on the useragent of requests to the UI. Regarding how you can test - I think if you try it from a few different browsers/apps that are allowed to access the UI, you will see a warning message if any of those user agents are unsupported (like the email calls out - https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html#warning-message).

https://github.com/firebase/firebase-js-sdk/issues/4421 was a related bug some folks observed when using an unsupported user agent.
