### ISSUE TITLE
The documentation is lacking information on using Federated Linking

### ISSUE THREAD

**Issue by ZerothLaw** [firebase/firebaseui-web#102]
I've tried looking through the source code, but there is no explanation of how to setup Firebase AuthUI to automatically or programmatically link accounts together.

**Comment by bojeil-google** [comment]
FirebaseUI automatically links accounts if there is an email conflict (singled account per email setting). You can test it by signing in with a Google email first and then sign in with a facebook account that has the same email. The linking flow should be triggered. However, FirebaseUI does not handle manual linking. You will have to do that yourself.

**Comment by ZerothLaw** [comment]
Ah, I see! Nevermind, closing this.
