### ISSUE TITLE
Create account window bug

### ISSUE THREAD

**Issue by Denisandrik** [firebase/firebaseui-web#1042]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Ventura 13.5.2
  * Browser version: Google Chrome Version 116.0.5845.187
  * Firebase UI version: 6.1.0
  * Firebase SDK version: 10.3.0

### [REQUIRED] Describe the problem

Incorrect "Create account" window when log in using email.

#### Steps to reproduce:
Sign in with email => enter the new email => look at "First & last name" field.
<img width="360" alt="Screenshot 2023-09-25 at 17 32 09" src="https://github.com/firebase/firebaseui-web/assets/33481712/0398b563-b3c4-4ee6-8f55-236e1ceb0a4f">

**Comment by jhuleatt** [comment]
Hi @Denisandrik, that field appears to be working in the live demo (https://fir-ui-demo-84a6c.firebaseapp.com/). I wonder if there is a CSS class name collision going on here? If you open the live demo, does the first&last name field display correctly for you?

**Comment by Denisandrik** [comment]
Hi @jhuleatt  Yes, you are right, there seems to be a conflict in my CSS code. Demo works correct. Sorry for noise, my mistake.
