### ISSUE TITLE
MFA Issue - internal server error 500

### ISSUE THREAD

**Issue by thekennysong** [firebase/firebaseui-web#1052]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase UI version: _____
  * Firebase SDK version: _____

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by jhuleatt** [comment]
Hi @thekennysong, a 500 error from the Auth backend might suggest an issue with Firebase Auth itself or how it is configured for your Firebase project, and is not likely related this library. Please [contact support](https://firebase.google.com/support/troubleshooter/report/bugs) instead. They should be able to help get this resolved.

I'm going to close this issue, but if you do think it could be related to FirebaseUI please open a new issue and fill out the issue template with the requested details of your setup.
