### ISSUE TITLE
FirebaseUI compatibility with modular SDK

### ISSUE THREAD

**Issue by TKELKAR123** [firebase/firebaseui-web#1058]
**Is your feature request related to a problem? Please describe.**
It is v tricky to have to deal with the backwards compatibility of v9 modular SDK working with the firebaseUI for authentication. 

**Describe the solution you'd like**
Enable a new version of firebaseUI to avoid having to create workarounds

**Describe alternatives you've considered**
Using the compat packages but you have explicitly stated in your docs that the goal should be to avoid writing code that is compat code, and moving to the new SDK. Given this is the case, the firebaseUI should be updated to enable this to avoid any compat code being written.

**Additional context**
If there is some way to use firebaseUI for authentication in such a way that minimises using compat code, and an easy way to migrate to the new library when it is launched for the v10 modular SDK, please let me know. That way, using firebaseUI reduces the risk of not being able to upgrade to v10 of the SDK when it's launched.

**Comment by jhuleatt** [comment]
Hi @TKELKAR123, please see https://github.com/firebase/firebaseui-web/issues/1055#issuecomment-1839365697 for some more information on this. That is the primary issue to discuss modular SDK support.
