### ISSUE TITLE
How can I remove email scope and add YouTube read scope and profile scope ONLY?

### ISSUE THREAD

**Issue by hughred22** [firebase/firebaseui-web#107]
Related to this StackOverflow thread: https://stackoverflow.com/questions/42586907/how-to-remove-email-scope-and-add-only-youtube-readonly-scope-using-firebase-goo

I only find provider.addScope('...') but there is no way to do remove scope...How to remove the default email scope or just customized my scope?

**Comment by TMSCH** [comment]
Hi @hughred22, I replied to your question on SO!

**Comment by hughred22** [comment]
Thanks! But I want a native Firebase solution. I don't want to roll out my own google auth. I want to use FiREBASE. I just need a simple Firebase solution that remove the email scope.

**Comment by TMSCH** [comment]
Unfortunately, this is currently not possible with a pure Firebase solution.
