### ISSUE TITLE
scope 'user_friends' not returning friends on user object

### ISSUE THREAD

**Issue by stuart-williams** [firebase/firebaseui-web#109]
I have set up several Facebook test user roles and the relationships between them, however when I use the scope 'user_friends' nothing is returned.

My ui config is pretty standard...

```js
{
  signInSuccessUrl: '/',
  signInOptions: [{
    provider: firebase.auth.FacebookAuthProvider.PROVIDER_ID,
      scopes: [
        'public_profile',
        'email',
        'user_friends'
    ]
  }]
}
```

I've had this working previously with Passport so kinda stumped...

**Comment by bojeil-google** [comment]
You would only get back the Facebook access token. You would need to query the facebook endpoint with that access token to get the additional info.
