### ISSUE TITLE
Don't get  Emails from Firebase (Email Confirm, Password Reset...) on some Mail Provider

### ISSUE THREAD

**Issue by DonatPlayZ** [firebase/firebaseui-web#1093]
Hello,
Currently im into setting up my Webpage with an Login Form. I created everything and it works like it should.
But then i tried to signup with a new email (@web.de) Mail, and i dont get any Mail ( no register, no password forgot) 
I also tried with @gmail.com, @aol.com this works like it should. I only dont get a single mail on 3 diffrent @web.de mails. ( Yes, i waited like 1 day and i also checked my SPAM!) 

Atm i dont have a custom domain added to firebase (still pending on verfication) is there something i miss? I don't think the Problem is my script bc it works on diffrent mail. But i will still add it here! 

`document.addEventListener('DOMContentLoaded', function () {
    const signupForm = document.getElementById('signup-form');
    const googleSignupButton = document.getElementById('google-signup');
    const auth = firebase.auth();

    signupForm.addEventListener('submit', function (e) {
        e.preventDefault();

        const email = document.getElementById('email').value;
        const password = document.getElementById('password').value;
        const confirmPassword = document.getElementById('confirm-password').value;

        if (password !== confirmPassword) {
            alert("Passwörter stimmen nicht überein!");
            return;
        }

        // Benutzer registrieren
        auth.createUserWithEmailAndPassword(email, password,)
        .then((userCredential) => {
            // E-Mail Verifizierung senden
            userCredential.user.sendEmailVerification()
                .then(() => {
                    alert('Verifizierungs-E-Mail wurde gesendet. Bitte überprüfen Sie Ihren Posteingang.');
                    firebase.auth().signOut();
                    location.href = '/signin.html';
                })
                .catch((error) => {
                    console.error('Fehler beim Senden der Verifizierungs-E-Mail:', error);
                });
        })
        .catch((error) => {
            console.error('Fehler bei der Registrierung:', error);
        });
});` 

Maybe someone have same Problems or know a fix? would be happy to get Help! bc im Stuck!

**Comment by bhagat-abhishek** [comment]
@DonatPlayZ Hey is your issues resolved, or you are still stuck with the issue.

**Comment by DonatPlayZ** [comment]
> @DonatPlayZ Hey is your issues resolved, or you are still stuck with the issue.

Hey, thank you for your Comment! It already work now! The Problem was the Firebase Domain. With custom Domain it work!

**Comment by bhagat-abhishek** [comment]
great
