### ISSUE TITLE
Firebase Service named 'auth' already registered

### ISSUE THREAD

**Issue by drixie** [firebase/firebaseui-web#11]
Go this in console.log

firebase.js:30 Uncaught Error: Firebase Service named 'auth' already registered.

I'll try to figure this out, but I'm just putting it here in case anyone else sees this issue

**Comment by bojeil-google** [comment]
Are you double including the library src file?

**Comment by Hongbo-Miao** [comment]
Got same error, in my case, I am using both

```
import '@firebase/auth';
import firebase from 'firebase/app';
```

in my client.

So I actually have both in my **package.json**,

    "@firebase/auth": "0.11.3",
    "firebase": "5.9.3",

After I remove `@firebase/auth` from **package.json**, the error is gone.

Seems `firebase` package includes `@firebase/auth` already.
