### ISSUE TITLE
Cordova Password Authentication, Operation not supported warning.

### ISSUE THREAD

**Issue by dvcroft** [firebase/firebaseui-web#111]
I know that provider (google, fb, etc.) sign in is not currently supported from a Cordova app, but my understanding is that email/password is supported.

When I call ui.start() a warning message pops up, "This operation is not supported in the environment this application is running on. “LOCATION.PROTOCOL” must be http, https or chrome-extension and web storage must be enabled."

If I dismiss the message and continue things seem to work.

How do I get rid of the message?

Here is how I call start:

`       var user = firebase.auth().currentUser;
        console.log("authenticate called");

        if (user) {
            alert("Already signed in");
        } else {
            var uiConfig = {
                callbacks: {
                    signInSuccess: function(currentUser, credential, redirectUrl) {
                        alert("Successful sign in");
                        return false;
                    }
                },
                signInOptions: [
                    firebase.auth.EmailAuthProvider.PROVIDER_ID
                ],
                signInFlow : 'popup',
                // Terms of service url.
                tosUrl: 'http://www.qualint.com'
            };

            // Initialize the FirebaseUI Widget using Firebase.
            var ui = new firebaseui.auth.AuthUI(firebase.auth());
            // The start method will wait until the DOM is loaded.
            ui.start('#firebaseui-auth-container', uiConfig);
`

**Comment by bojeil-google** [comment]
I believe getRedirectResult is getting called underneath regardless and this is why this error is happening (this API is not supported in this environment). We should check when no OAuth provider is enabled not to bother and call that.

**Comment by dvcroft** [comment]
That would be great. Thanks.

**Comment by bojeil-google** [comment]
This should be fixed already in release 1.0.1. As a side note, OAuth sign-in is now also supported for Cordova apps in release 2.1.1.

**Comment by dvcroft** [comment]
That is great news about OAuth, thanks!

On Jun 8, 2017 8:04 PM, "bojeil-google" <notifications@github.com> wrote:

This should be fixed already in release 1.0.1. As a side note, OAuth
sign-in is now also supported for Cordova apps in release 2.1.1.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/firebase/firebaseui-web/issues/111#issuecomment-307275285>,
or mute the thread
