### ISSUE TITLE
How to Return from Terms of Service in Cordova app

### ISSUE THREAD

**Issue by dvcroft** [firebase/firebaseui-web#112]
When a user clicks on the terms of service link in a Cordova app, how can they be returned to the sign in screen they had already started? When the Android back button is pressed, the sign in display is gone.

**Comment by bojeil-google** [comment]
FirebaseUI is currently only optimized for a browser environment. As signInWithRedirect for OAuth providers is not yet supported by Firebase Auth, FirebaseUI-web remains incompatible in general with Cordova. 
I have not tried it, but you can try passing the tos url as a javascript function and use  inappbrowser plugin to open in a browser:
javascript:cordova.InAppBrowser.open(...)
When the user goes back, they would go back right where they left in the password sign up screen.

**Comment by dvcroft** [comment]
Thanks for the response. I tried your suggestion but unfortunately the sign in widget disappears after the email is entered.

I have a solution though. If I put in "" as the toURL parameter the Terms of Service Link is not displayed. I can display my terms of service before starting the sign in process or something.

**Comment by bojeil-google** [comment]
Hey @rtm, this issue was opened a while back before OAuth sign in was supported for Cordova. We are in much better shape now.
We are making some changes to how the ToS is displayed to be more compliant with GDPR. Would making the ToS a callback function (to display this within the app) instead of a URL string simplify this for you?
Note even if you use a link to a browser, you can user [Firebase dynamic links](https://firebase.google.com/docs/dynamic-links/) to redirect back to your app from the ToS page.

**Comment by rtm** [comment]
@bojeil-google Thanks for your reply. Actually, initially I imagined the ToS link should be a URL relative to the app, and specified it as `"/user/tos"`, a route I had implemented in my Angular app, and that didn't work at all. Once I figured it should be a web link, I tried that, and it came up just fine, but when I hit the hardware back button it was unable to navigate back to the app. Even if I provided a firebase dynamic link as you suggest as a way to exit from the ToS, it would not solve the problem of people hitting the hardware back button.

The callback sounds like an ideal solution. Of course, what you have now is not really a very good solution to the overall ToS problem anyway. For instance, people signing up with FB should probably  see the ToS too, but as understand it at present the ToS display is limited only to the email/password flow. So many folks might end up implementing their own ToS approach anyway, which would be necessary in any case for people really taking this seriously and wanting users to have to re-accept the ToS when the legal folks update it etc. That particular case would really benefit from an addition to the basic Firebase auth user model, which would be to add an "acceptedTosOn" timestamp. That would let people with a simpler user model without their own user collection in the database to handle ToS managment without having to set up their own user table.

**Comment by bojeil-google** [comment]
We are revamping how and when the ToS is displayed. We will make sure it is displayed before any sign in/up method and not just email/password or phone as we currently do:
https://github.com/firebase/firebaseui-web/issues/396
We'll take your input into consideration. Your feedback would be very helpful when this change is ready.

**Comment by wti806** [comment]
[V3.4.0](https://github.com/firebase/firebaseui-web/releases/tag/v3.4.0) is released with the ability to provide callbacks for Terms of Service and Privacy Policy. So that the onClick callback of tos/pp link can be customized.
