### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by PavelPZ** [firebase/firebaseui-web#114]
It will be nice to provide e.g.
```https://github.com/firebase/firebaseui-web/tree/master/index.d.ts``` file.

The first version could look like:

```
declare module "firebaseui" {

  import firebase from 'firebase';

  interface IConfig {
    callbacks?: ICallbacks;
    credentialHelper?: auth.CredentialHelper;
    queryParameterForSignInSuccessUrl?: string;
    queryParameterForWidgetMode?: string;
    signInFlow?: 'redirect' | 'popup';
    signInOptions: Array<ISignInOption | string>;
    signInSuccessUrl?: string;
    tosUrl: string;
  }
  interface ICallbacks {
    signInSuccess?: (currentUser: firebase.User, credential?: firebase.auth.AuthCredential, redirectUrl?: string) => boolean;
    uiShown?: () => void;
  }
  interface ISignInOption {
    provider: string;
    scopes?: Array<string>;
    requireDisplayName?: boolean;
  }

  namespace auth {
    enum CredentialHelper { ACCOUNT_CHOOSER_COM, NONE }
    class AuthUI {
      constructor(auth: firebase.auth.Auth);
      start(containerCSSselector: string, config: IConfig);
    }
  }
}
```

**Comment by ErikSchierboom** [comment]
Any progress on this issue? Would be great to have typings! Especially since firebase itself already provides typings.

**Comment by bojeil-google** [comment]
We're swamped at the moment with a lot of feature work. We welcome external contributions on this.

**Comment by rtm** [comment]
@bojeil-google I know you're busy and you're doing a great job--thank!--but IMHO TS definition files should ship by default. Meanwhile, I've hacked the above to provide a `void` return type for `start` to make TS happy when in strict mode, a `GOOGLE_YOLO` constant, `disableAutoSignIn`, etc.

**Comment by laughinghan** [comment]
> Without them, you're essentially saying that no-one using this in a TS environment can follow the TS best practices of `strict: true`, unless I'm missing something. 

@rtm `strict: true` prohibits you from using implicit `any`, but you can still set explicitly declare things as `any`.

**Comment by Methodician** [comment]
Just checking in way later, since I'm using Angular and have decided to pull out of AngularFire2 after being burned a couple times... Are there typings? Are we stuck hacking around if we use TS?

**Comment by bojeil-google** [comment]
We have added the typescript definitions in [v3.1.0](https://github.com/firebase/firebaseui-web/releases/tag/v3.1.0). I haven't had a chance to confirm they work as expected.

**Comment by donmahallem** [comment]
@bojeil-google I do have v3.1.0 installed but it does look like the index.d.ts file isn't included if I look into the node_modules folder.

**Comment by bojeil-google** [comment]
You are right. We actually added closure externs too, but neither is available. It is likely something related to the deployment script we use. We apologize about that. We'll fix it in the next release.

**Comment by bojeil-google** [comment]
Hmm, I think we simply forgot to include the additional files here: https://github.com/firebase/firebaseui-web/blob/master/package.json#L5
If so, it should be an easy fix.

**Comment by donmahallem** [comment]
Great. Thanks for the update. In the meantime I copied the file manually from the repo and works as expected.

**Comment by bojeil-google** [comment]
Cool. Thanks for confirming. The fix is on the way: https://github.com/firebase/firebaseui-web/pull/438

**Comment by bojeil-google** [comment]
The fix is out: https://github.com/firebase/firebaseui-web/releases/tag/v3.1.1
I checked that `index.d.ts` is in there.

**Comment by wti806** [comment]
@jsshapiro The issue has been reported in issue #445. The fix will be in next release next week. Thanks
