### ISSUE TITLE
User cannot sign in with password if Google account is linked

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebaseui-web#118]
Firebase supports multiple auth methods. Users should be able to sign in with their email and password if they choose, even if they also have a Google account associated with their account. Currently, if you type in an email address whose account is linked to Google, you have no option to enter your password.

It would be more intuitive if a user could see their linked providers after entering the email, but still have the option of using their password.

**Comment by bojeil-google** [comment]
It is usually easier to sign in with a federated account as you avoid the need to type in a password in many cases (user would already be signed in). This issue is magnified in mobile devices. 
Perhaps we can offer this as a configurable option. Will relay this to relevant parties.

**Comment by bojeil-google** [comment]
I just checked. Actually, if you have a password provider and google provider linked and click sign in with email, you will be presented with the password sign in screen. 
https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/handler/common.js#L924

**Comment by mhuebert** [comment]
Does FirebaseUI delete the password of an account the first time you sign in with Google via the same email address? I am 100% certain that in accounts that have a password, you can keep using the password until you sign in to Google once, and then it requires you to use Google. 

I just verified this again on the demo site: https://fir-ui-demo-84a6c.firebaseapp.com/?mode=select

1. Create an account using email+password of a Gmail account
2. Sign out
3. Click 'sign in with Google' and select the same email as above
4. Sign out
5. Try signing in via email again. I see:

<img width="428" alt="screenshot 2017-04-04 11 07 31" src="https://cloud.githubusercontent.com/assets/165223/24649361/13672c80-1927-11e7-8d23-f671d9fbc081.png">

**Comment by TMSCH** [comment]
@mhuebert I replied on the issue you opened.
