### ISSUE TITLE
User cannot cancel or navigate back after clicking "Sign in with Email"

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebaseui-web#119]
After clicking "Sign in with Email" (not using AccountsChooser), the user has no way of clicking 'cancel' or 'back' to go back and choose a different authentication method. (Other authentication methods are also hidden at this stage.)

**Comment by TMSCH** [comment]
We don't provide any cancel button in any of the views indeed, however, the back button of the browser should work. Isn't it the case?

**Comment by mhuebert** [comment]
No, the back button does not work. If I open a blank tab and navigate to my sign-in screen, click to sign in via email, and then click 'Back', my browser goes back to the blank screen.

(this does not apply if you are using AccountChooser)

**Comment by TMSCH** [comment]
Oh, that's a bug indeed. Thanks for raising it.

**Comment by mhuebert** [comment]
Thanks for shipping this in the release so fast!

Minor note, the 'Cancel' button shows up even when the email window has been displayed automatically on widget start, & there's nothing to go 'back' to (when only the email provider is enabled)

**Comment by bojeil-google** [comment]
Yes I am aware of that. It's a low priority improvement, I can fix later. It only happens when email is only enabled and accountchooser.com is disabled.

**Comment by bojeil-google** [comment]
We can keep this issue open until it is fixed.

**Comment by bojeil-google** [comment]
This should be fixed in https://github.com/firebase/firebaseui-web/releases/tag/v2.3.0
Cancel button should not show when only Email provider is used and accountchooser.com is disabled.
