### ISSUE TITLE
Silent failure on invalid email / auth error

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebaseui-web#120]
If you "Sign in with Email" and paste in "me.@example.com" and press enter, no error is displayed, but if you open the console you should see a 400 error from an auth request. I believe all errors should display some feedback to the user.

**Comment by bojeil-google** [comment]
I just tried it, the info bar should be displayed with the message: 
The email address is badly formatted.  Dismiss

**Comment by mhuebert** [comment]
I just tried @ https://fir-ui-demo-84a6c.firebaseapp.com in both Chrome and Firefox, I see no error message.

To test there one must follow

1. "Sign in via Email"
2. "Add account"
3. type in me.@example.com
4. hit enter or press Next

I see no feedback.

**Comment by TMSCH** [comment]
@mhuebert @bojeil-google I am also able to reproduce the issue. It indeed only happens for some email addresses. I've forwarded the bug to the relevant people.

**Comment by bojeil-google** [comment]
I merged a PR to fix this issue. An error will be displayed in an info bar with a detailed message. Will push a patch update when i get the chance.
