### ISSUE TITLE
link multiple account error

### ISSUE THREAD

**Issue by qroosje** [firebase/firebaseui-web#126]
When trying to sign in with an account(twitter | facebook ) to an email that is already registered to an other provider. I get an error after firebase UI promts user to log in with the original(already registered account). 

Error: _POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=AIza*************************_I 400 ()_

Error: _[ 15.784s] [firebaseui] Internal error: {"error":{"errors":[{"domain":"global","reason":"invalid","message":"invalid access_token, error code 43."}],"code":400,"message":"invalid access_token, error code 43."}}_

Example: I sign up with twitter with email: john@gmail.com (goes successfully) and then I try to log in with facebook using  email (john@gmail.com), I get promted to first sign in with twitter and as I do this I get the previous error (firebase ui show internal error occured and does not log me in).

I am using the firebasui-web code on github. 
Any idea, suggestion, help is fine.

**Comment by bojeil-google** [comment]
I just merged a fix for this last night. I will push a CDN new version by end of day.

**Comment by bojeil-google** [comment]
This should have been fixed.
