### ISSUE TITLE
Material-Design-Lite dependency clobbers existing MDL variables

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebaseui-web#129]
I am using firebaseui-web in tandem with material-design-lite, and couldn't figure out why some of my components were being upgraded, while others were not. 

I traced it to FirebaseUI's bundling of a small number of MDL components as dependencies. If FirebaseUI is loaded *after* another MDL script, such as the default MDL javascript file, existing MDL global variable(s) (eg/ `window.componentHandler`) are overwritten, and only the components bundled with FirebaseUI can be upgraded.

A workaround is to make sure that FirebaseUI loads first, so that the MDL version you want in your app clobbers the MDL bundled with FirebaseUI.

Here is an example which includes one component which is bundled with FirebaseUI (progress bar), and one which is not (spinner). By swapping the order of the FirebaseUI and MDL script tags, you can see the effect:
https://codepen.io/mhuebert/pen/GWVyjz?editors=1000

I don't know if avoiding this type of collision is within the scope of this library (feel free to close this issue if not) but keeping this issue around & searchable might be useful to anyone else trying to use MDL+FirebaseUI together.

**Comment by bojeil-google** [comment]
The MDL js components are bundled with the firebaseui.js. One way to prevent this from happening would be to keep that dependency external. You can also build the library yourself without the MDL JS and include that separately. Currently the only way around it is to load FirebaseUI first as you pointed out.
It is tricky to change this to exclude MDL as it would break existing behavior in apps already using this library.
