### ISSUE TITLE
error ng:cpws when signing in with Google provider in an angular apps

### ISSUE THREAD

**Issue by mcialexliu** [firebase/firebaseui-web#130]
Error: as in the title

I am trying to put firebaseui into a modal for login in my angular application.

Here is how I implemented that.
In my controller on body tag (also with ng-app), i have a function to open an ui-bootstrap modal associate with an controller.
Then copy the code in the demo app.js to the controller and change those var to $rootScope.
Email/password login is fine, Google is the first provider I am trying after email/password login.

When I check the chrome javascript console and compare with the demo app, the sign is indeed success. Just somehow after getAccountInfo, something is being copied failed.
Even with the error, refreshing the page in browser, the auth status can be obtained with a proper firebase user obj.

Since this is the first ng app I am writing, i am not sure where did the copy happen and how it violate the rules causing ng:cpws

update: I write up a simple page angular app, same error occur.

Could anyone shed some light?

Also, I would like to ask how I can check if some one just registered?

Alex Liu

**Comment by mcialexliu** [comment]
Is there anybody would help?

Firebase has a handy wrap of angularfire, but still one have to implement the auth 1 by 1.
I thought firebaseui will work with angular seamlessly.
Or one should implement auth by angular instead?

**Comment by bojeil-google** [comment]
Hey Alex, can you elaborate more on this. It would be helpful if you can provide some code to reproduce this. All we can do is speculate.
FirebaseUI is not optimized for Angular but I don't see a reason why it shouldn't work with it.

**Comment by mcialexliu** [comment]
Here is the code i tried in a simple ng app
`
<html>
  <head>
    <meta charset="UTF-8">
    <title>FirebaseUI Auth Demo</title>
    <script src="https://www.gstatic.com/firebasejs/live/3.6/firebase.js"></script>
    <script src="config.js"></script>
    <link href="style.css" rel="stylesheet" type="text/css" media="screen" />
    <script src="https://cdn.firebase.com/libs/firebaseui/1.0.1/firebaseui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angularFire/2.3.0/angularfire.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/1.0.1/firebaseui.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body ng-app="testfbui" ng-controller="loginCtrl">
    <script src="login.controller.js"></script>
    <div class="modal-body" id="modal-body">
      <div id="container" class="login-container">
        <div id="loading" ng-show="loading">Loading...</div>
        <div id="loaded" class="" ng-show="!loading">
          <div id="main">
            <div id="user-signed-in" class="" ng-show="signedIn">
              <div id="user-info" class="user-info">
                <h4 class="auth-status-msg">Hello! {{user.displayName}}</h4>
                <div class="clearfix"></div>
              </div>
              <p>
                <button class="btn btn-warning" id="sign-out" ng-click="signOut()">Sign Out</button>
              </p>
            </div>
            <div id="user-signed-out" class="" ng-show="!signedIn">
              <h4 class="auth-status-msg">Hello, Sign in here</h4>
              <div id="firebaseui-spa">
                <div id="firebaseui-container"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
`

`
'use strict';
angular.module('testfbui', ['firebase'])
  .controller('loginCtrl', function( $scope, $rootScope, Firebase) {
	  var config = {
//my firebase project config
	  };

	  firebase.initializeApp(config, "abc");
		$rootScope.ui = $rootScope.ui ? $rootScope.ui : new firebaseui.auth.AuthUI(firebase.auth(), "ngtest");
		$rootScope.currentUid = null;
  	$rootScope.signedIn = false;
  	$scope.loading = true;

		$rootScope.uiConfig = $rootScope.uiConfig ? $rootScope.uiConfig : {
		  'callbacks': {
		    'signInSuccess': function(user, credential, redirectUrl) {
		      handleSignedInUser(user);
		      return false;		// Do not redirect.
		    }
		  },
		  'credentialHelper': firebaseui.auth.CredentialHelper.NONE,
		  'signInFlow': 'popup',		  // Opens IDP Providers sign-in flow in a popup.
		  'signInOptions': [
		    { provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
		      requireDisplayName: true
		    } , {
		      provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
		      scopes: ['https://www.googleapis.com/auth/plus.login']
		    }
		  ],
		  'tosUrl': '/tos'		// Terms of service url.
		};

		var handleSignedInUser = function(user) {
			$rootScope.user = angular.copy(user);
		  $rootScope.signedIn = true;
		  if (user.photoURL){
		    $scope.profilePic = user.photoURL;
		    $('#photo').attr("src", user.photoURL); 
		  }
		  $rootScope.$digest();
		};

		var handleSignedOutUser = function() {
		  $rootScope.signedIn = false;
		  $rootScope.userProfile = null;
      $rootScope.ui.start('#firebaseui-container', $rootScope.uiConfig);
		  $rootScope.$digest();
		};

		firebase.auth().onAuthStateChanged(function(user) {
		  if (user && user.uid == $rootScope.currentUid) {
		    return;
		  }
		  $scope.loading = false;
		  user ? handleSignedInUser(user) : handleSignedOutUser();		  
		});

	  $scope.signOut = function() {
	  	firebase.auth().signOut();
	  }

  });
`

**Comment by mcialexliu** [comment]
Sorry, I discover the mistake, which is a copying the user object to mutate to some other business object.
Oops
