### ISSUE TITLE
Internet Explorer 11 errors

### ISSUE THREAD

**Issue by gbittmann** [firebase/firebaseui-web#131]
Is it intended for firebaseui-web to support Internet Explorer 11? 

Using the first example, [starting-the-sign-in-flow](https://github.com/firebase/firebaseui-web#starting-the-sign-in-flow) everything seems to work fine in Chrome, Edge, and Firefox. 

Internet Explorer 11 however seems to have issues. I only tested providers Google and Email.

Attempting Sign in with Google redirects to the widget page as opposed to the successURL. I'm not sure if the problem is redirecting or you're never actually logging in.

Attempting to Sign in with email redirects correctly the first time, the second time you try this path you are redirected to https://www.accountchooser.com/learnmore.html.

**Comment by gbittmann** [comment]
I discovered [#93](https://github.com/firebase/firebaseui-web/issues/93) that a work around for the email flow exists, as long as you are turning off the account chooser.

However, this work around doesn't address the Google sign in flow. I have not been able to test other providers yet to verify whether they have the same issue.

**Comment by gbittmann** [comment]
I was able to setup Facebook and it works for Chrome, Edge and Firefox. Internet Explorerer 11 shows the same behavior as with Google.

Attempting Sign in with Facebook redirects to the widget page as opposed to the successURL.

**Comment by gbittmann** [comment]
Upon further investigation, the redirect problems with Internet Explorer 11 could not be duplicated in production. The problem can only be duplicated in development, which in this case is localhost:8080. 

I would say this is pretty low priority since it doesn't occur in production. It would save a lot of time for others who test browser compatibility in their local environments to have this listed in the known issues though.

**Comment by TMSCH** [comment]
Thanks @gbittmann for this thorough investigation! It seems that we should indeed mention that in the known issues. We have not tested the behavior of IE11 when deploying the widget on localhost, but we were not able to reproduce such behavior in production, so this is indeed a low priority bug.

**Comment by TMSCH** [comment]
Updated the doc: https://github.com/firebase/firebaseui-web#firebaseui-is-broken-in-ie11-when-deployed-on-a-local-server-accessed-through-localhost-but-works-when-deployed-on-a-remote-server.

**Comment by richtera** [comment]
This issue just cropped up in reverse for our apps. They work when running on localhost or a local http server but they don't allow login when the server is running in production. The server is running express on kubernetes with the google proxy and ends up using HTTP/2 for much of the code which I think might be adding complications that prevents onAuthChanged to be ever called. Unfortunately I am not sure how to debug this since I just get a few "Possible Unhandled Promise Rejection: undefined" and no other indication as to what's going wrong. The unhandled exceptions are coming from within initializeApp.
