### ISSUE TITLE
Firebase should be added as a peerDependency

### ISSUE THREAD

**Issue by lostpebble** [firebase/firebaseui-web#133]
Because I use both the `firebase` base module and this `firebaseui` module, I'm getting duplicates being generated in my javascript bundles after compiling. This is increasing the size massively (these libraries are by no means lean).

Usually in these kinds of projects its seen as a best practice to make these kinds of dependencies a `peerDependency` in `package.json` - because they are often relied upon in other parts of peoples' apps too and the versions for those dependencies should be maintained externally from child libraries. This prevents bundlers from including multiple versions.

This problem has caused my bundle to shoot up almost 100kb (and that's gzipped!)

**Comment by jalajc** [comment]
#140 
further to make apps cringe, firebaseapp and cdn.firebase.com are not as fast global networks as I would expect.
I remember eliminating extravagant jQuery Library altogether and writing my own javascript components (few required ones) for similar reasons!

**Comment by nicolasgarnier** [comment]
firebase is now in the `peerDependencies` :)
