### ISSUE TITLE
Poor messages when user had signed in previously with custom method

### ISSUE THREAD

**Issue by adelespinasse** [firebase/firebaseui-web#134]
My app is set to "One account per email address", so if a user tries to sign in using a different provider, using an account that uses the same email address, it fails. If the existing account was created with a custom sign-in method, the error messages shown to the user aren't very helpful.

FirebaseUI-web seems to have been designed on the assumption that it will never be used with apps that have custom sign-in methods. This might seem like a reasonable assumption, but in fact my app is using it for all the built-in sign-in methods, and it saves me a lot of trouble. My app has a custom sign-in method (using Slack), and uses FirebaseUI for sign-in using Google, Facebook, and email.

Also, I don't think it would terribly difficult to improve the error messages in this situation, although it might require [allowing custom sign-in methods to add provider data to accounts](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/MI4unsBqgIw/ROwVS4hAAQAJ) (so that the UI can tell the user the name of the sign-in method previously used).

Steps to reproduce:

1. In an app that has both a custom sign-in method and the built-in methods, sign in using the custom method first. You can try this on the test version of my company's app: https://test.agora.co/home (login button is in upper right corner; sign in with Slack).
1. Sign out. Then try to sign in using email.
1. (FirebaseUI will actually ask for your real name and new password, as if you were logging in for the first time - this is unfortunate and is inconsistent with the behavior when the existing account was created with Google or Facebook, where FirebaseUI will give an error message as soon as you type the email address.)
1. An error message is shown, but it is misleading:

![image](https://cloud.githubusercontent.com/assets/8228772/25314468/6049c4aa-2812-11e7-80be-2f1b168224f7.png)

I haven't recently attempted logging in with a Google or Facebook account linked to the same email address, but I think it gives a similarly misleading message.

**Comment by bojeil-google** [comment]
You are correct FirebaseUI is not compatible with custom authentication.

If the custom auth account has an email set, then password reset is the only way you can sign in with that account using FirebaseUI. There is no other means to detect it or sign in with it.
Firebase Auth only provides fetchProvidersForEmail to look up an account by email. Custom Auth accounts return an empty array. This normally signifies no account existing for that email. If you try to create an account, you will get an error that the account exists. The only way to possibly recover is by password reset.

Custom auth depends on the developer server to verify the user credential and mint the custom token. In general, developers with their own auth system will use custom auth. FirebaseUI is not set up for that. You have to build your own mechanism to sign in with custom auth.

**Comment by adelespinasse** [comment]
"You have to build your own mechanism to sign in with custom auth" - this part makes sense, and I have done that. The problem is that, in order to cleanly support both custom auth and email auth, you have to:

1.  Build your own mechanism for custom auth
2.  Re-implement email auth

The second thing shouldn't be necessary since email auth is built into FirebaseUI-web (i.e., support for creating a new account, logging in to an existing account, resetting a password, etc.) And it should be pretty straightforward to fix FirebaseUI-web so that it gives correct feedback in the situations I described above.

Or at least, it would be straightforward if the Firebase SDK was updated to fix [the issue I mentioned here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/MI4unsBqgIw/ROwVS4hAAQAJ). If that were fixed, I could probably make the needed updates to FirebaseUI via a pull request, since it appears to be open source now.

**Comment by adelespinasse** [comment]
Closed? What was the resolution? "Will not fix"?

**Comment by nicolasgarnier** [comment]
@adelespinasse: Yes "Will not fix", sorry for overlooking this.

Looks like from @bojeil-google 's comment that the error message is appropriate for this particular error. It is a bit generic but it also applies to some other case (i.e. you could use the Admin SDK to create an account without means of sign-in).

Regarding "FirebaseUI is not compatible with custom authentication". In change this FirebaseUI would need a to have a UI to let your users sign-in your custom flow but since these are entirely custom it does not seem possible to support this really. We'd need this as, for example because we need to ask your user to sign-in their existing accounts in order to link them to the new sign-in method so to implement this UX we need a way to have users sign-in your custom auth and that's not really possible.

**Comment by adelespinasse** [comment]
Thanks. It's not really relevant to me anymore, since I'm not working on that particular project.

I still disagree that the message is appropriate. "Without any means of sign-in" isn't true in this situation, and resetting the password probably doesn't work.

**Comment by nicolasgarnier** [comment]
Yes, technically you are right, a user can *always* be signed-in using custom auth. I guess the wording could be "Without any means of sign-in supported by firebaseUI" :)

I'll let @bojeil-google decide if he'd like to change the wording of that error in such way.

**Comment by bojeil-google** [comment]
It is not possible for us to tell the method of sign-in.
For example, consider the following cases:
1. User was created via admin SDK with just an email.
2. User was signed in anonymously and an email added.
3. User has all providers unlinked orphaning the account with just an email.
4. User was previously signed in with custom auth.

From our end, they all look the same when calling `fetchSignInMethodsForEmail`.
We have no reliable way to detect the cases above.
