### ISSUE TITLE
Add support for server-side render

### ISSUE THREAD

**Issue by rmmmp** [firebase/firebaseui-web#135]
I'm unable to make this run in a server-side render environment (e.g. [Ember FastBoot](http://ember-fastboot.com/) and [Angular Universal](https://universal.angular.io/)). The reason is that having this library in your code makes it run this code immediately in the minified version:

```javascript
window.addEventListener("load",function(){if("classList"in document.createElement("div")...
```

`window.addEventListener` isn't available in nodejs environment that's why the error happens.

My workaround is to exclude all **firebaseui-web** related codes from being compiled in the server-side environment scripts. However, it'd be nice if this library can seamlessly support both browser and server environment.

As a permanent solution, I think we should prevent browser API from running eagerly in the code. Either we can check if the APIs are available before running it or generate a separate AMD/ES6 module library where it'll only run after explicitly importing it and calling it in your app.

**Comment by bojeil-google** [comment]
This part of the code that runs immediately is actually part of the MDL library which our library depends on:
https://github.com/google/material-design-lite/blob/fd21836fd49d94270e58b252187ebe93410209e4/src/mdlComponentHandler.js#L479

One thing you can do is to remove the MDL dependency and build the library without it and then add it separately as you pointed out.

**Comment by rmmmp** [comment]
@bojeil-google, ah, so that's why I couldn't find the code in this repo.

Thanks but I think I'll stick to just excluding firebaseui itself. I don't want to add another step of separating the MDL dependency and building firebaseui myself. I just want a quick `npm install`.

Closing as the offending code is not related to firebaseui.
