### ISSUE TITLE
CSS style cannot be used from within a shadow root

### ISSUE THREAD

**Issue by mattpalermo** [firebase/firebaseui-web#136]
I am trying to use firebaseui-web from within a polymer element. I cannot get the styles to work within the shadow root. I believe this is because of the encapsulation that the shadow DOM provides.

http://jsbin.com/bijasiruva/edit?html,output

Perhaps this issue would be solved by https://github.com/firebase/firebaseui-web/issues/2.

In the mean time, is there any solutions to this problem?

**Comment by jtborst** [comment]
Create a new file with (I called it firebaseui-style-loader-module.html)
```
<dom-module id="firebaseui-styles">
  <template>
    <style>
      ...copy paste firebaseui.css from dist...
    </style>
  </template>
</dom-module>
```

And in the shadow root where your firebaseui-auth-container is, add
```
<link rel="import" href="../bower_components/firebaseui/dist/firebaseui-style-loader-module.html">
<style include="firebaseui-styles">
```

Would be nice to have the build generate this module file.

**Comment by mattpalermo** [comment]
Thankyou jtborst for this. I'm sorry but I can't remember too much about polymer but this will surely be a great reference for someone (or myself) in the future.

**Comment by nominator** [comment]
@jtborst you have saved me a lot of pain my friend. Kudos!!!
