### ISSUE TITLE
Event that the user is just registered (and first time sign-in with Auth provider)?

### ISSUE THREAD

**Issue by mcialexliu** [firebase/firebaseui-web#137]
Is there any event being emitted so that we know the user is just added to firebase auth?

At the moment, i can only keep it in database and when someone login, check if the uid is created in database, which is quite clumsy for just checking for a single event that is obviously can be emitted.  
I believe it is common that an apps need to have their own specific user profile.

Or is there any simple way to implement?

**Comment by bojeil-google** [comment]
Currently there is another way to track that via Firebase Functions.
https://firebase.google.com/docs/functions/auth-events#trigger_a_function_on_user_creation

**Comment by corysmc** [comment]
I'd like to be able to do this as well. I'd like to show new sign ups an onboarding experience, and hide that experience from existing users.

**Comment by bojeil-google** [comment]
This issue hasn't been updated but [`signInSuccessWithAuthResult`](https://github.com/firebase/firebaseui-web#signinsuccesswithauthresultauthresult-redirecturl) will provide additional user info regarding whether the user is new or existing. You can check:

    var isNewUser = authResult.additionalUserInfo.isNewUser;

**Comment by corysmc** [comment]
Awesome, thanks! @bojeil-google
