### ISSUE TITLE
Error code: auth/timeout

### ISSUE THREAD

**Issue by snackosphere** [firebase/firebaseui-web#14]
I'm using the "Starting the sign flow" code from the instructions. I only have the Email Provider enabled. I'm using the local server.  When I load the page, the widget progress bar goes for a while, then a little yellow box says "Error code: auth/timeout" yet the widget still works.  Any advice on how I can fix this? Thank you for your great work.

**Comment by bojeil-google** [comment]
Internally, the widget calls getRedirectResult to check if the sign in widget is coming back from a sign in with redirect event. For some reason it is timing out. Are you passing your authDomain via initializeApp? This is required here. If so, did you whitelist your page origin in the Firebase console. Also makes sure you are not running your test app from a file system environment file://index.html. It has to be served from a web server. You can then test via http://localhost. If this information is not helpful, please provide us with more information to help us investigate.

**Comment by snackosphere** [comment]
It works when I run it on Firefox both on localhost and firebaseapp.com.  I was using Opera, where it timeouts on localhost but runs on firebaseapp.com.  Thank you for your help.

**Comment by bojeil-google** [comment]
I tested on Opera 37.0.2178.32 in Ubuntu using localhost but couldn't get it to timeout. Make sure you are updating the api key and the auth domain to the correct one associated with your project. Are you getting any additional errors in the console?
