### ISSUE TITLE
firebaseui.js and firebase.js loading issues

### ISSUE THREAD

**Issue by jalajc** [firebase/firebaseui-web#140]
## Problem
After using the library for 6 months, I find that many user though click on signin button
but didn't ended up signing actually.
After detailed analysis and user feedback, **I discovered that firebaseui.js and firebase.js libraries didn't even loaded substantial number of times.** (while there are other reasons too, but this is one prime technical reasons)

## Symptoms
- firebase js libraries simply don't load (may be a better cdn and edge-node replication needed)
- files are too long to be loaded on slower/unreliable cellular network
## Geo
 - 99% of traffic comes from India. so all the cases found to be from various locations of India.
 - Even some metro (with good fast bandwidth)  user also faced the issue though
 - Other google services worked without issues in these Geos.
## Links used
- https://www.gstatic.com/firebasejs/3.6.8/firebase.js
- https://cdn.firebase.com/libs/firebaseui/1.0.0/firebaseui.js
- besides there were other js imported by these two libraries (e.g. Account Chooser)
## Work requested
 - size reduction of libraries
 - better cdn/edge mirroring
 - moving library to gstatic to minimize DNS unresolved errors.
## Aditional disgnostic info
 - avg ping time for gstatic.com: **2ms** (resolves to gstatic.com [172.217.26.227])
 - avg ping time for **cdn.firebase.com**: **132ms** (resolves to global-ssl.fastly.net [151.101.64.249])
 - avg ping time for google.com: **2ms** (resolves to 216.58.199.174)
 - avg ping time for firebaseapp.com: **130ms** (resolves to [151.101.1.195])
  - data from Mumbai, on fast broadband node. non-metro and smaller towns ping will be ~additional 30-100ms

**Comment by nicolasgarnier** [comment]
In general, if our CDN do not serve you well and performance is really important for you you should host and serve your own version of the library. Probably best is that you package the Firebase and FirebaseUI libraries in your app using webpack or similar.

Another optimisation: please avoid using `firebase.js`, it contains alsmot the whole Firebase SDK including FCM, Storage, etc... if you do not need all features prefer using submodules such as `firebase/auth` and `firebase/database` as described here: https://firebase.google.com/docs/web/setup
