### ISSUE TITLE
Firebaseui Account Chooser is not working!

### ISSUE THREAD

**Issue by maryam-abdullah** [firebase/firebaseui-web#143]
I added this line of code and it doesn't show the account chooser box, it automatically logins in with one account.
**credentialHelper: firebaseui.auth.CredentialHelper.ACCOUNT_CHOOSER_COM**

I would appreciate any help.
Thanks in advance.

**Comment by bojeil-google** [comment]
Do you mean the account chooser for Google sign in? They are different. If that's the case, we need to pass the prompt custom OAuth parameter when signing in with Google. We currently don't support that.

**Comment by maryam-abdullah** [comment]
Hi @bojeil-google,
I actually meant Firebaseui, not Specifically Google sign in.
I, later on, realized it works fine. But once you're logged in on facebook, it doesn't give you the option to sign in with a different account, instead, it automatically signs in with that account. Is that pretty normal?

**Comment by bojeil-google** [comment]
That is the default behavior for Facebook and most other OAuth providers. Facebook does have a custom OAuth parameter to force re-entry of the facebook password: https://developers.facebook.com/docs/facebook-login/reauthentication
The underlying firebase-auth.js supports that setting but FirebaseUI doesn't currently support that.

**Comment by maryam-abdullah** [comment]
Okay. I got your point.

Thanks for your help.
