### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'window.dialogPolyfill.registerDialog')

### ISSUE THREAD

**Issue by RafaelPlantard** [firebase/firebaseui-web#147]
I'm facing this issue when I'm trying to get log in with phone provider.
When I click to "change country" selector this error is thrown:
`TypeError: undefined is not an object (evaluating 'window.dialogPolyfill.registerDialog')`

**Comment by bojeil-google** [comment]
hey @RafaelPlantard can you provide more details on how to recreate this issue?

**Comment by channing-google** [comment]
Probably the same issue as #150?

**Comment by RafaelPlantard** [comment]
I guess it's the same issue @channing-google

**Comment by RafaelPlantard** [comment]
Redirecting to #150
