### ISSUE TITLE
npm run demo Error: No project active. Run with --project <projec tId> or define an alias by running firebase use --add

### ISSUE THREAD

**Issue by EmberJSParis** [firebase/firebaseui-web#148]
I have the same problem as above, My Java config is -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11
)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11,
mixed mode) ...................I am on Mac and I installed Java in usr/local/bin/java through the command brew cask install java .......................when I ran "npm run demo --project IDofproject" I get this error "Error: No project active. Run with --project or define an alias by
running firebase use --add" The initial objective it was to ran https://github.com/firebase/firebaseui-web/tree/master/demo but the error persist.........For information I done sudo
 chown -R $USER ~/.config/configstore then fire
base use --clear then firebase use --add......but still Error: No project active. Run with --project <projec
tId> or define an alias by
running firebase use --add......Please help......

**Comment by nicolasgarnier** [comment]
I will close this since it is old. When filing an issue please make sure to provide step by step way to replicate the issue a well as current and expected results. Ideally also please upload a version of your broken app so we can test and experience the issue.
