### ISSUE TITLE
signInSuccess callback doesn't work in 2.0 (works in 1.0)

### ISSUE THREAD

**Issue by PAK90** [firebase/firebaseui-web#149]
So I have this code:
```
  componentDidMount () {
    this.ui = new firebaseui.auth.AuthUI(firebase.auth());
    this.uiConfig = {
      'signInSuccessUrl': 'http://localhost:3333',
      'signInOptions': [
        firebase.auth.GoogleAuthProvider.PROVIDER_ID,
        firebase.auth.FacebookAuthProvider.PROVIDER_ID,
        firebase.auth.TwitterAuthProvider.PROVIDER_ID,
        firebase.auth.GithubAuthProvider.PROVIDER_ID,
        firebase.auth.EmailAuthProvider.PROVIDER_ID
      ],
      'signInFlow': 'popup',
      callbacks: {
        signInSuccess: function(currentUser, credential, redirectUrl) {
          alert("Signed in as "+currentUser + " with credential " + credential);
          this.setState({"modalIsOpen": false});
        }.bind(this),
        uiShown: function() {
          alert("doing login stuff.");
        }
      }
    };
  }
```

Basically, in v1 of firebaseui, it works fine. I log in with a Firebase user, the signInSuccess callback is called, life is good. However with v2.0.0 it doesn't work at all (whereas the test uiShown callback still works in both versions). I'd like to use the latest version of the component, but if it's not going to let me do signin callbacks, I won't be able to. I've looked through the docs and I don't think there's any implementation difference between v1 and v2, unless I'm missing something?

**Comment by bojeil-google** [comment]
Hey @PAK90, what happens in your case? do you get redirected to signInSuccessUrl directly, without the callback running at all? Do you get any errors in the console?

**Comment by PAK90** [comment]
@bojeil-google yep, sorry, should've mentioned that. No console errors, but I don't seem to get redirected to signInSuccessUrl either (tested that by pointing it at an invalid port, still saw my page after the failed 'login').

**Comment by zmarble** [comment]
I am seeing the same problem. I installed firebaseui with npm, got the latest, and was trying to use it in a React app. The ui would ask me to pick a gmail account but then the progress bar would just spin. I reverted to 1.0.1 and it worked fine.

**Comment by wguttmn** [comment]
Same here. Basically, uninstalled 1.0.1 using npm, installed 2.0.,0 using npm, and the callback function is NOT called. And no redirection. 

Environment:

* React

**Comment by bojeil-google** [comment]
Ok, so I investigated this and I am not a ReactJS developer. I rendered a FirebaseUI widget in ReactJS. I have 2 findings:
1.  Callback is getting run in 2.0.0 as expected. 
```
import React from 'react';
import ReactDOM from 'react-dom';
import firebase from 'firebase';
import firebaseui from 'firebaseui';

// Copy this from the Firebase Console.
const config = {
  ...
};
firebase.initializeApp(config);
const authUi = new firebaseui.auth.AuthUI(firebase.auth());

class FirebaseUI extends React.Component {
  componentDidMount() {
    const uiConfig = {
      'signInFlow': 'popup',
      'signInSuccessUrl': 'https://www.google.com',
      'credentialHelper': firebaseui.auth.CredentialHelper.NONE,
      'callbacks': {
        'signInSuccess': function(currentUser, credential, redirectUrl) {
          console.log('callback run: ' + this.props.label);
          alert("Signed in as "+currentUser + " with credential " + credential);
          return true;
        }.bind(this),
        uiShown: function() {
          alert("doing login stuff.");
        }
      },
      'signInOptions': [
        firebase.auth.GoogleAuthProvider.PROVIDER_ID,
        firebase.auth.EmailAuthProvider.PROVIDER_ID
      ]
    };
    authUi.start('#firebaseui-auth', uiConfig);
  }

  componentWillUnmount() {
    authUi.reset();
  }

  render() {
    return (
      <div id="firebaseui-auth"></div>
    );
  }
}

// ========================================

ReactDOM.render(<FirebaseUI label="react"/>, document.getElementById("root"));
```
I can see the console log and the alert show. In the end the page was redirecting as expected. 

2. You need to return true; in order for the callback to redirect. You are not doing so which is equivalent to returning undefined which evaluates to false. I am hoping you meant that your callback gets called but no redirect is occurring. Otherwise your comment seems very misleading.

**Comment by wguttmn** [comment]
I almost literally copied the code given above into my code base (incl. the "uiShown" function), and whilst I am seeing the "doing login stuff" alert as a result of the component being rendered in React, the "signInSuccess" callback is still not being invoked. 

On top of that, no errors, no console output, nothing that indicated that something is wrong.

**Comment by bojeil-google** [comment]
These are the react and firebase versions I am using:
"react": "^15.5.4",
"react-dom": "^15.5.4",
"firebase": "^4.1.1",
"firebaseui": "^2.0.0"

Can you host your reproduction somewhere so I can take a look? Would be great if you not obfuscate your code too.

**Comment by wguttmn** [comment]
A little progress on my side.  I decided to upgrade a few things before: 

"react": "^15.5.4",
"react-dom": "^15.5.4",
"firebase": "^4.1.1",
"firebaseui": "^2.0.0"

to match your code sample. There's a little progress now, but the callback is still not invoked.

Instead, I now get an iframe that shows the following message (with a dismiss link):

````
Cannot read property 'get' of undefined  Dismiss
```

**Comment by bojeil-google** [comment]
I can't do much unless I am able to recreate this issue on my end. One thing that could be helpful is to host a version of your app (preferably unobfuscated) so we can try to debug from there.

**Comment by fareesh** [comment]
+1 same issue with Vuejs. Progress bar spins and the callback doesn't fire. Works in 1.00 though. What should I be looking for to help debug this?

**Comment by bojeil-google** [comment]
Provide us with a web app link, preferably with the code unobfuscated. I just can't reproduce. I would be super interested to see why it would work in 1.00 and not the latest one. It is quite a mystery. I can't think of any change we recently made that would cause this.

**Comment by Tzelon** [comment]
@PAK90 Did you still have this issue?
I encounter the same problem in React 5.16.1
firebaseui version 2.3.0

**Comment by mastooo** [comment]
@bojeil-google I have this little app that surface the very same problem (ember in this case):
https://mykidscubby.com/login
I copied your config with your callbacks (from the example posted above).

The popup is shown (following `uiShown`). But no alert is shown following a successful login. Works on a previous version of the lib.

Thanks for your help. Below the config:

```javascript
let config = {
      'signInFlow': 'popup',
      'signInSuccessUrl': 'https://www.google.com',
      'credentialHelper': firebaseui.auth.CredentialHelper.NONE,
      'callbacks': {
        'signInSuccess': function(currentUser, credential, redirectUrl) {
          console.log('callback run: ');
          alert("Signed in as "+currentUser + " with credential " + credential);
          return true;
        }.bind(this),
        uiShown: function() {
          alert("doing login stuff.");
        }
      },
      'signInOptions': [
        firebase.auth.GoogleAuthProvider.PROVIDER_ID,
        firebase.auth.EmailAuthProvider.PROVIDER_ID
      ],
    };
```

**Comment by bojeil-google** [comment]
I noticed you package Firebase auth JS into your code and then include firebase and firebaseUI CDNs:
https://www.gstatic.com/firebasejs/4.2.0/firebase.js
https://cdn.firebase.com/libs/firebaseui/2.3.0/firebaseui.js
Firebase-auth is being double included with different obfuscation.

The following error is getting thrown and suppressed when signInWithCredential is called:
{code: "auth/argument-error", message: "signInWithCredential failed: First argument "credential" must be a valid credential."} even though a legitimate credential is being passed.
There is some issue with obfuscation. I assume your obfuscation is clashing with Firebase Auth's obfuscation.
Try packaging all the libraries (firebaseui and firebase.js) with the rest of your code and try again.

**Comment by brandonmikeska** [comment]
Hmm seems we are getting this after upgrading to 2.0. Any specifications on how we should upload a repo to reproduce the issue? 

Using these dependencies:
    "firebase": "^3.6.8",
    "firebaseui": "^2.3.0",
    "history": "4.2.0",
    "material-ui": "^0.17.4",
    "prop-types": "^15.5.8",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.4",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.7",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"

Noticed my react isn't as up to date. I will try updating that in the mean time.

**Comment by bojeil-google** [comment]
The other issue was related to obfuscation. Please investigate if this is related to obfuscation first. 
If not, upload to some test site. You'd save me a lot of time debugging it.

**Comment by brandonmikeska** [comment]
My apologies, I noticed that my firebase was 3.6.8 and upgraded it to 4.1.1 and it works now.
