### ISSUE TITLE
Nice redirects for existing accounts not working.

### ISSUE THREAD

**Issue by marcus7777** [firebase/firebaseui-web#153]
When I try and log in to a service that I already have the same email address I get nicely redirected to login with the account I've already got than that fails every time. :(
demo vid
https://youtu.be/Fql3jA6Xs-s
to recreate log in with Google, then with github which has the same email address as your Google account.
 
https://open-elements.org/bower_components/firebase-ui-auth/demo.html

if this cannot be resolved better just not having it at all. Just inform the user no link

**Comment by channing-google** [comment]
Can you double check your Github Client ID and secret that you configured in Firebase Console?

**Comment by marcus7777** [comment]
@channing-google you're right I don't have it completed properly. Seems to be working fine now.
