### ISSUE TITLE
Bypass Nascar screen when only phone auth provider is enabled

### ISSUE THREAD

**Issue by bojeil-google** [firebase/firebaseui-web#155]
There is no need to display the NASCAR screen when phone auth provider is the only one enabled. Instead, on rendering, the phone sign in start screen should be displayed immediately.

**Comment by josesuero** [comment]
I'm looking for a way to do this, can it be done programmatically?

**Comment by bojeil-google** [comment]
We will offer this out of the box. The only way to do this right now, is through a hack: wait for the NASCAR screen to render, get the "Sign in with phone number" button element and then trigger a click on it programmatically. The solution should be coming in soon. I recommend you wait a bit.

**Comment by josesuero** [comment]
that works, also can I adjust the labels, meaning de language, I want the "enter your phone" to be in other languages

**Comment by bojeil-google** [comment]
A feature request for internationalization is already filed for that. In the meantime you can fork the repo and customize the soy folder which contains all the labels.

**Comment by bojeil-google** [comment]
Bypass Nascar screen issue should be fixed in release 2.1.1.
