### ISSUE TITLE
Email Verification Resource Not Loading

### ISSUE THREAD

**Issue by picadipity** [firebase/firebaseui-web#161]
I am getting a 400 error response from:
https://www.googleapis.com/identitytoolkit/v3/relyingparty/setAccountInfo?key=<apiKey>

This occurs after auth.applyActionCode(actionCode) promise returns email successfully verified.  I used to be able to show a dialog containing firebaseui-auth-container.  I now have to popup a dialog using hard coded strings informing the user.

Does this ring a bell?  Which steps should I take to resolve this, or is it a recent change on the firebase ui side?

I've included these in <head>:
<link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/2.1.1/firebaseui.css"></link>
<script src="https://www.gstatic.com/firebasejs/4.1.2/firebase.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.1.2/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.1.2/firebase-auth.js"></script>
<script src="https://cdn.firebase.com/libs/firebaseui/2.1.1/firebaseui.js"></script>

**Comment by picadipity** [comment]
OS: iMac running macOS Sierra Version 10.12.5
Browser: Chrome Version 58.0.3029.110 (64 bit)

**Comment by bojeil-google** [comment]
Can you inspect the browser network console and get the exact request/response.
By the way you are double including firebase.js. You either include firebase.js on its own or firebase-app.js and firebase-auth.js. firebase.js includes all modules.

**Comment by picadipity** [comment]
Second part first: Not sure where all four came into use but took firebase-app.js and firebase-auth.js out.  Thanks!

I hope I have what you want in the attached file
[Output_161.pdf](https://github.com/firebase/firebaseui-web/files/1079507/Output_161.pdf)

**Comment by picadipity** [comment]
Doh, just wanted to click comment -- not close and comment...

**Comment by bojeil-google** [comment]
There is still the actual response missing. Would be extremely helpful if you can provide that.

**Comment by picadipity** [comment]
Here it is:

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "INVALID_OOB_CODE"
   }
  ],
  "code": 400,
  "message": "INVALID_OOB_CODE"
 }
}

**Comment by bojeil-google** [comment]
Hmm, are you sure the code is valid. This seems pretty clear. The email verification code provided is invalid. Try sending a new one and check it while inspecting the console. If it is not working, you need to notify the Firebase Auth team about it. 
I just tested it in my test app and it worked. A code that has already been used will return INVALID_OOB_CODE.

**Comment by picadipity** [comment]
I got it -- took some time because I needed to have dev tools running when pasting emailVerify link.

So here is the interesting result.  I get a sequence of calls: getAccountInfo, setAccountInfo, setAccountInfo -- the last setAccountInfo is probably giving me the wrong dialog causing me to have to popup my own dialog.

Here are the responses:
getAccountInfo
{
 "kind": "identitytoolkit#GetAccountInfoResponse",
 "users": [
  {
   "localId": "9VjktHWjMkNzAXvhVAn0zYwTl5j2",
   "email": "redmond_shippo@yahoo.com",
   "emailVerified": false,
   "displayName": "Shippo",
   "providerUserInfo": [
    {
     "providerId": "password",
     "displayName": "Shippo",
     "federatedId": "redmond_shippo@yahoo.com",
     "email": "redmond_shippo@yahoo.com",
     "rawId": "redmond_shippo@yahoo.com"
    }
   ],
   "passwordHash": "UkVEQUNURUQ=",
   "passwordUpdatedAt": 1.497583705E12,
   "validSince": "1497583705",
   "lastLoginAt": "1497583705000",
   "createdAt": "1497583705000"
  }
 ]
}
setAccountInfo
{
 "kind": "identitytoolkit#SetAccountInfoResponse",
 "localId": "9VjktHWjMkNzAXvhVAn0zYwTl5j2",
 "email": "redmond_shippo@yahoo.com",
 "displayName": "Shippo",
 "passwordHash": "UkVEQUNURUQ=",
 "providerUserInfo": [
  {
   "providerId": "password",
   "federatedId": "redmond_shippo@yahoo.com",
   "displayName": "Shippo"
  }
 ],
 "emailVerified": true
}
setAccountInfo
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "INVALID_OOB_CODE"
   }
  ],
  "code": 400,
  "message": "INVALID_OOB_CODE"
 }
}

**Comment by bojeil-google** [comment]
I am gonna speculate a bit as i am not sure about your app setup. It appears applyActionCode is being called twice. The first time it succeeds and the second time it fails since the code has already been used. I think there may be something in your code, possibly rendering the verify email widget twice in a row.

**Comment by picadipity** [comment]
You are probably right -- I have console spew before authActonCode and I only see that called once.  I have another page that uses this auth code but it shouldn't be loaded.  I'll try some more debugging and see if I can track this down.  For now I'm going to close this issue.
