### ISSUE TITLE
Edge: "Well that didn't work"

### ISSUE THREAD

**Issue by finppp** [firebase/firebaseui-web#162]
On Edge (40.15063.0.0) on the [Firebase UI Demo](https://fir-ui-demo-84a6c.firebaseapp.com/), when you select sign in with Google or Facebook using "single page application mode" the popup box display an error "Well that didn't work", before redirecting you to the correct page.

**Comment by blairjo** [comment]
+1
I am also seeing this on my application. 
It eventually works, but can be very jarring for the user.

**Comment by bojeil-google** [comment]
Firebase Auth has a possible fix on the way.

**Comment by blairjo** [comment]
@bojeil-google do you have any more info that?

Thanks

**Comment by bojeil-google** [comment]
Hey @blairjo, there is a fix for this in the core sdk (firebase.js/firebase-auth.js) but it may not make it to the upcoming release but the next one. I will keep you posted when it's out. You can always check https://firebase.google.com/support/release-notes/js for the latest releases.

**Comment by blairjo** [comment]
great news, thanks!

**Comment by bojeil-google** [comment]
This should be fixed in firebase 4.2.0: https://firebase.google.com/support/release-notes/js#4.2.0

**Comment by finppp** [comment]
Amazing! Thanks
