### ISSUE TITLE
Hostname match not found

### ISSUE THREAD

**Issue by karimmortabit** [firebase/firebaseui-web#166]
"Hostname match not found". I have this error randomly
 thrown at some configurations web and mobile. Can't find any tangible common specs. 
<img width="407" alt="webapp_ano" src="https://user-images.githubusercontent.com/3072971/27083945-bf2f0008-5039-11e7-8e17-37c934db6443.png">

**Comment by karimmortabit** [comment]
Does it have something to do with SSL certificates ? my app being hosted on Heroku, the original domain name myapp.herokuapp.com does have a certificate and allow https, but my main domain myapp.com doesn't.

**Comment by bojeil-google** [comment]
Make sure you whitelist myapp.herokuapp.com and myapp.com in the Firebase Console -> Authentication -> sign-in-method -> Authorized Domains. SSL certificates should not matter:
https://firebase.corp.google.com/u/0/project/$PROJECT_ID/authentication/providers

**Comment by karimmortabit** [comment]
Thanks @bojeil-google, I actually just managed to fix the error, in fact by adding in the Authorized Domains `www.myapp.com` in addition to `myapp.com`, even though I expected the latter to handle both of them at first, `www.myapp.com` being a subdomain of `myapp.com`. (This is suggested here https://support.google.com/firebase/answer/6400741)

**Comment by allamgr** [comment]
@bojeil-google @karimmorta  I have added my domain from heroku [project].herokuapp.com and it's not working.

**Comment by PurpleProgrammer** [comment]
Hey, I had been getting the auth/host-match-not-found error for some days and the problem was the following:

I had whitelisted the appname@.com, but not the www.appname.com domain. The 'www' in front counts as a separate domain and has to be whitelisted exclusively.

Make sure to whitelist your domain both with and without 'www' in the front.

**Comment by DAC696** [comment]
> Hey, I had been getting the auth/host-match-not-found error for some days and the problem was the following:
> 
> I had whitelisted the [appname@.com](mailto:appname@.com), but not the [www.appname.com](http://www.appname.com) domain. The 'www' in front counts as a separate domain and has to be whitelisted exclusively.
> 
> Make sure to whitelist your domain both with and without 'www' in the front.

I have added both domains in my firebase console but still getting the hostname error if you could help
