### ISSUE TITLE
failed: npm i firebaseui -save # using npm@5.0.2 node@v8.0.0

### ISSUE THREAD

**Issue by smorin** [firebase/firebaseui-web#167]
just tried to install firebaseui with npm in a project created with create-react-app

This is the log output of the failure.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'firebaseui',
1 verbose cli   '-save' ]
2 info using npm@5.0.2
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 http fetch GET 200 https://registry.npmjs.org/firebaseui 14ms (from cache)
7 silly pacote tag manifest for firebaseui@latest fetched in 36ms
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly install loadAllDepsIntoIdealTree
12 silly resolveWithNewModule firebaseui@2.1.1 checking installable status
13 http fetch GET 200 https://registry.npmjs.org/firebase 5ms (from cache)
14 silly pacote range manifest for firebase@^4.1.2 fetched in 8ms
15 silly resolveWithNewModule firebase@4.1.2 checking installable status
16 http fetch GET 200 https://registry.npmjs.org/base64url/-/base64url-2.0.0.tgz 7ms (from cache)
17 silly pacote remote manifest for base64url@https://registry.npmjs.org/base64url/-/base64url-2.0.0.tgz fetched in 24ms
18 http fetch GET 200 https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz 3ms (from cache)
19 silly pacote remote manifest for buffer-equal-constant-time@https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz fetched in 8ms
20 http fetch GET 200 https://registry.npmjs.org/dom-storage/-/dom-storage-2.0.2.tgz 3ms (from cache)
21 silly pacote remote manifest for dom-storage@https://registry.npmjs.org/dom-storage/-/dom-storage-2.0.2.tgz fetched in 6ms
22 http fetch GET 200 https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.9.tgz 2ms (from cache)
23 silly pacote remote manifest for ecdsa-sig-formatter@https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.9.tgz fetched in 6ms
24 http fetch GET 200 https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.9.3.tgz 2ms (from cache)
25 silly pacote remote manifest for faye-websocket@https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.9.3.tgz fetched in 11ms
26 http fetch GET 200 https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz 3ms (from cache)
27 silly pacote remote manifest for hoek@https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz fetched in 7ms
28 http fetch GET 200 https://registry.npmjs.org/isemail/-/isemail-1.2.0.tgz 2ms (from cache)
29 silly pacote remote manifest for isemail@https://registry.npmjs.org/isemail/-/isemail-1.2.0.tgz fetched in 12ms
30 http fetch GET 200 https://registry.npmjs.org/joi/-/joi-6.10.1.tgz 3ms (from cache)
31 silly pacote remote manifest for joi@https://registry.npmjs.org/joi/-/joi-6.10.1.tgz fetched in 17ms
32 http fetch GET 200 https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-7.4.1.tgz 3ms (from cache)
33 silly pacote remote manifest for jsonwebtoken@https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-7.4.1.tgz fetched in 25ms
34 http fetch GET 200 https://registry.npmjs.org/jwa/-/jwa-1.1.5.tgz 1ms (from cache)
35 silly pacote remote manifest for jwa@https://registry.npmjs.org/jwa/-/jwa-1.1.5.tgz fetched in 3ms
36 http fetch GET 200 https://registry.npmjs.org/jws/-/jws-3.1.4.tgz 2ms (from cache)
37 silly pacote remote manifest for jws@https://registry.npmjs.org/jws/-/jws-3.1.4.tgz fetched in 4ms
38 http fetch GET 200 https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz 2ms (from cache)
39 silly pacote remote manifest for lodash.once@https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz fetched in 4ms
40 http fetch GET 200 https://registry.npmjs.org/moment/-/moment-2.18.1.tgz 3ms (from cache)
41 silly pacote remote manifest for moment@https://registry.npmjs.org/moment/-/moment-2.18.1.tgz fetched in 39ms
42 http fetch GET 200 https://registry.npmjs.org/ms/-/ms-2.0.0.tgz 2ms (from cache)
43 silly pacote remote manifest for ms@https://registry.npmjs.org/ms/-/ms-2.0.0.tgz fetched in 4ms
44 http fetch GET 200 https://registry.npmjs.org/promise-polyfill/-/promise-polyfill-6.0.2.tgz 1ms (from cache)
45 silly pacote remote manifest for promise-polyfill@https://registry.npmjs.org/promise-polyfill/-/promise-polyfill-6.0.2.tgz fetched in 3ms
46 verbose stack TypeError: Cannot read property 'find' of undefined
46 verbose stack     at opts.integrity.digests.find.hash (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:264:33)
46 verbose stack     at Array.find (native)
46 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:263:15)
46 verbose stack     at emitNone (events.js:110:20)
46 verbose stack     at Transform.emit (events.js:207:7)
46 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
46 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
46 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
47 verbose cwd /Users/smorin/Dropbox/code/active/loginpoc/firelogin
48 verbose Darwin 15.5.0
49 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "firebaseui" "-save"
50 verbose node v8.0.0
51 verbose npm  v5.0.2
52 error Cannot read property 'find' of undefined
53 verbose exit [ 1, true ]

**Comment by bojeil-google** [comment]
I don't think this is an issue on our end.  A similar issue was reported here: https://github.com/firebase/firebase-js-sdk/issues/51 I would suggest updating your node/npm versions and try again.

**Comment by smorin** [comment]
This problem is now gone with:
npm 5.0.3
node v8.1.2
