### ISSUE TITLE
'Popup' Sign in Flow is not Working on Chrome

### ISSUE THREAD

**Issue by maryam-abdullah** [firebase/firebaseui-web#170]
Hello, I'm using the below code and logging in happens in a new tab and not as a pop-up in Chrome. It works normally in Firefox.

```
firebase.initializeApp(config);

var uiConfig = {
    callbacks: {
          signInSuccess: function (user, credential, redirectUrl) {
            }
    },
            credentialHelper: firebaseui.auth.CredentialHelper.ACCOUNT_CHOOSER_COM,
            queryParameterForSignInSuccessUrl: JS_RESOURCES.FrontUrl,
            signInFlow: 'popup',
            signInOptions: [
                firebase.auth.GoogleAuthProvider.PROVIDER_ID,
                firebase.auth.FacebookAuthProvider.PROVIDER_ID,
                firebase.auth.TwitterAuthProvider.PROVIDER_ID
            ]
};

var ui = new firebaseui.auth.AuthUI(firebase.auth());
ui.start('#firebaseui-auth-container', uiConfig);
```

Thanks.

**Comment by bojeil-google** [comment]
It's not on our end. This behavior change happened after upgrading to the latest Chrome version 59. We just call something like: 
`window.open('about:blank', '_blank', 'width=515,height=680,top=260,left=702,location=1,resizable=1,statusbar=1,toolbar=0');`

It works everywhere except the latest version of chrome.

**Comment by maryam-abdullah** [comment]
Yes, actually it was working fine. Days ago, it suddenly stopped. So, there's nothing we can do but wait for another update of Chrome. Right? 
Thanks anyways.

**Comment by channing-google** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=723655

**Comment by hbgconstable** [comment]
I'm getting a "This browser is not supported" with signInFlow set to default ('redirect') in Chrome. Is this related to the same issue?

**Comment by bojeil-google** [comment]
No it is not the same issue. You probably have 3rd party cookies and data disabled in your chrome settings.

**Comment by hbgconstable** [comment]
You're right. Sorry, should have looked at that first. I guess Google just decided to change that setting on my behalf!?! Thanks for the response.

**Comment by bojeil-google** [comment]
By the way, this bug was fixed on Chrome. Popup mode should now behave as expected.

**Comment by lukecwilliams** [comment]
@bojeil-google Do you have a reference for this?  I don't want to implement pop-up auth if some of my users are on an older version of Chrome and may have this functionality broken.  Disabling third party cookies is a recommended security practice.

**Comment by bojeil-google** [comment]
Hey @lukecwilliams, this issue was regarding popup behavior.

**Comment by PawanGulati** [comment]
@bojeil-google how to fix this about:blank pop up issue, coming after running SignInWithPopup method
No email selection options were coming just a blank pop up.
``` firebase.initializeApp(firebaseConfig)
  export const auth = firebase.auth()
  export const firestore = firebase.firestore()

  const provider = new firebase.auth.GoogleAuthProvider()

  provider.setCustomParameters({prompt: 'select_account'})

  export const SignInGoogle = () => auth.signInWithPopup(provider) 
```
and called SignInWithGoogle onClick but giving a blank pop up
