### ISSUE TITLE
https://github.com/firebase/firebaseui-web#developer-setup 

### ISSUE THREAD

**Issue by EmberJSParis** [firebase/firebaseui-web#173]
One of the Firebase support Engineers told me that the code here https://github.com/firebase/firebaseui-web#developer-setup doesn't work with EmberJS because the EmberJS is not directly affiliated with Firebase. It seems to me strange as the code here should work independent of the framework. Is anyone tested the Authentication code of Firebase here https://github.com/firebase/firebaseui-web#developer-setup ? Thanks
PS: I got a reply to use https://github.com/rmmmp/emberfire-utils#firebaseui but is still not working, normally https://github.com/firebase/firebaseui-web#developer-setup  should be independent of the framework

**Comment by nicolasgarnier** [comment]
This should work in any web apps as long as they are hosted in an HTTP/HTTPS environment.
