### ISSUE TITLE
Problems with UI buttons

### ISSUE THREAD

**Issue by sertony** [firebase/firebaseui-web#174]
I use FirebaseUI to display phone number based authentication and apperantly I experience some visual problems with verify and cancel button. Look at the image attached.

The problem appears only when I use https://cdn.firebase.com/libs/firebaseui/2.2.0/firebaseui.css file
Everything is fine when using https://cdn.firebase.com/libs/firebaseui/2.1.0/firebaseui.css.

<img width="596" alt="2017-06-20 18 46 27" src="https://user-images.githubusercontent.com/3024361/27342696-93a11074-55e9-11e7-838e-e8ae4c8c097a.png">

**Comment by channing-google** [comment]
Thanks for the report! What browser is this?

**Comment by sertony** [comment]
@channing-google I've tested it on Safari (Mac OS).
