### ISSUE TITLE
Firebase Login with Facebook & Twitter Returns Empty Email

### ISSUE THREAD

**Issue by maryam-abdullah** [firebase/firebaseui-web#176]
I'm getting an empty (null) email when signing in with Facebook & Twitter.
Option "Multiple accounts per email address" is enabled.

Thanks.

**Comment by maryam-abdullah** [comment]
I solved it by replacing "user.email" by "user.providerData[0].email".

**Comment by bojeil-google** [comment]
This is expected. For multiple accounts per email, the top level email is null except for password accounts. If you want to solve it, either switch back to "one account per email" or manually set the top level email via updateEmail API, though be aware this field has to be unique so only one user has the same email.
