### ISSUE TITLE
This operation is not supported in the environment this application is running on. "location.protocol" must be http, https, or chrome-extension and web storage must be enabled.

### ISSUE THREAD

**Issue by Jaronloch2** [firebase/firebaseui-web#178]
Hi, I'm using cordova and followed firebase, firebaseUI tutorials like a bible.
I successfully created the web part of the App which uses Google Auth / OAuth.
I can also manipulate the User data from the browser.

The problem is when I build it via `cordova build android` and install it on my android phone;
I get this error:

>  This operation is not supported in the environment this application is running on. "location.protocol" must be http, https, or chrome-extension and web storage must be enabled. Dismiss

I could not find any solution from google, my hair is almost gone and Auth is a must in my app.
Cordova is using File (file://) protocol if I'm not mistaken. And I think, God-forbid, firebase does not like that protocol using any Authentication method. I also found out that firebase SDK just had an update 15 hours ago that has Auth updates. I updated to that version (4.1.2 to 4.1.3) but still, no luck.

Facebook and Google Sign In works in a Computer Browser and there's no problem.

Is anybody experiencing or have solved this? Please enlighten me.

**Comment by bojeil-google** [comment]
Hey @Jaronloch2, I'd love to help you. I have helped others get their app to work in Cordova:
https://github.com/firebase/firebaseui-web/issues/172
https://github.com/firebase/firebaseui-web/issues/171
They did not report this issue. Are you doing any modifications from the default settings of Cordova?
Make sure the user agent is not modified. Also the SDK will listen to 'deviceready' event. If it doesn't get that signal in like a second, it times out and assumes you are not running in Cordova environment. Also make sure you did not disable web storage as the app relies on that.

**Comment by Jaronloch2** [comment]
Hi @bojeil-google !

Thank you for your willingness to help, I appreciate it. Regarding your questions:

Are you doing any modifications from the default settings of Cordova?

> No, I only followed the tutorials from the firebase website, and most likely they wont teach a beginner to modify the default settings.

Make sure the user agent is not modified

> No user agent has been set by me. I expect it's automatically set.

Also the SDK will listen to 'deviceready' event

>I wrapped FirebaseUI on Angular and I suppose angular won't run if the device is not ready?

Also make sure you did not disable web storage

> How and where can I set this properly on cordova?


Honestly, I just started cordova last weekend so I am a newbie, please bear with me. 😄

**Comment by Jaronloch2** [comment]
Here is my setup:

``` javascript
var config = {
		apiKey: "somerandom-string",
		authDomain: "myapp.firebaseapp.com",
		databaseURL: "https://myapp.firebaseio.com",
		projectId: "myapp",
		storageBucket: "myapp.appspot.com",
		messagingSenderId: "1234567890"
	  };
firebase.initializeApp(config);
var uiConfig = {
	callbacks: {
		signInSuccess: function(user, credential, redirectUrl) {
			if(user){
				angular.element('.player-views #player-email').html(user.email);
				alert(user.email);
			}else{
				angular.element('.guest-views').show();
				angular.element('.player-views').hide();
				alert('NO USER');
			}
			$rootScope.user	= user;
			console.log($rootScope.user)
			return true;
		},
	},
	signInOptions: [
	  firebase.auth.GoogleAuthProvider.PROVIDER_ID,
	  firebase.auth.FacebookAuthProvider.PROVIDER_ID,
	],
	signInFlow: 'redirect'
}; 
var ui = new firebaseui.auth.AuthUI(firebase.auth());
ui.start('#firebaseui-auth-container', uiConfig);
```

I'm calling that on my Angular controller just right after it initiallizes.
Firebase is initialized properly as my console.log there returns null and user data on the computer browser.

Also, in the android build
window.cordova returns an object
document.URL.indexOf('http://') returns -1
document.URL.indexOf('https://') returns -1
document.URL.indexOf('file://') returns 0

I found this issue that is I think identical to mine, but he did not state how he actually fixed his problem.
https://stackoverflow.com/questions/44651423/oauth-signin-cordova-firebase

**Comment by bojeil-google** [comment]
You need to isolate the issue. Can you first render FirebaseUI without angular? Most of the times the issue is from something else. Also if you are building from scratch (new Cordova app), add the FirebaseUI and firebase.initializeApp() code in the www/js/index.js after `app.initialize();` Let me know if this helps.

**Comment by Jaronloch2** [comment]
Goodness me, you are right! It actually worked when I tried it without angular and put inside index,js.  I'll remove the noose from my neck now. Thanks @bojeil-google !

**Comment by EdgarAmador82** [comment]
Buenas tardes Jaronloch2 

Podiras compartirme parte de tu solucion, en estos momentos se me esta presentando este inconveniente, me alegra tengas superado, muchas gracias https://github.com/Jaronloch2

**Comment by mvinib** [comment]
Estou com 

> Oi, estou usando cordova e seguido firebase, firebaseUI tutoriais como uma bíblia.
> Criei com sucesso a parte web do App que usa o Google Auth /OAuth.
> Eu também posso manipular os dados do Usuário a partir do navegador.
> 
> O problema é quando eu construí-lo via e instalá-lo no meu telefone android;
> Eu entendo este erro:`cordova build android`
> 
> > Esta operação não é suportada no ambiente em que este aplicativo está sendo executado. "location.protocol" deve ser http, https ou a extensão cromada e o armazenamento web devem ser ativados. Demitir
> 
> Não consegui encontrar nenhuma solução do Google, meu cabelo está quase desaparecido
> e a Auth é uma obrigação no meu aplicativo. Cordova está usando protocolo File (file://) se não me engano. E eu acho que, Deus me livre, base de fogo não gosta desse protocolo usando qualquer método de autenticação. Também descobri que o Firebase SDK tinha uma atualização há 15 horas que tem atualizações da Auth. Atualizei para essa versão (4.1.2 a 4.1.3), mas ainda assim, sem sorte.
> 
> Facebook e Google Sign In funciona em um navegador de computador e não há problema.
> 
> Alguém está experimentando ou resolveu isso? Por favor, me ilumine.

Estou com este mesmo problema em react native. Consigo realizar o login no WebBrowser, mas quando vou testar no celular, recebo o mesmo erro. Alguém sabe como resolver esse problema?
