### ISSUE TITLE
firebaseui-auth-container not showing up after signing out

### ISSUE THREAD

**Issue by ronyjacobson** [firebase/firebaseui-web#18]
Hi,
I used your manual to add authentication.

I managed to sign in a user, and remove the firebaseui-auth-container.
But when I'm signing out, the firebaseui-auth-container doesn't show back up.

If I go to my app when i'm already signed in, then press sign out, it works and I see the firebaseui-auth-container.

Source:
https://github.com/ronyjacobson/she-codes-tracks--

**Comment by bojeil-google** [comment]
Hey Rony, currently, firebaseui-auth cannot be re-rendered on the same page (show sign in widget on sign in, hide on sign in completion, show sign in widget again after sign out). It has not yet been optimized for single page application. For now if you are using a single page application, you will need to render the sign in widget in a popup whenever a sign in attempt is initiated.

**Comment by ronyjacobson** [comment]
Thanks for the response,
Will try to do so :)

**Comment by gbittmann** [comment]
If the sign-in widget should be in a pop up shouldn't that be mentioned in the readme, possibly with an example?

**Comment by TMSCH** [comment]
I have added the mention in the Readme, and the upcoming release will have a solution for this issue.

Closing as #30 is tracking the same issue.
