### ISSUE TITLE
"Cannot read property 'PROVIDER_ID' of undefined" error on version 2.1.1

### ISSUE THREAD

**Issue by geooot** [firebase/firebaseui-web#183]
For some reason, when clicking on any button results on this JavaScript error
```
firebaseui.js:331 Uncaught TypeError: Cannot read property 'PROVIDER_ID' of undefined
    at firebaseui.js:331
    at b (firebaseui.js:331)
    at firebaseui.js:73
    at ol.<anonymous> (firebaseui.js:273)
    at cf (firebaseui.js:148)
    at Bg.h.dispatchEvent (firebaseui.js:147)
    at Dg (firebaseui.js:184)
    at Bg.Tc (firebaseui.js:183)
    at af (firebaseui.js:144)
    at HTMLButtonElement.We (firebaseui.js:145)
```

My initialization code:
```
<script>
          var config = window.settings.FirebaseCredentials;
          firebase.initializeApp(config);
</script>
<script src="https://cdn.firebase.com/libs/firebaseui/2.1.1/firebaseui.js"></script>
<script>

   var uiConfig = {
        signInSuccessUrl: "/",
        signInOptions: [
            // Leave the lines as is for the providers you want to offer your users.
            firebase.auth.GoogleAuthProvider.PROVIDER_ID,
            firebase.auth.GithubAuthProvider.PROVIDER_ID,
            firebase.auth.TwitterAuthProvider.PROVIDER_ID,
            firebase.auth.FacebookAuthProvider.PROVIDER_ID
        ],
        tosUrl: "http://howlbits.com"
    };

    // Initialize the FirebaseUI Widget using Firebase.
    var ui = new firebaseui.auth.AuthUI(firebase.auth());
    // The start method will wait until the DOM is loaded.
    ui.start('#firebase-auth-container', uiConfig);
...
```

**Comment by geooot** [comment]
Found out the issue:

Firebase sdk was at version 3.3.3 updating it to the latest version solved the problem

**Comment by AnaghaJais** [comment]
Hi,how did you update to new version.I am also facing the same issue.I am using 4.1.3 firebase sdk.

**Comment by israelidanny** [comment]
I can confirm that this happens to me in the latest sdk version.

**Comment by wti806** [comment]
@israelidanny  Can you provide the version of firebaseui and firebase sdk you are using?

**Comment by geooot** [comment]
For me it is working with Firebase Version: 4.1.2, Firebase UI Version: 2.2.1

**Comment by ChrisBlueSpurs** [comment]
firebase 5.0.4 & firebaseui 3.0.0 getting this same error.

**Comment by dewetvdm** [comment]
For those of you facing this issue I realised when initialising firebase, this causes the issue.

This works for me

`
import firebase from 'firebase';
import firebaseui from 'firebaseui';

const firebaseAuthObj = firebase.auth;

const config = { ... };

firebase.initializeApp(config);

const ui = new firebaseui.auth.AuthUI(firebase.auth());

const uiConfig = {
    ...
    signInOptions: [firebaseAuthObj.GoogleAuthProvider.PROVIDER_ID],
    ...
};
`

Note when setting `signInOptions` for `uiConfig`, I reference the `firebaseAuthObj`

**Comment by elayers** [comment]
Adding  <script src="https://www.gstatic.com/firebasejs/6.3.2/firebase-auth.js"></script> worked for me

**Comment by inform880** [comment]
I'm having the same issue. I'm using the exact same example found here: https://github.com/firebase/firebaseui-web-react, except I'm using email provider, and I'm importing firebase from my config file, set up like so: 
```
import firebase from "firebase/app";
import "firebase/auth";
import "firebase/storage";

const firebaseConfig = {
...
};

const app = firebase.initializeApp(firebaseConfig);

export default app;
```
Does anyone have any idea why this would be happening? I'm on the latest version of firebase.

**Comment by microwriting** [comment]
`import firebaseui from 'firebaseui';`
I was using the above and it didn't work, but
The following worked fine.
`import * as firebaseui from 'firebaseui'`
