### ISSUE TITLE
Not enough color contrast when buttons have focus

### ISSUE THREAD

**Issue by code-tree** [firebase/firebaseui-web#185]
![image](https://user-images.githubusercontent.com/11289719/27719688-736f1dcc-5d97-11e7-9256-512d61e4bbf5.png)

Here Facebook has focus (tabbed). Most buttons have white text which is too hard to read when they have focus and are given a grey background.

**Comment by bojeil-google** [comment]
Hey @code-tree, this should be fixed in https://github.com/firebase/firebaseui-web/releases/tag/v2.3.0
