### ISSUE TITLE
Getting A network error has occurred dismiss

### ISSUE THREAD

**Issue by xerosanyam** [firebase/firebaseui-web#186]
Everything was working fine but suddenly started getting this error.
No clue on how to fix this. Removed cookies too, no effect.

**Comment by bojeil-google** [comment]
There are like 20 reasons why network errors could occur. I will list a few:
1. Network connection is down (app is offline).
2. Network connection is unstable or slow(poor network connection)
3. Some privacy chrome extensions can block certain connections unless whitelisted, etc.
4. Service workers with caching can block the embedding of the OAuth iframe which results in a network connection error.
5. Content Security Policies can also block connections to certain endpoints unless those endpoints are white-listed.
6. Anti-virus, firewalls can be too restrictive and block these connections.

There are many more reasons but I will keep it short.

Please provide details on your issue. The first thing you need to do is report network logs. That is the first thing you need to inspect. Check the network call that is failing and please report it with full details.

**Comment by xerosanyam** [comment]
Thank you, will do that once I get the error again :)

**Comment by kenara** [comment]
I am getting this error intermittently on Chrome (Ubuntu 16.04). This appears to be an old issue but none of the solutions or explanations I've seen have helped me. Not that I care about myself, I'm more worried for my users...

**Comment by mauronr** [comment]
Does FirebaseUI (or maybe Firebase auth) have any anti-bot detection? We have session recorder in our webapp and have noticed cases of this error message. In all of them it was a bot trying to log in. We can tell it's a bot because the clicking pattern is exactly the same in all sessions.
