### ISSUE TITLE
Change color of progress bar while redirecting

### ISSUE THREAD

**Issue by xerosanyam** [firebase/firebaseui-web#187]
While signing in, page redirects to link similar to https://abcd.firebaseapp.com/__/auth/handler?code=xxx
and shows a blank page with a purple color progress bar on top.
Is there a way to change content of this page ? 
or atleast color of progress bar ??

**Comment by bojeil-google** [comment]
No, this is not customizable. It is only a temporary progress bar as we redirect back and forth in the OAuth handshake. The page in a good connection will only be visible for a fraction of a second and in some cases too fast to be noticed by the human eye.

**Comment by wcandillon** [comment]
I hope this color will be customizable at some point to match the website brand.

**Comment by enchorb** [comment]
Any updates on customizing the color?

**Comment by marcusarnfast** [comment]
Yeah would be nice!
