### ISSUE TITLE
Phone auth pass data to redirect

### ISSUE THREAD

**Issue by zavod** [firebase/firebaseui-web#188]
How can I pass currentUser and credential to the redirectUrl? 
I have Python Django web stack and use Python Social Auth with social auth backend. I need to save userPhone to the database and auth user on the website after Phone verification. 
For GetDigits it was pass header: 
`X-Verify-Credentials-Authorization` with credentials information
How can I use your app by same way?

**Comment by bojeil-google** [comment]
I am not familiar with how Digits used to do this.
However, generally, you can just define your own logic to handle that in signInSuccess callback:
```
var uiConfig = {
  callbacks: {
    signInSuccess: function(currentUser, credential, redirectUrl) {
      // If you need to pass data to your backend, you will need to send the ID token.
      currentUser.getIdToken().then(function(idToken) {
        // You can add the ID token to the header, or postBody, etc.
        // For simplicity, let's append it to the URL.
        window.location.assign('http://yourSignInSuccessUrl/?idToken=' + idToken);
        // You will need to use the Python Admin SDK to verify the ID token and get the info from within it.
        // Check: https://firebase.google.com/docs/auth/admin/verify-id-tokens
      }).catch(function(error) {
        console.log(error);
      });
       // Do not automatically redirect.
       return false;
    },
  },
  ...
};
```

**Comment by zavod** [comment]
Thank you! It works for me

**Comment by bojeil-google** [comment]
Cool, glad it works.

**Comment by mido1677** [comment]
Thank you! I searched about this code long time and finally found him thank you very much
