### ISSUE TITLE
[ASK]back to main page or login page FirebaseUI after logout from Firebase ?

### ISSUE THREAD

**Issue by adeguntoro** [firebase/firebaseui-web#190]
hai, as you we see when i login, firebaseUI will send me to another page, but how i can back into my login page after sign out from Firebase ?
i try to implement from demo, but, i still dont understand.

**Comment by morganchen12** [comment]
Please move this issue to the [FirebaseUI-iOS](https://github.com/firebase/FirebaseUI-iOS/issues) repo.
