### ISSUE TITLE
No options in signInOptions to fix phone number

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [firebase/firebaseui-web#191]
It means the authentication will be done for the phone number and country code provided and that will not be changed by user (at the time of authentication).

1.) User will enter phone number (In custom input field, probably at the time of signup).
2.) Then we will ask for authentication of that phone - the user will not enter that number. We will fix the phone number and country code, so as to verify the user needs to enter verification code.

**Comment by bojeil-google** [comment]
Are you saying we should provide an option to pre-fill the phone number via some config field?

**Comment by AnkitMaheshwariIn** [comment]
Yes, or in signInOptions. So the authentication of given number could be possible. In that case we are not allowing user to change Phone number and Country code from UI.

**Comment by bojeil-google** [comment]
I see, let me discuss this with the other platform owners. When more than one provider is configured, we always start with the NASCAR screen (the one with all the buttons). When the user clicks `sign in with phone` they are taken to the phone sign-in. Populating a default number there is not typical. However, I see the value of that when only phone number provider is used which would skip the NASCAR screen. If we want to provide that, we should do it for the 3 platforms (web, Android and iOS).

**Comment by AnkitMaheshwariIn** [comment]
Ok, Thanks!

**Comment by dozer47528** [comment]
We also need the pre-fill phone number.
We migrated our phone number signup from Digits, and Digits can pre-fill the phone number.

Please add this feature.
Thanks!

**Comment by AnkitMaheshwariIn** [comment]
@bojeil-google - Is any work progress on pre-fill phone number. Is this feature added or any hope..?

**Comment by bojeil-google** [comment]
Hey @AnkitMaheshwariIn, if it were up to me, I would support this for when phone number provider is the only provider available (this skips the nascar screen and shows the phone sign-in screen directly). However, I think auto populating the phone number after the nascar screen (multiple providers enabled) is shown and the user clicks `sign in with phone number` is bad UX (should be disabled there). Anyway, this would provide feature parity with Digits developers. I would say there is hope for this. I need to run this by the team (we need to provide this for the 3 platforms) and then I can get back to you.

**Comment by bojeil-google** [comment]
This should be fixed in the latest release:
https://github.com/firebase/firebaseui-web/releases/tag/v2.4.0
You have the option to pass the full number or the country ID and national number components.

**Comment by AnkitMaheshwariIn** [comment]
@bojeil-google  Thanks a lot!
