### ISSUE TITLE
Feature Request: Add a callback for newly signed up users

### ISSUE THREAD

**Issue by johnson-yeap** [firebase/firebaseui-web#193]

**Comment by bojeil-google** [comment]
This is a limitation in the underlying Firebase core SDK. The feature request has already been filed. Once this is supported, we will update FirebaseUI to expose that information. I will update this thread on any update.

**Comment by johnson-yeap** [comment]
@bojeil-google
 Awesome! Glad to know!
 Can't wait!

**Comment by quincycs** [comment]
Any progress?  Thanks

**Comment by bojeil-google** [comment]
It's in the queue. We prioritized this feature request higher: https://github.com/firebase/firebaseui-web/issues/22 but as soon as that is done, we will implement this.

**Comment by nicolasgarnier** [comment]
Looks like now that `.isNewUser` is supported in the SDK this can be implemented. Assigning to you @bojeil-google !

**Comment by bojeil-google** [comment]
This should be fixed now. Starting in https://github.com/firebase/firebaseui-web/releases/tag/v2.7.0, we exposed a new callback that triggers with a `UserCredential` which can be used to check for `isNewUser`.
