### ISSUE TITLE
Cordova - Google sign in doesn't redirect back to app.

### ISSUE THREAD

**Issue by finppp** [firebase/firebaseui-web#195]
On sign in with Google, the app redirects to browser, then after sign in loads the app in the browser.

It does not redirect you back to the app. (which is what I expected)

When you navigate back to the app. Firebaseui says: "The redirect operation has been cancelled by the user before finalizing"

It does not log you in on the browser or app version.

I can sign in perfectly with email+pw, but not Facebook or Google

**Comment by bojeil-google** [comment]
It appears you have not set up Firebase Dynamic Links (android) or your custom scheme (iOS) correctly. Please make sure you follow the instructions stated here:
https://firebase.google.com/docs/auth/web/cordova

**Comment by finppp** [comment]
Hi there

I am confused exactly what the documentation requires me to do.

In step "4. Enable Firebase Dynamic Links:" 
Do you have to actually create a dynamic link? What I assumed was that you had to begin creating a link and then "Go back to the main Dynamic Links dashboard", without completing the link creation. This successfully displayed my Dynamic Link Domain.

I am then confused as how step 7 and beyond works. does the `<path url=>` in the `<universal-links>` have to be anything specific? I just used the snipped from the docs: `<path url="/__/auth/callback"/>`
Does this need to be related to the dynamic link I have created in step 4?

Thanks

**Comment by finppp** [comment]
I can now successfully sign in using Facebook, however Google sign-in seems to redirect to a new web-view, leaving both web-views signed out. 

Each sign in redirects to a new instance of web-view so after three sign in attempts I have this:

![webviews](https://user-images.githubusercontent.com/15324432/28620094-6a1158e6-7203-11e7-8162-fa16b2736126.PNG)

**Comment by bojeil-google** [comment]
4. you need to consent to the terms of service of FDL. If you can see your FDL domain (looks like: https://xyz.app.goo.gl) you are good to go.
7. It is pretty clear, you go to config.xml and update the following:
```
<universal-links>
    <host name="xyz.app.goo.gl" scheme="https" />
    <host name="my-app.firebaseapp.com" scheme="https">
        <path url="/__/auth/callback"/>
    </host>
</universal-links>
```
Where xyz.app.goo.gl is the FDL domain.
my-app.firebaseapp.com is your authDomain (you can get that from your Firebase web snippet).

If you don't configure these correctly, obviously the redirect will not work.

Also make sure if you are using Android, that launchMode setting: https://developer.android.com/guide/topics/manifest/activity-element.html#lmode is set to singleInstance.

**Comment by finppp** [comment]
In that case, I have done everything correctly, however google sign-in does not work.

**Comment by bojeil-google** [comment]
singleInstance is supposed to prevent that. I don't have enough data on your situation. Try changing to singleTask.
https://github.com/firebase/firebaseui-web/issues/171 had a similar problem where one was working but not the other. Please take a look.

**Comment by finppp** [comment]
`<preference name="AndroidLaunchMode" value="singleTask" />`
Did the job. 

Thankyou very much Bojeil!

**Comment by larssn** [comment]
Having the same problem, sadly `<preference name="AndroidLaunchMode" value="singleTask" />` doesnt work.

**Comment by larssn** [comment]
Now here's a funny tidbit: When we disconnect from WIFI and connect the android device to 3G/4G. It no longer stalls in the redirect back!?

Any ideas why that would be?

**Comment by larssn** [comment]
This happened on all the android devices we've tested, and only android. As I stated, browsers and iOS devices work.

**Comment by yoav-zibin** [comment]
@finppp can you attach your config.xml ?
I have the same issue that after I login it opens a new webview:
![image](https://user-images.githubusercontent.com/1890589/33234551-dc30e2e0-d1f6-11e7-8c4c-3e45a2aa773b.png)
and neither singleTask nor singleInstance helped.

I'm using PGB (phonegap build), and this my setup:
![image](https://user-images.githubusercontent.com/1890589/33234560-027a2682-d1f7-11e7-9977-15e3fc963b3c.png)
[config.txt](https://github.com/firebase/firebaseui-web/files/1503378/config.txt)

**Comment by yoav-zibin** [comment]
Oh, I found this issue https://github.com/firebase/firebaseui-web/issues/203 that says the problem is with PGB (phonegap build) with plugin cordova-universal-links-plugin. Issue still open :(
