### ISSUE TITLE
Is there a way to change google logo ?

### ISSUE THREAD

**Issue by xerosanyam** [firebase/firebaseui-web#196]
I want to change the logo
https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg
to something of my choice..

Also Sign in with email to Sign in with Email. 
is this possible ?

**Comment by bojeil-google** [comment]
Unfortunately, it is not easy to customize labels and logos in the UI without forking it and modifying the source code.
For the logo button, this is the recommended Google logo (Firebase is owned by Google).
Now that FirebaseUI is internationalized, it is not easy modifying labels as they are translated to many languages that FirebaseUI now supports.
Of course you can always use some hack to modify the FirebaseUI dom content on the page but you will need to do that at your own risk and make sure you don't break other components.
