### ISSUE TITLE
firebase create user by email not returning displayName using ui 2.3.0

### ISSUE THREAD

**Issue by jm93** [firebase/firebaseui-web#197]
seeing this issue closed several times in here, I am little shocked I have to post this issue.

using a simple firebase function, and using code very similar to the example here: https://firebase.google.com/docs/reference/functions/functions.auth.UserBuilder#onCreate

and using the sign in by email method on the firebase ui, and having the user sign up with first and last name,

my firebase function:
```
exports.createAccount = functions.auth.user().onCreate(function(event) {
	const data = event.data;
	console.log(data);
});
```

and the firebase function log shows me:
```
{ email: 'yoda@example.com',
  metadata: 
   { createdAt: 2017-07-28T14:29:08.000Z,
     lastSignedInAt: 2017-07-28T14:29:08.000Z },
  uid: 'xxxxxxxxxxx' }
```
where is yoda's displayName (should be: Yoda Yo) which he entered in firebase ui?

And, so if I used the entire example in the link I posted above, how am I supposed to send yoda a personalized sign up email using his first name, when firebase ui doesn't even return it?

**Comment by bojeil-google** [comment]
The Firebase function `onCreate` triggers immediately after the user is created. For an email/password, this is the `createUserWithEmailAndPassword`. We then call a separate API to `updateProfile` with the user's display name. By the time you get the event triggered (at `createUserWithEmailAndPassword`), the display name has not been set yet.

**Comment by jm93** [comment]
okay then. thanks for this new info. 

how about somewhere, the firebase team mention in ui or user creation documentation that email sign up does not act as expected or the same as other provider sign up. or fix it so they all work the same, ie don't return a user until all profile info like displayName is ready.

adding a new entry to my book "Coding Blind with Firebase Documentation".

**Comment by bojeil-google** [comment]
By the time the `getUser` Admin request resolves, the client `updateProfile` operation must have resolved. You could always add some short delay (in milliseconds) to make sure `updateProfile` has time to resolve.

Typically when you sign in with all federated providers (Google, Facebook, Twitter, GitHub), the display name is immediately populated and the displayName immediately available `onCreate`. 
For password sign up, the `displayName` is not always required. Many developers don't even want to force users to provide their name on password sign up. FirebaseUI makes it an optional field (after many developers requested that).

You can always add an HTTP endpoint with Firebase Functions after the sign-up operation resolves and send the ID token along to send the welcome email. You have a lot of options.

**Comment by jmnyv** [comment]
I have a functional setup using a delay, but it does create a race condition. It seems a nicer solution would be to add an onUpdate trigger on the UserBuilder object.

` functions.auth.user().onUpdate(...)`

**Comment by Dayjo** [comment]
onUpdate on auth is vital. 

I actually don't understand how there's no way to make this flow the same across providers. Also, no idea why this issue is closed. @bojeil-google saying "You have a lot of options" is a weird response. IMO this is a bug, that there's no way to handle it nicely. Adding a delay to code specifically to handle this is horrible :/

**Comment by mackelito** [comment]
@Dayjo a bit late I know :P ..
I think that the idea is that you first do a auth then fetch the user data.. Perhaps not Ideal in most cases but still..
