### ISSUE TITLE
Some errors being swallowed

### ISSUE THREAD

**Issue by code-tree** [firebase/firebaseui-web#198]
Firebase UI appears to swallow some errors, making it frustrating to debug. For example, it has been failing at [this line](https://github.com/firebase/firebaseui-web/blob/e01d04d46084066d8eaf83ddd8ee83723fb3cb18/javascript/widgets/handler/common.js#L479) and no error is shown in console. The signin process works without problems until completion where it shows a progress bar, the progress bar then disappears, and the app does nothing. It just sits there, not signed in, but not showing any errors.

After putting a `try` block around the problem, it reports:

```{code: "auth/argument-error", message: "signInWithCredential failed: First argument "credential" must be a valid credential."}```

Then inspecting the credential, it is:

```xg {Db: "user@domain", td: "password", providerId: "password"}```

I assume uglify has made Firebase UI out of sync with Firebase, but I don't know which is the cause, or how to resolve. Any ideas much appreciated, but making this issue because Firebase UI should have thrown the error rather than swallowing it (causing me hours of debugging fun :disappointed:).

**Comment by bojeil-google** [comment]
Can you describe how to recreate this? Are you simply signing in with an email and password? The credential should contain some other function within it. I am not sure why it is not there. That is what throws the error.

**Comment by code-tree** [comment]
Yes, just signing in with email and password (though other signins don't work yet either). It was working for a while but then, I think after upgrading packages, it stopped working.

Ok, so I think I worked it out. I'm using Angular CLI + AngularFire + AngularUI. Two copies of Firebase were getting pulled in (one by AngularFire and one by AngularUI). I was passing an AngularFire auth instance to AngularUI which then used it with its own copy of Firebase API, causing mismatches.

I was importing FirebaseUI via `import * as FirebaseUI from 'firebaseui'` which brings in the `npm.js` version that also brings in a copy of Firebase. What is the correct procedure for importing FirebaseUI in Angular2+ without bringing in Firebase again?

Many thanks

**Comment by bojeil-google** [comment]
Hmm, yeah FirebaseUI already pulls the Firebase dependency. I am not too familiar with AngularFire packaging. Ideally you want one copy. Worst case, you can build firebaseUI npm on your own and remove the firebase require: https://github.com/firebase/firebaseui-web/blob/master/gulpfile.js#L36

**Comment by code-tree** [comment]
Ok, I've solved it with the following (run before Angular bootstraps):

```typescript
import * as firebase from 'firebase/app'

// Attach firebase to window so FirebaseUI can access it
(<any>window).firebase = firebase

// Import FirebaseUI standalone (as its npm.js file causes double firebase code)
import 'firebaseui/dist/firebaseui'  // Imports for side effects only

// Declare `window.firebaseui` that the above import creates
declare global {
    const firebaseui
}
```

(I'll leave this open as it would still be helpful if FirebaseUI doesn't swallow errors for future debugging)

**Comment by nicolasgarnier** [comment]
FYI firebase is now a peer dependency rather than a dependency so the double import issues shouldn't happen because of firebaseui anymore.

Assigning to @bojeil-google regarding the error swallowing issue.

**Comment by bojeil-google** [comment]
This should be fixed now. Please re-open if you have any problems.
