### ISSUE TITLE
Cordova - Social Logins' redirect stalls on Android only

### ISSUE THREAD

**Issue by larssn** [firebase/firebaseui-web#200]
Hello

So we're in a situation where our Cordova app can't use the social logins in firebase.
We've followed the guide at https://firebase.google.com/docs/auth/web/cordova.

It works on iOS and in browsers (with a minor caveat for Chrome, being you have to disable an experimental flag - "QUIC").

We've looked into #195 and #171, and no solution was found there.

Inspecting the Cordova app's login window reveals that it hangs on the following request, which is pending until it "times out" after 1 min, with a status 200:

`https://www.googleapis.com/identitytoolkit/v3/relyingparty/createAuthUri?key=<removed our key>`

After that, it hangs at the following request for 1 min, until another "timeout" with another status 200.

`https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=<removed our key>&cb=1502365375805&androidPackageName=com.nuvopoint.nuvostore`

Then it displays the error: `An error happened. Please try again later.`:

Now the "funny" part: The login flow works when we disconnect our Android devices from our local network, and have them be on 3G/4G.

Why would our router block only Android devices from completing this login flow? It's something we need to solve, otherwise we might end up with a bunch of customers who can't login because they're using a certain router configuration.

**Comment by bojeil-google** [comment]
I don't think this is related to Firebase or FirebaseUI. I will try to look into it to see if I can reproduce it but it appears network related. The requests are timing out for some reason.

**Comment by larssn** [comment]
We have no idea what would cause this. Is the android webview using experimental flags like Chrome I wonder...

Thanks for looking into it.

**Comment by bojeil-google** [comment]
Try testing with a different device, different network, etc to isolate the cause of this.

**Comment by larssn** [comment]
We tried 3 different android devices, and they all had the same issue.

On different networks it works, and we just got a new router through the door, today. I suspect the problem will go away when we install it, but it still leaves me concerned: Why is the timeout a 200, and after exactly 1 min, AND ONLY on android devices, thats the question. As I said, the same app login flow works fine through a browser. It's puzzling.

Does `googleapis.com` have any kind of logging in their backend? Maybe they can see whats stalling.

**Comment by bojeil-google** [comment]
Network requests are set to timeout after 1 minute on a mobile device. It is a hardcoded value. It was previously shorter but some mobile networks can be very slow. How is it a 200? Does it actually return a response? Can you inspect a successful response is getting returned?

If you need to file a request to lookup the backend status of these requests, you will need to through official Firebase support as project specific details will need to be provided.

**Comment by larssn** [comment]
Yes, its a 200, and yes there's a response, headers and all. Thats why I'm suspecting that it's some serverside logic that is messing up.

Anyway, the router has been replaced, and the problem is gone.

**Comment by larssn** [comment]
We'll log a request with firebase support. Don't think you have much of a chance here @bojeil-google, but thanks for the help regardless.

**Comment by bojeil-google** [comment]
I am glad changing the router fixed this issue. Thanks for the update.
