### ISSUE TITLE
does the tosUrl serve any function?

### ISSUE THREAD

**Issue by dwelle** [firebase/firebaseui-web#201]
Docs say the `tosUrl` is required, but not including it in the config works fine. Moreover, including it doesn't seem to have any effect - the link is not rendered anywhere.

**Comment by bojeil-google** [comment]
It is not required but it is actually used during password sign up flows or phone number sign in when providing the SMS code.

**Comment by dwelle** [comment]
Alright. Maybe a tweak to readme is in order? PR?
