### ISSUE TITLE
Feature Request: Returning authorised scopes after successful Facebook login

### ISSUE THREAD

**Issue by fredjohnd** [firebase/firebaseui-web#208]
Hi, Is there a way to see which scopes were authorized after a user successfully logged in ?

Take this example: some of the scopes are optional and the user can uncheck them when logging in:
```signInOptions: [
      {
        provider: firebase.auth.FacebookAuthProvider.PROVIDER_ID,
        scopes: ['public_profile', 'email', 'user_likes'],
      }
 ```

When using `FB.login()` we can pass a parameter called `"return_scopes"` that will return all the scopes the user gave permission for.
 
Is this information available under any of the objects passed to the `signInSuccess` callback ? 

Thanks. 👍

**Comment by bojeil-google** [comment]
Hey @fredjohnd, this is currently not available in our underlying core SDK, but I have filed an internal feature request for it. I will keep you posted when I have an update on this.

**Comment by jhuleatt** [comment]
This is available in the [`User.providerData`](https://firebase.google.com/docs/reference/js/auth.user.md#userproviderdata) object for Facebook sign-ins under the `granted_scopes` key.
