### ISSUE TITLE
login doesn't work from the first time

### ISSUE THREAD

**Issue by kareemElsayedDEV** [firebase/firebaseui-web#209]
i am using the following to signin users

var uiConfig = {
        signInFlow: 'redirect',
        signInSuccessUrl: 'index.html',
        signInOptions: [
            firebase.auth.GoogleAuthProvider.PROVIDER_ID,
            firebase.auth.FacebookAuthProvider.PROVIDER_ID,
            firebase.auth.TwitterAuthProvider.PROVIDER_ID,
            firebase.auth.EmailAuthProvider.PROVIDER_ID,
            firebase.auth.PhoneAuthProvider.PROVIDER_ID
        ],
    };
    var ui = new firebaseui.auth.AuthUI(firebase.auth());
    ui.start('#justForAuthContainer', uiConfig);

the issue is that users must request the login process 2 times for them to actually log In
when using 
signInFlow: 'popup'
it works from the first time

after tracing the issue with redirect flow, it looks like the signInSuccessUrl/callbacks is not even reached and the page is auto reloaded
second time it works correctly as expected
the flow of the process works as follows
-> user request signIn
-> user is promoted with the signIn button
->page reload and user still is logged out
->user request signIn
->loading progress is showen, and logIn is successful 
app url: https://yalladoctors-d6e0e.firebaseapp.com/index.html

**Comment by bojeil-google** [comment]
I can't recreate it. I tested with: https://fir-ui-demo-84a6c.firebaseapp.com/widget#recaptcha=normal

It may have something to do with when you display the sign-in widget and how you detect the user is signed in or not. Provide the snippets for your rendering logic, or a link to your app.

**Comment by kareemElsayedDEV** [comment]
i updated the comment
the app has fixed frame with dynamically changing pages inside that frame(i don't think it has anything to do with this issue)

**Comment by bojeil-google** [comment]
This is an issue in your app. You are not letting the operation finish. There is a pending redirect, and in order for it to finish, the sign in widget has to be started. Whenever your webpage is reloaded, the sign in widget is not rendered. 
One trick you can do is remember that the user started a sign in flow and then on return to index.html page from IdP redirect, render the widget again. You can add #login to URL when the widget is rendered and then on redirect to #login, check the hash and render it again to complete the flow.

**Comment by bojeil-google** [comment]
We have added a new API `isPendingRedirect ` to help with this:
https://github.com/firebase/firebaseui-web/releases/tag/v2.6.0
