### ISSUE TITLE
On sign out the sign-in box doesn't appear

### ISSUE THREAD

**Issue by psingl** [firebase/firebaseui-web#211]
Firebase UI version: 2.3.0
Firebase Version: 4.3.1
I am using firebase ui in my angular 4 app. Once the user signs out, the sign in box does not appear. It simply shows blank. I am using only Phone Authentication in my app. Is this an issue or is there another method to do this. Any help would be appreciated.

**Comment by bojeil-google** [comment]
There is nothing we can do to diagnose this without comprehensive code to reproduce it.
Our SDK does not provide mechanism to detect when to render or not render the UI. This is up to the developer using existing methods in the core SDK like `onAuthStateChanged` listener.

**Comment by psingl** [comment]
Hey @bojeil-google  Can you tell me what to use in `onAuthStateChanged`?

**Comment by bojeil-google** [comment]
This depends entirely on your setup and website structure. You can do something like:
```
var ui = new firebaseui.auth.AuthUI(firebase.auth());
firebase.auth().onAuthStateChanged(function(user) {
  if (user) {
    // User is signed in, show your logged in screen, welcoming user, etc.
    // ...
  } else {
     // User not signed in or just signed out. Render the sign-in widget.
     ui.start('#firebaseui-auth-container', uiConfig);
  }
});
```

Try this with a basic setup first and let me know if it works for you.

**Comment by psingl** [comment]
Hey @bojeil-google This code is not working for me. I am using firebase along with angularfire2, this might be somewhere an issue.

**Comment by bojeil-google** [comment]
Hey @psingl, I need more details. FirebaseUI-web has been used alongside angularfire2 without such issue. It could be specific to your setup.

**Comment by psingl** [comment]
Hey @bojeil-google Can you please build a sample project using angular 4 and firebase and angularfire2?

**Comment by nicolasgarnier** [comment]
@psingl maybe you could try using that Angular wrapper? https://github.com/RaphaelJenni/firebaseui-angular it looks like it's meant to be used with angularfire and has samples on how to use it.
