### ISSUE TITLE
SMS Auth Verification doesn't format correctly on 320px width screens (e.g. iPhone 5, iPhone SE)

### ISSUE THREAD

**Issue by astromme** [firebase/firebaseui-web#212]
The auth widget seems to require a width of at least 383 pixels, too wide for the iPhone 5 and SE. This seems to be primarily because of the recaptcha. Can I do anything to fix this?

![screen shot 2017-09-19 at 3 27 07 pm](https://user-images.githubusercontent.com/126986/30618391-08c3f00e-9d4f-11e7-944b-02638e22499f.png)

**Comment by astromme** [comment]
This looks even worse when the captcha requires a visual check: 
![screen shot 2017-09-19 at 3 28 34 pm](https://user-images.githubusercontent.com/126986/30618429-492cd43a-9d4f-11e7-83a2-bb6a44c26bfb.png)

**Comment by bojeil-google** [comment]
Yeah this is indeed specific to reCAPTCHA. Unfortunately, reCAPTCHA is not responsive.
Did you test it with invisible reCAPTCHA. That may work better as the challenge gets centered.
We'd need to experiment with it and try to use CSS overrides to resize it.
There are multiple articles online on this. Here is one: https://geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/

**Comment by astromme** [comment]
The recaptcha is added automatically by firebaseui, I don't believe I have
the ability to change it.

**Comment by bojeil-google** [comment]
Hey @astromme, add the following style:
```
@media (max-width: 320px) {
  .firebaseui-recaptcha-container > div > div {
    transform: scale(0.9);
    -webkit-transform: scale(0.9);
    transform-origin: 0 0;
    -webkit-transform-origin: 0 0
  }
} 
```

I tried it, it resizes the reCAPTCHA box. When the challenge appear, it shows it centered on the screen. I will add the fix to our library too.

**Comment by bojeil-google** [comment]
This should be fixed in latest release:
https://github.com/firebase/firebaseui-web/releases/tag/v2.4.0
