### ISSUE TITLE
PhoneNumber auth on Cordova: A network error occured

### ISSUE THREAD

**Issue by derwaldgeist** [firebase/firebaseui-web#215]
I am trying to make phone number auth work in a Cordova app. Sometimes, it works correctly. But quite often (especially on Android), instead of the UI widget, this error shows up:

![network error 1](https://user-images.githubusercontent.com/3984535/30782736-5d0e973a-a138-11e7-8a04-a8639e273a5d.png)

(A network error occured. Close)

If I close the error message using the link, this button shows up:

![network error 2](https://user-images.githubusercontent.com/3984535/30782747-7e61d3ac-a138-11e7-994f-7dc7381da6cb.png)

(Login with a phone number)

If I click on this button, the error message shows up again. But never does the phone number widget itself show up after this time. It only appears if everything works at the very first try.

In principle, everything should be setup correctly, because sometimes it works fine. But having the error showing up over 50% of all tries is a show-stopper for me.

I added googleapis.com, google.com, and gstatic.com to the whitelist for both https and http, but still the problem exists. On the console, no error message is displayed.

**Comment by derwaldgeist** [comment]
This seems to only affect Android, on iOS it works fine.

**Comment by derwaldgeist** [comment]
I now tried to implement the non-widget way, by manually adding the recaptcha verifier to the page.

As soon as I call

`firebase.auth().signInWithPhoneNumber()`

this error is thrown:

```
error: O
code: "auth/network-request-failed"
message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
```

Again, this only happens on Android. In the browser and on iOS everything works as expected.

**Comment by bojeil-google** [comment]
We don't support phone authentication in a Cordova environment currently.

**Comment by cappittall** [comment]
@derwaldgeist, I come up the same issue. And just found this may help : https://stackoverflow.com/questions/44081040/ionic2-authentication-firebase

**Comment by derwaldgeist** [comment]
> We don't support phone authentication in a Cordova environment currently.

@bojeil-google Well, this is quite funny, as the Fabric support team recommended just this for Cordova:

>  For Cordova based apps, using the web migration guide: https://docs.fabric.io/web/digits/web-migration.html  and the corresponding setup from Firebase: https://firebase.google.com/support/guides/digits-web  is the best path forward. Give it a shot and let me know how it goes for you :) 

BTW: I got it working now on MeteorJS. This is a special situation, since Meteor runs the code from a local http server instead from the file system. The problem was, however, that the Firebase library relies on navigator.onLine that isn't working properly on Android. After adding cordova-plugin-network-information, the app worked fine.

**Comment by derwaldgeist** [comment]
I am closing this, as the problem is actually in the Firebase core api. Filed an issue there.
