### ISSUE TITLE
Anonymous user and account conversion to permanent account

### ISSUE THREAD

**Issue by pcarbonn** [firebase/firebaseui-web#22]
Same issue as [#123 in firebase-android](https://github.com/firebase/FirebaseUI-Android/issues/123): 

How can I use firebaseui-web to convert an anonymous account to a permanent one (i.e. one of the supplied auth providers) ?

As stated in the documentation and as I understand it, one must use the linkWithCredential method instead of the "normal" signInWith flow.  Can this be done with the current AuthUI version somehow?

**Comment by bojeil-google** [comment]
Hey @pcarbonn, currently this is not supported in firebaseui but it is an important feature we plan to support. The reason is that if you try to link a google or facebook provider to an anonymous account (linkWithRedirect), in some cases where the google or facebook account already exists, the login attempt will fail (you can only link a new account to an existing one).

**Comment by mellogarrett** [comment]
Any update on when this feature may be available?

**Comment by TMSCH** [comment]
Hi @mellogarrett we are working on it, but we can provide any ETA for now.

**Comment by andlcool** [comment]
Great work. Interested in this feature too. The firebaseui-web does a wonderful job with the authentication flow.

**Comment by SkyJedi** [comment]
I'd really like the option for anonymous login please

**Comment by mikaturk** [comment]
It's been a couple of months, is this feature coming any time soon (july/august?)

**Comment by dauledk** [comment]
Would be great with an update on this issue :)

**Comment by bojeil-google** [comment]
Hey guys, sorry for the delay. I completely agree this is a very important feature. We try to achieve feature parity among the 3 platforms (Android, iOS and web) and this is one of the main reasons this has been delayed. I can assure you it's on our roadmap. Some refactoring will be required to get this working first. You will see that in the coming months until we are able to align and get this out to all FirebaseUI developers.

**Comment by txedo** [comment]
Hi @bojeil-google . Is there any update on this? Thank you in advance.

**Comment by bojeil-google** [comment]
Hey everyone, this is a top priority for us now. I have moved it to p1. We are starting the work on this. It is quite complicated as there are many edge cases to cover and there are cases where upgrading will not work if the non-anonymous account already exists. We will provide a multi-phased solution to help unblock developers. I will keep you posted.

**Comment by bojeil-google** [comment]
Anonymous user upgrade flows are now available via FirebaseUI-web:
https://github.com/firebase/firebaseui-web/releases/tag/v2.6.0

**Comment by brt94** [comment]
My issue scenario : 
a new user sign anonymous then want to link(email/pw,gp,facebook) for reasons like skins currency etc.
He links email/pw - gp - facebook with no problem but the anonimous account is lost.

Solve 1: 
save anonimous auth in another variable then link again but it can break at some point
Solve 2:
if u use his creditentials in a DB just replace the uid in the DB after linking
