### ISSUE TITLE
Conflict with latest material design lite (1.3.0) styling

### ISSUE THREAD

**Issue by darkscript** [firebase/firebaseui-web#220]
There is a conflict when trying to use material design lite latest with firebaseui css styling, see image
![issue](https://user-images.githubusercontent.com/13992858/31008929-6b0a48aa-a50e-11e7-9bc4-e5c25748ce4b.PNG)

**Comment by bojeil-google** [comment]
Hmm I just built the FirebaseUI demo app with MDL ~1.3.0 but I can't reproduce this.
