### ISSUE TITLE
css-loader for webpack doesn't like your css

### ISSUE THREAD

**Issue by derrickbeining** [firebase/firebaseui-web#227]
I imported the auth ui css into my JS module, letting the css-loader webpack module handle it, but it found some badly formatted urls and gave me some parsing errors. I've forked the source and corrected the urls. I'll open a pull request for the edits.

**Comment by nicolasgarnier** [comment]
Looks like this mist have been fixed since I don't have issues on our test project here: https://github.com/firebase/friendlypix-web/

Let us know otherwise!
