### ISSUE TITLE
sign in with email doesn't show in popup even when configured as popup

### ISSUE THREAD

**Issue by mspanish** [firebase/firebaseui-web#229]
Hi when I try using the 'popup' mode in my single page app, all of the other providers (including phone) work perfectly, keeping the user inside of my app, except the email sign in provider. When I have that enabled it redirects the user to a new page, leaving the app.

Is there a way to override this?

thanks!

**Comment by bojeil-google** [comment]
Do you mean, it redirects to `accountchooser.com`? If so, you can disable that by passing:
`{credentialHelper: firebaseui.auth.CredentialHelper.NONE}`
In your configuration.

**Comment by mspanish** [comment]
thank you that's just what I was looking for. In your demo, the Single Page App shows the same behavior, where it leaves the app when selecting email for sign on - whereas the others all stay on the page. Since most people with an SPA will want to stay on the same page - you may want to let people know they need to use this setting to achieve that with the email option.

thanks very much for the super fast reply!

**Comment by taykcrane** [comment]
@bojeil-google @mspanish 

Hi, this still doesn't open up the email/pw prompt as a popup, it renders it within the firebaseui-auth-container div. Do we know of a way to open this as a popup like all the other IDP providers?

**Comment by bojeil-google** [comment]
This is the intended behavior. Email/password is rendered in the same container. For other IdPs, you are either redirected to their corresponding sites or a popup is opened and redirected to IdP site. You could create a separate page where you render firebaseui with redirect mode and then open that from your app. The user is signed in from there and then you would detect the state change via `onAuthStateChanged` listener and close that popup if still open.
