### ISSUE TITLE
Show enter email directly when only using EmailAuthProvider

### ISSUE THREAD

**Issue by amitkothari** [firebase/firebaseui-web#23]
When only using email as an option to sign-in, is it possible to directly show the enter email screen instead of showing 'Sign in with email' button first ?

**Comment by bojeil-google** [comment]
Hey Amit, this is a good idea. We will look into it. In the meantime, you could trigger a dynamic click on the visible email button to take the user to the sign in screen (enter email screen).

**Comment by amitkothari** [comment]
👍

**Comment by TMSCH** [comment]
@amitkothari the new release includes this feature! Please let us now if you experience any issues.
