### ISSUE TITLE
Auth UI Doesn't Load on iOS 10

### ISSUE THREAD

**Issue by maxmatthews** [firebase/firebaseui-web#239]
I'm trying to load the following page on iOS 10 Mobile Safari but the UI never seems to initialize. https://app.myhealthyday.com/loginAlexa

There are no errors or logs in the console. The page loads fine on iOS 11. I'm using React (Web) and have no problems on other OSes.

**Comment by bojeil-google** [comment]
I tested with a real device using iOS 9 and 11 and on a simulator with iOS 10 and can't replicate it. UI always shows for me. I will try to get my hands on a real iOS 10 device and test again.

**Comment by maxmatthews** [comment]
Sorry, I found the problem. iOS 10.2 and prior don't support URLSearchParams (https://caniuse.com/#search=URLSearchParams) which I was using to determine the signInSuccessUrl. 
Thanks for your help!
~Max
