### ISSUE TITLE
Do not modify Material Design Lite CSS classes

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/firebaseui-web#24]
I'm currently integrating FirebaseUI Auth into the FriendlyPix sample which uses Material Design Lite (MDL) for styling.

One issue is that FirebaseUI has modified MDL CSS classes styling so importing the FirebaseUI CSS will mess up any website that's using MDL. For example here is FriendlyPix:

Before:

![image](https://cloud.githubusercontent.com/assets/3766663/17058220/62083388-501f-11e6-9b62-4597d394f192.png)

After:

![image](https://cloud.githubusercontent.com/assets/3766663/17058226/6da770a0-501f-11e6-870c-0e48fa442420.png)

MDL is a popular styling framework now so i'd be best not to re-use/modify their CSS class names. I suggest either:

 - Namespacing/Prefixing all the class names used in Firebase-ui. For instance rename all `mdl-button` into `fui-mdl-button` (or simply `fui-button`)
 - Keep using the MDL class name but do not modify them, instead add a second class name for all CSS overrides/changes: You button that had `class="mdl-button"` would become `class="mdl-button fui-button"` where `mdl-button` only contains the original v1 MDL CSS styles and `fui-button` would be any Firebase-UI specific additions.

**Comment by nicolasgarnier** [comment]
Changing the order of the CSS imports (i.e. importing MDL proper after Firebase-ui) fixes things for my site but then the Firebase-UI elements don't always have proper styling for instance:

![image](https://cloud.githubusercontent.com/assets/3766663/17059235/87cde3f6-5024-11e6-9fe5-8469a3aaf029.png)

**Comment by channing-google** [comment]
Would it be possible to send us a demo page of the bug? I looked at our CSS and it seems that we are overriding some styles for input labels (which we will also fix) but nothing that should affect button styles.

**Comment by nicolasgarnier** [comment]
I just had a better look and some of these issues where on my end (like the color of the buttons). Actually it seems you guys are indeed not modifying any MDL classes (sorry for assuming that, I should have checked better) I was able to fix mostly issue with just importing my app's CSS last (which I should have done initially). However there is one tricky case where Firebase Auth UI's CSS interferes with MDL's, it's kind of what got me to wrongly assume you were modifying the classes:

Since you are not including all of MDL classes (for instance you're not including `mdl-layout__tab`) in the Firebase UI CSS, some elements in the site that use multiple CSS class are changed. For instance in my first screenshots above you can see that the tabs height is shorter. This is because my tab element are also buttons:

```html
<a href="/feed" class="mdl-layout__tab mdl-button ...">Feed</a>
```

In this case the `mdl-layout__tab` takes precedence on `mdl-button` in `material.min.css` but things change once we import `firebase-ui-auth.css` after that. To help you understand this is what Chrome shows me:

![image](https://cloud.githubusercontent.com/assets/3766663/17067544/78626a90-504c-11e6-8649-00f79cce46de.png)
![image](https://cloud.githubusercontent.com/assets/3766663/17067578/a73f9978-504c-11e6-8eed-d31fd32b2eb6.png)

As you can see usually `material.min.css > mdl-layout__tab` takes precedence on `material.min.css > mdl-button` but since we're importing `firebase-ui-auth.css` after `material.min.css` (we need to because of button styling) then `firebase-ui-auth.css > mdl-button` takes precedence again but then we don't have `firebase-ui-auth.css > mdl-layout__tab` that takes over again 💃 which explained the difference...

Well just wanted to mention it. In my case I'll just modify my HTML structure to have the button inside the tab as this is really a corner case not sure worth fixing (fixing would mean you guys would need to include the whole MDL CSS which might not be best)... Feel free to close.
