### ISSUE TITLE
undefined is not a function (evaluating 'window.addEventListener')

### ISSUE THREAD

**Issue by Squeegene** [firebase/firebaseui-web#240]
So I'm using firebaseui with React Native and have started from scratch to make sure I'm not going crazy.

After running 'react-native init FirebaseTEST' and then running 'npm install firebaseui --save', all I did was include the following in index.js:

```
import { AppRegistry } from 'react-native';
import App from './App';
import * as firebase from 'firebase';
import * as firebaseui from 'firebaseui';

AppRegistry.registerComponent('FirebaseTEST', () => App);
```

That's all I have changed. I get the error : "undefined is not a function (evaluating 'window.addEventListener') in npm.js. 

Am I doing something wrong or is this a bug?

![screenshot_20171109-204126 1](https://user-images.githubusercontent.com/13388244/32638688-78d6a6ea-c58e-11e7-934a-992ecee2ccd6.png)
![screenshot_20171109-204131 1](https://user-images.githubusercontent.com/13388244/32638695-81ab0cac-c58e-11e7-94a8-4f939f687df2.png)

**Comment by nicolasgarnier** [comment]
@Squeegene I don't think you can use `firebaseui-web` in React Native since it's only designed to be used on the web. Your best bet would be to use `firebaseui-ios` and `firebaseui-android` and build a bridge to use these native Android/iOS libraries in your React Native app.

**Comment by Squeegene** [comment]
thanks for the suggestion!
