### ISSUE TITLE
Login Loop when combined with Polymer Starter Kit

### ISSUE THREAD

**Issue by igniparra** [firebase/firebaseui-web#246]
Hello guys! I'm kinda new to web development, and I made my Polymer App with the starter kit.
I made an Index.html that makes the login using FirebaseUI Auth, and redirects to a main.html which was the old index.html. That calls my-app.html which has all the frames and stuff.

I added the startup sequence in both index and main files, and then index has the login widget, and main has the OnAuthStateChanged code.

I see in my firebase console that the login is being performed correctly, but for some reason, the site loads main (At least that's what's shown on the address bar) and I'm presented again with the FirebaseUI Login Screen.

I know this is probably an error from my side, but if anybody could help me out, I'd greatly appreciate it!

**Comment by nicolasgarnier** [comment]
@igniparra, to be able to help you we'll need you to provide the code that you are using and a step by step way to re-create the issue. Even better if you can upload a version of you broken app online for us to test.
