### ISSUE TITLE
Add Bower and npm support

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/firebaseui-web#25]
It would be great if I could install/import Firebase UI locally with something like `bower install firebase-ui`

**Comment by MrCsabaToth** [comment]
This would be good for me too

**Comment by dandv** [comment]
:-1: because [bower is being replaced by npm](https://pinboard.in/search/u:dandv/?query=against+bower) and fewer and fewer projects bother with bower.

![image](https://cloud.githubusercontent.com/assets/33569/20081086/2813d38e-a502-11e6-99c3-c67d7cd44121.png)

**Comment by MrCsabaToth** [comment]
@dandv Bower is phasing out, but some Polymer projects rely on it (like hoverboard), and bower is lighter wait in general than npm. I haven't ever done it, but how hard would it be to add a bower configuration?

**Comment by nicolasgarnier** [comment]
Let's just add both :D

**Comment by TMSCH** [comment]
npm and Bower supports have been added: https://github.com/firebase/firebaseui-web#npm-module and https://github.com/firebase/firebaseui-web#bower-component
