### ISSUE TITLE
How to capture signup event for a new user in case of "Sign in with email"?

### ISSUE THREAD

**Issue by gauravt1** [firebase/firebaseui-web#255]
I have integrated firebaseui-web in my current app but I'm facing an issue in case of singing in with email.
As of right now the flow is -

"Sign in with email"
1) If  you try it first time than it will prompt you for a username. That's good.
2) Than, It'll  ask you to fill your full name and password. That's also good.
3) But, when you hit the submit button, you can access the progress only in signInSuccess().

I have a problem with the third step above because right now I'm also hitting my api to save the user info on server side and it is not giving any such call back in documentation which handles the flow after sign up instead of it can only handle the flow in signInSuccess().

Is there any way with which I can catch the submit event here?

Or Is there any property which tells me that this is the first attempt of login after signup by user?

Please feel free to ask If you need any further information to reproduce or understand the issue.

**Comment by nicolasgarnier** [comment]
@gauravt1, coud you explain a bit more why using `signInSuccess` does not fit your need? Is it becasue you want a callback only for new account creations?

**Comment by gauravt1** [comment]
@nicolasgarnier , Yes I want a callback for new account creation. Actually, I need to save the user info on server as well on creation of account in firebase. Is it possible to do so?

**Comment by gauravt1** [comment]
Do I need to install "firebase-admin" and "firebase-tools" and integrate them with the app?

**Comment by nicolasgarnier** [comment]
For Cloud Fucntions? Yes. The easiest is to run `firebase init functions` and this will add a `functions` directory with a sample Cloud Function in it.

Here is also a sample app that's sending a "Welcome" email to new users upon account creation: https://github.com/firebase/functions-samples/tree/master/quickstarts/email-users

**Comment by bojeil-google** [comment]
For a client side solution, Firebase Auth now returns additional metadata on sign in/up which can help determine if a user is new or existing: https://firebase.google.com/support/release-notes/js#4.6.0
We plant to also return that to the developer soon. For now, you can check currentUser metadata and compare last sign in time with creation time to determine if a user is new or returning.

**Comment by kaynelynn** [comment]
I think this should definitely be added to FirebaseUI. My sign in works perfectly, but I store additional user information in the database and when a new account is created, my app crashes due to nil values. I need to know when a new user is created so I can prompt them to enter the additional info.

**Comment by codeofsumit** [comment]
I also think this saves us quite a lot of hassle with account creation. I currently have to check the DB for an existing user, create, fetch data again etc etc. It would be much easier if the returned payloads include `additionalUserInfo` and the `newUser` property 👌

**Comment by FrankEmiro** [comment]
i think you can save some time with :

``` 
...,

callbacks: {
        signInSuccessWithAuthResult: function (authResult, redirectUrl) {       
          var isNewUser = authResult.additionalUserInfo.isNewUser;
        },
      },
```
