### ISSUE TITLE
Error Code: auth/operation-not-supported-in-this-env

### ISSUE THREAD

**Issue by CharlJKruger** [firebase/firebaseui-web#26]
I have implemented Firebase UI web into my ionic app and it works awesome in chrome though when deploying to my android device, im getting the following error:

`Error Code: auth/operation-not-supported-in-this-enviroment`

I can create an account via email though facebook and gmail wont work. If I click them, it just brings back the error.

Any help would be appreciated. BTW thanks, its looking great and saves a huge amount of time.

**Comment by TMSCH** [comment]
Hi CharlJKruger,
Currently, some Firebase Auth operations are not supported in Ionic apps. These include signInWithRedirect and signInWithPopup (see [doc](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithRedirect)). FirebaseUI relies on signInWithRedirect for providers flows (Google, Facebook...), hence, this is not supported.
Unfortunately there is no work around at that time using FirebaseUI. For Ionic apps we would recommend using native SDK for each provider (Google, Facebook...) and then use the [signInWithCredential](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithCredential) method of the Firebase library.

**Comment by CharlJKruger** [comment]
Thank, will give it a try.
