### ISSUE TITLE
async signInSuccess

### ISSUE THREAD

**Issue by bestpika** [firebase/firebaseui-web#264]
If my `signInSuccess` is async function then redirect will before callback.
This is not the result of my expectation.

**Comment by bojeil-google** [comment]
You can return false in `signInSuccess` callback (this will disable the automatic redirect after that runs), complete your async function and then manually redirect when you your callback completes.

**Comment by bestpika** [comment]
@bojeil-google Thank you.

**Comment by bojeil-google** [comment]
You're welcome.
