### ISSUE TITLE
Error: OAuth on Cordova Android, get auth/redirect-cancelled-by-user

### ISSUE THREAD

**Issue by hmrtk** [firebase/firebaseui-web#267]
Followed the instruction to setup OAuth on my Cordova Android app (https://firebase.google.com/docs/auth/web/cordova) . After sign in on Google, I redirect back to the app but I get the following error:

code: auth/redirect-cancelled-by-user
message: the redirect operation has been cancelled by the user before finalizing.

Cordova version: 7.1.0
Android version: 6.3.0

OAuth Works fine on both iOS and Web

**Comment by bojeil-google** [comment]
With the limited information you provided, it is impossible to tell. It seems likely that the app link redirect is not getting intercepted by your app.
You need to make sure you configured you FDL link correctly and set up your universal link configuration  correctly in config.xml.
Also you need to debug `cordova-universal-links-plugin` to make sure it is intercepting the link:
```
universalLinks.subscribe(null, function(eventData) {
  console.log('universalLink: ' + eventData.url);
});

```

**Comment by hmrtk** [comment]
@bojeil-google Regarding FDL link, are you referring to the link that is in `abc123.app.goo.gl` format? If so, yes I have just rechecked and its setup correctly.

Please elaborate more on the universal link setup in config.xml for android. I did not find any explanation about it on the guid. Thank you

**Comment by bojeil-google** [comment]
Then you have a problem in that configuration. Are you completing sign in before the redirect back to the app? Just to make sure you are actually signing in.

Are you using Cordova or PhoneGap build? There is a know issue with the latter in the plugin. I described.

```
<universal-links>
    <host name="abc123.app.goo.gl" scheme="https" />
    <host name="my-app.firebaseapp.com" scheme="https">
        <path url="/__/auth/callback"/>
    </host>
</universal-links>
```

Make sure that is correct. You have to substitute your authDomain too, `my-app.firebaseapp.com`.

**Comment by hmrtk** [comment]
@bojeil-google  I am using Cordova for build. I just verified that the universa-links is setup correctly in my config.xml. 
I am not sure if sign in is completed before I get redirected back to the app. I can confirm that it works fine on redirect back from iOS. How can I check that?

below is the code I use to sign in. 

```javascript
firebase.auth().signInWithRedirect(new firebase.auth.GoogleAuthProvider())
.then(function() {
      debugger;
      // -- never hit here
        return firebase.auth().getRedirectResult();
      }).then(result => {
     debugger;
     // -- never hit here
      })
      .catch(error => {
    debugger;
    // this is where I catch the error
      });
```

**Comment by bojeil-google** [comment]
You would know. Does the sign in page show? Do you provide your email/password?
Android and iOS work differently.
Anyway, there must be something wrong in your setup. Just can't predict what it is on my end. 
Did you consent to FDL terms of service?
Did you also add launch mode in your config.xml:
`<preference name="AndroidLaunchMode" value="singleTask" />`

**Comment by hmrtk** [comment]
Yes, sign in page shows, I provide email address and I can signin. This happens after the sign-in is complete and I am being redirected back to the app.

Just verified `<preference name="AndroidLaunchMode" value="singleTask" />` is added to my config.xml.

I signed FDL terms of service before I was able to get the FDL link on Firebase console.

Let me know if you require any other information from my side. Thank you.

**Comment by hmrtk** [comment]
just for the reference in the future, I have changed AUTH_DOMAIN from firebase URL to custom auth domain I have setup, and its working now. Thanks again @bojeil-google

**Comment by bojeil-google** [comment]
So you were using a custom domain for your `authDomain`. That would have helped if you had mentioned it from the beginning. Would have saved both of us a lot of time. Anyway, we should add this to our documentation.

**Comment by hmrtk** [comment]
Yes! I assumed the default URL should be the one I have to setup in the universal-links. Having it on the documentation would help for sure. Thanks.

**Comment by attex** [comment]
@bojeil-google i am facing the same issue. What do you guys mean by "custom domain" ? 

I am using 
`<universal-links>
    <host name="****.page.link" scheme="https" />
    <host name="<projectID>.firebaseapp.com" scheme="https">
      <path url="/__/auth/callback" />
    </host>
  </universal-links>` 

in my config.xml and so in the index.html:

`var config = {
            apiKey: "****************************************",
            authDomain: "<projectID>.firebaseapp.com",
            databaseURL: "https://<projectID>.firebaseio.com",
            projectId: <projectID>,
            storageBucket: "<projectID>.appspot.com",
            messagingSenderId: "*************"
        };`

**Comment by bojeil-google** [comment]
Hey @attex, @hmrtk was using a custom `authDomain`. Instead of `<projectID>.firebaseapp.com`, he was using his own domain `www.example.com. 

Regarding your case, I notice you are using `****.page.link` domain for FDL. Is this a new project? do you have a `*.app.goo.gl` FDL domain already? The reason why I ask is because Firebase Auth currently doesn't allow multiple FDL domains. They will always pick the oldest one. They are working on supporting multiple FDL domains and supporting specifying one. To solve the problem, you have to use the existing `*.app.goo.gl` domain as you universal link or create a new project and create one FDL domain of format `*.page.link`, and that is the one that will be used.

**Comment by attex** [comment]
@bojeil-google in fact i am not using a custom domain. 

Where can I see my domains? 
In my mind I am just using the ***.page.link domain. The project was created 2 weeks ago.

When i recreated the android platform there is a new error message: Auth/network-request-failed
I also couldn't resolve the script: `<script src="https://www.gstatic.com/firebasejs/3.2.1/firebase.js"></script>`

When I manually inserted the script (download it & link it) firebase can be resolved but the Error message from above shows up. 

Does this have something to do with that ? 

Thanks

**Comment by bojeil-google** [comment]
You asked the question about custom domains. I am just answering.
You seem to be using a very outdated version of firebase SDK `3.2.1`. Please update to the latest.

**Comment by attex** [comment]
Done (now 5.2.0), I am still facing this error. 

Do you have any idea why this might occur ? 

This is my login code, and I could sign in with an account but the return throws an error...
`firebase.auth().signInWithRedirect(provider).then(function() {
  return firebase.auth().getRedirectResult();    **// i got here .. but then the network error occurs**
}).then(function(result) {
  // This gives you a Google Access Token.
  // You can use it to access the Google API.
  var token = result.credential.accessToken;
  // The signed-in user info.
  var user = result.user;
  // ...
}).catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;
});`

**Comment by Santoshah** [comment]
I have the same error. I am still unable to resolve. However I have found a link where someone had answer. But I am unable to understand it. If any one understand, please let me know. 

[Link is here](https://www.questarter.com/q/unable-to-google-login-auth-redirect-cancelled-by-user-27_48045496.html)

**Comment by diegomesata** [comment]
My problem was cordova-universal-links-plugin, in the config.xml file you have to register your universal links:
 `
 <universal-links>
        <host name="myapp.page.link" scheme="https" />
        <host name="myapp.firebaseapp.com" scheme="https">
            <path url="/__/auth/callback" />
        </host>
  </universal-links>
`

That settings will modify your AndroidManifest.xml file on build.

`
<activity ....> .............
 <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="vpsapps-b5799.firebaseapp.com" android:scheme="https" android:path="/__/auth/callback"/>
      </intent-filter>
    </activity>
`

But for some strange reason the AndroidManifest.xml was not updated. So I uninstall and reinstall the plugin, build again and the file was modified correctly.
 
I'm using this fork @prageethsilva/cordova-universal-links-plugin, because the cordova-universal-links-plugin is not building on phonegap cordova 8.

**Comment by Santoshah** [comment]
I also had fixed my issue. It seems I haven't use universal link plugin . it fixed after that.

**Comment by christianjose16** [comment]
I had the same issue,

Cordova Version 6.3.1

    <universal-links>
        <host name="planetafutbol.page.link" scheme="https" />
        <host name="planetafutbol-f3441.firebaseapp.com" scheme="https">
            <path url="/__/auth/callback" />
        </host>
    </universal-links>

    <preference name="AndroidLaunchMode" value="singleTask" />

    <feature name="UniversalLinks">
        <param name="android-package" value="com.nordnetab.cordova.ul.UniversalLinksPlugin" />
        <param name="onload" value="true" />
    </feature>

still no updating the manifest file

anyone can helpme please?

**Comment by kchrs** [comment]
Why this issue is marked as closed? @bojeil-google Problem remains. The answer given is not a proper one. Overall Firebase documentation is out of order.
