### ISSUE TITLE
Allow to use popup for IDPs

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/firebaseui-web#27]
It would be great if we could have a setting that would allow to use the popup flow for IDPs instead of the redirect that's currently used. I've just integrated Firebase UI in a single page app (only enabled Facebook and Google) and the UX would be much nicer with a popup.

**Comment by TMSCH** [comment]
The new release now allows to use popup instead of redirect for IDPs. Please refer to the documentation: https://github.com/firebase/firebaseui-web#sign-in-flows
