### ISSUE TITLE
Cannot implement invisible recaptcha.

### ISSUE THREAD

**Issue by diljo** [firebase/firebaseui-web#271]
I am using firebaseui-web in my React.js website. When I try to use invisible recaptcha, it's not working. When I hovered over the Recaptcha badge, it is showing this message **"This site key is not enabled for the invisible captcha."**
I want to know where to add the site key.

**Comment by bojeil-google** [comment]
Hmm, I just tested invisible recaptcha and I didn't encounter any issues. Firebase Auth will provision a reCAPTCHA site key for you. You don't need to specify one. It is strange you are receiving that error. Can you provide more information on this? Can you check your console for any additional. Also if possible, can you dig up the site key that is causing this error?

**Comment by bojeil-google** [comment]
One more question: Are you using a new Firebase Auth project? Or did you happen to migrate from a Google Identity Toolkit project to Firebase Auth?

**Comment by bojeil-google** [comment]
Ok, it seems that for migrated Google Identity Toolkit projects will need to be whitelisted to support invisible reCAPTCHA. This is needed to prevent breakage for old projects still using the old SDK. Please provide your project ID and we will whitelist it for you. Be aware if you are using the JS SDK for identity toolkit that you use the latest one.

**Comment by mohamedsharaf** [comment]
> Ok, it seems that for migrated Google Identity Toolkit projects will need to be whitelisted to support invisible reCAPTCHA. This is needed to prevent breakage for old projects still using the old SDK. Please provide your project ID and we will whitelist it for you. Be aware if you are using the JS SDK for identity toolkit that you use the latest one.

@bojeil-google 
 i have same erorr 
This site key is not enabled for the invisible captcha.
this is my project id can you whitelist it for me

**Comment by bojeil-google** [comment]
It is better not to share sensitive information on public forums. You need to open a [Firebase Support](https://firebase.google.com/support/) ticket to do so.
