### ISSUE TITLE
After Update to 4.8.0, Firebase does not have auth() function

### ISSUE THREAD

**Issue by gaoyike** [firebase/firebaseui-web#272]
I just update my app to 4.8.0.

When I run ` var firebase = require('firebase'); console.log(firebase)`

The 'firebase' does not have firebase.auth(). It has following:

[firebase
{__esModule: true, initializeApp: ƒ, app: ƒ, Promise: ƒ, …}
INTERNAL
:
{registerService: ƒ, createFirebaseNamespace: ƒ, extendNamespace: ƒ, createSubscribe: ƒ, ErrorFactory: ƒ, …}
Promise
:
ƒ Promise()
SDK_VERSION
:
"4.8.0"
app
:
ƒ app(name)
apps
:
(...)
database
:
ƒ (appArg)
default
:
{__esModule: true, initializeApp: ƒ, app: ƒ, Promise: ƒ, …}
initializeApp
:
ƒ initializeApp(options, name)
__esModule
:
true
get apps
:
ƒ getApps()
__proto__
:
Object](url)

**Comment by gaoyike** [comment]
Also, 
import {auth} from 'firebase';
 auth is undefined

**Comment by wti806** [comment]
I tried myself with Chrome and it works fine. Could be similar with this one: https://github.com/firebase/firebase-js-sdk/issues/363
Could you please try to clean and reinstall the dependencies?

**Comment by gaoyike** [comment]
Thanks @wti806 
I solved it by reinstall all dependencies. 
It works fine now.
