### ISSUE TITLE
When is the link to tosUrl presented to the user?

### ISSUE THREAD

**Issue by nuthinking** [firebase/firebaseui-web#274]
I am particularly interested if there is a way to make this link prominent and perhaps force the user to check a box before progressing.

Thanks.

**Comment by bojeil-google** [comment]
We currently show it when the user is creating an email/password account or during phone number sign-in when asked to provide the SMS code.

**Comment by nuthinking** [comment]
Thanks for the info! I will add some custom UI for it then.

**Comment by bojeil-google** [comment]
Sounds good.
