### ISSUE TITLE
Multiple FirebaseAuth components on a page?

### ISSUE THREAD

**Issue by AAverin** [firebase/firebaseui-web#275]
I have 2 modal popups with a bit different design. I was hoping to have Auth in both places, but only one of those shows up.

**Comment by bojeil-google** [comment]
Are you trying to show 2 sign in screens on the same page? What is the practical use case where you need 2 widgets? We only allow one sign-in screen. If you have different designs. You can customize the UI each time you render it.

**Comment by AAverin** [comment]
@bojeil-google I have 2 buttons that show modal popups.
1 button is "Member's Area" for existing users – clicking show allow to login via social networks
2 button is "Purchase" for new users and it requires to be signed in, so it should also show social signup
Technically, in the code, they are on the same page, within same <body>. 
Visually they are different, of course.

I might be able to workaround somehow, but maybe there is an easy way to show same UI in 2 different places?

**Comment by bojeil-google** [comment]
You can't show both at the same time. When one modal is triggered and another is still showing, you should first reset the old UI and hide it and then render the new one. You could also have 2 instances and just delete an old instance when it is to be hidden, and instantiate it again when it is needed again.
 
It's not feasible to show 2 UIs at the same time. You get into weird cases where for redirect operations, you are not sure which UI to use to complete the action. There are not enough practical use cases to justify the effort to support this.

I suggest you apply the toggle logic I recommended.
