### ISSUE TITLE
Running in file: location.protocol

### ISSUE THREAD

**Issue by AAverin** [firebase/firebaseui-web#276]
I need to signin in a chromium window that runs in `location.protocol="file:"` – it's an Adobe Photoshop HTML panel, they run Chromium 41.0.2272.104,
Is building custom UI the only way for me, or I can somehow use firebaseui-web?

**Comment by AAverin** [comment]
Message I get now:
```
This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.
```

**Comment by bojeil-google** [comment]
OAuth sign in is not supported in that environment for obvious reasons. If we do, we have no way to verify who is signing in these users. We rely on origin verification. That's how OAuth sign-in works. Anyone can steal your API key and sign in your users from a file origin and wreak havoc to their data.

**Comment by AAverin** [comment]
Would that mean that in such environment I can only support `firebase.auth().loginWithEmailAndPassword()`?

**Comment by bojeil-google** [comment]
Yes that is correct. If you want to do this at your own risk, you can open a browser window, render the FirebaseUI there, sign in the user and then pass back the result to your app securely, somehow.

**Comment by AAverin** [comment]
I see.
Thanks for the help.
