### ISSUE TITLE
Bypass Signin with Google button?

### ISSUE THREAD

**Issue by MichaelFromin** [firebase/firebaseui-web#277]
I am building an app that will only support logging in with a Google credential.  When I use the examples for using this library and Firebase for authentication, the user is presented with a sign in page that contains a Google button labeled Sign in with Google.  As this will be the only option I want to offer that button is a superfluous step in the login.  Is there a way to bypass that and go straight to the Google page that asks me to pick an account for login?

**Comment by bojeil-google** [comment]
If you just want to support Google sign-in without showing the button, you could render the UI, hide the button with CSS, and dynamically trigger a click on the invisible button when the user triggers the sign-in. It is helpful to show the button as it has the Google icon and makes it clear to the user they are signing in with Google. Also if you are using popup mode, a button click is required to prevent the popup from getting blocked by browsers.
Also check out the one-tap sign in integration, it will save the user a button click for signing in with Google.
