### ISSUE TITLE
Display human readable message instead of error codes

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/firebaseui-web#28]
When an error occurs currently the Error code is displayed. For instance when the account is disabled we display a popup with the following messsge:

```
Error code: auth/user-disabled  
Dismiss
```

Since this is supposed to be a reference implementation of the auth flow it would be nice to have all the known errors translated into a proper message for the user.

For instance for`auth/user-disabled` we should display something like "Your account has been disabled. Please contact the app's administrator."

**Comment by channing-google** [comment]
Fixed for 0.5.0.
