### ISSUE TITLE
Firebase UI Web + GoDaddy Forwarding w/ Masking (inside frames) --> SAME ORIGIN error.

### ISSUE THREAD

**Issue by davidbernat** [firebase/firebaseui-web#280]
Hello all,

I love Firebase UI. It's wonderful. Thank you for your development.

1. Firebase UI is set up successfully on a GCE VM at IP 104.198.97.68:5050.
2. I use site runsonaether.com on GoDaddy.
3. With forwarding (no masking, so that the browser URL redirects to 104.198.97.68), Firebase UI works.
4. With forward + masking, GoDaddy handles this by putting the redirect in a frame. I do not have control over this. 

```
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
 <html>
   
 <head>
 <title>runsonaether.com</title> 
</head>
<frameset rows="100%,*" border="0">
<frame src="http://104.198.97.68:5050" frameborder="0" />
<frame frameborder="0" noresize />
</frameset>
</html>
```

5. FirebaseUI from within a frame produces this SAME_ORIGIN restriction: 
```
Refused to display 'https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=482061924689-nho8tltb7f3i9k0icsieadrj535dfcq2.apps.googleusercontent.com&scope=https://www.googleapis.com/auth/userinfo.email+profile+https://www.googleapis.com/auth/plus.login....' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

All of the above are the expected behavior. However, it does not allow me to use in its current configuration FirebaseUI with masked forwarding. What is the workaround or more appropriate solution?

Thank you,

**Comment by bojeil-google** [comment]
This is not an issue on our end. IdPs like accounts.google.com refuse to render in a frame or iframe

**Comment by davidbernat** [comment]
Thank you for your response. Yes, I understand what you are saying. I posted in case you had any workaround you could provide.

I did solve the problem by using my GC Ingress to handle port forwarding form 80 -> server port, instead of doing so at the DNS juncture.
