### ISSUE TITLE
SAML authentication?

### ISSUE THREAD

**Issue by The-Alchemist** [firebase/firebaseui-web#282]
I was wondering if anyone had any sample code to use SAML to authenticate with Firebase.

I'm willing to submit a PR if someone points me in the right direction.  What's the best example to start with?  Does the Firebase auth API even support the "SAML-way" of doing things?

Thanks!

**Comment by The-Alchemist** [comment]
moving to Firebase google  group.  Will post URL once post is approved

**Comment by tmaier** [comment]
Hi, did you get any response?

**Comment by The-Alchemist** [comment]
@tmaier : sorry, forgot to post back: https://groups.google.com/d/msg/firebase-talk/tUYXF7GRTqQ/GvByFofYBAAJ
