### ISSUE TITLE
Account Linking Doesn't Work On Cordova

### ISSUE THREAD

**Issue by johnkmzhou** [firebase/firebaseui-web#290]
When trying to login with Facebook credentials when Firebase has my Google authentication, I get back a message saying "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address." That was the result when I tested on iOS and Android emulators. When I tested the same code on browsers, I successfully went through the account linking sign-in flow.

Pertinent info:
cordova@8.0.0
"cordova-android": "^7.0.0",
"cordova-ios": "^4.5.4",
"cordova-plugin-browsertab": "^0.2.0",
"cordova-plugin-buildinfo": "^2.0.1",
"cordova-plugin-compat": "^1.2.0",
"cordova-plugin-customurlscheme": "^4.3.0",
"cordova-plugin-inappbrowser": "^2.0.1",
"cordova-plugin-whitelist": "1",
"cordova-universal-links-plugin": "git+https://github.com/walteram/cordova-universal-links-plugin.git",
"firebase": "^4.9.0",
"react-firebaseui": "^1.0.10"

![device-2018-01-24-224737](https://user-images.githubusercontent.com/25243410/35380913-b5b48ad0-015e-11e8-86bf-e18f1dc725e5.png)

**Comment by wti806** [comment]
Hi, @johnkmzhou. Thank you for pointing out this issue. We are able to replicate this issue and also already spotted where the bug is. Will come up with a quick fix and let you know.

**Comment by bojeil-google** [comment]
This should be fixed now:
https://github.com/firebase/firebaseui-web/releases/tag/v2.6.0

In addition, make sure to upgrade firebase-auth.js version to the latest version which contains some Cordova Android specific fixes:
https://firebase.google.com/support/release-notes/js#4.9.1
