### ISSUE TITLE
firefox style errors

### ISSUE THREAD

**Issue by marcus7777** [firebase/firebaseui-web#296]
https://youtu.be/93LpgEwjYaM
only if logging in with email
can you help?

**Comment by bojeil-google** [comment]
Looks like an issue unique to your app where the CSS styles are not getting detected on that custom component you created.
You are using polymer in Chrome whereas you are using the web component polyfill library in Firefox. There is a difference in how each is rendered.

**Comment by marcus7777** [comment]
okay thanks, so need "if firefox css"
