### ISSUE TITLE
FirebaseUI support for Firefox extensions

### ISSUE THREAD

**Issue by batraabhishek** [firebase/firebaseui-web#297]
I am working on a common chrome/firefox extension. I have integrated FirebaseUI auth, and it works perfectly fine as chrome extension. Whereas on firefox, I am getting the following error. 

**This operation is not supported in the environment this application is running on. "location.protocol" must be HTTP, https or chrome-extension and web storage must be enabled.**

![screen shot 2018-01-30 at 9 14 16 pm](https://user-images.githubusercontent.com/3257840/35575515-923c065c-0602-11e8-872a-3bcdc9f80f13.png)

Am I missing something or is firefox extensions not supported yet. ?

Thanks

**Comment by wti806** [comment]
Hi, @batraabhishek  Did the error occur when you click the OAuth sign in button or when the widget get rendered?

**Comment by bojeil-google** [comment]
The underlying Firebase Auth SDK currently does not support firefox extensions. 
In fact, Chrome extensions are supported but FirebaseUI-web will not work out of the box with Chrome extensions if you are using OAuth providers.

You are welcome to [file a feature request](https://firebase.google.com/support/) for supporting firefox extensions/

**Comment by batraabhishek** [comment]
@wti806 This error came while the widget rendered.

**Comment by nicolasgarnier** [comment]
To re-iterate: FirebaseUI won't support Firebase Extensions, it doe snot support Chrome extensions either. We recommend you file a feature request so that at least the underlying Firebase Auth SDK supports Firefox extensions using the link provided by @bojeil-google.
