### ISSUE TITLE
Is it possible to upload avatar on registration? 

### ISSUE THREAD

**Issue by Levelleor** [firebase/firebaseui-web#298]
Facebook and other social networks sync their avatars with Firebase but on manual registration, the user is unable to pick an avatar. Is it possible to enable this somewhere or it simply isn't a feature in Firebase UI?

**Comment by bojeil-google** [comment]
I am assuming you are referring to the user's photoURL? When you sign in with Facebook or other social providers, the provider's photoURL would be set on that user (`auth.currentUser.photoURL`).
If you need to update that to something different, you would need to do so after registration.

**Comment by Levelleor** [comment]
@bojeil-google That's exactly what I mean. Usually, websites let users upload that `photoURL` right in registration form. 

So looks like that's impossible.

**Comment by bojeil-google** [comment]
It is correct we do not handle this on our end but you could still implement that and from a user's perspective, it would still appear as part of the registration process.

So after a user clicks the `sign in with Facebook` button, they would redirect back to the page, and be signed in under the hood (our sign in callbacks would trigger) but you would then show the option to upload their `photoURL`. We are also working on exposing additional user info in the callback to help determine if a user is new or existing. You would give the user the option to choose their avatar if this is a new user.

**Comment by Levelleor** [comment]
Yea, I know I could do something like that with callbacks. Thanks!
