### ISSUE TITLE
Demo instructions are off

### ISSUE THREAD

**Issue by cloudjlb** [firebase/firebaseui-web#299]
Looks like the demo instructions need to be updated as does the demo html.

**Comment by AnthonyNahas** [comment]
@cloudjlb  take a look at [ngx-auth-firebaseui](https://www.npmjs.com/package/ngx-auth-firebaseui) 👍 here is a  [live demo](https://ngx-auth-firebaseui.firebaseapp.com/home) hosted by firebase

**Comment by nicolasgarnier** [comment]
I'll close this because this is old and doesn't contain details and since the instructions and demos have been changed since.

If you think the instructions and demos are still incorrect please post here again or create a new issues with the exact issues you are facing.
