### ISSUE TITLE
signInSuccessUrl always required

### ISSUE THREAD

**Issue by MarcMouallem** [firebase/firebaseui-web#3]
The documentation states that the `signInSuccessUrl` is only required as follows.

> signInSuccessUrl: The URL where to redirect the user after a successful sign-in. **Required** when the signInSuccess callback is not used or when it returns true.

However this is not the case. Currently by having the `signInSuccess` callback return false you can ignore the `signInSuccessUrl`, but it it still required otherwise the following error will be thrown and the `signInSuccess` function will not be called.

> firebase-auth.js:48 Uncaught Error: Configuration signInSuccessUrl is required.

**Comment by bojeil-google** [comment]
signInSuccessUrl is currently always required even when false is returned in the callback.

**Comment by christianlanz** [comment]
Please make "signInSuccessUrl" optional. If it's set, do the redirect, if not - do nothing.

**Comment by bojeil-google** [comment]
We will work on making that optional. However for you case, return false in you sign in callback so no redirect happens while you call user.getToken() or on resolution, do the redirect manually.

**Comment by Tim15** [comment]
I have the same issue. I hope it's fixed soon.

**Comment by christianlanz** [comment]
@bojeil-google What sign in callback are you talking about? Is there any documentation?

**Comment by bojeil-google** [comment]
Just to clarify, the callback I was referring to is explained in the README.md in the "Example with all parameters used":
`'callbacks': {
          'signInSuccess': function(currentUser, credential, redirectUrl) {
             // No redirect.
             return false;
          }
}`

**Comment by bojeil-google** [comment]
Hey @itispeach, the redirectUrl parameter is optional and will only be populate if you pass a signInSuccessUrl query parameter in the sign in widget url. I assume you are not passing. In addition signInSuccess callback will be triggered only when a user is logged in. So currentUser should always be populated. Here is one way you can do this:

`'signInSuccessUrl': '<url-to-redirect-to-on-success>',
  'callbacks': {
  'signInSuccess': function(currentUser, credential, redirectUrl) {
   // This will redirect to redirectUrl if available or the signInSuccessUrl you specified in the config when
   // there is no redirectUrl.
    // return true; 
    // If you to redirect manually, redirect here and return false.
    window.location.href = '<my-website's-protected-page>';
    return false;
  }
}`

**Comment by itispeach** [comment]
Hmmm, I'm still stuck. here's more of my code. I tried to apply your example, but I can still navigate strait to the "protected page" even though I'm in an incognito window. I must be missing a concept, here. My only thoughts were, oh, I need 

`<script src="https://www.gstatic.com/firebasejs/3.1.0/firebase.js"></script>
    <script>
      var config = {
      apiKey: "give-this-to-no-one",
      authDomain: "nor this",
      databaseURL: "can't share this",
      storageBucket: "for-me-to-know-and-you-to-find-out",
      };
      firebase.initializeApp(config);
    </script>
    
    <script src="https://www.gstatic.com/firebasejs/ui/live/0.4/firebase-ui-auth.js"></script>
    
    <script type="text/javascript">
      var uiConfig = {
          'queryParameterForWidgetMode': 'mode',
          'queryParameterForSignInSuccessUrl': 'signInSuccessUrl',
          'signInSuccessUrl': '<private-site-that-only-authenticated-users-can-visit>',
          'signInOptions': [
            firebase.auth.EmailAuthProvider.PROVIDER_ID
          ],
          'callbacks': {
            'signInSuccess': function(currentUser, credential, redirectUrl) {
              window.location.href = '<public-site-its-okay-to-visit>';
              return false;
            }
          }
        };
      </script>`

Do I need to use this somewhere? `firebase.auth().onAuthStateChanged(function(user) {});`

**Comment by bojeil-google** [comment]
Hey @itispeach, check the response I gave on stackoverflow:
http://stackoverflow.com/questions/38191852/is-there-a-signinfailureurl-parameter-for-github-project-firebaseui-for-web

**Comment by TMSCH** [comment]
We fixed this issue in the new release. It will raise an error only if there is the `signInSuccessUrl` is required, i.e. if the `signInSuccess` callback returns `true` (i.e. proceed with redirect) and no `redirectUrl` has been given as a URL parameter, or that both `signInSuccessUrl` and `signInSuccess` callback are not given.

**Comment by oliversisson** [comment]
I thought I'd just write the solution to this error
"No redirect URL has been found. You must either specify a signInSuccessUrl in the configuration, pass in a redirect URL to the widget URL, or return false from the callback"

All you need to do is return false in the signInSuccess callback

```
  const uiConfig = {
    callbacks: {
      signInSuccess: () => false,
    },
```

**Comment by GreatFireWall** [comment]
@oliversisson Not work.

![image](https://user-images.githubusercontent.com/4510984/58929644-96fe5e00-878a-11e9-9b23-9c285b38551a.png)

**Comment by bojeil-google** [comment]
Your callback is returning a promise which [evaluates](https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/handler/common.js#L563) to true.

**Comment by GreatFireWall** [comment]
@bojeil-google Oh, thanks, solved.

**Comment by brandonfajardo** [comment]
<img width="770" alt="Screen Shot 2019-06-12 at 5 07 55 PM" src="https://user-images.githubusercontent.com/28847524/59386479-c128c080-8d34-11e9-8e74-83f596a5b067.png">
<img width="445" alt="Screen Shot 2019-06-12 at 5 07 09 PM" src="https://user-images.githubusercontent.com/28847524/59386486-c554de00-8d34-11e9-88dd-b5a17a091fc3.png">

Still receiving this error, please help!

**Comment by bojeil-google** [comment]
You are returning a promise which resolves to true which triggers the redirect. Since no URL provided, an error is shown. Change the callback to be synchronous.

**Comment by brandonfajardo** [comment]
> You are returning a promise which resolves to true which triggers the redirect. Since no URL provided, an error is shown. Change the callback to be synchronous.

Is it possible to use async here?

**Comment by alipetarian** [comment]
@brandonfajardo I used this way and it worked for me. 

![image](https://user-images.githubusercontent.com/13538128/87294331-08c3e200-c51d-11ea-9e72-b2de342c8aa0.png)

**Comment by Chuiantw1212** [comment]
Why is this issue closed? Having a not so making sense work around did not really solve the problem. 
In modern framework, it is a common scenario to route to various paths after signed in.

It is logical to make this field optional,
considering making it optional won't make a breaking change.

**Comment by ishaiavrahami** [comment]
how this issue solved?

**Comment by thdoan** [comment]
I'm encountering this issue.

My setup:
```
<script src="https://www.gstatic.com/firebasejs/9.22.1/firebase-app-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.22.1/firebase-app-check-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.22.1/firebase-auth-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.22.1/firebase-functions-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/ui/6.0.2/firebase-ui-auth.js"></script>
<script>
...
ui.start('#firebaseui-auth-container', {
  signInOptions: [
    {
      callbacks: {
        signInSuccess: () => false,
      },
      forceSameDevice: true,
      provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
      signInMethod: firebase.auth.EmailAuthProvider.EMAIL_LINK_SIGN_IN_METHOD,
    }
  ],
});
...
</script>
```

Steps to reproduce:

1. Enter email and click Next button
2. Click on email verification link in email
3. You're successfully signed in, but there's this error:

_firebase-ui-auth.js:378 Uncaught Error: No redirect URL has been found. You must either specify a signInSuccessUrl in the configuration, pass in a redirect URL to the widget URL, or return false from the callback._

I tried adding this to `signInOptions`, but I didn't like the experience because when you land on the page (a single-page app), it redirects to itself (reloads), which is a bad UX:

```
signInSuccessUrl: '/',
```

I'm wondering if the culprit might be the minifier, which changes the code to this: `callbacks:{signInSuccess:()=>!1}`
