### ISSUE TITLE
Allow clearing and re-rendering the widget to better support single page apps

### ISSUE THREAD

**Issue by alfongj** [firebase/firebaseui-web#30]
Currently, the sign in widget has to be rendered in its own page, usually in a popup page for single page applications. It will throw an error if the developer tries to render it more than once on the same page.
Here are a bunch of common situations:
The developer renders the sign in widget on their single page webpage if the user is logged out.

Federated sign in
-----------------------
1. The nascar screen is presented. The user clicks google sign in button
2. OAuth flow is triggered and the page redirects back to the same original page and the sign in success callback is called and the widget is cleared without any redirect. The developer now displays the authenticated content while showing the sign out button.
3. sign out button is clicked and the sign in widget is supposed to be rendered again but since it was previously rendered to process the redirect result for step 2, an error would be thrown.

Password sign in (account chooser disabled for simplicity)
-------------------------
1. The user signs in with email.
2. The sign in form is presented without any page redirect.
3. On success, the sign in form is cleared and the developer shows the authenticated content on the same page along with a sign out button.
4. sign out button is clicked and the sign in widget is supposed to be rendered again but since it was previously rendered to show the nascar screen in step 1, an error would be thrown.

**Comment by TMSCH** [comment]
The new release now has a `reset()` method that disposes of the widget and allows to re-render it on the same page. The demo app in the examples folder shows how to use FirebaseUI in a Single Page Application context.

**Comment by tarangkhandelwal** [comment]
This enhancement really helps out in integrating firebaseui with Ionic/Angular app . Thanks

**Comment by bamarni** [comment]
@tarangkhandelwal : the doc says only email provider is supported, did you manage to integrate other providers with ionic? Also, are you using angularfire? I'd appreciate if you could share a small code snippet on how you did it :) thanks

**Comment by tarangkhandelwal** [comment]
Well it did worked on  browser's while working on Ionic app , but seems like ionic isn't supported officially and gives error on actual device. 
and yes I am using angularfire .  

https://github.com/firebase/firebaseui-web/issues/26
