### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by maryam-abdullah** [firebase/firebaseui-web#300]
Hey there,

Logging in with Facebook, Twitter and Google gave a 502 bad gateway.

Any thoughts?

Thanks in advance.

**Comment by maryam-abdullah** [comment]
Then I tried to log in after a while, I got **A network error has occurred**.

**Comment by MikeVerhees** [comment]
same for me, I checked multiple projects on web and cordova android/ios, the issue stays the same.

**Comment by maryam-abdullah** [comment]
Ah, then that means it's caused by Firebase.

I have no idea what the reason might be.

**Comment by JarikH** [comment]
Looks like it's indeed an issue with Firebase.
https://status.firebase.google.com/incident/Authentication/18002

**Comment by maryam-abdullah** [comment]
Thank you for sharing this information.

**Comment by nicolasgarnier** [comment]
Looks like this was a temporary issue that is now resolved. Closing this.
