### ISSUE TITLE
Failed to register a ServiceWorker unsupported MIME type ('text/html')

### ISSUE THREAD

**Issue by sunilmaiya** [firebase/firebaseui-web#307]
This is the following snippet i am tryign to run to get messaging client ID 

`const messaging = firebase.messaging(); 
messaging.getToken()
    .then(function(currentToken) {
      if (currentToken) {
      console.log(currentToken);
      } else {
        console.log('error: no token');
      }
    })
    .catch(function(err) {
      console.log('An error occurred while retrieving token. ', err);
    });`

its giving an error shown below

`{
browserErrorMessage: "Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').",
code: "messaging/failed-serviceworker-registration",
message:"Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html'). (messaging/failed-serviceworker-registration).",
stack: "FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html'). (messaging/failed-serviceworker-registration).
at https://www.gstatic.com/firebasejs/4.9.0/firebase.js:27:14334
at <anonymous>"
}`

**Comment by bojeil-google** [comment]
You posted to the wrong repo. This seems likes a messaging issue. Post your question to https://github.com/firebase/firebase-js-sdk/
