### ISSUE TITLE
VerifyPassword: undefined??

### ISSUE THREAD

**Issue by recklessruby** [firebase/firebaseui-web#309]
Hello, I recently updated to 2.6.0, thanks for including anonymous authentication, it's exactly what I needed! 

When an anonymous user merges with a previously signed in user I get this error in the console. 
firebaseui.js:165 - [ 74.584s] [firebaseui] verifyPassword: undefined
It doesn't happen when anonymous users are upgraded to new users.
My sign-in flow is working fine regardless of the error, users are appearing in the firebase console etc and anonymous users and their data are deleted/merged as expected. 
I thought perhaps I'm not setting a variable in my uiConfig object? I couldn't see anything in the documentation about setting verifyPassword?
 
Since adding 2.6.0 I've updated my code to include the signInFailure callback which copies and removes anonymous users carts when they upgrade to a non-anonymous account, but even without this code I was getting the verifyPassword: undefined error. 

Hope you can help! 

`var currentUser;
var anonUser;
var accountUpgradeInProgress = false;
// FirebaseUI config.
var uiConfig = {
  callbacks: {
    signInSuccess: function(currentUser, credential, redirectUrl) {
      // Do something.
      // Return type determines whether we continue the redirect automatically
      // or whether we leave that to developer to handle.
      var url = decodeURI(window.location.hash);
      var user = firebase.auth().currentUser;

      handleSignedInUser(user, url);
      return false;

    },
    // signInFailure callback must be provided to handle merge conflicts which
    // occur when an existing credential is linked to an anonymous user.
    signInFailure: function(error) {
      // For merge conflicts, the error.code will be
      // 'firebaseui/anonymous-upgrade-merge-conflict'.
      if (error.code != 'firebaseui/anonymous-upgrade-merge-conflict') {
        return Promise.resolve();
      } else {

        unsubscribeToCart();
        accountUpgradeInProgress = true;

        return dbUserCollection.doc(anonUser.uid).delete()
        .then(function(){
          return anonUser.delete()
        })
        .then(function(){
          //Sign in user
          console.log("Anon user deleted");
          return firebase.auth().signInWithCredential(error.credential);
        })
        .then(function(){
          console.log("User signed in");
          //Check for other carts in user's name.
          return dbCartCollection.where("userRef", "==", firebase.auth().currentUser.uid)
          .orderBy("lastUpdated", "desc").get()
        })
        .then(function(querySnapshot){
          console.log("Looking for duplicate carts");
          //console.log(querySnapshot);
          var batch = db.batch();
          var cartData;
          //If other carts present then delete outstanding carts.
          if(querySnapshot.size > 0){
            if(cart.cart.length === 0){
              var count = 0;
              querySnapshot.forEach(function(doc){
                if(count === 0){
                  console.log(doc);
                  cartData = doc.data();
                  cart.cart = cartData.cart;
                  cart.numItems = cartData.numItems;
                  cart.total = cartData.total;
                  cart.tax = cartData.tax;

                  duplicateCartRef = dbCartCollection.doc(cart.id);
                  batch.delete(duplicateCartRef);
                  cart.id = doc.id;
                  count++;
                } else {
                  duplicateCartRef = dbCartCollection.doc(doc.id);
                  batch.delete(duplicateCartRef);
                }
              });

            } else {
              //Something in anon user cart, delete other carts.
              querySnapshot.forEach(function(doc){
                console.log(doc);
                var duplicateCartRef = dbCartCollection.doc(doc.id);
                batch.delete(duplicateCartRef);
              });
            }

            return batch.commit()
          }
        })
        .then(function(){
          return dbCartCollection.doc(cart.id).set({
            cart: cart.cart,
            total: cart.total,
            numItems: cart.numItems,
            tax: cart.tax,
            userRef: firebase.auth().currentUser.uid,
          }, {merge: true});
        })
        .then(function(){
          console.log("Cart user ref updated");
          var date = Date.now();
          var user = firebase.auth().currentUser;
          return dbUserCollection.doc(user.uid).set({
            userCart: {
              ref: cart.id,
              lastUpdated: date,
            }
          }, {merge: true})
        })
        .then(function(){
          console.log("User cart ref updated");
          var user = firebase.auth().currentUser;
          var url = decodeURI(window.location.hash);
          cart.uid = user.uid;
          accountUpgradeInProgress = false;
          handleSignedInUser(user, url);
        })
        .catch(function(error){
          console.log("ERROR: ", error);
        });
      };
    },
    uiShown: function() {
      // The widget is rendered.
      // Hide the loader.
     $("#sign-in-loader").removeClass("active");
     $("#sign-in-loader").addClass("disabled");
    }
  },
  autoUpgradeAnonymousUsers: true,
  signInFlow: 'redirect',
  signInSuccessUrl: '#profile/',
  signInOptions: [
    // Leave the lines as is for the providers you want to offer your users.
    {
      provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
      requireDisplayName: true,
    }
  ],
  credentialHelper: firebaseui.auth.CredentialHelper.NONE,
  // Terms of service url.
  tosUrl: '',
};`

**Comment by bojeil-google** [comment]
Hey @recklessruby thanks for reporting this issue. It is hard to tell, why you are getting this error.
When this happens, does the flow get interrupted and does signInFailure not get called? Do you see any other errors in the console? 
If `signInFailure` gets called, does it finish running?

**Comment by recklessruby** [comment]
Hi @bojeil-google no problem! 

Flow isn't interrupted. I've just put a breakpoint on the first if statement within the signInFailure callback. signInFailure is only called once and tracks through all promises as expected and then calls handleSignedInUser. 

No other errors in the console, none of my functions are listed in the call stack for the error either. 

However, I do get a returned promise during the sign-in flow from a firestore realtime update. I unsubscribe from the updates when signInFailure is called using the function below. I've also included the subscribeToCart() function, the promise returns to doc.exists = false. I guess this is a remnant from subscribing to the anon user cart and it being deleted/editing as the user is merged. 

`
function subscribeToCart(cartID){

  dbCartCollection.doc(cartID)
  .onSnapshot(function(doc){

    if(doc.exists){
      var cartData = doc.data();
      //Current User's cart
      cart.cart = cartData.cart;
      cart.total = cartData.total;
      cart.numItems = cartData.numItems;
      cart.tax = cartData.tax;
      cart.totalCart();

    } else {
      console.log("No such cart, cart ID: ", doc.id);
      //cart.clearCart();
    }
    updateCartTotalIcon(cart);
    $("#cart-list").html(Handlebars.templates.cartList(cart));

  }, function(error){
    console.log("ERROR: ", error);
  });

}
function unsubscribeToCart(){
  dbCartCollection.onSnapshot(function(){});
}`

Here is the full console error. 

`[244.138s] [firebaseui] verifyPassword: undefined
$f @ firebaseui.js:165
Yf.h @ firebaseui.js:165
Hf.log @ firebaseui.js:162
eg @ firebaseui.js:165
(anonymous) @ firebaseui.js:298
r.b @ auth.js:23
mt @ auth.js:26
vt @ auth.js:26
ou.Mb @ auth.js:25
$ @ auth.js:19
Promise resolved (async)
Xu @ auth.js:18
J @ auth.js:18
pt @ auth.js:25
ht @ auth.js:24
ou.xc @ auth.js:23
e.g @ firebaseui.js:149
ef @ firebaseui.js:152
$e @ firebaseui.js:151
D.A @ firebaseui.js:151
Me @ firebaseui.js:146
Promise resolved (async)
Je @ firebaseui.js:146
Ie @ firebaseui.js:146
bf @ firebaseui.js:151
Oe @ firebaseui.js:150
D.F @ firebaseui.js:150
r.b @ auth.js:23
mt @ auth.js:26
vt @ auth.js:26
ou.Mb @ auth.js:25
$ @ auth.js:19
Promise resolved (async)
Xu @ auth.js:18
J @ auth.js:18
pt @ auth.js:25
ht @ auth.js:24
ou.xc @ auth.js:23
e.g @ firebaseui.js:149
ef @ firebaseui.js:152
$e @ firebaseui.js:151
D.A @ firebaseui.js:151
Me @ firebaseui.js:146
Promise resolved (async)
Je @ firebaseui.js:146
Ie @ firebaseui.js:146
bf @ firebaseui.js:151
Oe @ firebaseui.js:150
D.D @ firebaseui.js:149
g @ firebaseui.js:151
Promise resolved (async)
cf @ firebaseui.js:151
Oe @ firebaseui.js:150
(anonymous) @ firebaseui.js:147
e.h @ firebaseui.js:149
ef @ firebaseui.js:151
$e @ firebaseui.js:151
D.A @ firebaseui.js:151
Me @ firebaseui.js:146
Promise resolved (async)
Je @ firebaseui.js:146
Ie @ firebaseui.js:146
bf @ firebaseui.js:151
Oe @ firebaseui.js:150
E @ firebaseui.js:148
am @ firebaseui.js:351
(anonymous) @ firebaseui.js:347
r.g @ auth.js:23
mt @ auth.js:26
vt @ auth.js:26
ou.Mb @ auth.js:25
$ @ auth.js:19
Promise resolved (async)
Xu @ auth.js:18
J @ auth.js:18
pt @ auth.js:25
ut @ auth.js:22
ct @ auth.js:23
Z.then @ auth.js:21
ou.hb @ auth.js:252
i @ auth.js:275
Hk @ firebaseui.js:351
(anonymous) @ firebaseui.js:347
(anonymous) @ firebaseui.js:341
(anonymous) @ auth.js:257
Promise resolved (async)
ou.dc @ auth.js:257
i @ auth.js:275
(anonymous) @ firebaseui.js:341
D @ firebaseui.js:147
$l @ firebaseui.js:341
(anonymous) @ firebaseui.js:347
r.g @ auth.js:23
mt @ auth.js:26
vt @ auth.js:26
ou.Mb @ auth.js:25
$ @ auth.js:19
Promise resolved (async)
Xu @ auth.js:18
J @ auth.js:18
pt @ auth.js:25
ht @ auth.js:24
(anonymous) @ auth.js:19
(anonymous) @ auth.js:142
(anonymous) @ auth.js:138
vn @ auth.js:45
ln @ auth.js:44
Ne @ auth.js:77
ou.fc @ auth.js:75
ou.zb @ auth.js:75
XMLHttpRequest.send (async)
Ie @ auth.js:73
mr.m @ auth.js:138
wr @ auth.js:137
(anonymous) @ auth.js:142
Z @ auth.js:19
Tr @ auth.js:142
(anonymous) @ auth.js:153
r.g @ auth.js:23
mt @ auth.js:26
vt @ auth.js:26
ou.Mb @ auth.js:25
$ @ auth.js:19
Promise resolved (async)
Xu @ auth.js:18
J @ auth.js:18
pt @ auth.js:25
ht @ auth.js:24
(anonymous) @ auth.js:19
(anonymous) @ auth.js:142
(anonymous) @ auth.js:138
vn @ auth.js:45
ln @ auth.js:44
Ne @ auth.js:77
ou.fc @ auth.js:75
ou.zb @ auth.js:75
XMLHttpRequest.send (async)
Ie @ auth.js:73
mr.m @ auth.js:138
wr @ auth.js:137
(anonymous) @ auth.js:142
Z @ auth.js:19
Tr @ auth.js:142
(anonymous) @ auth.js:153
r.g @ auth.js:23
mt @ auth.js:26
vt @ auth.js:26
ou.Mb @ auth.js:25
$ @ auth.js:19
Promise resolved (async)
Xu @ auth.js:18
J @ auth.js:18
pt @ auth.js:25
ut @ auth.js:22
ct @ auth.js:23
Z.then @ auth.js:21
ou.qc @ auth.js:258
i @ auth.js:275
k.xb @ firebaseui.js:347
Bj @ firebaseui.js:252
Pk @ firebaseui.js:297
(anonymous) @ firebaseui.js:315
(anonymous) @ firebaseui.js:253
(anonymous) @ firebaseui.js:238
oe @ firebaseui.js:140
ne @ firebaseui.js:139
k.handleEvent @ firebaseui.js:228
a.(anonymous function).a.(anonymous function) @ firebaseui.js:138
le @ firebaseui.js:136
he @ firebaseui.js:137
b @ firebaseui.js:134
`

**Comment by bojeil-google** [comment]
I think the error is from your end. Something in your `signInFailure` logic.

This is the line throwing this:
https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/handler/common.js#L1023

`startSignInWithEmailAndPassword` is called and it will fail with an error due to merge conflict.

`onUpgradeError` will trigger:
https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/authui.js#L895

This calls your `signInFailure` callback: https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/authui.js#L1243

It waits for your promise to resolve. It doesn't expect an error to be thrown. If it gets an error, in your case some `error.code` that it doesn't know how to handle:
https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/handler/common.js#L1023

Since there is no message on the error, it is shown as undefined.

**Comment by bojeil-google** [comment]
Ok, we did some investigation, and it appears to be on our end. This is a benign error. It shows up in the console but has no effect. We will catch that error so it doesn't show up in the browser console.

**Comment by recklessruby** [comment]
Ok thanks for finding the issue, I’m pleased it’s not an issue with my code!

**Comment by wti806** [comment]
We fixed the issue in our internal repo and the fix will be rolled out in next minor version release. Thanks for pointing it out. @recklessruby

**Comment by wti806** [comment]
@recklessruby This issue is fixed in 2.6.2 release. https://github.com/firebase/firebaseui-web/releases. Thanks

**Comment by recklessruby** [comment]
Brilliant thanks for fixing it! 👍
