### ISSUE TITLE
Regression in 2.6: Getting Uncaught exception when calling .reset in componentWillUnmount in React

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/firebaseui-web#310]
I'm getting an uncaught exception when calling `.reset()` in `componentWillUnmount` in React apps:

![image](https://user-images.githubusercontent.com/3766663/36073346-5f2af72e-0f2f-11e8-8963-6fe02cbf3929.png)

This was working fine in v2.5.1 (just tested) and I'm getting the issue with the latest (v2.6.0) release.

You can see the issue here: https://test-27bb7.firebaseapp.com/

**Comment by nicolasgarnier** [comment]
FYI [react-firebaseui](https://github.com/firebase/firebaseui-web-react) calls `.reset()` in the `componentWillUnmount `. The deployed app is the example react-firebaseui app: https://github.com/firebase/firebaseui-web-react/tree/master/example

**Comment by bojeil-google** [comment]
We made a lot of changes in `2.6.0` to support anonymous user upgrade flow. I assume there is some underlying promise that is getting cancelled and whose cancellation error is not getting caught. This should be benign but I will try to investigate which promise is not catching this error and suppress it.

**Comment by nicolasgarnier** [comment]
Yes, just FYI this does not provokes any other side effects. I can sign-in and out and sign-in again without issues.

**Comment by wti806** [comment]
The bug has been fixed in 2.6.2 release. https://github.com/firebase/firebaseui-web/releases
