### ISSUE TITLE
Angular 5 & Firebase: phone authantication, Verify your phone number - cannot read property “call” or undefined

### ISSUE THREAD

**Issue by MJahangir82** [firebase/firebaseui-web#317]
I'm trying to use Firebase drop in UI for authentication. since it is working fine for all providers expect Phone authentication. I can receive the 6 digit code on my phone. on verification of the code its raise an exception. my source code is available on GitHub. https://github.com/MJahangir82/FirebaseUI-Angular/tree/master/sample
![capture](https://user-images.githubusercontent.com/22867317/36339352-a069687c-13dc-11e8-80de-7296a9c815f6.PNG)

**Comment by wti806** [comment]
This is an issue introduced in 2.6.0.  We already released 2.6.1 with the fix earlier today. Could you please try to upgrade your firebaseui? Thanks for reporting the issue.

**Comment by MJahangir82** [comment]
Thanks! @wti806  you are fantastic :)

**Comment by brs14ku** [comment]
Is this error back? 

firebaseui@2.7
firebase@4.13.1

I'm gettting exact same thing as OP with the drop in.

**Comment by brs14ku** [comment]
For whatever it's worth, I downgraded to 2.6.1 because you noted that the bug was fixed in it and now it works. I guess the bug was reintroduced?

**Comment by bojeil-google** [comment]
I tested with our demo app: https://fir-ui-demo-84a6c.firebaseapp.com/ which uses the latest version and I can't reproduce it.
