### ISSUE TITLE
Only one-tap signing without google login button.

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebaseui-web#319]
Is it possible for me to use firebaseui-web _only_ for the one-tap sign up pop-up?
Because I have a custom button for google login, without using firebaseui-web.

I followed the guide here:
https://github.com/firebase/firebaseui-web#one-tap-sign-up

This is my code. I currently also see the google login-button.
```js
firebase.initializeApp(config)
    let ui = new firebaseui.auth.AuthUI(firebase.auth())
    ui.start('#firebaseui-auth-container', {
      signInOptions: [
        {
          provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
          authMethod: 'https://accounts.google.com',
          clientId: 'myid.apps.googleusercontent.com'
        },
      ],
      credentialHelper: firebaseui.auth.CredentialHelper.GOOGLE_YOLO
    })
    ui.disableAutoSignIn()
```

**Comment by bojeil-google** [comment]
If you just want to use one-tap sign-up, you could just use it on its own without firbeaseui-web.
Only other thing you can do is hide the google button using CSS.

**Comment by mesqueeb** [comment]
@bojeil-google thank you for the good advice! Hiding the container with CSS made it work!
