### ISSUE TITLE
unable to login with social on ionic app

### ISSUE THREAD

**Issue by malikasinger1** [firebase/firebaseui-web#32]
## in one of my chat application https://github.com/malikasinger1/inzi-chat-app

# I'm Unable to login with facebook on ionic app

**Comment by bojeil-google** [comment]
Firebase auth v3 sign in with popup and redirect are not yet supported for ionic/cordova frameworks. Check the thread:

https://groups.google.com/forum/#!searchin/firebase-talk/cordova$20facebook%7Csort:relevance/firebase-talk/mC_MlLNCWnI/UHU6R-4iBAAJ

Unfortunately, this workaround will not work for firebaseui-web. However once these methods are supported, firebaseui-web should be compatible.

**Comment by TMSCH** [comment]
Hi @malikasinger1 ,
You're referring to Firebase SDK v2. FirebaseUI uses SDK 3+ Please post your question on StackOverflow.
Closing this issue.

**Comment by bojeil-google** [comment]
FYI, FirebaseUI v2.1.1 now supports OAuth sign-in for Cordova.
