### ISSUE TITLE
Only show one-tap sign in after rendering a view/div.

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebaseui-web#320]
I'm currently using firebaseui-web for the one-tap login popup by google on my SPA.

Is there any way to delay the popup until a div appears or until the user presses a button?

Since it's a SPA that can be played around with before signing up, it might scare users away if the popup is shown as soon as the users open my app.

**Comment by bojeil-google** [comment]
One-tap sign-up hint selector shows only when you render the sign-in UI with FirebaseUI-web. 
If you want to show it on its own at the time of your choosing, you may as well just do it separately without using firebaseui.

**Comment by mesqueeb** [comment]
@bojeil-google In case I want to have the full integrated CSS etc. for the signin popup, shouldn't I best use firebaseui?

**Comment by bojeil-google** [comment]
I don't know what you mean. The way this is designed is to show the hint selector when the FirebaseUI sign-in screen renders. Your customization request is too specific and may not meet other developer/application needs. We want to provide a solution that works for everyone and not tailored for one application.

**Comment by mesqueeb** [comment]
@bojeil-google 
Nevermind about that last post.
When integrating [Google One-Tap sign in](https://developers.google.com/identity/one-tap/web/retrieve-hints) it's very clear how to choose on when you want the login popup come out for the first time, and when to authenticate returning users:

- `googleyolo.hint()`: should be put on the login page or in my case (in my SPA) is called programatically when the user presses a button or reaches a condition.
- `googleyolo.retrieve()`: should be put on all pages that need a user authenticated. I have an SPA so I load this in the beginning of my `main.js`.

It's unclear with firebaseui how to call the one-tap popup programatically. (That's why I opened this thread.)

### My Catch-22

- If I render the firebaseui only when the user presses a button, will the auto authentication for returning users still work?
- If I render the firebaseui from the start in my `main.js` it will also pop up for users who never visited, which might scare away new users.

**It's a dilemma. : D**

**Comment by bojeil-google** [comment]
We provide all the tools you need to do whatever you want to do. 
You could render FirebaseUI and not show the one-tap sign-up. You can render it while showing it. You can enable auto sign-in and you can disable it via `disableAutoSignIn`. You can also only show the hint selector without showing FirebaseUI by hiding the Google button. 
If you want more guidance and help crafting a solution, stackoverflow would be a good place where experts from the community can help out and others can benefit from the answer.

If you don't want to use firebaseui-web, you can sign in with Firebase using Google ID token returned as follows:
```
firebase.auth().signInWithCredential(firebase.auth.GoogleAuthProvider.credential(idToken));
````

**Comment by mesqueeb** [comment]
@bojeil-google 
Thanks!
Do you know how I can "You could render FirebaseUI and not show the one-tap sign-up."
Do you mean with CSS `display: none`?

**Comment by mesqueeb** [comment]
One-Tap says to put `googleyolo.retrieve()` but firebase UI is only to be put on login-pages.
I guess I'm confused what to do with non-login pages but still want to show the auto-selection of the user in the One-Tap popup.

On pages where the firebase ui is not included, the general firebase auth listener will automatically log in my users, right? However, in this case I don't get an animation where a user is selected in One-Tap.

I wonder if it's possible to still show the animation from One-Tap where the google account is auto-selected and a green round ✅ appears.

Implementing One-Tap directly also is not an option since they don't provide auto-login when the user has several accounts.

**Comment by bojeil-google** [comment]
It is not clear I understand you. The 2 systems work independently. There is no way to show the selection animation in one-tap when a user selects a Firebase sign-in option.
