### ISSUE TITLE
Autocomplete Warning from Within #firebaseui-container Content

### ISSUE THREAD

**Issue by zipzit** [firebase/firebaseui-web#321]
The javascript tied to this repo generates significant content inside`<div id="firebaseui-container"></div>`.   For what ever reason, the Chrome browser dev tools console gets quickly filled up with warnings:  

`[DOM] Input elements should have autocomplete attributes (suggested: autocomplete='name', confirm at https://goo.gl/6KgkJg) <input type=​"text" id=​"form_name" name=​"name " class=​"form-control " required=​"required" placeholder=​"Name">​`

I'm assuming the fix is something like [this.](https://stackoverflow.com/questions/47842910/after-upgrading-google-chrome-to-version-63-0-3239-84-i-have-started-receiving-e) .  

And by the way, I'm really grateful to the Google team for all that they've provided here.. Many thanks!

**Comment by wti806** [comment]
I am using chrome 64 and doesn't see the warning you mentioned. Could you please provide more detail of how to reproduce it? Like what flows triggered the warning?

**Comment by zipzit** [comment]
As I'm preparing a response to wti806 comment, I did a trial run on a windows machine (chrome).  What the heck, no console messages there at all.    

Here's my new summary:

  Warnings not visible on Windows 10 machine, Chrome 63.0.3239.132 (Official Build) (64-bit)
  Warnings not visible on Windows 10 Machine Firefox 58.0.2 (64 bit)

  Warnings totally visible on MacOS (laptop), Chrome 64.0.3282.167   <-- Huh?
  Warnings not visible on MacOS, Chrome Canary 66.0.3350.0 64-bit
  Warnings not visible on MacOS, Safari 11.0.3

Way odd.  You are welcome to inspect the site, the error will display without actually submitting a phone number.  Click on the [phone menu selection. ](http://loseweight.vegas/#phone_list) 

http://loseweight.vegas

Do note, this is a jQuery Mobile site, and as such there could easily be some odd behavior between firebase javascript methods and jQm functionality...  

and if this issue is off base on my part, profuse apologies...

Oh, a side note, I went from 230 lbs to 185 lbs (50 lbs) of weight via that group in just under three months...

**Comment by wti806** [comment]
I tried with the phone sign in page with both Chrome 63.0.3239.132 and Chrome 64.0.3282.167 on my laptop(MacOS). And also in Linux Chrome browser. Didn't see warnings at all.  The only thing printed in the console is "on #phone_list 'page' ".

**Comment by wti806** [comment]
I was able to reproduce it. The log level is verbose rather than warning or error. And it's because a recent release of Chrome. And the element it's complaining about is "form_name", which is not in firebaseUI. I think it's the Contact Us page. You should be able to fix it on your side.

**Comment by zipzit** [comment]
Doh!  Totally right.  This one is totally on me.  Again, Profuse apologies...
