### ISSUE TITLE
When I call firebaseui it tries to start a new instance.

### ISSUE THREAD

**Issue by xenzox1** [firebase/firebaseui-web#325]
When I run the "new firebaseui.auth.AuthUI (firebase.auth ())", it tries to start the firebase again using the "firebase.initializeApp (...). Auth", but this gives an error: TypeError: firebase .initializeApp (...). auth is not a function; path: node_modules / firebaseui / dist / npm.js: 336.
![image](https://user-images.githubusercontent.com/28571385/36543146-aab06ebe-17c1-11e8-96db-2c44f35ab4fe.png)

**Comment by bojeil-google** [comment]
Internally FirebaseUI-web creates a temporary instance to help sign-in and handle anonymous user upgrade. However, I think your issue is not FirebaseUI related. You seem to have some issue with the Firebase JS sdk. Try initializing an Auth instance separately and debug from there.

**Comment by wti806** [comment]
I've seen another developer having the same issue.  #322 Can you try to re-install your node modules?

**Comment by xenzox1** [comment]
@bojeil-google  I made a login flow with email and password and it worked perfectly as you can test here: https://votacao-67558.firebaseapp.com/auth/register;

@wti806  I reinstalled the node_modules and it continues giving error;

**Comment by wti806** [comment]
Can you provide the code of how you initialize FirebaseUI?

**Comment by bojeil-google** [comment]
I went to the URL provided in my Chrome browser 64.0.3282.167 and signed in successfully a couple of times without any error.

**Comment by xenzox1** [comment]
Well, I rewrote the page code and it does not return any more errors, but it does not display anything. The path to the page is: https://votacao-67558.firebaseapp.com/auth/

Her code is this:
``import React, {Component} from 'react';
import {auth, googleProvider, emailProvider} from '../../back/firebase/firebase';
import 'firebaseui/dist/firebaseui.css';
import * as firebaseui from 'firebaseui';

export default class Auth extends Component {
    uiConfig = null;
    ui = null;

    constructor() {
        super();
        this.uiConfig = {
            signInOptions: [
                {
                    provider: googleProvider.PROVIDER_ID,
                    authMethod: 'https://accounts.google.com',
                    clientId: '1076835671674-qjgnnqk2ahl4svn0mlbtuhqn2b6p7pa6.apps.googleusercontent.com'
                },
                emailProvider.PROVIDER_ID,
            ],
            credentialHelper: firebaseui.auth.CredentialHelper.GOOGLE_YOLO,
            tosUrl: '/tos'
        };

        this.ui = new firebaseui.auth.AuthUI(auth);
    }

    componentDidMount() {
        this.ui.start('#firebaseui-auth-container', this.uiConfig);
    }

    componentWillUnmount() {
        this.ui.reset();
    }

    render() {
        return (
            <div>
                <div id="firebaseui-auth-container"/>
            </div>
        );
    }
}``

**Comment by xenzox1** [comment]
Well, I rewrote the page code and it does not return any more errors, but it does not display anything. The path to the page is: https://votacao-67558.firebaseapp.com/auth/

Her code is this:
```JSX
import React, {Component} from 'react';
import {auth, googleProvider, emailProvider} from '../../back/firebase/firebase';
import 'firebaseui/dist/firebaseui.css';
import * as firebaseui from 'firebaseui';

export default class Auth extends Component {
    uiConfig = null;
    ui = null;

    constructor() {
        super();
        this.uiConfig = {
            signInOptions: [
                {
                    provider: googleProvider.PROVIDER_ID,
                    authMethod: 'https://accounts.google.com',
                    clientId: '1076835671674-qjgnnqk2ahl4svn0mlbtuhqn2b6p7pa6.apps.googleusercontent.com'
                },
                emailProvider.PROVIDER_ID,
            ],
            credentialHelper: firebaseui.auth.CredentialHelper.GOOGLE_YOLO,
            tosUrl: '/tos'
        };

        this.ui = new firebaseui.auth.AuthUI(auth);
    }

    componentDidMount() {
        this.ui.start('#firebaseui-auth-container', this.uiConfig);
    }

    componentWillUnmount() {
        this.ui.reset();
    }

    render() {
        return (
            <div>
                <div id="firebaseui-auth-container"/>
            </div>
        );
    }
}
```

**Comment by yoiang** [comment]
Sorry to interrupt the conversation's flow, reverting to Firebase `4.8.0` has resolved the issue for me if that's notable to any maintainers. 

I was in the same boat, getting the same error where reinstalling `node_modules` did not resolve the issue.

**Comment by xenzox1** [comment]
@yoiang Thanks but it did not work :(

**Comment by bojeil-google** [comment]
You are not importing firebase. We need it to initialize a firebase app.

**Comment by xenzox1** [comment]
I start in an external file called firebase.jsx:
```JSX
import * as firebase from 'firebase';
import 'firebase/firestore';

const config = {
    apiKey: "<Some codes>",
    authDomain: "<Some codes>",
    databaseURL: "<Some codes>",
    projectId: "<Some codes>",
    storageBucket: "<Some codes>",
    messagingSenderId: "<Some codes>"
};

firebase.initializeApp(config);

const auth = firebase.auth();
const storage = firebase.storage();
const firestore = firebase.firestore();
const googleProvider = new firebase.auth.GoogleAuthProvider();
const emailProvider = new firebase.auth.EmailAuthProvider();
auth.useDeviceLanguage();

export {auth, storage, firestore, firebase, emailProvider, googleProvider};
```

**Comment by bojeil-google** [comment]
You export but you do not import it:
`import {auth, googleProvider, emailProvider} from '../../back/firebase/firebase';`

**Comment by xenzox1** [comment]
Do I need a variable called firebase to call firebaseUI?

**Comment by xenzox1** [comment]
It did not work to import the firebase...

**Comment by bojeil-google** [comment]
I cannot see what you are doing wrong. I have the exact code in my reactjs app and it works fine:
```
import firebase from 'firebase';
import firebaseui from 'firebaseui';
...
const authUi = new firebaseui.auth.AuthUI(firebase.auth());

```

**Comment by xenzox1** [comment]
I found a solution, instead of importing the variables from my file with the firebase settings, I just imported the firebase object directly at the top of the page. Possibly the error was caused because I already import the firebase configuration file into a component higher than the react-router-dom.
Auth.jsx with firebaseui:
```JSX
import React, {Component} from 'react';
import firebase from 'firebase';
import 'firebaseui/dist/firebaseui.css';
import * as firebaseui from 'firebaseui';

export default class Auth extends Component {
    uiConfig = null;
    ui = null;

    constructor() {
        super();
        this.uiConfig = {
            signInOptions: [
                {
                    provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
                    authMethod: 'https://accounts.google.com',
                    clientId: '<Some code>'
                },
                firebase.auth.EmailAuthProvider.PROVIDER_ID,
            ],
            credentialHelper: firebaseui.auth.CredentialHelper.GOOGLE_YOLO,
            tosUrl: '/tos'
        };

        this.ui = new firebaseui.auth.AuthUI(firebase.auth());
    }

    componentDidMount() {
        this.ui.start('#firebaseui-auth-container', this.uiConfig);
    }

    componentWillUnmount() {
        this.ui.reset();
    }

    render() {
        return (
            <div>
                <div id="firebaseui-auth-container"/>
            </div>
        );
    }
}
```

App.jsx top level component:
```JSX
import React, {Component} from 'react';
import './css/App.css';
import {BrowserRouter as Router, Switch} from 'react-router-dom';
import MyRoute from './back/routes/MyRoute';
import Routes from './back/routes/Routes';
import authRoutes from './back/routes/authRoutes';
import {auth} from './back/firebase/firebase';
import {isEmailVerified, sendEmailVerification} from "./back/firebase/userControl";
import CircularProgress from "material-ui/CircularProgress";
import {deepPurple500} from 'material-ui/styles/colors'

class App extends Component {
    constructor() {
        super();
        this.state = {
            isAuth: null,
        }
    }

    componentDidMount() {
        auth.onAuthStateChanged(user => {
            if (user) {
                this.setState({isAuth: true});
                if (!isEmailVerified()) {
                    sendEmailVerification();
                }
            } else {
                this.setState({isAuth: false});
            }
        });
    }

    render() {
        if (this.state.isAuth == null) {
            return <div className="centered"><CircularProgress size={250} thickness={8} color={deepPurple500}/></div>;
        }
        return (
            <Router>
                <div>
                    <div className="faixa_cor"/>
                    <Switch>
                        {this.state.isAuth ?
                            Routes.map((route, i) => <MyRoute key={i} {...route}/>) :
                            authRoutes.map((route, i) => <MyRoute key={i} {...route}/>)
                        }
                    </Switch>
                </div>
            </Router>
        )
    }
}

export default App;
```
