### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by zhulduz** [firebase/firebaseui-web#328]
I get always an error as in the demo example when I set 
`signInSuccess: () => false`.

The error is in the attached screenshot:
<img width="1149" alt="screen shot 2018-02-26 at 12 16 25" src="https://user-images.githubusercontent.com/1921276/36655775-ef7562f4-1aee-11e8-9dc2-7319dd92335d.png">

**Comment by wti806** [comment]
Duplicated issue #310. We are going to have a minor release with the fix.

**Comment by wti806** [comment]
Fixed in release 2.6.2. https://github.com/firebase/firebaseui-web/releases
