### ISSUE TITLE
Detect login in progress

### ISSUE THREAD

**Issue by gleno** [firebase/firebaseui-web#339]
When a login is in progress the widget displays an MDL progress bar. We wish to display a helpful message that the  login in in progress. How do I detect when this login progress begins?

**Comment by bojeil-google** [comment]
We currently have a `uiShown` callback you can use: https://github.com/firebase/firebaseui-web#uishown

**Comment by gleno** [comment]
@bojeil-google I'm sorry, there seems to be a misunderstanding. The uiShown() callback is called after the widget initializes. I am talking about the phase of authentication where the widget is showing the loading animation as it authenticates with the provider.

1. Widget loads.
2. User clicks the widget, follows google authentication.
3. Back to the original web page. The widget is displaying the loading animation.
4. Redirect happens.

I need to be able to detect the time between 3 and 4, so that I can override the animation displayed by the widget with something meaningful - like a note that says that authentication is in progress.

Is there an event for that? Can I find out what phase of authentication we are currently at?

**Comment by bojeil-google** [comment]
Modifying the DOM of the sign-in UI can be risky as it could break things, especially if underlying components change, which may happen as we update the library and add new features. This is why we don't provide an official way to do this. You would need to fork and modify the library. 
There is an undocumented to do this but you would need to do it at your own risk as this unofficial API could be removed in the future: https://github.com/firebase/firebaseui-web/issues/288

**Comment by gleno** [comment]
I don't want to modify the widget. I'll just hide it, while it's thinking and put up a full screen message. I want the loading to be obvious to the user, and it's not at the moment. While it might be reasonable on mobile, it's not on the deaktop. 

I think maybe I won't need the UI after all. While simplifying the default login, it's very inblexible in terms of design language integration. 

Thanks for the link, I'll take a look!

**Comment by nicolasgarnier** [comment]
P|One way you could do this @gleno is by modifying the CSS of that "loading" element. You can add text via CSS using the `:before` CSS selector and a `content` attribute with some text. This way you can easily add a bit of helpful text like "Hold on tight we're signing-you in". :)

**Comment by theGABS** [comment]
Hey, I have similar problem, it is not about HOW display loading, it is about WHEN display loading. 

something like

firebase.something.authProcessIsStart().then(() => {
  showMyLoader();
}).
