### ISSUE TITLE
Modularize FirebaseUI

### ISSUE THREAD

**Issue by TangSteven** [firebase/firebaseui-web#341]
For my simple Firebase UI setup (Google, Facebook, and Email and Password), more than 80% of the CSS code and about 50% of the JS code is never used according to DevTools Coverage. 

I believe it would be more efficient to offer each authorization package provider as an individual component like how [Material Design Components Web](https://github.com/material-components/material-components-web/) works, to prevent unused code from slowing down web page loading.

**Comment by bojeil-google** [comment]
Thanks for the feature request, @TangSteven . I agree that we should tackle this issue long term but we have higher priority items on our agenda that we have committed to deliver to developers. These take precedence.
In the meantime, you can always use JS compilers that provide dead code elimination.

**Comment by nicolasgarnier** [comment]
Let's close this one and track this in #257.
