### ISSUE TITLE
signInSuccess not being called on successful login

### ISSUE THREAD

**Issue by rlansky** [firebase/firebaseui-web#342]
Hi,

Using the latest version of the Firebase Javascript SDK (4.10.1) with Firebaseui-web, I'm finding that my signInSuccess callback is no longer being called when the user successfully logs in. The result is that the login widget just sits there.

 If I dial back the Firebase version to 4.10.0, it all works as expected. Does anyone have idea what's happening with this? Here's my UI config for reference:

```
   const uiConfig = {
      callbacks: {
        signInSuccess: (user) => {
          //  This never gets called when I use Firebase 4.10.1, it does get called if I use Firebase 4.10.0
          this.props.onLogin(user);
          return false;
        },
        uiShown: () => {
          document.getElementById('loginLoadingIndicator').style.display = 'none';
        }
      },
      credentialHelper: firebaseui.auth.CredentialHelper.NONE,
      signInFlow: this.props.signInFlow,
      signInOptions: [
        firebase.auth.EmailAuthProvider.PROVIDER_ID,
        firebase.auth.GoogleAuthProvider.PROVIDER_ID
      ],
      signInSuccessUrl: '/',
      tosUrl: `http://${siteUrl}/terms`
    };
```

Thanks in advance,
--Rick

**Comment by bojeil-google** [comment]
Just tested this with firebaseui@2.6.2 and firebase@4.10.1 and the signInSuccess callback triggered.

**Comment by rlansky** [comment]
Huh... those are the same versions I tried it with.

**Comment by bojeil-google** [comment]
I basically modified the demo app to use these versions and tested and checked the callback was triggered.

**Comment by rlansky** [comment]
Well. It still doesn't work in my app. Not sure what other stuff I have that could be causing this. But if it's just me, I'll go ahead and close this for now.

**Comment by tweeres04** [comment]
@rlansky Did you figure this out? I'm getting the same thing

**Comment by rlansky** [comment]
I did not.

**Comment by rlansky** [comment]
I did just try this again with the newest versions, 4.11.0 for Firebase and 2.6.3 for firebase-ui web, and now things are working again.

**Comment by tweeres04** [comment]
Ok thanks, I'll try upgrading everything and see how it goes.

**Comment by tweeres04** [comment]
Can confirm, upgrading to the latest version resolved it
