### ISSUE TITLE
Network Error in Demo website

### ISSUE THREAD

**Issue by uilgniw** [firebase/firebaseui-web#346]
Network Error is occurred in Demo website and in my website
Step to reproduce:
1. visit [demo website](https://fir-ui-demo-84a6c.firebaseapp.com/)
2. click on any login button
3. read the error

Someone on Stackoverflow said this issue is due to Content Security Policy, and by removing the `<form>` tag, it works.

**Comment by bojeil-google** [comment]
We can't recreate this. This issue must be unique to your environment. It could be your network connection, some chrome extension installed, browser, etc.
