### ISSUE TITLE
could not get data

### ISSUE THREAD

**Issue by sangaji** [firebase/firebaseui-web#350]
sorry this my first app
i have problem why i can't get data after redirect into my app but even thought when i test with run browser its work nicely
can someone give me solusion?

**Comment by bojeil-google** [comment]
Your question is unclear and cryptic. Please provide more details and provide snippets. Also clarify your question. What "data" are you referring to?

**Comment by sangaji** [comment]
sorry im newbie but i try too tell u
i make aplication with cordova and i use login twitter with firebase
when i try that with cordova run browser it work nicely and on my console.log they show my data after login like name,email,user id and etc
but when i make that in apk that can't work nicely cause i can't get data after redirect from twitter on my app cordova
can u give me solution?
sorry my english so bad

**Comment by bojeil-google** [comment]
Refer to the documentation on this:
https://firebase.google.com/docs/auth/web/cordova
