### ISSUE TITLE
Error: OAuth on Cordova Android, get auth/redirect-cancelled-by-user.

### ISSUE THREAD

**Issue by lucasmaurice** [firebase/firebaseui-web#353]
Same as #267 with some differences :

- I do not use a custom domain.
- I use Cordova 8.0.0
- I use cordova-universal-links-plugin in ^1.2.1
- The authentication was working in past on both iOS and Android, and now work only on ios.
(Got `auth/redirect-cancelled-by-user`)

I've try :
```javascript
universalLinks.subscribe(null, function(eventData) {
    console.log('universalLink: ' + eventData.url);
});
```
But nothing happen.

`<preference name="AndroidLaunchMode" value="singleTask" />` is present

Here is my connection script:
```javascript
firebase.auth().signInWithRedirect(provider).then(function() {
    return firebase.auth().getRedirectResult();
}).then(function (result) {
    facebookLogin(result);
    if(_callback) _callback(result);
}).catch(function (error) {
    facebookError(error);
    // Go here an get the error `auth/redirect-cancelled-by-user`
    if(_error) _error(error);
});
```

I've try with both `GoogleAuthProvider()` and `FacebookAuthProvider()`, same result.

Thanks in advance for your help.

**Comment by bojeil-google** [comment]
Can you explain what changed since it last worked?
If the manual subscriber is not triggering, it is likely an issue with the plugin.

**Comment by lucasmaurice** [comment]
There is a lot of change but in others parts of the application. The mains changes who can affect this is : I switch Cordova from 7.x to 8.0.0 and Android from 6.x.x to 7.0.0.

**Comment by lucasmaurice** [comment]
It seems to work with Android  6 instead of Android 7 ...

**Comment by joeychong** [comment]
I am having the same problem.
I am using Cordova 8.0.0, it run well on IOS but having the `auth/redirect-cancelled-by-user` on my Android 7 too.
So, do you manage to solve on Android 7?

**Comment by raviteja1982** [comment]
I am running into the same issue as well. Appreciate it, if anyone could post the fix for this.

**Comment by diegomesata** [comment]
My problem was cordova-universal-links-plugin, in the config.xml file you have to register your universal links:
  <universal-links>
        <host name="myapp.page.link" scheme="https" />
        <host name="myapp.firebaseapp.com" scheme="https">
            <path url="/__/auth/callback" />
        </host>
  </universal-links>

That settings will modify your AndroidManifest.xml file on build.

<activity ....> .............
 <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="vpsapps-b5799.firebaseapp.com" android:scheme="https" android:path="/__/auth/callback"/>
      </intent-filter>
    </activity>

But for some strange reason the AndroidManifest.xml was not updated. So I uninstall and reinstall the plugin, build again and the file was modified correctly.
 
I'm using this fork @prageethsilva/cordova-universal-links-plugin, because the cordova-universal-links-plugin is not building on phonegap cordova 8.
