### ISSUE TITLE
Using with Google Actions

### ISSUE THREAD

**Issue by blundell** [firebase/firebaseui-web#356]
I've deployed this to my own firebase hosting.

Trying to now work out what the URL endpoints are for using this with the Google Assistant API's
https://developers.google.com/actions/identity/account-linking

<img width="593" alt="screen shot 2018-03-28 at 12 42 25" src="https://user-images.githubusercontent.com/655860/38026831-7fbdc9b6-3285-11e8-8c84-835484fdc325.png">
<img width="473" alt="screen shot 2018-03-28 at 12 42 30" src="https://user-images.githubusercontent.com/655860/38026832-7fd2fc64-3285-11e8-8849-5c56b7206c4c.png">

Can anyone help please?

**Comment by bojeil-google** [comment]
You have to build these endpoints. They our out of scope for Firebase Auth as we don't currently issue third party tokens and only first party tokens. There are some posts for this on stackoverflow.
https://stackoverflow.com/questions/42916987/actions-on-google-account-linking-with-firebase
https://stackoverflow.com/questions/47099318/adding-account-linking-to-my-actions-on-google-app
