### ISSUE TITLE
[Feature Request] Support Email Link auth

### ISSUE THREAD

**Issue by Tsuki** [firebase/firebaseui-web#359]
Please support using sendSignInLinkToEmail authentication

**Comment by bojeil-google** [comment]
Thank you for your request, @Tsuki. This is definitely a feature we need to support.

**Comment by lanman2000** [comment]
Any updates on when this will be supported?

**Comment by bojeil-google** [comment]
Hey @lanman2000, we don't have a specific date but this is on our roadmap. We have had some urgent features to release dealing with privacy policies and terms of service. We also have some features that were requested by developers in our pipeline that we are wrapping up.

**Comment by bojeil-google** [comment]
We would definitely like to support it this year.

**Comment by blowsie** [comment]
Is this feature imminent?

**Comment by bojeil-google** [comment]
It should be coming soon. We are trying to align FirebaseUI Android, iOS and web on this.

**Comment by salmoro** [comment]
@bojeil-google I see that the recently released version 3.5 has support for email links but I can't seem to get it to work.

I've spun up the demo locally (as the demo site is not updated with 3.5) and hooked it up to an account of mine and all methods work other than email link which gets suck at a blank page with no message and no email sent either:

![chrome_2018-12-20_19-46-21](https://user-images.githubusercontent.com/20197680/50301629-87b37e80-0490-11e9-932a-3e0c43d638ef.png)

I directly compare this on the same project to calling `firebase.auth.sendSignInLinkToEmail()` which works well.

I made sure to add the `emailLinkSignIn` function in the configuration but it doesn't seem to get called.

Thanks

**Comment by salmoro** [comment]
@wti806 That's the thing, there are no errors. CSS is latest In my project it's from 3.5 and so for the demo I've run.

**Comment by salmoro** [comment]
After I enter the email and click next the `firebase-container` just empties out:
![chrome_2018-12-20_20-35-06](https://user-images.githubusercontent.com/20197680/50303770-c5b3a100-0496-11e9-9ddc-34f6d330b855.png)

**Comment by wti806** [comment]
It's weird. I just tried to clone the repo and run the demo and it works fine for me. Did you change the code in demo directory by any chance?

**Comment by salmoro** [comment]
No I have not.

**Comment by wti806** [comment]
Could you please post the index.html file in the demo app here?

**Comment by salmoro** [comment]
I think I found the issue

**Comment by wti806** [comment]
For now, please use the gstatic version of firebaseUI. We need  to fix the issue with CDN and npm.

**Comment by wti806** [comment]
V3.5.1 has been released which includes the fix.

**Comment by derekperkins** [comment]
Should this issue be closed?
