### ISSUE TITLE
Recommended way to use in a modal?

### ISSUE THREAD

**Issue by corysimmons** [firebase/firebaseui-web#360]
A modal's markup is usually removed/added to the page as needed.

If firebaseui is watching a specific DOM element, then 1) that element isn't on the page until the modal is opened, 2) that element is unable to be watched when the modal is closed.

99.9999% of my frustration with this project is just trying to use it with React and as a modal... :(

**Comment by bojeil-google** [comment]
I am not sure what the problem is here.
When the modal is about to be displayed, you render FirebaseUI (that's when it cares about the element it will be rendered in). Right before it is being closed, you delete the FirebaseUI instance.

**Comment by corysimmons** [comment]
Codesandbox of FirebaseUI in react-modal or it's not possible 🏋️
