### ISSUE TITLE
Linking Multiple Accounts

### ISSUE THREAD

**Issue by kkcodes** [firebase/firebaseui-web#361]
Hello,

I am using Firebase for Web, Android and iOS.

In Android, we have implemented the link:

Link Multiple Auth Providers mentioned here:
https://firebase.google.com/docs/auth/android/account-linking

Now, I am trying to replicate the same thing for the web that is mentioned here, https://firebase.google.com/docs/auth/web/account-linking

However, I want to use this library in order to achieve this. I haven't found any way to do this. Can anyone guide me to get the desired result? 

Also, if in Android, an user account is Link with other Auth provider, then the Sign In for Web stops working. 

Like I tried to login with facebook, with id abc@test.com, it returns sayting that an account is already there for abc@test.com, Sign in with Google. And, if I try to sign in with Google, it replies with this error:

**_User can only be linked to one identity for the given provider_**

Any help would be appreciated.

Thanks

**Comment by kkcodes** [comment]
Hi,

The example that you have mentioned leads to this: 
https://user-images.githubusercontent.com/5721836/31921889-c20439ba-b83f-11e7-8482-51446faa35e3.png 

??

And, also if it doesn't is there any way to achieve this using this library?

**Comment by wti806** [comment]
The account link feature is built-in in firebaseui. You don't need to handle it manually. As in the image you posted, the Facebook provider is linked to the Google account. I don't quite understand what else you are trying to achieve?

**Comment by kkcodes** [comment]
Hi, 

I am not able to achieve this. Here is the detailed scenario.

The above shared image's scenario is not working for me. I tried for Google Sign (abc@test.com) and then tried to use the Facebook Login with the same email (abc@test.com) . But, it says you have already  have an account on Google, sign in with it and if I sign in then the above multi auth connected to the same account is not working. 

In the provider, it remains Google. And from the Android side, if they create the above mentioned scenario, then the Login with Google Stops working and it responds with this error, 

User can only be linked to one identity for the given provider

Do let me know, if I am doing something wrong.

Thanks.

**Comment by kkcodes** [comment]
I have already tested it and it works fine, but I am not sure at the firebase end whether it links both the provider to the same Firebase Account.

  <script src="https://cdn.firebase.com/libs/firebaseui/2.7.0/firebaseui.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/2.7.0/firebaseui.css" />
    <script type="text/javascript">
      // FirebaseUI config.
      var uiConfig = {
        signInSuccessUrl: '<url-to-redirect-to-on-success>',
        signInOptions: [
          // Leave the lines as is for the providers you want to offer your users.
          firebase.auth.GoogleAuthProvider.PROVIDER_ID,
          firebase.auth.FacebookAuthProvider.PROVIDER_ID,
          firebase.auth.TwitterAuthProvider.PROVIDER_ID,
          firebase.auth.GithubAuthProvider.PROVIDER_ID,
          firebase.auth.EmailAuthProvider.PROVIDER_ID,
          firebase.auth.PhoneAuthProvider.PROVIDER_ID
        ],
        // Terms of service url.
        tosUrl: '<your-tos-url>'
      };

      // Initialize the FirebaseUI Widget using Firebase.
      var ui = new firebaseui.auth.AuthUI(firebase.auth());
      // The start method will wait until the DOM is loaded.
      ui.start('#firebaseui-auth-container', uiConfig);
    </script>

I am using the exact above same code. Any help would be appreciated.

**Comment by wti806** [comment]
As you've seen, it works fine with our test app. It's not likely a bug with our library.  We cannot help if we are not able to replicate the issue. If you could deploy your site somewhere, we could probably help you find out what happened.

**Comment by kkcodes** [comment]
Issue is resolved. Thanks.

**Comment by saikat-aedifex** [comment]
@kkcodes Can you provide the details on how you resolved the issue? I'm also running into the same issue with 

> I tried for Google Sign (abc@test.com) and then tried to use the Facebook Login with the same email (abc@test.com) . But, it says you have already have an account on Google, sign in with it and if I sign in then the above multi auth connected to the same account is not working.

Thanks for your input

**Comment by philsp** [comment]
I'm running into the same problem in the demo app. Accounts are not linked

Using first Google and then Email shows: "You already have an account - You’ve already used paul.sampleman@gmail.com. Sign in with Google to continue."

**Comment by brayo-pip** [comment]
almost 4 years later I'm experiencing the same problem... any help will be appreciated

**Comment by AntonioVentilii** [comment]
same here

**Comment by 0xbrayo** [comment]
It wasn't #1038
