### ISSUE TITLE
how do I extend the token's expiration period ?

### ISSUE THREAD

**Issue by testdnmedia** [firebase/firebaseui-web#362]
I want to extend the token expiration after login, how to do ?

**Comment by bojeil-google** [comment]
You can't extend the expiration. The token expires every hour. You just get a new token anytime you need it by calling `firebase.auth().currentUser.getIdToken()`. It will either returned an unexpired cached token or a new one if the old one was expired.

**Comment by deepfriedbrain** [comment]
I came across this issue with the same question.

May I ask, if getIdToken() is able to return a valid token in any case, then in what case do we need to use a Refresh token? In several places I read that after the ID token has expired, we need to use the refresh token to get a new ID token. I'll really appreciate if you can clarify this.

**Comment by bojeil-google** [comment]
The refresh token is used under the hood by `getIdToken` to get a new ID token when the previous one expires. Normally you don't need to use it if you are using the supported client SDKs. The refresh token can be used to get a new ID token if you want to do this on your own too via REST API. Some developers use this in platforms that are not officially supported by Firebase.

**Comment by deepfriedbrain** [comment]
That makes it clear. Thank you so much. It will be great if you can put this information (as clearly as you mentioned here) somewhere in the documentation too.
