### ISSUE TITLE
RecaptchaVerifier failed: Third argument "app" must be an instance of Firebase App.

### ISSUE THREAD

**Issue by bmass02** [firebase/firebaseui-web#369]
# Problem
Phone Auth encounters an error ("RecaptchaVerifier failed: Third argument "app" must be an instance of Firebase App.") after user clicks "Sign in with Phone".

### Working Conditions [repro](https://givegrove-test.firebaseapp.com/login)
**Using Webpack externals (to allow auto initialization of Firebase [link](https://firebase.google.com/docs/hosting/reserved-urls#sdk_auto_configuration))**
FirebaseUI: 2.3
Firebase: 4.12

**Without using Webpack externals**
FirebaseUI: 2.6 (potentially latest; didn't test)
Firebase: 4.12

### Failing Conditions [repro](https://givegrove-bm.firebaseapp.com/login)
**Using Webpack externals**
FirebaseUI: >2.3
Firebase: >4.6.1 (didn't test below since I needed Firestore)

## Discussion
I can't pinpoint what is going wrong. When Webpack externals is not used, then "firebase" is not in the global scope, which causes it to work. Maybe there is some condition checking for "firebase" in the global scope, and if that condition is met, it executes some buggy code? [This](https://github.com/firebase/firebaseui-web/blob/dc57287e1ae72fb8d0fea1c6f0678f03fe438e45/javascript/widgets/handler/phonesigninstart.js#L136) is where it is saying an "instance of Firebase App" is not provided.

**Comment by bojeil-google** [comment]
It checks this is an instanceOf `firebase.app.App`: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/args.js#L381

Not sure why auto-initialization would be different here. Underneath it does the same thing.
I speculate it is some issue related to obfuscation. Did you try manually initializing the firebaseApp instance and then test again?

**Comment by bmass02** [comment]
Actually, firebase being in the global namespace shouldn't affect anything since the demo uses it in the global namespace. Maybe it has something to do with firebase being included separately. Manually initializing throws a "duplicate app" error if done along side the auto-initialization.

**Comment by bojeil-google** [comment]
That is what I meant, manually initialize without auto-initialization to debug this issue.

**Comment by bmass02** [comment]
I did that also and still got the same error. I even used the src link from the demo and that also failed.

**Comment by bmass02** [comment]
I just looked at the difference between the npm.js file for 2.3 and 2.4. As of 2.4, there are added `require` statements at the top. These will cause it to fail if FirebaseUI is included as an NPM while Firebase is included via CDN. Maybe if the require fails, it can look for the variables in the global space?

**Comment by nicolasgarnier** [comment]
Thanks for sharing your fix!

**Comment by bateview** [comment]
Can you be more specific how to solve the problem?
