### ISSUE TITLE
Auth/operation not supported in this environment [For Sign-In with Google]

### ISSUE THREAD

**Issue by drishi94** [firebase/firebaseui-web#37]
For a new web developer or firse-time firebase user going through the firebaseui-web tutorial sequentially in github, they will experience an issue if they try to support login through one of our federated providers and test it locally in the file environment. 

![screen shot 2016-08-16 at 10 51 18 am](https://cloud.githubusercontent.com/assets/21042322/17709778/65c24840-639f-11e6-9b8b-f7aec11ef72d.png)

This can be easily resolved if the user uses the Firebase CLI, using **firebase serve** so it goes through localhost, but an introduction to this is missing in the Github. Perhaps we could also make the error code message indicate this solution so developers will know where to go.

**Comment by TMSCH** [comment]
I will add this to the README. Thanks for pointing this out.

**Comment by fedex1** [comment]
I believe the issue still exists even if you use "firebase serve"

I run "firebase serve" then go to http://localhost:5002 and still I see "Error code: auth/app-not-authorized  Dismiss"

Can you give details how localhost can be used to login.

For example, see

![screenshot from 2016-08-18 16-10-28](https://cloud.githubusercontent.com/assets/167614/17789109/b4c7ea38-655e-11e6-9a67-68a616c746b8.png)
![screenshot from 2016-08-18 16-11-28](https://cloud.githubusercontent.com/assets/167614/17789112/b9ec75a6-655e-11e6-95e5-fe91c0b50ffc.png)
![screenshot from 2016-08-18 16-18-32](https://cloud.githubusercontent.com/assets/167614/17789276/74c10810-655f-11e6-8b20-7dd27716ae94.png)

**Comment by TMSCH** [comment]
This is a different error. This is related to a configuration issue. Go to Firebase console, your project, then Auth > Sign-in methods and make sure `localhost:5002` is an authorized domain.

**Comment by fedex1** [comment]
@TMSCH Thank you for the quick response and I apologize for delay.

But I still see issues.

If I try to add localhost:5000 or any host with port at https://console.firebase.google.com/project/classified-678e9/authentication/providers I see an error message "A valid domain name is required (e.g. 'myapp.com')"

![screen shot 2016-08-20 at 4 38 21 pm](https://cloud.githubusercontent.com/assets/167614/17833771/dce3e99e-66f4-11e6-8049-3a9d8034ee15.png)

In addition,  if I serve on port 80 of localhost, I still see the error (this is on a mac (not sure if that matters))
`
$ sudo firebase serve -p 80`

![screen shot 2016-08-20 at 4 38 57 pm](https://cloud.githubusercontent.com/assets/167614/17833777/100e2014-66f5-11e6-8dc0-bfdc56b7f89b.png)

**Comment by bojeil-google** [comment]
You are getting that error most likely because you have some referrer restrictions on you api key. When you create a new firebase console, an api key is provisioned with no restrictions. Did you create this api key manually? or are you migrating from an older Firebase project?

**Comment by fedex1** [comment]
I apologize.  I started from scratch and it works correctly.  Thanks for your replies and your patience.

**Comment by TMSCH** [comment]
The new 0.5.0 release improved the error messages being displayed, which should help debugging.
