### ISSUE TITLE
Google auto login (firebaseui::rememberedAccounts)

### ISSUE THREAD

**Issue by dhust** [firebase/firebaseui-web#374]
When I sign in with Google Auth and logout on my phone it allows me to pick which account I would like to log in with. Perfect. When I sign in and logout on my computer it just automatically logs me in. I don't want that.

The only thing I can see that might be an issue is when I go to Local Storage in the developer tools it shows:

`Key` of `firebaseui::rememberedAccounts` and a 
`Value` of `[{"email":"myusername@gmail.com","displayName":"John Smith","photoUrl":"https://lh6.googleusercontent.com/-ssbOlSuTyNc/AAAAAAAAAAI/BBBBBTI/JD2Nlh1K_bI/photo.jpg","providerId":"google.com"}]`

I'm assuming this is what's automatically logging me in because it's remembering my account information. I've tried clearing the cache and browsing history so then I can choose an account again, but that only works for one sign in and then it goes back to logging me in automatically again. Any ideas?

**Comment by incinirate** [comment]
If you look closer at the readme on the front page you will find:

> Auto sign-in for returning users can be disabled by calling `ui.disableAutoSignIn()`. This may be needed if the FirebaseUI sign-in page is being rendered after the user signs out.

**Comment by bojeil-google** [comment]
Your question is unclear, but I assume you are talking about Google OAuth sign in and not accountchooser.com.

This is an OAuth thing. When you sign in with Google you remain signed in and user is not prompted to sign in again.
If you want to force re-authentication when you sign in with google via firebaseui, you can pass the custom parameter `prompt`. It is mentioned in the README. I am copying and pasting it:

```
ui.start('#firebaseui-auth-container', {
  signInOptions: [
    {
      provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      scopes: [
        'https://www.googleapis.com/auth/plus.login'
      ],
      customParameters: {
        // Forces account selection even when one account
        // is available.
        prompt: 'select_account'
      }
    },
```
When you sign out with Firebase Auth, you only sign out from Firebase. If you want to sign out from Google, you have to redirect to the google single sign out URL.

**Comment by minhhunghuynh1106** [comment]
wtf
