### ISSUE TITLE
How to set RenderMode for Google Smart Lock, No Docs

### ISSUE THREAD

**Issue by praveeno** [firebase/firebaseui-web#376]
https://github.com/firebase/firebaseui-web/blob/dc57287e1ae72fb8d0fea1c6f0678f03fe438e45/javascript/externs/googleyolo.js#L138

I'm using GOOGLE_YOLO as credential Helper in firebaseui,
wondering how to set renderMode to bottomSheet for this.

**Comment by wti806** [comment]
Currently from what I know, we don't support custom render mode in firebaseUI.

**Comment by praveeno** [comment]
Please Let me know, What should be done, If i make a PR for this

**Comment by praveeno** [comment]
@wti806 Is there any way to set RenderMode.

**Comment by praveeno** [comment]
For Temporary Solution 

`
import { openyolo } from '@openid/openyolo';
openyolo.setRenderMode('bottomSheet');`
