### ISSUE TITLE
Problem running Demo Closure Template and need for Java

### ISSUE THREAD

**Issue by rebeccapeltz** [firebase/firebaseui-web#380]
I am trying to run the demo.  I get a popup saying I need a version of Java.  I'm running on a Mac 10.10.5.  To investigate, I saw that the first step is to call build and that build just calls gulp.  The error below indicates the problem is in not having Java.  Is Java required to build this project?

becky-mac:demo peltzr$ npm run build

> firebaseui@2.7.0 build /Users/peltzr/Downloads/firebaseui-web-master
> gulp

[12:34:26] Using gulpfile ~/Downloads/firebaseui-web-master/gulpfile.js
[12:34:26] Starting 'build-soy'...
[12:34:26] Starting 'build-css'...
[12:34:26] Starting 'build-css-rtl'...
[Closure Templates Error] No Java runtime present, requesting install.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firebaseui@2.7.0 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the firebaseui@2.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peltzr/.npm/_logs/2018-05-02T19_34_27_023Z-debug.log
becky-mac:demo peltzr$ gulp
[12:34:34] Working directory changed to ~/Downloads/firebaseui-web-master
[12:34:35] Using gulpfile ~/Downloads/firebaseui-web-master/gulpfile.js
[12:34:35] Starting 'build-soy'...
[12:34:35] Starting 'build-css'...
[12:34:35] Starting 'build-css-rtl'...
[Closure Templates Error] No Java runtime present, requesting install.

becky-mac:demo peltzr$

**Comment by bojeil-google** [comment]
Yes, you are required to have a Java Runtime Environment.
https://github.com/firebase/firebaseui-web#dependencies

**Comment by rebeccapeltz** [comment]
I'm still missing something or is there a specific version required?

becky-mac:firebaseui-web-master peltzr$ java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

[14%] soy_files Compiling 3 soy files to out (0.1 sec)[Closure Templates Error] Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by gokercebeci** [comment]
Same issue too ..

```
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
...
[18:37:18] Starting 'build-css-rtl'...
[14%] soy_files Compiling 3 soy files to out (0.2 sec)[Closure Templates Error] Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by gokercebeci** [comment]
```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
[JDK8](
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) It works.

**Comment by nicolasgarnier** [comment]
Looks like only JDK8 works but not JDK10. I'll make sure this is specified in the README.
