### ISSUE TITLE
able to get verified phone number but it also says undefined at the same time

### ISSUE THREAD

**Issue by vkprakash** [firebase/firebaseui-web#389]
This is where I access the cookie and use the value for a google maps marker label
` var markerLabel = document.cookie;
  var marker = new google.maps.Marker({
    position: {
      lat: data.User.l[0],
      lng: data.User.l[1]
    },
    map: map,
    label: markerLabel`

This is the code where I create the cookie
` 'signInSuccess': function(user, credential, redirectUrl) {
    // You can also access this via firebase.auth().currentUser.phoneNumber
    document.cookie =  (firebase.auth().currentUser.phoneNumber);
    handleSignedInUser(user);
    // Do not redirect.
    //'signInSuccessUrl': "http://localhost:8080/CurrentLocation.html",
    return true;
  }`

For some weird reason it the marker label keeps saying PhoneNumber=undefined; +1##########
It displays the users verified number but it also says undefined I only want it to display the phone number.
<img width="787" alt="screen shot 2018-05-08 at 6 43 26 pm" src="https://user-images.githubusercontent.com/6581045/39893441-91a526b6-5458-11e8-93ac-35de8f0f5912.png">

**Comment by bojeil-google** [comment]
Please open this issue in stackoverflow. This repo is not for debugging applications.
