### ISSUE TITLE
Force form rendering if only one provider is given

### ISSUE THREAD

**Issue by eveningkid** [firebase/firebaseui-web#39]
I think it speaks for itself given the title, but just in case: wouldn't it be nice to automatically get the login form loaded if, let's say, only the `firebase.auth.EmailAuthProvider.PROVIDER_ID` option is passed to the `signInOptions` array from the configuration object? Then, there would be no need for the user to click the only given option.

Or maybe come up with an additional parameter that would allow this?

I'm looking forward seeing this code to be open-sourced though. Keep it up! :)

**Comment by bojeil-google** [comment]
I think you are referring to this: https://github.com/firebase/firebaseui-web/issues/23

**Comment by eveningkid** [comment]
Oh, right. My bad! Good news then, hope this can be implemented anytime soon.
