### ISSUE TITLE
firebase phone auto login

### ISSUE THREAD

**Issue by vkprakash** [firebase/firebaseui-web#390]
`/**
 * @return {!Object} The FirebaseUI config.
 */
function getUiConfig() {
  return {
    'callbacks': {
      // Called when the user has been successfully signed in.
    'signInSuccess': function(user, credential, redirectUrl) {
    // You can also access this via firebase.auth().currentUser.phoneNumber
    document.cookie =  (firebase.auth().currentUser.phoneNumber);
    handleSignedInUser(user);
    // Do not redirect.
    //'signInSuccessUrl': "http://localhost:8080/CurrentLocation.html",
    return true;
  }
    },
    // Opens IDP Providers sign-in flow in a popup.
    'signInSucc essUrl':  "http://localhost:8080/homepage_latest.html",
    'signInFlow': 'popup',
    'signInOptions': [
      // The Provider you need for your app. We need the Phone Auth
      //firebase.auth.TwitterAuthProvider.PROVIDER_ID,
      {
        provider: firebase.auth.PhoneAuthProvider.PROVIDER_ID,
        recaptchaParameters: {
          type: 'image', // another option is 'audio'
          size: 'invisible', // other options are 'normal' or 'compact'
          badge: 'bottomleft' // 'bottomright' or 'inline' applies to invisible.
        }
      }
    ],
    // Terms of service url.
    'tosUrl': 'https://www.google.com'
  };
}

// Initialize the FirebaseUI Widget using Firebase.
var ui = new firebaseui.auth.AuthUI(firebase.auth());

/**
 * Displays the UI for a signed in user.
 * @param {!firebase.User} user
 */
var handleSignedInUser = function(user) {
  document.getElementById('user-signed-in').style.display = 'block';
  document.getElementById('user-signed-out').style.display = 'none';
  document.getElementById('name').textContent = user.displayName;
  document.getElementById('email').textContent = user.email;
  document.getElementById('phone').textContent = user.phoneNumber;
  if (user.photoURL){
    document.getElementById('photo').src = user.photoURL;
    document.getElementById('photo').style.display = 'block';
  } else {
    document.getElementById('photo').style.display = 'none';
  }
};

/**
 * Displays the UI for a signed out user.
 */
var handleSignedOutUser = function() {
  document.getElementById('user-signed-in').style.display = 'none';
  document.getElementById('user-signed-out').style.display = 'block';
  ui.start('#firebaseui-container', getUiConfig());
};

// Listen to change in auth state so it displays the correct UI for when
// the user is signed in or not.
firebase.auth().onAuthStateChanged(function(user) {
  document.getElementById('loading').style.display = 'none';
  document.getElementById('loaded').style.display = 'block';
  user ? handleSignedInUser(user) : handleSignedOutUser();
});

/**
 * Deletes the user's account.
 */
var deleteAccount = function() {
  firebase.auth().currentUser.delete().catch(function(error) {
    if (error.code == 'auth/requires-recent-login') {
      // The user's credential is too old. She needs to sign in again.
      firebase.auth().signOut().then(function() {
        // The timeout allows the message to be displayed after the UI has
        // changed to the signed out state.
        setTimeout(function() {
          alert('Please sign in again to delete your account.');
        }, 1);
      });
    }
  });
};

/**
 * Initializes the app.
 */
var initApp = function() {
  document.getElementById('sign-out').addEventListener('click', function() {
    firebase.auth().signOut();
  });
  document.getElementById('delete-account').addEventListener(
      'click', function() {
        deleteAccount();
      });
};

window.addEventListener('load', initApp);
`
What is the code I need to use to automatically log a user in after they are verified and leave the app. Right now everytime you leave the app it keeps coming back to the homescreen where you need to get a code again and enter it in. How do I automatially log the user in the times after they are verified?

**Comment by bojeil-google** [comment]
You don't need to automatically log in a user after they are already signed in. Firebase auth sessions are indefinite. You need to setup the `onAuthStateChanged` listener to detect if a user is signed in already and handle it from there without needing to show the sign in widget. In that case, you just redirect. Otherwise, if no user is signed in, render firebaseui.

**Comment by vkprakash** [comment]
What exactly would I add to my code to do that?

**Comment by bojeil-google** [comment]
This GitHub repo is for reporting issues and filing client SDK requests related to FirebaseUI. Please post general/basic Firebase coding questions to stackoverflow with `firebase-authentication` tag.
```
....
firebase.auth().onAuthStateChanged(function(user) {
  if (!user) {
    // Not signed in. Show UI.
    ui.start('#firebaseui-container', getUiConfig());
  } else {
    // Signed in, redirect to sign in success url.
    window.location.assign('/signedInUrl');
  }
});
```
