### ISSUE TITLE
one email address per account

### ISSUE THREAD

**Issue by phancey** [firebase/firebaseui-web#391]
I have set this up on my project. I logged in with my Google Account, logged out, tried to login with my Twitter account and it told me I already had a login with that email address and I should sign in via Google.
All good.

Then I tried signing in via Twitter on my phone. It worked fine. No messages. Now that user has 2 providers listed.
Then if I try to sign in with Email/Password back on my computer, it shows me my Google email. I try to login with that and it tells me I already have logged in via Twitter.....

a) I wasn't expecting them to be able to do this. I thought they would be prompted to use the first choice ie in this case Google as per my first attempt.
b) if it is allowed - then why the inconsistency in my experience?

project - react-2bytes-burger2

thanks
Phil

**Comment by phancey** [comment]
But the experience is inconsistent.The accounts weren't linked originally, there was only the Google one. And when I tried logging in via Twitter it prevented me telling me to login with Google because the email addresses were the same.The only reason the user got linked to Twitter account too was because on a further attempt it then allowed me to login via Twitter. So why did one time it prevent me from logging in via a second provider but the next time allow me to do so, thus linking multiple accounts?On May 11, 2018 6:19 PM, bojeil-google <notifications@github.com> wrote:Both accounts are linked to the same user. Signing in with either will work. It's not possible for us to figure out the preference if multiple accounts are linked without providing multiple options for the user to choose.
We currently just pick the first one we get back from the Firebase Auth backend: https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/handler/common.js#L1447

**Comment by bojeil-google** [comment]
I don't understand what you are saying. After the accounts got linked, the user can sign in with either provider. If the user clicked the `sign in with google` or `sign in with twitter`, they would log in to the same account.

**Comment by phancey** [comment]
I am saying that I did not expect the accounts to be linked in the first place. I don't understand the logic being applied. I create a user in the first place by logging in under my Google account (user created automatically). Then I logout. Then I login by selecting "Login with Twitter". This shows me a message saying that I already have an account and I should sign in with Google and it then gives me a "Sign in with Google" button. I assumed this was preventing me from using my Twitter login and forcing me to use the Google login that was used first. But it is at that point that it seems to link the accounts.
If I can use more than one provider then why, when I try to "sign in with email" does it then follow the same pattern but in this case NOT add the "email provider". Instead it forces me to login via Twitter.

**Comment by bojeil-google** [comment]
If you don't want to link accounts, you will need to switch to "multiple accounts per email" via the Firebase Console. Otherwise we will aim to merge accounts and if a user that previously signed in with google or twitter tries to sign in with email using the same email, we will offer them to sign in with an existing account instead of create a new email/password account.
