### ISSUE TITLE
YOLO not working

### ISSUE THREAD

**Issue by smashah** [firebase/firebaseui-web#393]
YOLO/one-tap is not working for me (and for some others).

Did fb-ui team know about the whitelisting? If so, why is it not in the docs?

Currently getting the following error on a whitelisted origin (localhost):

`The client origin is not permitted to use this API.`

Can anyone recreate?

Reference:
https://stackoverflow.com/questions/50289065/google-yolo-stop-working-the-client-origin-is-not-permitted-to-use-this-api
https://twitter.com/sirdarckcat/status/994867137704587264
https://news.ycombinator.com/item?id=17044518

**Comment by bojeil-google** [comment]
We are well aware of this. We add a link to one-tap sign up for getting started (in our README). This github repo is not meant for documenting how to use and configure one-tap. Our demo app also works as expected with one-tap integration. If you have issues with one-tap, please file with the appropriate channels.

**Comment by ajonp** [comment]
I feel like the README.md should be updated to reflect that One Tap cannot be used in production for new Apps. If agreed I would be happy to make the pull request.

> The beta test program for this API is currently closed. We are improving the API's cross-browser functionality and will provide updates here in the coming months.

**Comment by bojeil-google** [comment]
Hmm, the wording can be revised. The API is not available to the general public, but there are applications using it in production and there is no guideline against that. Our demo app uses it: https://fir-ui-demo-84a6c.firebaseapp.com/
You have to go through their whitelisting process.

**Comment by jake-nz** [comment]
How about a big warning in your docs? That way people won't waste time getting this working locally when it can't be used in production.

**Comment by NawarA** [comment]
Haha, yeah. I spun my wheels a few hours wondering what I was doing wrong. This article helps me realize its not a production feature, but a disabled feature...which the docs should mention!!
