### ISSUE TITLE
Authentication not persisting between sessions on Xcode ios simulator

### ISSUE THREAD

**Issue by JMEssex** [firebase/firebaseui-web#394]
### **Issue**
While developing a simple react-native authentication app using firebase, I am unable to maintain user authentication persistence between application reload JS (⌘R).
_Layman Terms_: I have to type in the credentials every time I reload my app.

Utilizing:
`firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL)` 
is returning an error:
`{code: "auth/unsupported-persistence-type", message: "The current environment does not support the specified persistence type."}`

- If I set the Persistence to "SESSION" or "NONE", no error pops up after sign-in.
- If I omit the `setPersistence` helper method from my application, the Persistence acts as if "NONE" is the default persistence.
- It is almost as if the `firebase.auth.Auth.Persistence` is defaulting to "NONE" instead of "LOCAL" for react-native.

### Replication Code
Firebase is being imported using the command: `import firebase from 'firebase';`

This is the onAuthStateChanged method being run inside of in the root/App component.
```
    state = { loggedIn: null };

    componentWillMount() {
        firebase.auth().onAuthStateChanged((user) => {
            if (user) {
                this.setState({ loggedIn: true });
            } else {
                this.setState({ loggedIn: false });
            }
        });
    }
```

Here is the relevant code producing the error inside my Login component which I titled LoginForm. In this component I am using 3 helper functions `onButtonPress` `onLoginFail` `onLoginSuccess` as well as a button input to submit the credentials.
```
class LoginForm extends Component {
    state = { email: '', password: '', error: '' };

    onButtonPress() {
        const { email, password } = this.state;

        this.setState({ error: '' });
        firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL)
            .then(() => firebase.auth().signInWithEmailAndPassword(email, password))
            .then(this.onLoginSuccess.bind(this))
            .catch(() => {
                firebase.auth().createUserWithEmailAndPassword(email, password)
                .then(this.onLoginSuccess.bind(this))
                .catch(this.onLoginFail.bind(this));
            });
    }

    onLoginFail(error) {
        const { code, message } = error;
        this.setState({ error: `code: "${code}",\nmessage: "${message}"` });
    }

    onLoginSuccess() {
        this.setState({
            email: '',
            password: '',
            error: ''
        });
    }

    // omitted additional non-relevant code below for rendering jsx to the user...
}

export default LoginForm;
```

### **Environment**

1. Application Target Platform: iOS

2. Development Operating System: macOS High Sierra

3. Build Tools: Xcode 10.0 (SimulatorApp-851.2 CoreSimulator-518.19), iOS 10.0 through 11.3

4. React Native version: 0.55.4

5. Firebase Version: 5.0.1

6. Firebase Module: Authentication

**Comment by bojeil-google** [comment]
This is completely unrelated to FirebaseUI-web. I don't even think it is related to firebase-auth. I believe this is related to the build mechanism for firebase in react-native and node.js environments starting in 5.0.x which was fixed in 5.0.2. AsyncStorage (needed for react-native) and other dependencies like XMLHttpRequest (needed for node.js) https://github.com/firebase/firebase-js-sdk/issues/799 were not getting required. Try upgrading to 5.0.2.

**Comment by JMEssex** [comment]
Yes you can close this thread. It was a regression issue in 5.0.1 which was just fixed in 5.0.2 a few days ago. Thank you and my appologize for posting this into FirebaseUI-web instead of Firebase-js-sdk

**Comment by jhoughjr** [comment]
firebase-ui-web in a hybrid app on Mac OS also does not persist auth state at all.
Making me seriously reconsider using it which sucks but if I cant auth users properly.
I had thought functionality like that would just work in a framework like this.

**Comment by wti806** [comment]
@jhoughjr Can you provide more details of the environment you are running on? This is the repo for firebaseui-web. If you are using react. there is a separated repo for the react wrapper: https://github.com/firebase/firebaseui-web-react
