### ISSUE TITLE
[Feature Request] Provide externs file to support Google Closure Compiler 

### ISSUE THREAD

**Issue by AndriyGo** [firebase/firebaseui-web#395]
`firebase-js-sdk` provides [externs](https://github.com/firebase/firebase-js-sdk/tree/master/packages/firebase/externs) which can be used with Google Closure Compiler. Unfortunately, the same is not true about the `firebaseui-web`. This makes it extremely difficult to obfuscate Java Script.

It would be really great if you could ship externs at some point.

**Comment by bojeil-google** [comment]
It should already be available: https://github.com/firebase/firebaseui-web/blob/master/externs/firebaseui-externs.js

The file should be accessible here: https://github.com/firebase/firebaseui-web/blob/master/package.json#L10
