### ISSUE TITLE
 FirebaseUI ToS and Privacy Policy change for GDPR compliance 

### ISSUE THREAD

**Issue by wti806** [firebase/firebaseui-web#396]
To show "By continuing, you are indicating that you accept our Terms of Service and Privacy Policy." in the first screen displayed to user. And At footer of every  other screen, show links to privacy policy and ToS.

**Comment by rmmmp** [comment]
Nitpick. I don't think Privacy Policy is something to be read not accepted unlike the Terms of Service. Maybe something like this..

_By continuing, you're indicating that you've read the Privacy Policy and agree to the Terms of Service_

Feel free to ignore if I'm incorrect
