### ISSUE TITLE
v3.0.0 Documentation

### ISSUE THREAD

**Issue by makcakaya** [firebase/firebaseui-web#401]
Is there a documentation for the v3.0.0 release?

I am trying to use the `authResult` object of callback `signInSuccessWithAuthResult(authResult, redirectUrl)` but there is no information about the structure of the object.

The description states

> The AuthResult of successful sign-in operation. The AuthResult object has same signature as firebase.auth.UserCredential.

but there is no information about `firebase.auth.UserCredential` itself in the README.md or in https://firebase.google.com/docs/reference/js/firebase.auth. 

It is a little hard to use the library if there is no simple way to find reference information about it.

**Comment by bojeil-google** [comment]
Hey @makcakaya majority of sign in methods in firebase v5.x now return a `firebase.auth.UserCredential`. Here is the documentation from the official references:
https://firebase.google.com/docs/reference/js/firebase.auth#.UserCredential

We should update our docs to point to that. The link above should be helpful.

The benefit of this object is that it also contains additional user info, method of sign in and whether a user is new or existing, in addition to the user and any OAuth credential.
