### ISSUE TITLE
demo + popup + email does nothing

### ISSUE THREAD

**Issue by jayenashar** [firebase/firebaseui-web#402]
Steps to reproduce:

1. https://fir-ui-demo-84a6c.firebaseapp.com/
2. Click "Sign In with Popup" button
3. Click "Sign In with email" button
4. Enter a valid email address
5. a. Press "Enter" or "Return" on your keyboard
5. b. Click "NEXT" button

Expected: prompt for password
Unexpected: nothing

**Comment by bojeil-google** [comment]
Hey @jayenashar, thanks for reporting this. We accidentally forgot to update the firebase.js CDN version on that page. It should be fixed now.
