### ISSUE TITLE
credential is null

### ISSUE THREAD

**Issue by kkcodes** [firebase/firebaseui-web#404]
Hello,

I am trying to Sign in with email and after entering the ID, For a new user getting the normal sign up form to enter first and last name with password.

After submitting it, I am getting this notice message:

credential is null

The sign in success method is being reached and the credential is null. 

Can anyone please tell me what's the reason and what am I doing wrong?

Thanks

**Comment by iprignano** [comment]
I'm having the same problem – more specifically, `signInSuccessWithAuthResult` returns an `UserCredentials` object with a null `credential` value. This only happens for users that register with the Email provider (Google provider works fine).

I'm using firebase `5.0.3` and firebaseui `3.0.0`.

**Comment by bojeil-google** [comment]
We always return null credentials for Email/password credentials. We've done so from the beginning. Even the underlying firebase core library doesn't return the email/password credential on promise resolution.

**Comment by iprignano** [comment]
I see – I must've missed the documentation paragraph about it. Thanks!

**Comment by kkcodes** [comment]
And credential is returned for Phone sign in?

**Comment by bojeil-google** [comment]
Phone auth credentials are one time only. After we use them to sign in the user, they are useless.

**Comment by kkcodes** [comment]
Ok. And Is there a way, to customize the look and feel of the UI?

**Comment by elidakirigo** [comment]
hi, if no credentials are assigned can i get a way to store data of a certain user?
