### ISSUE TITLE
User is not automatically logged after signup with email and requireDisplayName.

### ISSUE THREAD

**Issue by jaros** [firebase/firebaseui-web#406]
I got such behaviour only in v3.0.0. In v2.7.0 all is good.

Steps to reproduce:
- enable EmailAuthProvider
- signInFlow: 'popup'
- signInSuccess returns false
- credentialHelper: none
- requireDisplayName: true  ==> that's what breaks the flow.

After clicking "Save" for Signing up nothing happens for user - I see the same registration screen.
Eventually user is registered and it looks like something is broken in the returning promise result function.

**Comment by wti806** [comment]
I cannot reproduce with our test app. Could you please provide your app for us to debug? Also, are you saying that after you click save, the sign up screen is showing?

**Comment by jaros** [comment]
got such an error message...
<img width="423" alt="screen shot 2018-05-26 at 10 12 46" src="https://user-images.githubusercontent.com/903893/40574136-9f6103c0-60cd-11e8-99b1-d767524c4dfc.png">

**Comment by jaros** [comment]
My bad => versions incompatibility.
I've used firebaseui@3.0.0 with firebase@4.12.1
after upgrade to firebase@5.0.1 all is good.
I close the issue.
