### ISSUE TITLE
No callback after signup with email and password if requireDisplayName = true

### ISSUE THREAD

**Issue by thdk** [firebase/firebaseui-web#408]
When using EmailAuthProvider  with **requireDisplayName: true** the callback signInSuccessWithAuthResult is never fired.

See js fiddle: https://jsfiddle.net/0uscwpv3/ 
(Don't forget to add your api key and such in the js code in the fiddle)

```
var uiConfig = {
  'callbacks': {                    
     signInSuccessWithAuthResult: (authResult, redirectUrl) => {
          // this never fires when new user signs up with email and password
          return false;
      } 
    },
    signInFlow: 'popup',
    signInOptions: [
         {
             provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
             requireDisplayName: true
          }
      ]            
   };
 firebaseUI.start('#firebaseui-auth-container', uiConfig);
```
When using **requireDisplayName: false** the registration of new users works.

**Comment by bojeil-google** [comment]
You are using the wrong firebase.js version. You should use 5.x with firebaseui 3.x. The reason why it doesn't trigger is because of an error that is actually being swallowed after sign in and the unexpected signature is returned. We need to surface these errors at least via the browser console.

**Comment by thdk** [comment]
Correct, it works after updating my firebase.js version. Thanks!
