### ISSUE TITLE
Email Link Auth Support

### ISSUE THREAD

**Issue by saul-mtz** [firebase/firebaseui-web#409]
Hi,
Thanks for you awesome project, is there a plan to support this "new" auth method:
https://firebase.google.com/docs/auth/web/email-link-auth

**Comment by wti806** [comment]
Hi, @saul-mtz 
Supporting email-link sign in is definitely on our list. It will be one of the next a few items we wanted to work on.

**Comment by CosticaPuntaru** [comment]
maybe add a way to add other types so open source community can help, especially for https://firebase.google.com/docs/auth/web/custom-auth

**Comment by bojeil-google** [comment]
Custom auth is very different than email link sign in (natively supported without any server dependency). Please open a separate feature request for that.

**Comment by choopage** [comment]
Looking forward to email-link sign-in. Thanks @wti806 .

**Comment by nicolasgarnier** [comment]
Closing this as a duplicate. Please follow https://github.com/firebase/firebaseui-web/issues/359 to know about FirebaseUI support for this feature.
