### ISSUE TITLE
Required first and last name for password sign-in?

### ISSUE THREAD

**Issue by courthead** [firebase/firebaseui-web#41]
Your email/password sign-in flow is prompting users for "First & last name":

![screen shot 2016-09-01 at 5 29 32 pm](https://cloud.githubusercontent.com/assets/148083/18188865/7d7a6e86-706a-11e6-9231-f9f090ea6fc5.png)

I don't ever want to display my users' real names on my site, and I'm afraid they'll be freaked out that they're being asked that information. Unfortunately, it's currently a required field in the email/password form.

This makes the email/password sign-in option unusable for any site that wants to maintain its users' privacy.

How can I disable this?

**Comment by rlansky** [comment]
If you are willing to download the firebase-ui-auth.js file and server it yourself from your server, this is a pretty easy change to make. Once you get the file, search for the text: `First &amp; last name`

Once you find that text, you can change it to anything you want. I changed mine to read `Display Name`.

**Comment by alfongj** [comment]
In the future we want to make this screen more customizable, but we will likely work on this after we release 1.0.

Thank you @rlansky for providing a temporary workaround!

**Comment by xorscode** [comment]
I agree with the OP.  Why is this designed this way?  Rarely would a site on the internet require first and last name for registration.

**Comment by courthead** [comment]
@alfongj Any plans for this? Seems like at least 5 ppl here would like options, and probably more who haven't found this thread.

**Comment by bojeil-google** [comment]
Hey @courthead, I will take this one over. Sorry about the delay. We are starting to look into it. I will keep you posted.

**Comment by xorscode** [comment]
Thank you Bojeil for picking this up!

**Comment by samtstern** [comment]
This is tracked in other platforms at:
   * https://github.com/firebase/FirebaseUI-Android#467
   * https://github.com/firebase/FirebaseUI-iOS/issues/245
