### ISSUE TITLE
No user after account-chooser. Succeeds on second time.

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebaseui-web#411]
I'm not sure what I am doing wrong, but the firebase authListener doesn't find any user the first time after the account chooser.
Then logging in again a second time firebaseui skips the account chooser and immediately redirects back after which the firebase authListener _does_ recognise the user. The same is true for the Google account chooser as for the "sign in with email" and choosing the same google address.

This problem makes it so all my users need to press the login button twice. Once for account chooser another time to actually make the login get recognised.

Here is my build:
### Firebase initialisation
```js
firebase.initializeApp(config.firebase)
firebase.auth().onAuthStateChanged(user => {
  if (user) {
    return console.log('found this user! ', user)
  }
  console.log('no user found during authListener!')
})
firebase.auth().getRedirectResult()
.then(result => { console.log(result.user) })
.catch(error => { console.log(error) })
```
### Here is what happens when the login page is mounted
```js
let ui = firebaseui.auth.AuthUI.getInstance()
if (!ui) {
  ui = new firebaseui.auth.AuthUI(firebase.auth())
}
ui.start('#firebaseui-auth-container', uiConfig)
```
### Here is my config:
```
uiConfig = {
  signInSuccessUrl: '/',
  signInOptions: [
    {
      provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
      requireDisplayName: false
    },
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
  ],
  tosUrl: 'localhost'
}
```
Versions:
`    "firebase": "^5.0.4",`
`    "firebaseui": "^3.0.0",`
PS:
My website is a Vuejs SPA.

**Comment by bojeil-google** [comment]
Your explanation is cryptic. What do you mean by account chooser? account chooser can mean multiple things. Please provide a clear explanation of the problem.

**Comment by mesqueeb** [comment]
@bojeil-google 
Thank you very much for your comment.
I have recorded a GIF to show you what I mean.

1st time: I get an account chooser showing google accounts.<br>
- after this firebase does not recognise a user logging in

2nd time: firebaseui immediately redirects me back
- after this firebase recognises a user

![2018-06-07 16 31 16](https://user-images.githubusercontent.com/3253920/41085246-540040fa-6a71-11e8-8e18-5f86d3cf0d4c.gif)

**Comment by bojeil-google** [comment]
I am not sure why this is happening. It speculate this is related to your logic. This is not a behavior we can reproduce.

**Comment by mesqueeb** [comment]
@bojeil-google Thank you very much for your help.

Is there anything I _should_ need to set up in my app besides these catcher functions to see if a user logs in through firebaseui-web?
```js
firebase.auth().onAuthStateChanged(user => {
  if (user) {
    return console.log('found this user! ', user)
  }
  console.log('no user found during authListener!')
})
firebase.auth().getRedirectResult()
.then(result => { console.log(result.user) })
.catch(error => { console.log(error) })
```
Or should the above be enough to capture a log in through firebaseui-web?

**Comment by edgewood1** [comment]
I've encountered the same problem

**Comment by edgewood1** [comment]
I had the <div id="firebaseui-auth-container"></div> inside of a modal, which interfered with the flow sign-in process.

**Comment by wengzilla** [comment]
I am also running into the same problem... Have we discovered the root cause for this?
