### ISSUE TITLE
Invisible recaptcha bottom right badge does not display.

### ISSUE THREAD

**Issue by TheBear44** [firebase/firebaseui-web#414]
https://fir-ui-demo-84a6c.firebaseapp.com/#recaptcha=invisible

**Comment by bojeil-google** [comment]
Hmm, I can reproduce this. This was always working. It appears as if reCAPTCHA has changed the CSS for the badge. It used to have fixed positioning as I recall but this has changed and the firebaseui overflow hidden is preventing it from showing. We'll look into this.

**Comment by bojeil-google** [comment]
This should already be fixed: https://github.com/firebase/firebaseui-web/releases/tag/v3.1.0
