### ISSUE TITLE
Option to make accountChooser optional

### ISSUE THREAD

**Issue by courthead** [firebase/firebaseui-web#42]
When users click "sign in with email", I think they expect to be shown a couple inputs where they can enter their email and password. However, instead they get this account chooser:

![screen shot 2016-09-01 at 5 40 01 pm](https://cloud.githubusercontent.com/assets/148083/18188961/3a6af5e2-706b-11e6-9489-14d99aa0f3a5.png)

I don't think this is an intuitive flow. As a user, I'm asking:

> What are these "accounts"? I've never signed into this website with any of these email addresses. This looks like an OAuth flow. Are these my Google accounts? I don't know what an "account" is, so I don't know what the "Add Account" link does. I just want to type in an email address!

Is there a reason the UI works this way instead of standard email/password flow? At the very least can we use the term "email" instead of "account"?

**Comment by erlgry** [comment]
It would indeed be nice to have an option to disable the account chooser. It is confusing in that the account chooser and the google sign in screens look very similar. Further accountchooser.com is not something the end users understand or trust. Thus if an option to disable the account chooser was made available, in that case it would also be nice to display the email sign in form in-line, without the redirect or popup mode.

**Comment by alfongj** [comment]
Just to follow up, this is something we want to work on before the 1.0 milestone. Stay tuned!

**Comment by courthead** [comment]
Thanks @alfongj! If this is a blocker for anyone else reading this, you can use implement a custom username/password login in addition to using this plugin, and display the two alongside each other seamlessly. I'm doing that here: https://www.indiehackers.com/sign-in

**Comment by rlansky** [comment]
If you are looking for an easy work-around to this problem, you can download the firebase-ui-auth.js file, make a one character change to the file, serve it up locally, and now it'll never show this picker.

Once you download the file, look for the text that reads: `"accountChooserEnabled",!0`

Once you find that, change the `!0` to be `!1`

When you serve that version of the file from your server, it'll now never show the account choosers.

**Comment by darrinm** [comment]
It now appears that the config variable 'accountChooserEnabled': false disables the account chooser.

**Comment by neelavar** [comment]
I'd certainly agree with this issue of making 'accountChooser' optional.

The hack provided by **rlansky** works perfect.
It would be useful to add this 'accountChooserEnabled' into the Config Options.

**Comment by indiespace** [comment]
@darrinm is right, it's been added. They need to close this issue(because they might be still doing some testing) and then we can add it to the docs.

**Comment by TMSCH** [comment]
This configuration parameter is not yet exposed, and won't work once we officially support this feature as part of the 1.0.0 release as it will be a different name. I would advise not to rely on this being the correct parameter until release 1.0.0.

**Comment by bojeil-google** [comment]
To disable accountChooser.com, use the following config:
'credentialHelper': firebaseui.auth.CredentialHelper.NONE

**Comment by ericwhittakerjr** [comment]
Hey, so I used this parameter to not show the credentialHelper, but it seems that this parameter is not honored by my mobile phone browsers. Is there any reason that this would work on desktop but not on mobile?

**Comment by enun03** [comment]
Thanks @bojeil-google, adding the 'credentialHelper' property to the uiConfig object worked for me...
