### ISSUE TITLE
Version issue with cordova-universal-links-plugin

### ISSUE THREAD

**Issue by rtm** [firebase/firebaseui-web#425]
In the readme, you say

> Install the necessary Cordova plugins, make the necessary Firebase Console changes and update your config.xml file as documented in [OAuth Sign-In for Cordova](https://firebase.google.com/docs/auth/web/cordova)

In that document, it says to install the universal links plugin

> Plugin to handle Universal Links (Android app link redirects) `cordova plugin add cordova-universal-links-plugin --save`

However, the universal links plugin is not compatible with Cordova Android 7.0.0. See [this issue](https://github.com/nordnet/cordova-universal-links-plugin/issues/133). One could downgrade to Cordova Android 6.3.0, but there are other Cordova plugins which require 7.0.0. Therefore, we are reduced to using an [ugly hack/fork](https://github.com/walteram/cordova-universal-links-plugin/pull/1) against the universal links plugin.

Yes, I know, this is not a problem with firebaseUI per se. It's not even a problem with Firebase authorization per se. However, it **is** a problem in the sense that I cannot use those features with Cordova, given the version incompatibilities. At a minimum, one might hope that this would be documented, or if `cordova-universal-links-plugin` is going to be recommended as the "official" approach for users of Firebase authentication under Cordova, it would be even more wonderful if the Firebase team could provide some kind of work-around or alternative.

**Comment by PetersonRyan** [comment]
Did you ever find a solution to this problem? It seems to not be fixed yet.

**Comment by nicolasgarnier** [comment]
Closing this as duplicate, please refer to https://github.com/firebase/firebaseui-web/issues/219
