### ISSUE TITLE
Customize Sender Name when using SMTP

### ISSUE THREAD

**Issue by eleith** [firebase/firebaseui-web#431]
When using a custom SMTP for authentication, the `Sender Name` field is not used in the `from` field of the email. If you turn off custom SMTP, then it works.

my guess is that because the SMTP option only has a field for "sender address" it ignore the `Sender Name` field from the authentication template.

so either this is a bug or a feature request =]

**Comment by eleith** [comment]
similar comment on this thread about slow email sending times -> https://github.com/firebase/firebaseui-web/issues/234#issuecomment-357239823

**Comment by bojeil-google** [comment]
This is not a client sdk: firebaseui-web or firebase-js-sdk feature. Please open a support ticket feature request:
https://firebase.google.com/support/
