### ISSUE TITLE
Console logs from AccountChooser even when it is disabled

### ISSUE THREAD

**Issue by deepfriedbrain** [firebase/firebaseui-web#437]
I'm seeing console log messages in the browser dev console. These logs are from accountchooser.com. However, accountchooser is disabled in my configuration and I don't see the accountchooser screen during sign in at all. So, is this a bug or a misconfiguration?

![image](https://user-images.githubusercontent.com/1531669/41834397-bafcbe6e-7886-11e8-8302-93a992f24564.png)

```
<body>
    <div id="firebaseui-auth-container"></div>

    <script type="text/javascript">
        var uiConfig = {
            'signInSuccessUrl': '/',
            'signInOptions': [
                firebase.auth.GoogleAuthProvider.PROVIDER_ID,
                firebase.auth.FacebookAuthProvider.PROVIDER_ID,
                firebase.auth.EmailAuthProvider.PROVIDER_ID
            ],
            'tosUrl': '/terms',
            'credentialHelper': firebaseui.auth.CredentialHelper.NONE
        };
    
        var ui = new firebaseui.auth.AuthUI(firebase.auth());
        ui.start('#firebaseui-auth-container', uiConfig);

    </script>
</body>
```

**Comment by bojeil-google** [comment]
This is not reproducible. You can see it for yourself in our test app: https://fir-ui-demo-84a6c.firebaseapp.com/
Please provide minimal, complete, and verifiable examples before opening issues.

**Comment by deepfriedbrain** [comment]
I've added Firebase Auth to a test site: 

https://firebase-auth--brainbok.netlify.com/oauth2callback?mode=select&signInSuccessUrl=/app

If you open the dev console and simply refresh the page, you'll see the log messages in the console from accountchooser.com.

Do a view source on that page, scroll all the way to the bottom where you'll find the Firebase configurations. 

Let me know whether this is good enough or you need more info.

**Comment by deepfriedbrain** [comment]
I found that adding mode=select query parameter to the URL causes the logs to be printed. If I remove that parameter, I don't get the logs. 

Without that parameter, I don't see any difference in behavior as the redirection still works. So what's the purpose of this parameter. The documentation is confusing. It says: 

"You must include the mode explicitly in the URL when using the signInSuccessUrl parameter, otherwise FirebaseUI will directly redirect to the URL specified."

**Comment by deepfriedbrain** [comment]
@bojeil-google This is now a question on the documentation. If this is not the right channel to seek clarification on the documentation, then please direct me accordingly.

Waiting for a response. Thanks.

**Comment by bojeil-google** [comment]
Hey @deepfriedbrain, this is a remnant from the `google-identity-toolkit` codebase.
You can choose to pass it or not. The result is the same. When `select` is added, it automatically loads the `accountchooser.com` dependencies which log the console messages. For example, notice that if you go through the `accountchooser.com` flow, when you go back to your sign in page, the query parameter is added automatically on return.
We'll clarify the documentation on this.
