### ISSUE TITLE
iOS + Chrome Popup does not work

### ISSUE THREAD

**Issue by dholbrook86** [firebase/firebaseui-web#44]
Steps to reproduce:
* Log in
* Refresh
* Log out
* Refresh
* Try and log back in again

Results:
* Popup closes before auth can return.
or
* Gray screen
![img_0515](https://cloud.githubusercontent.com/assets/4501147/18225951/10d0ef2c-71bd-11e6-9e18-8af65e8bc2c3.PNG)

**Comment by bojeil-google** [comment]
Thanks for reporting this issue. Can you confirm the iOS and chrome version you detected this in? I was able to notice a similar issue in iOS 9.3.3 chrome 53.0.2785.86. I will need to investigate this further.

**Comment by bojeil-google** [comment]
This should be fixed now.

**Comment by dholbrook86** [comment]
I had replied to the email and not here. Sorry about that. For the record here is that info you asked for.
iOS: 9.3.5
Chrome: 53.0.2785.86
I noticed this issue in vanilla firebase authentication as well. The fix you made, is this also an issue in there?

**Comment by bojeil-google** [comment]
The issue was in the firebase authentication SDK (signInWithPopup specifically) and not in firebaseui-web. It should be fixed there.

**Comment by zirho** [comment]
I encounter this issue.

iOS 10.2
chrome 55.0.2883.79

grey screen.

**Comment by bojeil-google** [comment]
Hey @zirho,
I just tested signInWithPopup on an iOS 10.2 device with chrome 55.0.2883.79.
I was able to recreate this. After the popup sign in completes and the popup window closes. The original page is strangely greyed out. When I click the tab button typically used to switch among tabs (it shows on the top right corner), the page is displayed again and the user is signed in. I tested with Safari on the same device without any problem. This seems to be some Chrome iOS bug. I will experiment further with this. I checked the link you included. The popup is already opened with _blank target on iOS chrome. This is a new issue that occurs in the latest chrome version for iOS 10.2.

**Comment by bojeil-google** [comment]
Hey @zirho, after more investigation, this seems to happen when consent is already granted and the window is opened and closed immediately. A slight delay was added to the popup for that specific environment and after testing seems to work (the grey screen was no longer showing). This is a way around this until ChriOS fixes this bug.

**Comment by zirho** [comment]
Hi, @bojeil-google 
How should I solve this on my project?
Would getting the latest of firebaseui solve the problem or should I fork this repo and fix to use?
Thanks a lot!

**Comment by bojeil-google** [comment]
you don't need to do anything (the changes were made on the page that opens). It should be fixed automatically.

**Comment by zirho** [comment]
@bojeil-google sweet!

thanks a lot.
