### ISSUE TITLE
Choosing account from account chooser does not proceed with login

### ISSUE THREAD

**Issue by rtm** [firebase/firebaseui-web#441]
When I click "Sign in with email", and the account chooser comes up, and I choose an account, I expect to proceed to login with that account. Instead, it simply returns me to the login screen. Now, when I click "Sign in with email" again, it goes ahead and starts the login process (such as asking for password), **without** re-displaying the account chooser.

This is the same issue as report on SO [here](https://stackoverflow.com/questions/50733796/firebaseui-web-no-recognised-user-after-account-login).

This is obviously sub-optimal for my users, who have to press "Sign in with email" twice to get logged in. What am I doing wrong?

I am on 3.1.1 if it matters, and this is using Cordova. 

Speaking of Cordova, I'm puzzled by the following note in the docs:

> As the application runs within an embedded webview, accountchooser.com will always be disabled.

For me, accountchooser.com is very much enabled, unless I disable it with `credentialHelper: firebaseui.auth.CredentialHelper.NONE`, which is actually a huge improvement. IMHO the account chooser is ugly and confusing.

**Comment by wti806** [comment]
@rtm What environment were you running your cordova app on? iOS or Android or even we could see the same issue on browser environment? I cannot replicate the issue on the end. Besides, if you don't want to use accountchooser, you can always disable it by setting credentialHelper to NONE.

**Comment by rtm** [comment]
@wti806 Thanks for following up. I was using the Cordova "browser" platform, which I use to develop and test. I will try running this on Android as well and let you know.

**Comment by wti806** [comment]
If you test on Android or iOS, I believe accountchooser will be disabled. But still, I recommend you to set credentialHelper to NONE if you prefer not to use it. I tested with browser as well, selecting an account will either ask you to create a new account or enter the password of existing account. It won't go back to the first sign in page.
