### ISSUE TITLE
Password reset mail  does not come from custom domain

### ISSUE THREAD

**Issue by rtm** [firebase/firebaseui-web#443]
I'm using firebaseui in my Cordova/Android/Firebase app. I've set up a custom domain for my project, but yet the "forgot password" email sent out by firebaseui is coming "from" `app-name.firebaseapp.com`. This is a little bit confusing to the user, potentially. I've set the `authDomain` in my firebase config to the custom domain name; is there something else I can do to get the email to come from the custom domain instead of `app-name.firebaseapp.com`, or is this expected behavior?

**Comment by wti806** [comment]
https://stackoverflow.com/questions/34955165/custom-firebase-reset-password-email-and-landing-page  For these kinds of questions, you can easily get an answer from stackoverflow.
