### ISSUE TITLE
TypeScript type omissions in definitions

### ISSUE THREAD

**Issue by coldino** [firebase/firebaseui-web#445]
Version: firebaseui 3.1.1

Using the noImplicitAny setting in a TypeScript project that includes firebaseui causes the following errors from your type definitions:
```
ERROR in .../node_modules/firebaseui/dist/index.d.ts(70,5):
TS7010: 'start', which lacks return-type annotation, implicitly has an 'any' return type.
ERROR in .../node_modules/firebaseui/dist/index.d.ts(71,5):
TS7010: 'setConfig', which lacks return-type annotation, implicitly has an 'any' return type.
```

The fix is simple - state that both `start` and `setConfig` have a void return type.
It might also be sensible to add noImplicitAny to your linting.

**Comment by royprigat** [comment]
Hi,
I also encountered this issue recently. 
Could you please explain how would you go about stating the return type of 'start'?

**Comment by wti806** [comment]
@royprigat  We already have a fix for this and will be in our next release. If you want to fix it locally on your own, just return void for those two methods.
