### ISSUE TITLE
vue with firebaseui

### ISSUE THREAD

**Issue by saleemadat** [firebase/firebaseui-web#447]
hi i want to put firebase ui web in my app but i keep getting
Tl(...).updateCurrentUser is not a function
`<template>

  <v-container fluid>
    <v-layout row wrap>
      <v-flex xs12 class="text-xs-center" mt-5>
        <h1>Sign In</h1>
      </v-flex>
      <v-flex xs12 sm6 offset-sm3 mt-3>
        <form @submit.prevent="userSignIn">
          <v-layout column>
            <v-flex>
              <v-alert type="error" dismissible v-model="alert">
                {{ error }}
              </v-alert>
            </v-flex>
            <v-flex>
              <v-text-field
                name="email"
                label="Email"
                id="email"
                type="email"
                v-model="email"
                required></v-text-field>
            </v-flex>
            <v-flex>
              <v-text-field
                name="password"
                label="Password"
                id="password"
                type="password"
                v-model="password"
                required></v-text-field>
            </v-flex>
            <v-flex class="text-xs-center" mt-5>
              <v-btn color="primary" type="submit">Sign In</v-btn>
            </v-flex>
          </v-layout>

     <div id="firebaseui-auth-container"></div>
  

        </form>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>
import firebase from 'firebase'
import firebaseui from 'firebaseui'
export default {

  name: 'home',
  mounted() {
    var uiConfig = {
      signInSuccessUrl: '/home',
      signInOptions: [
        firebase.auth.GoogleAuthProvider.PROVIDER_ID,
        
        ]
      };
    var ui = new firebaseui.auth.AuthUI(firebase.auth());
    ui.start('#firebaseui-auth-container', uiConfig);
    },

  data () {
    return {
      email: '',
      password: '',
      alert: false
    }
  },
  methods: {
    userSignIn () {
      this.$store.dispatch('userSignIn', { email: this.email, password: this.password })
    }
  },
  computed: {
    error () {
      return this.$store.state.error
    },
    loading () {
      return this.$store.state.loading
    }
  },
  watch: {
    error (value) {
      if (value) {
        this.alert = true
      }
    },
    alert (value) {
      if (!value) {
        this.$store.commit('setError', null)
      }
    }
  }
}
</script>

<style lang="css">

</style>'

Tl(...).updateCurrentUser is not a function

**Comment by bojeil-google** [comment]
You need to upgrade the `firebase` underlying dependency to a version >=5.0.0

**Comment by saleemadat** [comment]
that worked thank you

**Comment by siddug** [comment]
Facing this issue. Firebase version is 5.3.1

Any ideas?

**Comment by saleemadat** [comment]
I had the same problem, my global firebase is 5~ but my package.json had only 1.8 so i just updated in the package.json to version>=5.0.0 and it worked. Let me know
