### ISSUE TITLE
User profile (PhotoURL and DisplayName) not getting when using 'autoUpgradeAnonymousUsers'

### ISSUE THREAD

**Issue by microtheta** [firebase/firebaseui-web#449]
I've set  `autoUpgradeAnonymousUsers: true` to automatically link the just logged in user to current  Anonymous user. 

I've already set required callbacks,
```
callbacks: {
  signInSuccessWithAuthResult: function(/*,authResult  redirectUrl */) { 
    return true;
  },
 signInFailure: function(error) {
  //merge data and login user
 }
}
```

But when a Anonymous user sign in with Google. User's profile data such as photourl and display name is not set (though it's there inside the `providerData`!).  i.e. authResult.user.displayName is empty! Only email is getting set.

When I keep `autoUpgradeAnonymousUsers: false` it's working as expected. I.e. profile data is set.

Do we need to handle profile updation manually?

**Comment by bojeil-google** [comment]
This is by design. We don't overwrite existing profile fields, especially since the user may already have some attributes set before linking another credential.
You will have to do this manually. You can easily set them as follows:

```
user.updateProfile({
  displayName: user.providerData[0].displayName,
  photoURL: user.providerData[0].photoURL
}).then(function() {
  // Successfully updated.
}).catch(function(error) {
  // Some error occurred.
});
```

**Comment by microtheta** [comment]
Understood and agree with you. 
Thanks for the quick reply.
