### ISSUE TITLE
Signing in after being in a pending state for 1h gives an error 

### ISSUE THREAD

**Issue by alfongj** [firebase/firebaseui-web#45]
When using Firebase UI auth Web: If I reach a pending state (for instance the screen asking if I want to confirm signin with a different account that the one we initially tried to link) and wait for 1h before completing the sign-in flow I will get the following error:

Failed to load resource: the server responded with a status of 400 ()
https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=...

This happens because the Credentials object that is passed to sign in the main Firebase app is expired.

**Comment by TMSCH** [comment]
This error is now properly handled. The user will be redirected to the sign-in page and an error message will be displayed.
