### ISSUE TITLE
documentation needs update

### ISSUE THREAD

**Issue by hgghyxo** [firebase/firebaseui-web#450]
On the following documentation page: 
https://firebase.google.com/docs/auth/web/firebaseui

The tutorial includes `autoUpgradeAnonymousUsers` in the config under the 'Upgrading anonymous users' section, however the shown CDN version of firebaseUI is 2.5.1, which does not support this function yet.
`<script src="https://cdn.firebase.com/libs/firebaseui/2.5.1/firebaseui.js"></script>`

This results an invalid config issue for autoUpgradeAnonymousUsers in the console

**Comment by wti806** [comment]
@hgghyxo You are right. This feature was introduced in v2.6.0. We will update the documentation. Thanks.

**Comment by wti806** [comment]
Updated the doc.
