### ISSUE TITLE
Glitch when loading Firebase UI on Angular component

### ISSUE THREAD

**Issue by ghost** [firebase/firebaseui-web#475]
Hello Firebase,

I'm loading up the Firebase Auth UI on an Angular component, and the page's content first loads with the Firebase Auth UI loading asynchronously thereafter. But when it loads, it renders with an instantaneous glitch of a black/white box.

Video: https://youtu.be/1NGFFXsqD40

Do you have any idea why this is happening?

**Comment by bojeil-google** [comment]
This is not a glitch. What is happening is the progress bar is showing before the UI is rendered and then gets hidden quickly when it is determined there is no pending operation. This is likely due to the async nature of some of the APIs. We can look into trying to improve this.

**Comment by datureezy** [comment]
@bojeil-google thanks for your response. would love for an improvement; either being able to turn the progress bar off, or having the hiding not happen at all.

**Comment by bojeil-google** [comment]
I actually looked at it. I think I have a feasible solution to the problem. We can detect if there is a pending redirect sign in operation. When that happens, we can completely skip showing that screen.

**Comment by RaphaelJenni** [comment]
Created an issue on the official firebaseui repo. We will see what they say. https://github.com/firebase/firebaseui-web/issues/501

**Comment by jhuleatt** [comment]
per #501 it sounds like this issue has been resolved. Please reopen if that's not the case.
