### ISSUE TITLE
firebase.auth.OAuthCredential is undefined

### ISSUE THREAD

**Issue by abraztsov** [firebase/firebaseui-web#476]
Hello Firebase,

I'm trying to access credential from `firebase.auth.OAuthCredential` to use it in `reauthenticateAndRetrieveDataWithCredential` but it returns `undefined`.

I tried both `firebase.auth` and `firebase.auth()`, both `undefined`

Use it like this:

```
import firebase from 'firebase';

...
const user = firebase.auth().currentUser;
const credential = firebase.auth().OAuthCredential.accessToken;
await user.reauthenticateAndRetrieveDataWithCredential(credential);
await user.updateEmail(email);
...

```

**Comment by bojeil-google** [comment]
At the moment, `OAuthCredential` has no direct use. Better use the direct providers as documented.
That said, you are using this API incorrectly.
```
const provider = new firebase.auth.OAuthProvider('facebook.com');
const credential = provider.credential(null, 'FB_ACCESS_TOKEN');
....
// You are better off using the built in provider class.
const credential = firebase.auth.FacebookAuthProvider.credential( 'FB_ACCESS_TOKEN');
```
For similar usage questions, please use stackoverflow.

**Comment by hammadkhandev** [comment]
Undefined class 'OAuthCredential'.
Try changing the name to the name of an existing class, or creating a class with the name 'OAuthCredential'.
`
  // Google Sign-In method
  Future<User?> signInWithGoogle() async {
    try {
      final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();
      final GoogleSignInAuthentication googleAuth = await googleUser!.authentication;
      **final OAuthCredential credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );**
      final UserCredential userCredential = await _auth.signInWithCredential(credential);
      return userCredential.user;
    } catch (e) {
      print("Error signing in with Google: $e");
      return null;
    }
  }`
