### ISSUE TITLE
isPendingRedirect() and browser 'back' navigation

### ISSUE THREAD

**Issue by dsl101** [firebase/firebaseui-web#478]
I'm using the result of `isPendingRedirect()` to update the page in which the widget is contained (this is a Vue-based SPA), and also to show / hide a 'log in anonymously' button. But if the user clicks on, say, 'Sign in with Email', they are taken to the account chooser page (away from my app). If they then realise they clicked on the wrong button and hit the browser 'back' button, my app is loaded again, but `isPendingRedirect()` returns `true`, so my page now doesn't have a log in anonymously button, and also the label now says 'Please wait' instead of 'Please log in', as it's expecting the login to be in progress.

How can I tell the difference between my page loading because there really is a pending login, and simply due to navigation?

**Comment by bojeil-google** [comment]
It is not clear how you are using `isPendingRedirect` to show/hide a 'log in anonymously' button. This API is only used to help you determine if the sign-in UI needs to be rendered to complete some pending operation like a return from a sign-in via redirect or an accountchoose.com flow.

**Comment by dsl101** [comment]
I was originally using it to determine whether to show the 'log in anonymously' button that wasn't present in firebaseui. Now of course that is there in 3.2, but still I would like to have a text label on the page which says "Please log in using one of the methods below" on first render of the login page, and switch to "Please wait" when there really is a login in progress.

The behaviour of login with email is different depending on whether there are stored credentials (e.g. it sometimes redirects to the account chooser, and sometimes simply opens the input boxes for email address), with the former then causing a redirect back to the main app page for the password input.

But in any case, going to the account chooser and then using the browser back button (so the original application page is reloaded) doesn't feel like the login is 'in progress', as the user still needs to select a method to log in with.

**Comment by fterradev** [comment]
Yes, @dsl101. I think when returned to one's app by clicking the back button on an account chooser page, `isPendingRedirect` shouldn't return true, since no redirect will ever take place.

**Comment by dmorris99** [comment]
@fterradev  Agreed - is there no way at all to determine if the user *canceled* the login flow by hitting the back button??

**Comment by DilGoo** [comment]
Any updates regarding this?

**Comment by Neilpoulin** [comment]
Yeah, i have a very similar issue. It seems like when hitting the back button as described in the original post, firebaseUI tries for a few seconds to do some authentication (not sure what exactly it's doing) and shows the loading indicator, eventually realizes that it can't process anything. Then, it removes the loading indicator and shows the configured buttons. 

As far as I can tell, there is no way to hook into this state change. I'd almost expect that the `signInFailure` method would be called, but it is not. 

I just implemented a very hacky way to check for this situation that seems to work, for now. Basically, when my page loads and it sees that firebase UI is pending a redirect, I set up an interval that looks to see if the list of sign in buttons is present on the page, using a query selector like this: `.firebaseui-card-content .firebaseui-idp-list`. If an HTML node is found on the page, then I know that firebaseUI has reset itself, and I trigger my custom state change to reset, too.

**Comment by molimauro** [comment]
Yeah unfortunately there is no way to understand this and sadly I had to switch to "popup" signInFlow.

**Comment by ubragg** [comment]
I've been running into this issue with this library on a couple of different projects, and I just found [this solution](https://stackoverflow.com/a/45857949/2035869) on StackOverflow, which works great for my multi-page app, so not 100% sure if it will work for an SPA.

**Comment by bojeil-google** [comment]
`isPendingRedirect()` is to determine whether the UI needs to be rendered to complete a `signInWithRedirect`, `linkWithRedirect` or `accountchooser.com` redirect operations. If the user hits a `Sign in with email` button accidentally and then the user clicks the browser back button, showing the UI again is still reasonable as it should render the sign-in UI (which is the screen where the user was before the redirect).
