### ISSUE TITLE
Event to indicate login flow has started

### ISSUE THREAD

**Issue by dsl101** [firebase/firebaseui-web#479]
In a new private window (or a window with so cached account credentials), clicking 'Sign in with Email' opens a widget on the same page. But in a window _with_ cached credentials, the page is navigated to the account chooser.

In the first case, because I'm showing a 'Sing in Anonymously' button, I need to hide that button when 'Sign in with Email' is clicked, just like the UI widget hides any other providers. But I don't see an event or other test for that situation. How can this be done?

**Comment by wti806** [comment]
Did you implement 'Sign in Anonymously' on your own? You provided this option in [V3.2 ](https://github.com/firebase/firebaseui-web/releases/tag/v3.2.0). You can enable it so firebaseUI would handle this for you.

**Comment by dsl101** [comment]
Ah, yes, I've been doing it myself so far, and hadn't realised it came in.

**Comment by wti806** [comment]
Here is the [instruction](https://github.com/firebase/firebaseui-web#configure-anonymous-provider) of how to set it up.

**Comment by dsl101** [comment]
Tx. All sorted.
