### ISSUE TITLE
isPendingRedirect() returns false when auth state changes

### ISSUE THREAD

**Issue by fterradev** [firebase/firebaseui-web#488]
After selecting an account on the provider's (e.g. Google) page (sign in with redirect), at first isPendingRedirect() returns true. But a few seconds later it returns false, before the redirect has happened. Notably, it will return false when handling an onAuthStateChanged, even though the redirect has not happened yet.

Not sure if this could help, but just to give some context, I faced it while trying to undestand how to show a consistent authentication status output. Either the user information, or a sign in button, or none when onAuthStateChanged hasn't fired yet. And I was trying to avoid rerendering some ui to show the user information when there's a pending redirect, since that would be visible for just a second or so.

Fortunately there seems to be an easy workaround. Store the initial value (on page load or likewise) of isPendingRedirect(), and use this stored value as your "source of truth" regarding that.

**Comment by fterradev** [comment]
Even with the workaround I've mentioned, the app still suffers in the case described in #478 .

**Comment by bojeil-google** [comment]
Can you explain when you are calling `isPendingRedirect()`? And why do you need to call it multiple times?
After the UI is rendered (when you return back from the redirect) the pending redirect status will be reset as expected since the pending redirect status has been acted on.

Note calling `app.reset()` or `app.start()` again will reset that field.

**Comment by fterradev** [comment]
Ok, I got an instance of firebaseui.auth.AuthUI assigned to my component's property named ui.
`this.ui = new firebaseui.auth.AuthUI(firebase.auth());`

The issue happens when calling `this.ui.isPendingRedirect()` after `this.ui.start()`.
Does that reset the pending redirect status?

Why I call it multiple times?
The first time is for telling whether I should start the ui, as explained at https://github.com/firebase/firebaseui-web#using-firebaseui-for-authentication, see "This is only relevant for single page apps or apps where the sign-in UI is rendered conditionally (e.g. button click)".
The second time would be, after `firebase.auth().onAuthStateChanged` fires, for telling whether I should rerender some UI to display user's info, which I don't want to do when there's a pending redirect.
Note, whenever my page is accessed, `firebase.auth().onAuthStateChanged` is fired, and I believe that's the first oportunity for telling whether a user is signed-in (I appreciate any help for pointing out another (hopefully faster) way of knowing whether a user is signed-in).

In the case after the user selects an account, `firebase.auth().onAuthStateChanged` is fired twice. The first time always returning null.
The second time gives me the user info, right before the redirect gets performed.
Maybe that's another issue also. I mean, maybe this redirect is not needed. Or maybe `firebase.auth().onAuthStateChanged` shouldn't get fired before that redirect.

And in the case user sees the account selection page but instead of selecting one he clicks the back button, `this.ui.isPendingRedirect()` will return true but a redirect never gets performed (#478). So my app is not able to know whether the user has selected an account an a redirect is about to happen or the user has clicked the back button. In the later case, my app fails to show my sign in button (which displays the firebaseui widget. I keep it initially hidden, because I don't want to show it when it's in a loading state, for ui/ux reasons).

**Comment by bojeil-google** [comment]
This works as expected. The only reason for this API is to inform you that there is a pending redirect operation. Once you call `start()`, the redirect is acted on. This flag is now false.
If the user clicks the back button, there is no way for us to tell.

**Comment by fterradev** [comment]
Thank you.
When the user clicks the back button, I just think the API shouldn't signal a pending redirect, because it seems there's none. But again maybe this is more related to #478.

**Comment by nicolasgarnier** [comment]
Let's close this and keep #478 for the back button issue.
