### ISSUE TITLE
Verification Email Template

### ISSUE THREAD

**Issue by satrox28** [firebase/firebaseui-web#489]
Hi,

Is it possible for us to change the Email address verification Template message or host our own template externally for Firebase.

![screenshot from 2018-08-27 12-23-07](https://user-images.githubusercontent.com/24196271/44640383-fc4f4280-a9f3-11e8-9468-e9dfe80e992d.png)

**Comment by bojeil-google** [comment]
Currently this is not possible, but the Firebase Auth team has plans down the road to support that.
