### ISSUE TITLE
Error: Could not find the firebaseUI widget element on the page

### ISSUE THREAD

**Issue by autsada** [firebase/firebaseui-web#490]
Hi,

I just use FirebaseUI in my react app, I run dev-server to test the app on localhost. The sign-in buttons (email, Google, Facebook, and etc.) on the sign-in page show up as normal for every first time that I run dev-server, but if I refresh the page (without signing in) or I sign in and sign out, all sign-in buttons is gone (returning to the sign-in page but there is no sign-in buttons). In the console, error pop up showing 

>  Error: Could not find the FirebaseUI widget element on the page 

I have to shut down and rerun the dev-server to make the app works again.
Is there any suggestion for this issue?

**Comment by nicolasgarnier** [comment]
@autsada for react apps, feel free to use our React Wrapper: https://github.com/firebase/firebaseui-web-react this should take care of most of these issues for you.

**Comment by jelling** [comment]
2023 update: 

The `firebaseui-web-react` project appears abandoned and this was still happening for me on hard page refreshes.

The root cause in my case seemed to be that `firebase.auth` was being called before `firebase` existed. So I was able to fix it by adding a check for existence:

```
   <div>
         {firebase && (
              <StyledFirebaseAuth
                uiConfig={uiConfig}
                firebaseAuth={firebase.auth()}
              />
            )}
   </div>
```
