### ISSUE TITLE
no type information for signInSuccess callback

### ISSUE THREAD

**Issue by hirochachacha** [firebase/firebaseui-web#491]
https://github.com/firebase/firebaseui-web/blob/master/types/index.d.ts#L21-L29

**Comment by wti806** [comment]
@hirochachacha SignInSuccess callback is going to be deprecated in favor of SignInSuccessWithAuthResult as documented here: https://github.com/firebase/firebaseui-web#signinsuccesscurrentuser-credential-redirecturl

**Comment by hirochachacha** [comment]
Oh, I see. Thank you for your quick response.
