### ISSUE TITLE
Autologin happens before any login is triggered

### ISSUE THREAD

**Issue by zorgoz** [firebase/firebaseui-web#492]
I can configure and show the widget and appears to work as expected. But `firebase.auth().onAuthStateChanged` is fired with the previously logged in user while the widget is still up, and nothing was pressed on it even with `ui.disableAutoSignIn();` and even when I comment out every call related to `AuthUI`. This happens only if the user was not explicitly signed out with `firebase.auth().signOut()`. It looks as if there would be a parallel logon flow. Note: the application is running with hosted configuration.

**Comment by bojeil-google** [comment]
Please provide some snippets of what you are doing and a clear way to reproduce it.

**Comment by wti806** [comment]
@zorgoz I think there is some misunderstanding here. `ui.disableAutoSignIn()` is only relevant to google one-tap sign-up. I think what you are looking for is how Auth state is persisted. The documentation is [here](https://firebase.google.com/docs/auth/web/auth-state-persistence  )

**Comment by zorgoz** [comment]
You might well be right about that. Thank you.

**Comment by mrkam2** [comment]
I have a similar issue and I'm expecting the UI to recognize it was authenticated in and hide (similar to what is happening in a one-tap sign in). Why isn't it happening? Am I missing anything?

Observed behavior:
- ui.start is called and the widget is shown with "Sign in" buttons,
- firebase.auth().onAuthStateChanged handler is fired with the use signed in information,
Got: The widget is still showing "Sign in" buttons.
Expected: The widget is hidden.
