### ISSUE TITLE
Ui testing with Puppeteer

### ISSUE THREAD

**Issue by piq9117** [firebase/firebaseui-web#506]
Hi! First of all thanks for this project.

I'm currently using email and google auth provider. The email login button has the attribute `data-provider-id="password"` and the google login button has the attribute `data-provider-id="google.com"`. I can target the google login button with the selector `button[data-provider-id=password]"` even though its data attribute is `data-provider-id=google.com` but I haven't found a way to target the email login button. I would appreciate any guidance, thanks!

**Comment by wti806** [comment]
Try `document.querySelector('[data-provider-id="google.com"]')`. It works for me.

**Comment by piq9117** [comment]
cool! thanks @wti806
