### ISSUE TITLE
Return CORS headers for the CDN .js files

### ISSUE THREAD

**Issue by dandv** [firebase/firebaseui-web#508]
As mentioned in https://github.com/firebase/firebase-js-sdk/issues/332#issuecomment-423402372, trying to [dynamically import](https://developers.google.com/web/updates/2017/11/dynamic-import) `https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.js` fails:

> Access to Script at 'https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.js' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.

Adding CORS headers would allow loading Firebase Web UI dynamically, a very common use case for logged in users.

**Comment by dandv** [comment]
This is now solved, thanks for the quick turnaround!

**Comment by bojeil-google** [comment]
Actually not yet. I only fixed this for the staging cdn.

**Comment by wti806** [comment]
@dandv CORS headers have been added to files from both CDN and gstatic. This issue should be resolved. Please try agin and let us know. Thanks
