### ISSUE TITLE
KI - Firebase Auth does not work in Safari private browsing

### ISSUE THREAD

**Issue by tomscript** [firebase/firebaseui-web#51]
As stated in the README.md FirebaseUI doesn't work in Safari when using private browsing. I have no issue adding a fake localStorage but since the web version is not open sourced this leaves me in a tough spot. Is there a rough ETA to when this will be implemented?

**Comment by bojeil-google** [comment]
Hey @tomscript, this issue is due to Firebase auth library not supporting that mode for popup and redirect operations. This can't be solved on the firebaseui-web side of things. There are currently no plans to support these operations in safari private mode browsing in firebase auth.

**Comment by ernestp** [comment]
Hi guys, any workaround to make firebase auth work in Safari?
I'm not using firebaseui-web, only firebase-auth.

**Comment by tomscript** [comment]
@ernestp I'm not with the Firebase team but I believe the answer is no. The problem isn't with firebaseui-web but with firebase-auth.

**Comment by aaronbuchanan** [comment]
@tomscript I'm hitting this too & I can't find any resolution. know where we can file a ticket about this?

**Comment by tomscript** [comment]
not that i know of sorry, maybe here -> https://firebase.google.com/support/contact/bugs-features/

**Comment by nicolasgarnier** [comment]
Let's close this issue in favor of https://github.com/firebase/firebase-js-sdk/issues/1040 that's where the real fix can take place.
