### ISSUE TITLE
FR: speed up social login

### ISSUE THREAD

**Issue by dandv** [firebase/firebaseui-web#511]
Logging in with Twitter (either redirect or popup mode) is ~5x slower than other solutions. Try [Firebase](https://fir-ui-demo-84a6c.firebaseapp.com/) vs. [auth0](https://auth0.com/learn/lock-demo/) for example, or the social login from [Spectrum](https://spectrum.chat/login).

**Comment by dandv** [comment]
![firebase web ui sign in with twitter](https://user-images.githubusercontent.com/33569/46509479-caea4380-c7f7-11e8-9b9e-e590c14ca302.gif)

**Comment by rachelmyers** [comment]
Thanks for flagging this. We're always working on this, and we'll continue to make improvements.
