### ISSUE TITLE
Login error!! error:The redirect operation has been cancelled by the user before finalizing.

### ISSUE THREAD

**Issue by Santoshah** [firebase/firebaseui-web#512]
The sign in page opens and I log in with my Gmail id then it directs back to the app then shows this error. Not sure where I am missing.

I am using the firebase app domain.
```   
<script>
      // Initialize Firebase
      var configfirebase = {
        apiKey: "***********************",
        authDomain: "*****************.firebaseapp.com",
        databaseURL: "https://f*************.firebaseio.com",
        projectId: "************",
        storageBucket: "************",
        messagingSenderId: "**********",
      };
      firebase.initializeApp(configfirebase);
    </script>
```

```
var provider = new firebase.auth.GoogleAuthProvider();
function firebaselogin() {
    firebase.auth().signInWithRedirect(provider).then(function() {
      return firebase.auth().getRedirectResult();
    }).then(function(result) {
      var token = result.credential.accessToken;
      var user = result.user;
      app.dialog.alert('Login success!! Welcome:' + result.user );
    }).catch(function(error) {
      // Handle Errors here.
      var errorCode = error.code;
      var errorMessage = error.message;
     app.dialog.alert('Login error!! error:' + errorMessage );
    });
}
```

![screenshot_4](https://user-images.githubusercontent.com/3863771/46063123-845a7080-c189-11e8-84c5-829830cf38d0.png)

**Comment by bojeil-google** [comment]
This is not a firebaseui-web related issue. For core Auth library related issues, you should open the ticket in https://github.com/firebase/firebase-js-sdk
That said, you have provided no actionable information on your issue. You don't even provide the environment, sdk version, cordova version, etc.

**Comment by Santoshah** [comment]
Cordova 8.0.0 tried with 7.0.0 also
npm 5.6.0
node 8.11.1
window 7

sdk android-28

**Comment by Santoshah** [comment]
The issue has been resolved. Thanks for you co-operation.

[https://github.com/firebase/firebase-js-sdk/issues/1254#issuecomment-425130600](Resolve link)
