### ISSUE TITLE
Possible to redirect to `chrome-extension://...` options page after sign in?

### ISSUE THREAD

**Issue by mikob** [firebase/firebaseui-web#513]
Firebase ui is loading perfectly in my `chrome-extension://.../options.html` page. However, after the sign-in we are redirected to an `about:blank` page even with this in the configuration and as a whitelisted-domain in the firebase auth project settings:
```
{
// doesn't work
 signInSuccessUrl: 'chrome-extension://lnnmjmalakahagblkkcnjkoaihlfglon/views/options.html',
...
```

Any reason why this doesn't work? I understand the popup flow should work for chrome extensions, but is there any chance that the non-popup flow will work in the future?

Thank you!

**Comment by wti806** [comment]
@mikob If you use signInSuccessUrl config, it simply does this: https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/handler/common.js#L799 , which will not work for chrome extension. Instead, you could use `signInSuccessWithAuthResult` callback and put your logic to redirect to your extension page in there.
