### ISSUE TITLE
[Sample app] Uncaught Error: This operation is sensitive and requires recent authentication

### ISSUE THREAD

**Issue by jalajc** [firebase/firebaseui-web#52]
**Error:** 

```
> POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/deleteAccount?key=<somebeautifulkey> 400 ()
> firebase.js:71 Uncaught Error: This operation is sensitive and requires recent authentication. Log in again before retrying this request.
```

**Steps to replicate:**

> Delete an account that you have signed-into some(?) days back.

**Expected Intuitive user flow:** 

> "Before deleting please authenticate again" or sort of

In-fact I would enforce re-authenticate irrespective of time they logged-in on sensitive operations such as 'delete account'.

Also, in general if you can help with understanding _exception handling_ to create own custom logic/navigation
![delete account exception - requires recent authentication](https://cloud.githubusercontent.com/assets/13805246/18543924/e1ffb83a-7b4f-11e6-8101-35c959eb8eb4.png)

**Comment by bojeil-google** [comment]
This is a firebase auth related behavior. firebaseui-web does not offer delete functionality. You can always try to reauthenticate again before deleting. In fact that is the point of it, to make sure the user is authenticated before calling this sensitive operation. reauthenticate cannot be called automatically as a Firebase auth credential needs to be provided to it. To populate a credential you have to get the OAuth provider access token (pertaining to that account), or ask for the user to provide his/her password. Reauthorization mode could actually be avery interesting feature for firebaseui. I will relay this request to the relevant parties. Thanks for bringing this up.

**Comment by TMSCH** [comment]
The demo code has been updated to handle this error properly when deleting account.
