### ISSUE TITLE
Css broken 

### ISSUE THREAD

**Issue by MatthieuVeillon** [firebase/firebaseui-web#524]
### [REQUIRED] Describe your environment

  * Operating System version: Mac Os 10.13.6
  * Browser version:  Chrome 70.0.3538.77 (
  * Firebase UI version: 3.4.1
  * Firebase SDK version: 5.5.8

### [REQUIRED] Describe the problem

Can't figure out why the design is broken as per the picture below. Are there any dependencies which should come with the npm installation I might miss ?  I believe no other style is applied on my end. 

The auth flow works properly. I might miss some obvious things here

<img width="1113" alt="screen shot 2018-11-12 at 06 44 55" src="https://user-images.githubusercontent.com/20015180/48346045-d8d98280-e647-11e8-90eb-223c9d896c89.png">

#### Relevant Code:
```export const uiConfig = {
  signInFlow: "popup",
  signInSuccessUrl: "/localhost:3000",
  signInOptions: [
    // Leave the lines as is for the providers you want to offer your users.
    firebase.auth.FacebookAuthProvider.PROVIDER_ID,
    firebase.auth.EmailAuthProvider.PROVIDER_ID
  ],
  // tosUrl and privacyPolicyUrl accept either url string or a callback
  // function.
  // Terms of service url/callback.
  tosUrl: "/localhost:3000",
  // Privacy policy url/callback.
  privacyPolicyUrl: function() {
    window.location.assign("/localhost:3000");
  }
};

// Initialize the FirebaseUI Widget using Firebase.
export const ui = new firebaseui.auth.AuthUI(firebase.auth());
// The start method will wait until the DOM is loaded.

```

**Comment by bojeil-google** [comment]
Looks like you are not including the CSS dependency at all. Please check the README section to learn more about that.
