### ISSUE TITLE
Send parameter to createUser event

### ISSUE THREAD

**Issue by xerosanyam** [firebase/firebaseui-web#525]
**Is your feature request related to a problem? Please describe.**
Firebase web doesn't send any parameters to createUser event, which would be very useful in finding out if user was a referred user or which domain he subscribed from, etc

**Describe the solution you'd like**
I should be able to pass some parameters and be able to access in createUser event

**Describe alternatives you've considered**
I've considered storing info in sessionStorage and then making the required changes

**Comment by bojeil-google** [comment]
Hey @xerosanyam, this is not a FirebaseUI specific feature. For generic Auth/Cloud Functions features, it is better you file an official [Firebase feature request](https://firebase.google.com/support/). It will get routed to the relevant owners.
