### ISSUE TITLE
Privacy policy: what sign-in user should know

### ISSUE THREAD

**Issue by jalajc** [firebase/firebaseui-web#53]
Well this is a generic question regarding Privacy and Data usage practices applicable to all Firebase repositories in general. However I didn't figure out a place to ask (neither could find if its been asked earlier). But seemed _tactically_ important for broader adaption of Firebase.

> As we handle user data through Firebaseui-web (Firebase in general) for our website users, which in almost all cases includes handling of personally identifiable information, we are obliged by our operating-ethics and applicable laws to disclose how the data is stored, used/analysed/shared within Firebase/Google databases or any other privacy information ( in addition to our own privacy policy)

Would appreciate If someone from Firebase team can highlight:
- what user should definitely know with regards to privacy and data collection at Firebase
- where to direct user for detailed version (the ever updated version) of Firebase privacy policy
- geographic location(s) where user data is stored? and
- countr(y/ies) of applicable laws

**Comment by alfongj** [comment]
@jalajc This seems like a very broad question, out of scope for what the issues in this repo should be used for. 

Would you mind reaching out to the [Firebase troubleshooting form](https://firebase.google.com/support/contact/troubleshooting/) instead?

**Comment by jalajc** [comment]
@alfongj Thanks for the pointer, I was looking for that only.
