### ISSUE TITLE
Can't build localized widget

### ISSUE THREAD

**Issue by suga0828** [firebase/firebaseui-web#530]
I am trying to build my localized widget via npm in spanish, but the problem is before

The problem is that the `npm install` command does not work.

I'm using:

`git clone https://github.com/firebase/firebaseui-web.git`
`cd firebaseui-web`
`npm install `

and it's dont work. I receive this:

`$ npm i`

> grpc@1.10.1 install C:\Users\Win 7\Documents\Alexander\Desarrollo-Web\Proyectos\firebaseui-web\node_modules\firebase\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library
`
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-win32-ia32-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python34\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Win 7\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build""--library=static_library" "--module=C:\\Users\\Win 7\\Documents\\Alexander\\Desarrollo-Web\\Proyectos\\firebaseui-web\\node_modules\\firebase\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-ia32-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Win 7\\Documents\\Alexander\\Desarrollo-Web\\Proyectos\\firebaseui-web\\node_modules\\firebase\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-ia32-unknown"
gyp ERR! cwd C:\Users\Win 7\Documents\Alexander\Desarrollo-Web\Proyectos\firebaseui-web\node_modules\firebase\node_modules\grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Win 7\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Win 7\Documents\Alexander\Desarrollo-Web\Proyectos\firebaseui-web\node_modules\firebase\node_modules\grpc\src\node\extension_binary\node-v64-win32-ia32-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Win 7\Documents\Alexander\Desarrollo-Web\Proyectos\firebaseui-web\node_modules\firebase\node_modules\grpc\src\node\extension_binary\node-v64-win32-ia32-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Win 7\Documents\Alexander\Desarrollo-Web\Proyectos\firebaseui-web\node_modules\firebase\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Win 7\\Documents\\Alexander\\Desarrollo-Web\\Proyectos\\firebaseui-web\\node_modules\\firebase\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\Win 7\Documents\Alexander\Desarrollo-Web\Proyectos\firebaseui-web\node_modules\firebase\node_modules\grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Win 7\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Win 7\Documents\Alexander\Desarrollo-Web\Proyectos\firebaseui-web\node_modules\firebase\node_modules\grpc\src\node\extension_binary\node-v64-win32-ia32-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Win 7\Documents\Alexander\Desarrollo-Web\Proyectos\firebaseui-web\node_modules\firebase\node_modules\grpc\src\node\extension_binary\node-v64-win32-ia32-unknown' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Win 7\AppData\Roaming\npm-cache\_logs\2018-11-29T20_00_15_257Z-debug.log

I suspect that the problem is not related to firebaseui-web but to the dependencies that I have installed but really don't get a solution.

I am using Windows 7 32bit, npm 6.4.1 , node v10.13.0. Python 2.7.

**Comment by wti806** [comment]
@suga0828 Can you downgrade to node 8/9 and try again?

**Comment by suga0828** [comment]
I uninstall node 10.13.0 and install node 8.14.0. I keep using npm 6.4.1, Python 2.7 and the same OS.

Its dont work. I receive this (at the end):

`Proyecto "C:\Users\Win 7\Desktop\firebaseui-web\node_modules\node-sass\build\binding.sln" en nodo 1 (destinos predeterminados).`
`ValidateSolutionConfiguration:`
`Compilando la configuración de soluciones "Release|Win32".`
`MSBUILD : error MSB3428: No se pudo cargar el componente "VCBuild.exe" de Visual C++. Para corregir este problema, 1) instale .NET Framework 2.0 SDK, 2) instale Micros oft Visual Studio 2005 o 3) agregue la ubicación del componente a la ruta de acceso del sistema si está instalado en otro lugar. ` `[C:\Users\Win 7\Desktop\firebaseui-we b\node_modules\node-sass\build\binding.sln]
Compilación del proyecto terminada "C:\Users\Win 7\Desktop\firebaseui-web\node_modules\node-sass\build\binding.sln" (destinos predeterminados) -- ERROR.`


`ERROR al compilar.`

`"C:\Users\Win 7\Desktop\firebaseui-web\node_modules\node-sass\build\binding.sln" (destino predeterminado) (1) ->`
`(_src_\libsass destino) ->`
`MSBUILD : error MSB3428: No se pudo cargar el componente "VCBuild.exe" de Visual C++. Para corregir este problema, 1) instale .NET Framework 2.0 SDK, 2) instale Micr osoft Visual Studio 2005 o 3) agregue la ubicación del componente a la ruta de acceso del sistema si está instalado en otro lugar. ` `[C:\Users\Win 7\Desktop\firebaseui- web\node_modules\node-sass\build\binding.sln]`

    `0 Advertencia(s)`
   `1 Errores`

`Tiempo transcurrido 00:00:06.56`
`gyp ERR! build error`
`gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1`
`gyp ERR! stack     at ChildProcess.onExit (C:\Users\Win 7\Desktop\firebaseui-web\node_modules\node-gyp\lib\build.js:258:23)`
`gyp ERR! stack     at emitTwo (events.js:126:13)`
`gyp ERR! stack     at ChildProcess.emit (events.js:214:7)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`
`gyp ERR! System Windows_NT 6.1.7601`
`gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Win 7\\Desktop\\firebaseui-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="`
`gyp ERR! cwd C:\Users\Win 7\Desktop\firebaseui-web\node_modules\node-sass`
`gyp ERR! node -v v8.14.0`
`gyp ERR! node-gyp -v v3.6.2`
`gyp ERR! not ok`
`Build failed with error code: 1`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})`

`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js` `
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the node-sass@3.13.1 postinstall script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\Win 7\AppData\Roaming\npm-cache\_logs\2018-12-07T12_48_45_990Z-debug.log`

In the line that talk about MSBUILD : error MSB3428 says somethings like:

" 0 warning 1 errors "

Twice:

"It could not load "VCBuild.exe" component of Visual C++. For fix: 1) install .NET Framework 2.0 SDK or 2) Install Microsoft Visual Studio 2005 or 3) Add the location of the component to the system path if it is installed elsewhere."

`node-sass@3.13.1 postinstall: `node scripts/build.js` `
`npm ERR! Failed at the node-sass@3.13.1 postinstall script.`

I do not think that i have installed this .Net Framework version (really i have 4.7.1) neither Microsoft Studio 2005 (i think that have 2013 12.0.30501.0 or 2017 14.1426405.0 or both).

Also i tried using nvm-windows (Node Version Manager - Windows) and receive the same error.

**Comment by suga0828** [comment]
Should I try, now, to change the .NET framework?

**Comment by draperunner** [comment]
Try deleting the node_modules directory and install again.

**Comment by suga0828** [comment]
Every time I tried, I did it from scratch. All over again. I will try again one more time. Thanks.

**Comment by lightsound** [comment]
@suga0828 
I could install with node 6.0.0. If you have been in trouble, it is worth to try.

**Comment by suga0828** [comment]
@lightsound i reinstall node-sass (last version) and its solved.

**Comment by tomoyuki28jp** [comment]
Facing the same issue :(

**Comment by suga0828** [comment]
This problem was by npm/node versions not firebaseui-web.

**Comment by imbilal1** [comment]
Did you resolve this issue ?

**Comment by suga0828** [comment]
Yes, @imbilal1. In this moment I reinstall node-sass (delete node_module's node-sass folder and install again, manually) and was solved.
