### ISSUE TITLE
updateCurrentUser failed: First argument "user" must be an instance of Firebase User or null.

### ISSUE THREAD

**Issue by juanmaguitar** [firebase/firebaseui-web#536]
### Describe your environment

  * Operating System version: Mac
  * Browser version: Google Chrome Version 71.0.3578.98
  * Firebase UI version: `"react-firebaseui": "^3.1.2"`
  * Firebase SDK version: ` "firebase": "5.7.1"`

### Describe the problem

I'm using the `https://github.com/firebase/firebaseui-web-react` wrapper 
My implementation it seems to do the login properly on firebase (as i can see the mail logged on "Users" but on my react app I'm getting this error all the time

```
updateCurrentUser failed: First argument "user" must be an instance of Firebase User or null.  Dismiss
```

No `signInSuccessUrl` redirection or `signInSuccessWithAuthResult` callback works after this error

```
    signInSuccessUrl: '/',
    callbacks: {
      signInSuccessWithAuthResult: function(authResult, redirectUrl) {
        console.log(authResult)
        console.log(redirectUrl)
        return true
      }
    }
```

I have no clue about how to debug this or what would be the error

Any ideas?

**Comment by mindhivefi** [comment]
Same problem here, but this happens to me only when using typescript. I made a test with similar code with javascript with the same environment and same code and it did work. 

The actual firebase auth works. A new user is been created to firebase app but then something goes wrong. I have not yet been able to find the exact place where.

**Comment by wti806** [comment]
@juanmaguitar I tried with "firebase": "5.7.1" and "firebaseui": 3.2.0 as react-firebaseui used. But cannot reproduce the error you mentioned.  updateCurrentUser is called here for every sign-in operation: https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/authui.js#L1653. And the error is thrown from firebase core SDK complying about the provided argument is not a User object. So I'd appreciate it if you could print some trace of the user object passed to updateCurrentUser and build the firebaseui library yourself to help us investigate the issue. Otherwise, without being able to reproduce, it's really hard to help.

**Comment by WriterDuet** [comment]
I hit this error, and the reason was we had two copies of Firebase (one we were including manually, one which npm was pulling in). That caused this bug because for some reason it was using the manual one we specified to invoke the FirebaseUI React component and then calling updateCurrentUser() in the underlying npm version of Firebase (and thus checking the type there). Both versions of Firebase were 5.7.1 so it wasn't a versioning issue, it was that we had two copies of Firebase and the component wasn't consistent about which one it used (which I'd argue is a bug in FirebaseUI or the React-FirebaseUI module, but I ain't dying on that hill).

**Comment by leoshaw** [comment]
Also hit this - can't explain what was going on, but eventually fixed it by replacing some imports of `@firebase/...` that I'd copied from a tutorial https://github.com/LazyFatArrow/vue-quiz-pwa/blob/master/src/firebase.js with the non-@ versions

**Comment by u12206050** [comment]
If you are using loading firebase by via scripts then you can't use the npm versions, and also not the firebaseui npm version.

I had the same issue bue resolved it by loading all the firebase and firebaseui scripts via <script> tag instead of npm.

**Comment by surferjeff** [comment]
I saw this same error using vuejs-cli, webpack, typescript, and a locally built firebaseui node module.

This work-around worked for me:

Only list firebaseui in my project's packages.json:
```json
  "dependencies": {
    "firebaseui": "file:../../../firebaseui-web",
   }
```

Import the firebase modules from firebaseui's `node_modules` directory:
```ts
import firebase from "firebaseui/node_modules/firebase/app";
import "firebaseui/node_modules/firebase/functions";
import * as firebaseui from "firebaseui";
import "firebaseui/dist/firebaseui.css";
```

I'm afraid I've built a house of cards.  Is this technically sound?  Is there a better way?

**Comment by jmargolisvt** [comment]
I recently updated to firebase 8, and related deps including firebaseui 4.8.1 (I have tried several versions, they all give me this error).  It loads a login box, but when trying to enter creds or create a new user, I get this error:

> updateCurrentUser failed: First argument "user" must be an instance of Firebase User or null.

How can I restore the auth functionality?

firebase.js
```
import firebase from 'firebase/firebase';
import '@firebase/firestore';
import { FIREBASE_CONFIG } from '../keys';

const config = FIREBASE_CONFIG;

export const firebaseApp = firebase.initializeApp(config);
export const db = firebaseApp.firestore();
```

/store/index.js (abbreviated)
```
import firebase from 'firebase/firebase';
import * as firebaseui from 'firebaseui';
import '@firebase/firestore';

// This is our firebaseui configuration object
const uiConfig = ({
	signInSuccessUrl: '',
	signInOptions: [
		firebase.auth.EmailAuthProvider.PROVIDER_ID,
	],
	callbacks: {
		signInSuccessWithAuthResult: authResult => {
			store.dispatch(login(authResult));
		},
	},
});

// This sets up firebaseui
const ui = new firebaseui.auth.AuthUI(firebase.auth());

// This adds firebaseui to the page
export const startFirebaseUI = elementId => {
	ui.start(elementId, uiConfig);
};
```

I have tried solutions suggested in these discussions, but they are not working for me.
https://github.com/firebase/firebaseui-web/issues/536
https://github.com/firebase/firebaseui-web/issues/776

I'm seeing what looks like a valid auth response in the console too.  Here is the `verifyPassword` response:
```
{
  "kind": "identitytoolkit#VerifyPasswordResponse",
  "localId": "VgZWszYv8cYDJLQsIr3YzwcZJ4s1",
  "email": "user@gmail.com",
  "displayName": "My User",
  "idToken": "<<a_long_token>>",
  "registered": true,
  "refreshToken": "<<another_token>>",
  "expiresIn": "3600"
}
```
Here is the getAccountInfo response:
```
{
  "kind": "identitytoolkit#GetAccountInfoResponse",
  "users": [
    {
      "localId": "VgZWszYv8cYDJLQsIr3YzwcZJ4s1",
      "email": "user@gmail.com",
      "displayName": "Me",
      "passwordHash": "<<a hash>>",
      "emailVerified": false,
      "passwordUpdatedAt": 1561313504412,
      "providerUserInfo": [
        {
          "providerId": "password",
          "displayName": "Me",
          "federatedId": "user@gmail.com",
          "email": "user@gmail.com",
          "rawId": "user@gmail.com"
        }
      ],
      "validSince": "1561313504",
      "lastLoginAt": "1627418219738",
      "createdAt": "1561313504412",
      "lastRefreshAt": "2021-07-27T20:36:59.738Z"
    }
  ]
}

```
