### ISSUE TITLE
Nothing happening after popup

### ISSUE THREAD

**Issue by krokhale** [firebase/firebaseui-web#54]
I have an app with google and facebook social logins enabled. Everything seems to be fine except that it bombs out after popup for the social logins. The popup closes and there is no redirect or error message. Both signInSuccess and signInSuccessUrl do not seem to be having any effect.

What am i missing?

These are the versions i am using:

    <script src="https://www.gstatic.com/firebasejs/live/3.0/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/live/3.0/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/ui/live/0.5/firebase-ui-auth.js"></script>

**Comment by bojeil-google** [comment]
Please use the latest version: 3.4
A code snippet of your configuration would be very helpful.

**Comment by jalajc** [comment]
Krishna @krokhale, please check and share developer console output, as this closing of pop-up behavior could be for many reasons.
One easy to miss thing in initial setup is to whitelist your IP/domain (from where you are triggering firebase call?) inside firebase console. All in all, prima facie your config needs to be validated.

**Comment by krokhale** [comment]
Thanks for the quick replies folks, it was all working fine until a couple of days ago and there was no output/error on the developer console. It simply pops open the google login screen, walks you through the steps and finally just closes. Updating the version to 3.4 resolved it for me. I believe the demos are not updated with that version.
