### ISSUE TITLE
Prompt for password, although only EMAIL_LINK_SIGN_IN_METHOD is activated

### ISSUE THREAD

**Issue by usu** [firebase/firebaseui-web#541]
### [REQUIRED] Describe your environment
  * Operating System version: Windows 10
  * Browser version: Chrome 71
  * Firebase UI version: 3.5.1
  * Firebase SDK version: 5.7.2

#### Steps to reproduce:
Only activated provider is email link authentication (see config below). For some users, firebaseUI started to prompt for a password instead of sending the email link, although no password has been set (frontend has no included functionality to set a password).

I have not yet figured out, how to reproduce. Behavior is consistent: Once firebaseUI decides that a user is in "password mode", firebaseUI always prompts for password.

This is annoying, as we wanted to rely on email link authentication only and our frontend has not foreseen any means for the user to set & reset passwords.

#### Relevant Code:

```javascript
  const uiConfig = {
      autoUpgradeAnonymousUsers: true,
      signInFlow: 'popup',
      credentialHelper: firebaseui.auth.CredentialHelper.NONE,
      signInOptions: [
        {
          provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
          signInMethod: firebase.auth.EmailAuthProvider.EMAIL_LINK_SIGN_IN_METHOD,
          forceSameDevice: true,
          emailLinkSignIn() {
            return {
              url: `${process.env.BASE_URL}#/login`,
              handleCodeInApp: true
            };
          },
        },
      ],
      callbacks: {...},
      },
    };
```

**Comment by wti806** [comment]
@usu If the user is an existing user with password, firebaseui would prompt the user to password entry. That's the expected behavior.

**Comment by usu** [comment]
@wti806 Thanks for your reply. Understood that this is expected behavior.

The problem is that "something" is setting passwords for my users and I have not yet figured out what. So either it is FirebaseUI or the Firebase SDK or the Firebase backend. Probably difficult to find out and debug but I will try.

What is your opinion on an option to force sending email links, even if the user has previously set a password (e.g. `forceEmailLink: true`). From a perspective of firebase functionality this should be possible, as I can successfully call `sendSignInLinkToEmail` for all users, even if a password has previously been set.

**Comment by bojeil-google** [comment]
Hey @usu, we shouldn't set a password on the user without the user or the developer calling it explicitly. I think you should investigate how this is happening. It is most likely happening on your end. Perhaps you are hosting multiple versions of FirebaseUI which could explain why in some cases the user is being prompted to sign in or sign up with a password.

As for forcing email link sign-in on existing users, we will look into its feasibility. We don't want to over-complicate the logic.

**Comment by usu** [comment]
Found the bug in my own codebase that generated the passwords.
While upgrading anonymous users, I was by mistake generating the credential with `EmailAuthProvider.credential(email, link)` instead of using `EmailAuthProvider.credentialWithLink(email, link)`.

Interestingly, the signin procedure still worked fine, but a password was set as a side effect.
