### ISSUE TITLE
Recovery email page not loading proper language

### ISSUE THREAD

**Issue by synga** [firebase/firebaseui-web#543]
### [REQUIRED] Describe your environment

  * Operating System version:  Windows 10
  * Browser version: Google Chrome 71
  * Firebase UI version:  3.5
  * Firebase SDK version: 3.5.1

### [REQUIRED] Describe the problem

After sending the password recovery email and opening the link it doesn't display the page texts in brazilian portuguese, even if you configure the firebase to send the email in said language. The email text is translated and everything is OK, the problem is only in the page.

When opening the recovery page and insecting it show the following warning:

`Falha no carregamento do <script> com a fonte “https://www.gstatic.com/firebasejs/ui/3.0.0/firebase-ui-auth__pt_br.js”.`

So it fails to load the pt_br translations for the page and it's showing in english. In the LANGUAGES.MD file it says the portuguese is just `pt` and not `pt_br`.

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by wti806** [comment]
@synga The language code for Portuguese (Brazilian) is just pt rather than pt_br. How did you import the localized version of firebaseui? And could you please try with "pt"? We will also update the doc to clearly document this.

**Comment by synga** [comment]
@wti806 the warning i received is not on my code or my application, i'm using `pt` in my code, this warning is in the recovery page, the page that shows after i click the recovery email link and where a prompt for the new password pops up. Does it have any chance that this page is still targeting the older version of Portuguese (Brazilian)?

**Comment by wti806** [comment]
@synga I was able to replicate the issue. The reason is that the language code we used in client SDK is different from our backend.  Portuguese (Brazilian)'s locale code should be pt-BR. Working on a fix for this. Will keep you posted.

**Comment by wti806** [comment]
@synga The issue should be fixed now. And the language code for Portuguese (Brazilian) should be `pt_br`. Thanks for reporting this issue.
