### ISSUE TITLE
Phone Auth is not working 

### ISSUE THREAD

**Issue by vishal758** [firebase/firebaseui-web#547]
After sending the otp, the page says "OTP Sent" but it is not received on my phone. I tried many times but the same thing happens again and again. Is it bcoz I am running it in localhost or something else?
Can anybody plz suggest me what should I do?

**Comment by bojeil-google** [comment]
Do you happen to be using a [whitelisted test phone number](https://firebase.google.com/docs/auth/web/phone-auth#test-with-whitelisted-phone-numbers)? If so, no SMS code is sent in that case.
