### ISSUE TITLE
signInSuccessWithAuthResult doesn't fire when signInFlow is redirect

### ISSUE THREAD

**Issue by twmills** [firebase/firebaseui-web#548]
### Describe your environment

  * Operating System version: macOS 10.14
  * Browser version: Chrome 71.0.3578.98
  * Firebase UI version: 3.5.2
  * Firebase SDK version: 5.8.0

### Describe the problem
The `signInSuccessWithAuthResult` callback is not called when signInFlow is `redirect`, but does get called when signInFlow is `popup`.

#### Steps to reproduce:
Set `signInFlow` to `redirect` and then to `popup` and observe when `signInSuccessWithAuthResult` is and isn't called.
 
#### Relevant Code:
```javascript
const uiConfig = {
      signInFlow: 'redirect',
      signInSuccessUrl: '/',
      callbacks: {
        signInSuccessWithAuthResult: (authResult, redirectUrl) => {
          console.log("HELLO!!!!");
          return true;
        },
      },
      signInOptions: [
        firebase.auth.GoogleAuthProvider.PROVIDER_ID,
        firebase.auth.GithubAuthProvider.PROVIDER_ID,
      ],
    };
```

```javascript
<StyledFirebaseAuth uiConfig={uiConfig} firebaseAuth={firebase.auth()} />
```

**Comment by wti806** [comment]
@twmills I think it's related to your own environment or setup. I tested with our demo app [here](https://github.com/firebase/firebaseui-web/tree/master/demo).  You can try it to see if the redirect mode works.

**Comment by MaurizioGC** [comment]
The callback "signInSuccessWithAuthResult" does not get called if the "signinFlow: 'redirect'" and you miss the configuration key 
   "signInSuccessUrl: 'https://localhost:8080/'" (localhost if in dev env otherwise your domain)
