### ISSUE TITLE
Support subdomains for phone auth

### ISSUE THREAD

**Issue by johncblandii** [firebase/firebaseui-web#549]
**Is your feature request related to a problem? Please describe.**

Authenticating from dynamic subdomains throws a `Hostname match not found` error. It makes it impossible for our site to use phone auth via web on subdomains (mobile app integration is fine).

<img width="369" alt="screenshot 2019-01-23 02 41 10" src="https://user-images.githubusercontent.com/134952/51593681-5e837500-1eb8-11e9-96ec-80023d368004.png">

We tried a workaround of using our own Recaptcha sitekey, but cannot control the Recaptcha `sitekey` because it is [blacklisted in this project](https://github.com/firebase/firebaseui-web/blob/7ce12f52d514623aa13a1f3a0befa2e2c33417ce/javascript/widgets/config.js#L178-L183).

We are aware of the [Set a web app's OAuth redirect domains](https://support.google.com/firebase/answer/6400741?hl=en) page and https://github.com/firebase/firebaseui-web/issues/166. Neither resolve the problem at hand.

**Describe the solution you'd like**

We would like the ability to officially support subdomains. If `mysite.com` has dynamic subdomains, `user1.mysite.com` should work just as well as `www.mysite.com` or otherwise. Adding all subdomains is not scalable and likely impossible for the number of subdomains we have available.

**Describe alternatives you've considered**

A solution could be to allow us to control our `sitekey` so we can turn off domain verification, at our own peril. We understand the implications and, at this point, would choose them over not being able to use phone auth at all.

**Additional context**

We are fully aware this request might best be served elsewhere (different issue system in a different part of Google/Firebase). Please let us know if this is the case.

Sources:
/firebasejs/5.7.0/firebase-app.js
/firebasejs/5.7.0/firebase-auth.js
firebaseui/3.5.1/firebaseui.js
firebaseui/3.5.1/firebaseui.css

**Comment by bojeil-google** [comment]
This is not clear in our documentation but for phone auth, only exact domain match is allowed, unlike OAuth domains. The latter (subdomain whitelisting for OAuth operations) exists for backward compatibility with legacy Firebase which followed that behavior. Phone Auth was introduced after and only supports exact domain matches. You are also welcome to file a [feature request](https://firebase.google.com/support/).

**Comment by allamgr** [comment]
@bojeil-google I have the site mounted on heroku project and have the domain added and still getting this issue.

![image](https://user-images.githubusercontent.com/1780017/58435274-b6f89800-808d-11e9-9960-b3076995780e.png)
