### ISSUE TITLE
Verification email being sent even after email is verified.

### ISSUE THREAD

**Issue by SunilRumbaLama** [firebase/firebaseui-web#55]
Firebase `sendEmailVerification()`does send the email verification, however, even after the email is verified, it keeps on sending the email verification notice. Is there a timeout that we can set, so that the verification message last for certain time. However, the email verification notification coming even after the email is verified does seem to be bug for firebase.

**Comment by bojeil-google** [comment]
You can call sendEmailVerification even if the email is already verified. That said, this is a manual operation you have to explicitly call. I am not sure what you mean by verification email being sent even after email is verified. You can the emailVerified status before sending it.

**Comment by Splaktar** [comment]
Is there even support for sending verification emails in firebaseui-web? I can't seem to find any. This question seems to be referring to the Firebase SDK only?

**Comment by TMSCH** [comment]
@Splaktar it is indeed a question referring to the Firebase SDK.

**Comment by jasan-s** [comment]
I also received 2 verfication emails after I sent the verfication request.  The other 2 emails came several hours later , without any action. The app is still in development so I am the only one who have access to it.

**Comment by puf** [comment]
Please indicate when you cross-post: https://stackoverflow.com/questions/44604551/getting-multiple-verification-emails-from-firebase?noredirect=1#comment76199144_44604551

**Comment by puf** [comment]
And as [you just indicated there](https://stackoverflow.com/questions/44604551/getting-multiple-verification-emails-from-firebase?noredirect=1#comment76203355_44604551):

>human error: I was calling it within a deep nested code

**Comment by nicolasgarnier** [comment]
To sum this up:  Yes `sendEmailVerification()` will send an email even if the email has already been verified. You need to check if the email has already been verified i the code to avoid this behavior.
about the delayed emails: we used to have some issues with email sending from Firebase being delayed but his has been fixed since.
