### ISSUE TITLE
Unable to delete and signout when signed in using phone verification?

### ISSUE THREAD

**Issue by vishal758** [firebase/firebaseui-web#550]
When I am trying to sign in using phone verify then after successful sign in I am unable to sign out or delete account and after that I am strucked on the signed in screen (i.e the sign out and delete account button doesn't provide any functionality). Earlier they were working fine. I haven't change any anything.
Can anybody plz suggest me how to solve this issue.

**Comment by bojeil-google** [comment]
It is impossible to determine the cause of this with the information provided. Please provide a way to recreate this.
