### ISSUE TITLE
 Alternatively you can provide a callbacks.signInSuccess function.

### ISSUE THREAD

**Issue by voidstarfire** [firebase/firebaseui-web#552]
I'm looking to create a custom callback after sign in so that I can fetch user data before proceeding.

"According to the documentation we can provide a function for callbacks.signInSuccess."

Does not seem to work as intended and Typescript complains it's wrong.

I'm using the most barebones app possible.

Get the following error:
https://i.imgur.com/K64dc0D.png

**Comment by bojeil-google** [comment]
Hey @voidstarfire, the callback is [`signInSuccessWithAuthResult`](https://github.com/firebase/firebaseui-web#signinsuccesswithauthresultauthresult-redirecturl).
You can also check out the type definitions [here](https://github.com/firebase/firebaseui-web/blob/master/types/index.d.ts#L22) too.

**Comment by voidstarfire** [comment]
@bojeil-google Thanks for the reply.

It doesn't take a function though? Also doesn't exist on the 'callbacks' options.
https://imgur.com/a/V2scDIy
