### ISSUE TITLE
[Action Required] Google+ APIs and OAuth requests are being shutdown on March 7, 2019

### ISSUE THREAD

**Issue by rajaraodv** [firebase/firebaseui-web#553]
Hi there, I got the following email from Google. I'm using FirebaseUI but haven't really done any changes to the scopes. It looks like the FirebaseUI is using Google+ `plus.me` somewhere internally. Wondering how to resolve this. Any help greately appreciated. 

Hello Google+ Developer,

The email below contains your most recent usage of Google+ APIs. Note: It includes Google+ OAuth scope requests, which are also affected by the Google+ shutdown. A prior email sent to active API callers did not include information about OAuth requests. One final reminder email will be sent in February to users who still have active API or OAuth request activity.

What do I need to know?
On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown, with API calls starting to intermittently fail as early as January 28, 2019, and OAuth requests for Google+ scopes starting to intermittently fail as early as February 15, 2019.

What do I need to do?
Please update your projects listed below by March 7, 2019 and ensure they are no longer using Google+ APIs, or requesting Google+ OAuth scopes. The data below shows which Google+ API methods your projects have recently called, as well as Google+ OAuth scopes it has requested.

Note: If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature to the more comprehensive Google Sign-in authentication system

Project | Google+ API Name | Version | Method or OAuth Scope
-- | -- | -- | --
App name | OAuth | N/A | plus.me

.

**Comment by bojeil-google** [comment]
Hey @rajaraodv we removed the `plus.me` scope from our backend logic last week. Can you confirm that you are not manually requesting that scope or other Google+ scopes? We refer to some of these scopes (`plus.login`) in our repo documentation and we will remove that to avoid confusing developers:

- https://github.com/firebase/firebaseui-web#configure-oauth-providers

**Comment by rajaraodv** [comment]
I'm not using any additional scope. So I guess I just need to update the lib then?

**Comment by bojeil-google** [comment]
The change we made should not require client side change. To confirm, try to sign in with Google in your app with FirebaseUI. Then go to your accounts.google.com -> Security -> Third-party apps with account access, check that your app is not asking for any Google+ scopes.

**Comment by rajaraodv** [comment]
Just did that and I see:

Has access to:	
Basic account info
View your basic profile info
View your email address

Access is given on:	
Just now


but, why am I getting that notification then?

**Comment by bojeil-google** [comment]
I am not sure, perhaps this notice was sent before our backend server made the change.

**Comment by rajaraodv** [comment]
Anyway, I'll update the version to the latest and hope for the best
