### ISSUE TITLE
Firebase UI not working with last Firebase SDK version 5.8.x

### ISSUE THREAD

**Issue by devsheder** [firebase/firebaseui-web#556]
### Environment

  * Operating System version: Mac OS 10.13.3
  * Browser version: Chrome 71.0.3578.98
  * Firebase UI version: 3.5.2
  * Firebase SDK version: 5.8.2
  * TypeScript version: 3.3.1
  * ReactJs version: 16.8.0

#### Steps to reproduce:
I've upgraded my project to last firebase SDK version.
The Firebase UI crash while trying initializing Firebase App.

Stack on the screen :
![screen shot 2019-02-06 at 11 03 58](https://user-images.githubusercontent.com/19798549/52333997-ffb51400-29fe-11e9-8c9f-0d39ddb1a9d9.png)

FYI : Firebase have changed their structure, regarding of my code below

##### firebase.tsx code
```typescript
import firebase from "@firebase/app";
import "@firebase/auth";
import "@firebase/database";
import "@firebase/firestore";
import "@firebase/functions";

// Masked because there are my personel credentials
const config = {
  ...
};

if (!firebase.apps.length) {
  firebase.initializeApp(config);
}

export default firebase;
```

##### code to initialize Firebase UI
```typescript
import * as firebaseui from "firebaseui";
import * as React from "react";
import firebase from "../firebase";
import "./AuthForm.css";

const { auth } = firebase;

class AuthForm extends React.Component<{}, {}> {
  private firebaseUi?: firebaseui.auth.AuthUI = undefined;

  public componentDidMount() {
    const uiConfig = {
      signInOptions: [
        auth!.EmailAuthProvider.PROVIDER_ID,
        auth!.GoogleAuthProvider.PROVIDER_ID
      ],
      signInSuccessUrl: "/"
    };

    this.firebaseUi = new firebaseui.auth.AuthUI(auth!());
    this.firebaseUi.start("#firebaseui-auth-container", uiConfig);
  }

  public componentWillUnmount() {
    if (!!this.firebaseUi) {
      this.firebaseUi.delete();
    }
  }

  public render() {
    return (
      <div className="col-12 col-md-12">
        <h4 className="text-center">Sign in</h4>
        <div id="firebaseui-auth-container" />
      </div>
    );
  }
}

export default AuthForm;
```

**Comment by bojeil-google** [comment]
Hey @devsheder were you able to get it to work with any version older than 5.8.x? Can you share the last version this worked with?

**Comment by devsheder** [comment]
Hi @bojeil-google 
With the latest 5.7.x it's was working fine.

**Comment by wti806** [comment]
@devsheder I'm not sure why you are using the scoped packages. But it might be related. Could you please remove the "@" in your import statement and try again? It should be `firebase/app` `firebase/auth`
etc.

**Comment by devsheder** [comment]
@wti806 I've noticed that since the 5.8.x it's the way we have to use Firebase SDK. I had to change many code in my app to get the Firebase SDK working.
If I set the imports as you say (without @) I have the same error as in the stack above.

Can you try and tell me if you get that working ?

**Comment by wti806** [comment]
@devsheder What is changed since 5.8.x?

**Comment by devsheder** [comment]
@wti806 Here is my old code :
```typescript
import * as firebase from "firebase/app";
import "firebase/auth";
import "firebase/database";
import "firebase/firestore";
import "firebase/functions";

// Masked because there are my personel credentials
const config = {
  ...
};

if (!firebase.apps.length) {
  firebase.initializeApp(config);
}

const settings = {/* your settings... */ timestampsInSnapshots: true};
firebase.firestore().settings(settings);

export default firebase;
```
This code doesn't run anymore :
![image](https://user-images.githubusercontent.com/19798549/52399938-00f94600-2abe-11e9-8110-ee541a88e199.png)
Even if I comment the line which called firestore function, I have the same problem when I try access this function with other code in my app.

I had to make the changes you've seen above to make it work.
I don't have any explanation, because I didn't find anything in doc.

**Comment by Feiyang1** [comment]
I couldn't reproduce the error. Firestore has a breaking API change for timestamps, you can see the release note here: https://firebase.google.com/support/release-notes/js#5.8.0
but I don't think it's related to your issue. 

I suggest deleting node_modules and reinstalling the dependencies and see if it resolves your issue.

**Comment by devsheder** [comment]
HI @Feiyang1 
I tried what you've said and I still have the same issue :
> TypeError: __WEBPACK_IMPORTED_MODULE_0_firebase_app__.firestore is not a function

On this link we can see that :
> Version 5.8.0 - Jan 17, 2019
> Added a type definition file for all firebase components, so that they work with TypeScript with dynamic import.

I think, that's why I had to change my code.
Have you try de reproduce the problem with TypeScript or just with JavaScript ?

**Comment by devsheder** [comment]
Problem solved here : https://github.com/firebase/firebase-js-sdk/issues/1523

Thanks guys for your help :)
