### ISSUE TITLE
Errors with version 3.4.0 of Firebase

### ISSUE THREAD

**Issue by rlansky** [firebase/firebaseui-web#56]
I tried upgrading my npm dependency of Firebase from 3.3.2 to 3.4.0. But when I did that, I started getting errors in firebase-ui-auth.js. Here's the details of the error I get in the browser:

<img width="1392" alt="screen shot 2016-09-20 at 4 36 34 pm" src="https://cloud.githubusercontent.com/assets/3543346/18691525/64821ae6-7f51-11e6-91ac-5b05bbd8ef5b.png">

Has anyone else gotten this to work with version 3.4.0 of Firebase?

Cheers,
--Rick

**Comment by bojeil-google** [comment]
I think this may be related to this issue: https://groups.google.com/forum/#!topic/firebase-talk/s98ZYWpTLHI

**Comment by rlansky** [comment]
Thanks, yeah, that does seem to be the same issue. 

I guess the real problem is that I'm using firebase is an npm module, and firebase-ui-auth has to be included as a direct script (there is currently no npm option). I don't want to include firebase as a script as well, so the alternative seems to be to wait for this project to be an npm module. I see that is listed as a P1 issue, so hopefully it won't be too much longer. 

Thanks again!

**Comment by TMSCH** [comment]
Closing, as the NPM request is tracked in another issue.
