### ISSUE TITLE
uiConfig error : defaultCountry, whitelistedCountries, defaultNationalNumber & loginHint

### ISSUE THREAD

**Issue by ravivit9** [firebase/firebaseui-web#563]
### [REQUIRED] Describe your environment

  * Operating System version: ____Mac_
  * Browser version: ___Chrome Version 72.0.3626.119__
  * Firebase UI version: __"firebaseui": "^3.5.2",___
  * Firebase SDK version: __"firebase": "^5.8.5",___

### [REQUIRED] Describe the problem
I am trying to configure trying the following for phone authentication using firebase-ui
```
      defaultCountry: 'GB',
      defaultNationalNumber: '1234567890',
      loginHint: '+11234567890',
      whitelistedCountries: ['US', '+44'],
```
All the above gives me a console error at runtime.

#### Steps to reproduce:

<img width="590" alt="screenshot 2019-03-03 at 18 44 16" src="https://user-images.githubusercontent.com/3435829/53699865-8e416900-3de4-11e9-9cc2-621412b80361.png">

#### Relevant Code:
`    const uiConfig = {
      signInSuccessUrl: '/books',
      signInOptions: [
        firebase.auth.PhoneAuthProvider.PROVIDER_ID
      ],
      defaultCountry: 'GB',
      defaultNationalNumber: '1234567890',
      loginHint: '+11234567890',
      whitelistedCountries: ['US', '+44'],
      tosUrl: 'https://ajonp.com/terms',
      privacyPolicyUrl: function() {
        window.location.assign('https://ajonp.com/privacy');
      }
    };
    this.ui = new firebaseui.auth.AuthUI(this.afAuth.auth);
    this.ui.start('#firebaseui-auth-container', uiConfig);`

**Comment by bojeil-google** [comment]
You are passing them incorrectly:
```
signInOptions: [{
  provider: firebase.auth.PhoneAuthProvider.PROVIDER_ID,
  defaultCountry: 'GB',
  defaultNationalNumber: '1234567890',
  loginHint: '+11234567890',
  whitelistedCountries: ['US', '+44']
}]
```
Check the example in the docs:
https://github.com/firebase/firebaseui-web#configure-phone-provider
