### ISSUE TITLE
Getting a problem with installation Firebase on a Vue project

### ISSUE THREAD

**Issue by nurda2001** [firebase/firebaseui-web#564]
Getting a problem with installiation Firebase on a Vue project
My environment info:
OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    bootstrap-vue:  2.0.0-rc.11
    vue:  2.6.4
    vue-functional-data-merge:  2.0.7
    vuetify:  1.5.0 ( if its needed)

Also, i have seen some fixes, like changing the node version but it doenst work. At the first npm install, i saw a problem with pythonFinder, and setted it up, however it still doesnt work 

[log.txt](https://github.com/firebase/firebaseui-web/files/2949593/log.txt)

**Comment by bojeil-google** [comment]
From the log attached, there is no clear indication the error is related to FirebaseUI. You may want to post your question on stackoverflow, you'll get better help from developers who are more familiar with npm in windows environments.

**Comment by tohagan** [comment]
This is due to gRPC library (needed by `firestore` and `onCall`) failing to build under node-gyp. 
Latest Firebase release now uses a JS implementation of gRPC (used to be binary) so I'd try an upgrade to your Firebase SDK version. 

This answer is unofficial .. I'm not on the Firebase team.
