### ISSUE TITLE
We have blocked all requests from this device due to unusual activity.

### ISSUE THREAD

**Issue by lanman2000** [firebase/firebaseui-web#566]
#### Environment:

  * Operating System version: Windows 10
  * Browser version: Chrome 73.0.3683.86
  * Firebase UI version: 3.5.1
  * Firebase SDK version: 5.7.2

### [REQUIRED] Describe the problem

Any time we attempt to use the firebase user sendEmailVerification() method it doesn't send the email and we see the following error in dev tools:

code: "auth/too-many-requests", message: "We have blocked all requests from this device due to unusual activity. Try again later."

We have already increased the sign in quota in firebase console which is suggested but that did not fix it.

#### Steps to reproduce:

Call sendEmailVerification() method on any firebase user

#### Relevant Code:

firebase.auth().currentUser.sendEmailVerification()

**Comment by bojeil-google** [comment]
This is the wrong forum for this issue. FIrebaseUI does not send email verifications.
You are better opening the issue with [Firebase Support](https://firebase.google.com/support/) as it could be unique to your project and sensitive project details will be needed to investigate this.

I speculate you are resending the email to the same user too frequently (in a short period of time). I think they recently increased the duration between same emails sent to the same recipient. Usually after some time, maybe a minute, the restriction will be lifted for that email.
I think you will get more details from support.

**Comment by mdmasudsikdar71** [comment]
One of the possible solutions:

1. Go to your Firebase console -> AUTH -> Users table
2. Locate the user you are testing.
3. Delete this user.
4. Retest.

**Comment by CalvinJamesHeath** [comment]
im getting the same error with email verification 

{code: "auth/too-many-requests", message: "We have blocked all requests from this device due to unusual activity. Try again later.", a: null}

**Comment by ramonpaolo** [comment]
same error here
My last request was 12 hour ago, and now i get this error too

**Comment by ahmed-alhelali** [comment]
Have you found a solution to this problem?

**Comment by hasnainelahi** [comment]
How we can increase the Firebase limit of 5 SMS per phone number per 4 hours? any solution?

**Comment by brijeshpatel009** [comment]
> How we can increase the Firebase limit of 5 SMS per phone number per 4 hours? any solution?

You can visit this link to find out about your usable plan.
https://firebase.google.com/docs/auth/limits

**Comment by leoey** [comment]
i got it too

Access Blocked
We have blocked all requests from this device due to an abnormal number of requests and/or unusual activity.
Try again later.

<img width="599" alt="Image" src="https://github.com/user-attachments/assets/71248a6b-34e7-4774-b400-ddd960ca2032" />
