### ISSUE TITLE
Demo web page not properly configured.

### ISSUE THREAD

**Issue by Zubnix** [firebase/firebaseui-web#571]
Trying to login using Google auth fails with error:

The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain (fir-ui-demo-84a6c.firebaseapp.com) to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

**Comment by bojeil-google** [comment]
Thanks for the notification. The API key in the demo app needs to be updated.

**Comment by wti806** [comment]
Whitelisted additional domains for the API key. It should be resolved. Thanks!
