### ISSUE TITLE
Firestore console UI crashes browser when accessing large entity  

### ISSUE THREAD

**Issue by jimmyff** [firebase/firebaseui-web#572]
Sorry I can't find an appropriate place to file this issue so please let me know if there is somewhere better.

I have multiple collections that are made up of entities containing 4 maps (of type <int, bool>), each of these maps contain 8000 items. When I try to access these in the browser UI it crashes my browser.

Ideally any array/map that contains more than say 50 items should be closed by default and only when you expand them should it add all the dom elements.

**Comment by wti806** [comment]
Please contact the [firebase support](https://firebase.google.com/support/). Your question is not related to FirebaseUI at all.
