### ISSUE TITLE
Is it safe for the merge conflict process of anonymous upgrade to be handled client side?

### ISSUE THREAD

**Issue by freshgrapes** [firebase/firebaseui-web#583]
Is it safe for the merge conflict process of anonymous upgrade to be handled client side? I already have the code working, however, the part where you copy the old data from anonymous user and update it to the new user requires writing to database, is it safe to have client handle the code?

I tried to move the code to Cloud Functions and have Cloud Functions take care of the database writing to Cloud Firestore, but it does not seems to be possible to move all of the code into one Cloud Functions because `return firebase.auth().signInWithCredential(cred);` needs to be handled by the client and saving anonymous user's credential on local variable to pass to the Cloud Functions sounds dangerous because user can just manipulate the credential and send the wrong credential to Cloud Functions.

What's the best way to do this?

The entire workflow of handling merge conflict of anonymous user upgrading that I am talking about is as followed:

```
// signInFailure callback must be provided to handle merge conflicts which
    // occur when an existing credential is linked to an anonymous user.
    signInFailure: function(error) {
      // For merge conflicts, the error.code will be
      // 'firebaseui/anonymous-upgrade-merge-conflict'.
      if (error.code != 'firebaseui/anonymous-upgrade-merge-conflict') {
        return Promise.resolve();
      }
      // The credential the user tried to sign in with.
      var cred = error.credential;
      // If using Firebase Realtime Database. The anonymous user data has to be
      // copied to the non-anonymous user.
      var app = firebase.app();
      // Save anonymous user data first.
      return app.database().ref('users/' + firebase.auth().currentUser.uid)
          .once('value')
          .then(function(snapshot) {
            data = snapshot.val();
            // This will trigger onAuthStateChanged listener which
            // could trigger a redirect to another page.
            // Ensure the upgrade flow is not interrupted by that callback
            // and that this is given enough time to complete before
            // redirection.
            return firebase.auth().signInWithCredential(cred);
          })
          .then(function(user) {
            // Original Anonymous Auth instance now has the new user.
            return app.database().ref('users/' + user.uid).set(data);
          })
          .then(function() {
            // Delete anonymnous user.
            return anonymousUser.delete();
          }).then(function() {
            // Clear data in case a new user signs in, and the state change
            // triggers.
            data = null;
            // FirebaseUI will reset and the UI cleared when this promise
            // resolves.
            // signInSuccessWithAuthResult will not run. Successful sign-in
            // logic has to be run explicitly.
            window.location.assign('<url-to-redirect-to-on-success>');
          });
```

**Comment by bojeil-google** [comment]
Can you clarify what you mean by manipulating the credential? Having one credential is not enough. You need the other credential too.

Overall, it should be ok to copy the data client side. After all Realtime database and Firestore are all serverless. In this case you can only access the authenticated user's data (you will have the authenticated anonymous and the authenticated non-anonymous user). If your rules are set correctly to only allow the corresponding user to access data, then this should be fine, because Firebase security rules will block access to one user if that user is not authenticated.

Though you can also copy the data server side via cloud function by sending the ID token for each user and validating both and then copying the data. This is basically the same as above but you do the validation manually server side.

**Comment by freshgrapes** [comment]
@bojeil-google thanks for the reply. I will list my concerns in 2 questions below:

1. What I am worrying about is code like this:
```
// Original Anonymous Auth instance now has the new user.
            return app.database().ref('users/' + user.uid).set(data);
```

If this is executed on the client side, wouldn't the user be able to use browser's devtools, change the value of the variable `data`, and use the above code to hack the database? (For example, changing the "subscription status" variable inside `data` from "free" to "paid", and write it to Cloud Firestore for free access to paid data)

2. Also with code like this:
```
return firebase.auth().signInWithCredential(cred);
```

If the user happens to know the user id of another user, wouldn't the user able to just manipulate `cred` and sign in as another user, since this is all executed client side?

Thanks so much!

**Comment by bojeil-google** [comment]
1. For admin only data (subscription, user roles, billing, etc), you should definitely resort to setting these server side. You can use cloud functions and pass the ID tokens of both users and handle the merge server side.

2. You can't manipulate `cred`. This would contain email/password, OAuth access tokens, phone number OTPs, etc of the signed in user. The user must have already proved ownership of these credentials before the credentials are generated and provided in the callback for you. If the attacker knows the credential, then the victim's account is already compromised.

**Comment by freshgrapes** [comment]
@bojeil-google 

After reading your reply, since I am dealing with admin data when migrating anonymous users, looks like I will have to move everything into the server, and leave only this line `return firebase.auth().signInWithCredential(cred);` to be executed in client?

Is there any ways to move `return firebase.auth().signInWithCredential(cred);` into the server as well? I tried to do it but `admin.auth()` does not have a `signInWithCrediential()` method. Is it meant to be executed in client side only?

**Comment by bojeil-google** [comment]
I think you'll have to do something like this:

```
signInFailure: function(error) {
  // ...
  var cred = error.credential;
  var anonymousIdToken;
  var credUserIdToken;
  var cred = error.credential;
  // Get anonymous user ID token.
  return firebase.auth().currentUser.getIdToken()
    .then(function(token) {
      anonymousIdToken = token;
      // Sign-in cred user.
      return firebase.auth().signInWithCredential(cred);
    })
    .then(function(result) {
      // Get signed in user ID token.
      return firebase.auth().currentUser.getIdToken();
    })
    .then(function(token) {
      credUserIdToken = token;
      // This should validate both tokens via Firebase Admin SDK.
      // Get uid of first token.
      // Get uid of second token.
      // Copy first user data to second user.
      // Delete first user.
      // Return response to client, function should resolve.
      return sendToServerAndMerge(anonymousIdToken, credUserIdToken);
    });
}
```

**Comment by freshgrapes** [comment]
@bojeil-google That's really helpful!

Is my understanding below correct?

1. It is safe to have the client sending `credUserIdToken` to the server, since `creUserIdToken` isn't manipulatable (and if it is manipulated by the user using browser's devtools or something, Firebase will check for me automatically and reject the token?), and I can just grab the uid of `credUserIdToken` on the server for further processing.

2. On the other hand, it is NOT safe to have the client sending JUST the uid of `credUserIdToken` (like `credUserIdToken.id`) to the server, since `credUserIdToken.id` is simply a string and can be easily manipulated by the client using the browser's devtools.

**Comment by freshgrapes** [comment]
@bojeil-google sorry, but another question:

3. Since `credUserIdToken` is a variable stored on the client side, can the client user see what's inside `credUserIdToken`, such as email/password and OAuth access tokens that you listed, by using the browser's devtools or any other tools? (Because for example if you have a variable `currentNumber` and its value is 2, the client can easily see that its value is 2 by using the browser's devtools, and the client can even change the value)

**Comment by bojeil-google** [comment]
ID tokens cannot be manipulated without validation failing. They are cryptographically signed by a private key. Any manipulation will result in the validation failing. Learn more how to validate ID tokens in the [Firebase docs](https://firebase.google.com/docs/auth/admin/verify-id-tokens).

Definitely do not trust `uid`. That provides zero security.

ID tokens are like temporary proofs and expire after one hour. They do not contain any passwords within them. Learn more about [JWTs](https://jwt.io/introduction/).

**Comment by freshgrapes** [comment]
@bojeil-google  In the approach you advised above, you use the function `return sendToServerAndMerge(anonymousIdToken, credUserIdToken);`. But the client can still mess with the app by doing `return sendToServerAndMerge(anonymousIdToken, anonymousIdToken);` or `return sendToServerAndMerge(credUserIdToken, credUserIdToken);`, since both ID tokens are valid, and this will still be accepted and processed server side.

Is there any ways we could move the entire `signInFailure: function(error) {...` operation into the server (specifically, this part: `return firebase.auth().signInWithCredential(cred);`)?

**Comment by bojeil-google** [comment]
There is no security downside in what you are describing. Why would someone do that? They won't get anything out of it. You can't move the part you describe to the server. The merge conflict is detected on the client side, when we effectively try to `linkWithCredential` on the anonymous user. 

Technically you can sign in with the credential server side (our client sdk can run in a Node.js environment) but this is not a requirement. However, if you do so, the user will be authenticated on your server and not on the client.

**Comment by freshgrapes** [comment]
@bojeil-google  If someone runs `return sendToServerAndMerge(credUserIdToken, credUserIdToken)`, then my `credUser` will be deleted by the server, since the first user gets deleted and `credUser` is now both the first and the second user.

When you said that the client sdk can run in a Node.js environment, did you mean I can put the entire FirebaseUI on the server side?  Do you know any documentations that I can go and find out how to accomplish this?

**Comment by bojeil-google** [comment]
As I already said, they would need to own both users (you can't get an ID token of a user without signing in with that suer). You can also enforce that the non-anonymous user is already authenticated by checking the `auth_time` on the token.
Please learn more about ID tokens and JWTs and the security they provide.
I think you can also use stackoverflow to further discuss strategies for these types of issues.

**Comment by christopherread** [comment]
@bojeil-google Reading the [official documentation](https://firebase.google.com/docs/auth/web/firebaseui) for the error `firebaseui/anonymous-upgrade-merge-conflict`, is it valid to:

1. call `auth.currentUser.linkWithCredential(credential)`,
2.  instead of copying/deleting user data, and calling `auth.signInWithCredential(error.cred)`

as described [in this official documentation](https://firebase.google.com/docs/auth/web/anonymous-auth), if that's the behavior I want?

**Comment by bojeil-google** [comment]
Hey @christopherread, you can't call `auth.currentUser.linkWithCredential(credential)` as it will fail. We try to do that first on your behalf but it will fail if the `credential` belongs to an existing user. This is what we call a merge conflict and you have to manually copy the data from one use to the other. You could sign in directly with the credential in the error but you would lose the current anonymous auth user.

**Comment by christopherread** [comment]
Thank you, I should have checked the `firebaseui` source first, before asking!
