### ISSUE TITLE
Must include firebase separately ? firebaseui not enough?

### ISSUE THREAD

**Issue by mehdi-cit** [firebase/firebaseui-web#59]
Hello, tried to include the firbaseui (classic script tag) only but found out firebase is undefined.
Does one have to include yet another script for firebase proper? I guess there must be duplicates between the two. 
How'd one go about using both and still not importing more javascript than the absolute minimum?

**Comment by bojeil-google** [comment]
They are 2 separate libraries. You have to include the firebaseui script and at least firebase-app.js and firebase-auth.js (the combination firebase.js works too).

**Comment by TMSCH** [comment]
Please have a look at: https://github.com/firebase/firebaseui-web#installation and the snippet under https://github.com/firebase/firebaseui-web#starting-the-sign-in-flow. You are required to copy and paste the initialization snippet from the Firebase console.
