### ISSUE TITLE
Uncaught ReferenceError: ui is not defined

### ISSUE THREAD

**Issue by GreatFireWall** [firebase/firebaseui-web#593]
![image](https://user-images.githubusercontent.com/4510984/58881584-0c2b4e00-870d-11e9-88d8-7c73ff0d3a63.png)

![image](https://user-images.githubusercontent.com/4510984/58881691-4563be00-870d-11e9-96dd-1a1899aba54d.png)

**Comment by RohanTalip** [comment]
It looks like your first screenshot is from the "[OAuth providers](https://firebase.google.com/docs/auth/web/firebaseui#oauth_providers_google_facebook_twitter_and_github)" section of the firebaseui-web documentation.

You should also read the "[Sign in](https://firebase.google.com/docs/auth/web/firebaseui#sign_in)" section a bit further down, which has this definition:
```
var ui = new firebaseui.auth.AuthUI(firebase.auth());
```

(The ordering of sections on that documentation page could be improved.)

That definition can also be found on the [main GitHub page for firebaseui-web](https://github.com/firebase/firebaseui-web#starting-the-sign-in-flow), i.e. this repository.
