### ISSUE TITLE
firebaseui-web License

### ISSUE THREAD

**Issue by SuhwanCha** [firebase/firebaseui-web#596]
https://github.com/firebase/firebaseui-web-react/blob/master/LICENSE
at line 190:
```
   Copyright [yyyy] [name of copyright owner]
```

Please fill year and name of the copyright owner

**Comment by RohanTalip** [comment]
@SuhwanCha, I think you meant https://github.com/firebase/firebaseui-web/blob/master/LICENSE as the firebaseui-web-react LICENSE already has that filled in (and is a separate repository).

**Comment by wti806** [comment]
Fixed in https://github.com/firebase/firebaseui-web/pull/606
