### ISSUE TITLE
Customizing the redirect domain for Google sign-in

### ISSUE THREAD

**Issue by colinoops** [firebase/firebaseui-web#597]
I understand that we can customize the redirect domain via Firebase Auth by changing the "auth domain" parameter, but how can I do this in firebaseui-web?

var config = {
  apiKey: '...', // Changed from 'my-app-12345.firebaseapp.com'.
  `authDomain: 'auth.custom.domain.com',` // How can I do this in firebaseui-web?
  databaseURL: 'https://my-app-12345.firebaseio.com',
  projectId: 'my-app-12345',
  storageBucket: 'my-app-12345.appspot.com',
  messagingSenderId: '1234567890'
};
firebase.initializeApp(config);

**Comment by bojeil-google** [comment]
No additional changes should be needed in FirebaseUI. It will automatically pick up the custom domain from the `firebase.auth()` instance you initialized it with.

```
var config = {
  apiKey: '...',
  authDomain: 'auth.custom.domain.com',
  databaseURL: 'https://my-app-12345.firebaseio.com',
  projectId: 'my-app-12345',
  storageBucket: 'my-app-12345.appspot.com',
  messagingSenderId: '1234567890'
};
firebase.initializeApp(config);

// AuthUI instance will use custom authDomain above.
var ui = new firebaseui.auth.AuthUI(firebase.auth());
```

**Comment by colinoops** [comment]
Thanks @bojeil-google! This resolved my issue.
