### ISSUE TITLE
Regarding Phone number Authentication

### ISSUE THREAD

**Issue by VishalThareja** [firebase/firebaseui-web#599]
re-captcha not working on web view while integrating a call from JavaFX to a javascript written for phone auth communication.

The error we are facing: RecaptchaVerifier is only supported in a browser HTTP/HTTPS environment.

**Comment by bojeil-google** [comment]
I don't know what you mean by "integrating a call from JavaFX to a javascript " but as the error message says, reCAPTCHA has to be loaded and rendered from a browser environment.

**Comment by VishalThareja** [comment]
I am having a desktop app in JavaFX, I am displaying an HTML file in webview in java and that HTML file executing javascript respectively which making call on Firebase Phone Auth using reCAPTCHA.
But reCAPTCHA is not being loading in webview.

As I mentioned error I am facing this : RecaptchaVerifier is only supported in a browser HTTP/HTTPS environment.

**Comment by bojeil-google** [comment]
The error is clear. reCAPTCHA only works from an http/https environment. Most webviews are served as a file, eg. `file://assets/.../index.html` which is clearly not an http/https environment.

**Comment by sobri3195** [comment]
you just convert html to php and DONE.
