### ISSUE TITLE
Can't use signInWithPopup. Only signInWithRedirect.

### ISSUE THREAD

**Issue by davidgilbertson** [firebase/firebaseui-web#6]
It would be great if it was possible to use `signInWithPopup`. Is this planned?

Sorry if I'm logging this in the wrong spot, I'm a little confused, is this (going to be) the repo for the actual code? [This page](https://firebase.google.com/docs/auth/#implementation_paths) mentions 'forking the repo' of Firebase UI. I guess that's referring to the iOS and Android falvors?

**Comment by bojeil-google** [comment]
Currently, only the iOS and the android version are open sourced.
Regarding signInWithPopup for firebaseui-web, we are interested in supporting that. I will convey your request to the relevant personnel.

**Comment by davidgilbertson** [comment]
@bojeil-google you want me to close this? Or leave it open to track progress?

**Comment by bojeil-google** [comment]
Feel free to close it. I think we will implement this feature but may take a bit of time before we get to it.
