### ISSUE TITLE
Can't change preselected phone number prefix USA +1

### ISSUE THREAD

**Issue by leolux** [firebase/firebaseui-web#601]
Even if I use the localized npm and firebaseui binaries as a npm module the default phone number always begins with USA +1.

Changing the HTML lang attribute or changing the default language of the browser doesn't any effect on the number prefix.

**Comment by bojeil-google** [comment]
Please check the [documentation](https://github.com/firebase/firebaseui-web#configure-phone-provider), you can preselect the default country by passing the `defaultCountry`.

**Comment by leolux** [comment]
Setting the `defaultCountry `to 'DE' does work:
``
signInOptions: [
        {
            provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
            requireDisplayName: false,
            defaultCountry: 'AT',
            whitelistedCountries: ['AT', '+43', 'DE', '+49']     
        },
``
Setting `whitelistedCountries` does not work either.

**Comment by wti806** [comment]
`defaultCountry` and `whitelistedCountries` only work for `firebase.auth.PhoneAuthProvider`. Please check the documentation.

**Comment by leolux** [comment]
Ok, thank you very much and sorry for missing that detail!
