### ISSUE TITLE
Unclear documentation about how to build a localized npm module

### ISSUE THREAD

**Issue by leolux** [firebase/firebaseui-web#609]
I have successfully build a localized npm module. But I am struggling using this module because of this sentence

> "Make sure all underscore symbols in the LANGUAGE_CODE are replaced with dashes. "

What exactly should one do here and at which step, before or after the build?

**Comment by bojeil-google** [comment]
Check the language codes [here](https://github.com/firebase/firebaseui-web/blob/master/LANGUAGES.md)
For example, if you are building npm module for es_419, you would build it as follows:
`npm run build build-npm-es-419`

You will need to clone the repo and `npm install` first.

You can then import:
import firebaseui from './dist/npm__es_419';

This is documented in the [Building FirebaseUI](https://github.com/firebase/firebaseui-web#building-firebaseui) section.

**Comment by leolux** [comment]
Alright, thanks!
