### ISSUE TITLE
Google Sign in With Different Account

### ISSUE THREAD

**Issue by JGSolutions** [firebase/firebaseui-web#61]
Not sure if this is a feature request or a bug but how do we login with a different google account?

**Comment by TMSCH** [comment]
Hi,
This has been raised in another issue (#38). This is currently not possible as the default behavior of the Google accounts chooser is to automatically select the one signed in if there's only one. You can go to https://accounts.google.com and sign in to another account if you want to have the choice.
Closing this issue in favor of the former one.

**Comment by JGSolutions** [comment]
Ok thanks

**Comment by ddimitrop** [comment]
Not sure if I got the question correctly but would prompting for account selection help?
For example:

```
let provider = new firebase.auth.GoogleAuthProvider();
provider.setCustomParameters({
  prompt: 'select_account'
});
firebase.auth().signInWithPopup(provider)
```

**Comment by bojeil-google** [comment]
At the time FirebaseUI was built, custom OAuth parameters were not supported by the Firebase Auth. As they are supported now, we could look into providing a way to configure some of these when initializing the UI. For example we could require prompting to select an account or force reauthenticate in facebook UI, or set the language, etc.

**Comment by giano574** [comment]
Any updates on this?

**Comment by bojeil-google** [comment]
This should be fixed in 2.1.1 release.
Check https://github.com/firebase/firebaseui-web#configure-oauth-providers
You can now pass `customParameters` for OAuth providers. This will accept the `prompt` field that Google OAuth supports.

**Comment by nategr03** [comment]
@bojeil-google Is there a way we can use a similar approach with _FacebookAuthProvider_? What I'm trying to achieve is that when the user chooses to log in with Facebook, he gets a prompt asking to choose an account. Is this possible?

**Comment by bojeil-google** [comment]
This behavior depends on the IdP. In this case, Facebook needs to expose that capability via custom OAuth parameters. 

I know that Facebook has one parameter to require password re-entry:

```
'customParameters': {
  'auth_type': 'reauthenticate'
}
```

I don't know if they have another parameter to change accounts or whether reauthenticate flow allows account change.
