### ISSUE TITLE
Build broken when using localized npm import statement

### ISSUE THREAD

**Issue by leolux** [firebase/firebaseui-web#610]
After following the documentation I import firebaseui like this:
`import * as firebaseui from './firebaseDE/4.1.0/dist/npm__de'`

But this breaks my build process and leads to the following error:
```
These dependencies were not found:
* firebase/empty-import in ./firebaseDE/4.1.0/dist/npm__de.js
* firebase/empty-import in ./firebaseDE/4.1.0/dist/npm__de.js
```
Note: I am using vue-cli for the build process.

**Comment by bojeil-google** [comment]
This seems like a duplicate of https://github.com/firebase/firebaseui-web/issues/609
