### ISSUE TITLE
FirebaseUI 4.0.1 is missing firebaseui.auth object

### ISSUE THREAD

**Issue by scriptPilot** [firebase/firebaseui-web#613]
Version 4.0.0 works great!

**Comment by wti806** [comment]
There is no v4.0.1. You should use v4.1.0.

**Comment by Spy-Seth** [comment]
I'm having the same issue with version `v4.1.0`. Rollbacking to `v4.0.0` fix the issue.

**Comment by wti806** [comment]
Can you guys provide more information of how you import FirebaseUI, the code snippet to reproduce the error and the package.json, so that we can try to reproduce. Thanks.

**Comment by jerryorta-dev** [comment]
This is working for me. I'm using Typescript ( Angular 8+ project ).

Imports:
```
import * as firebase from 'firebase/app';
import * as firebaseui from 'firebaseui'

```

Then use:

```
    // Initialize the FirebaseUI Widget using Firebase.
    const ui = new firebaseui.auth.AuthUI(firebase.auth());
```

**Comment by redreceipt** [comment]
`4.0.0` didn't work for me either

**Comment by wti806** [comment]
Again, without the code snippet of how you import firebaseui, we are not able to help you debug.

**Comment by redreceipt** [comment]
I figured it out and I think I know what's tripping everyone up, in your docs, you reference to paste in the initialization code from the console. That code mentions adding other SDKs but it's a little unclear what that means (at least it was to me).

<img width="635" alt="Screen Shot 2019-08-13 at 2 15 16 PM" src="https://user-images.githubusercontent.com/2659478/62966759-aecf0f80-bdd5-11e9-9ba6-f8bbdaf03ab3.png">


I simply needed to add this line where it mentions the `TODO`:

```html
<!-- TODO: Add SDKs for Firebase products that you want to use
        https://firebase.google.com/docs/web/setup#config-web-app -->
<script src="https://www.gstatic.com/firebasejs/6.3.5/firebase-auth.js"></script>
```

**Comment by Spy-Seth** [comment]
I was getting this issue with v4.1, and today I try to upgrade in v4.2 and I still have the issue.

```js
import firebaseui from "firebaseui";
import MyApplication from "./MyApplication";

console.log(firebaseui);

const myApplicationRootNode = document.getElementById("my-application-root");
if (!myApplicationRootNode) {
  throw new Error(
    'Unable to find the application root node "#my-application-root" in the DOM.'
  );
}

const parameters = {
  firebase: {
    apiKey: "...",
    authDomain: "...",
    databaseURL: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
    appId: "..."
  },
  // ...
};

const myApplication = new MyApplication(process.env.NODE_ENV, parameters);

myApplication.attachToDom(
  myApplicationRootNode, 
  firebaseui.auth.AuthUI // here `firebaseui.auth` is undefined
); 
```

Ad the content of the `firebaseui` import:
<img width="650" alt="Screenshot 2019-10-02 at 09 11 00" src="https://user-images.githubusercontent.com/95120/66024620-9ab1af80-e4f4-11e9-8e31-8d2c1f658941.png">


This is a TypeScript project with Parcel as bundler.
