### ISSUE TITLE
Missing `button` class on cancel button in new account creation flow

### ISSUE THREAD

**Issue by soaxelbrooke** [firebase/firebaseui-web#620]
### Describe your environment

  * Operating System version: Ubuntu 18
  * Browser version: Firefox 68.0.2
  * Firebase UI version: 4.1.0
  * Firebase SDK version: 7.2.3

### Describe the problem

The `Cancel` button in the sign in flow does not have the `button` class, as the other buttons in the sign in flow do.   This causes incorrect styling for UIs that use the `button` class:

![image](https://user-images.githubusercontent.com/2815794/63298800-3068e680-c289-11e9-8149-28785971a82c.png)

**Comment by wti806** [comment]
@soaxelbrooke We don't add "button" class to any of  the buttons. Not sure why your app has the button class in submit button. Are you using any frameworks that could automatically add the class? Besides, you can always use the 'firebaseui-button' class to override the css.

**Comment by soaxelbrooke** [comment]
Hey @wti806, thanks for the response! Hmm, I am not doing anything that would automatically add the class.  After looking at the soy templates, they appear to agree, as I don't see any `button` class specified there.  I'll look into it more on my side, thanks!
