### ISSUE TITLE
Authentication not working under Chrome OS Linux development environment.

### ISSUE THREAD

**Issue by TrustyTechSG** [firebase/firebaseui-web#629]
### [REQUIRED] Describe your environment

  * Operating System version: __CHROME OS 76___
  * Browser version: __CHROME 76___
  * Firebase UI version: __4.1.0___
  * Firebase SDK version: __6.4.0___

### [REQUIRED] Describe the problem
All user account login return "The user account has been disabled by an administrator. " error under development environment.

#### Steps to reproduce:
1. Enable Linux on Chrome OS 76.
2. Open Linux terminal under 'Linux Apps', setup node 10 and react development server, start then development server with the exact same git code base with is working well on Mac or Windows development environment.
3. Try login any user account, received error 'The user account has been disabled by an administrator', but all tested account are enabled and can be login successfully under other environment.

**Comment by laurentpayot** [comment]
Kind of a workaround: I switched to a real Linux development environment with https://galliumos.org/ and it removed the lags and this sort of bugs.

**Comment by bojeil-google** [comment]
The error "The user account has been disabled by an administrator" is a backend error that is thrown when a user is disabled. This is highly unlikely to be related to the environment or firebaseui-web. You can inspect the network console and you should notice a USER_DISABLED error returned by the Auth server. We also never disabled the user automatically. It must have been disabled either via Admin SDK or Firebase Console UI.

**Comment by bojeil-google** [comment]
Please file a ticket with [Firebase Support](https://firebase.google.com/support/). Check the network requests. If the error is returned from the Auth server, there is little we can do in this public client library forum to help with this. This is a backend behavior and not related to the client libraries. You will need to provide details on your project and ways to reproduce, including the accounts to sign in with, etc.

**Comment by TrustyTechSG** [comment]
> Please file a ticket with [Firebase Support](https://firebase.google.com/support/). Check the network requests. If the error is returned from the Auth server, there is little we can do in this public client library forum to help with this. This is a backend behavior and not related to the client libraries. You will need to provide details on your project and ways to reproduce, including the accounts to sign in with, etc.

Noted, thank you.

**Comment by TrustyTechSG** [comment]
> Kind of a workaround: I switched to a real Linux development environment with https://galliumos.org/ and it removed the lags and this sort of bugs.

I will try on this, thank you.

**Comment by TrustyTechSG** [comment]
For anyone who saw this issue please ignore it, this is my personal mistake, I was on a disabled git branch on chrome environment. Stupid mistake.

@bojeil-google sorry and thank you for your reply.
