### ISSUE TITLE
Are we at 1.0?

### ISSUE THREAD

**Issue by rlansky** [firebase/firebaseui-web#63]
Hi,

Reading the Firebase blog (https://firebase.googleblog.com/2016/11/live-from-firebase-dev-summit-in-berlin.html), I see that Firebase UI is updated to 1.0. But when I look at this project, I can't tell if it's really at 1.0 or not. 

There are a lot of files here now, so that's encouraging. But the examples in the README all still make use of the 0.5 version of Firebase UI:

`<script src="https://www.gstatic.com/firebasejs/ui/live/0.5/firebase-ui-auth.js"></script>`

Also, looking at the 1.0 Milestone in this project, none of the issues listed in there as being assigned to that Milestone are marked as done.

So I'm a little confused if we're really at 1.0 in this project, can anyone on the project provide some insight?

Thanks in advance,
--Rick

**Comment by bojeil-google** [comment]
Hey Rick, sorry for the confusion and thanks for reporting this issue. We have definitely launched version 1.0. We will update the links and address relevant open issues shortly.

**Comment by TMSCH** [comment]
I have updated the README with the correct URLs. I will update the issues still open in the milestone with more information.
