### ISSUE TITLE
Does Firebase Auth support Reddit oAuth?

### ISSUE THREAD

**Issue by jlei523** [firebase/firebaseui-web#632]
See title

**Comment by bojeil-google** [comment]
No it does not. We only support the providers documented in the [Firebase docs](https://firebase.google.com/docs/auth/web/start).

**Comment by bojeil-google** [comment]
[Identity Platform](https://cloud.google.com/identity-platform/docs/quickstart-cicp), which FirebaseUI supports, does [support OIDC providers](https://cloud.google.com/identity-platform/docs/how-to-enable-application-for-oidc) (id_token flow only for now). Though I do not know if Reddit OAuth is OIDC compliant.
