### ISSUE TITLE
esm build seems to be broken (initializeApp is not a function)

### ISSUE THREAD

**Issue by juanmait** [firebase/firebaseui-web#637]
* Operating System version: macOS Mojave 10.14.5
  * Browser version: Chrome 76
  * Firebase UI version: 4.2.0
  * Firebase SDK version: 7.2.0

Trying to import firebaseui as described in the docs for webpack users throws a runtime error:

```
Uncaught TypeError: firebase_app__WEBPACK_IMPORTED_MODULE_0__.initializeApp is not a function
    at new Vn (esm.js:406)
    at Module../src/client.js (client.js:28)
    at __webpack_require__ (bootstrap:63)
    at bootstrap:198
    at bootstrap:198
```

Warning are also shown at build time:

```
WARNING in ./node_modules/firebaseui/dist/esm.js 192:218-231
"export 'auth' (imported as 'firebase') was not found in 'firebase/app'
 @ ./src/client.js

WARNING in ./node_modules/firebaseui/dist/esm.js 193:159-172
"export 'auth' (imported as 'firebase') was not found in 'firebase/app'
 @ ./src/client.js

WARNING in ./node_modules/firebaseui/dist/esm.js 193:229-242
"export 'auth' (imported as 'firebase') was not found in 'firebase/app'
 @ ./src/client.js

WARNING in ./node_modules/firebaseui/dist/esm.js 193:320-333
"export 'auth' (imported as 'firebase') was not found in 'firebase/app'
 @ ./src/client.js

... and so on
```

#### Relevant Code:

```js
import firebase from 'firebase/app';
import 'firebase/functions';
import 'firebase/auth';
import * as firebaseui from 'firebaseui';

firebase.initializeApp({
  apiKey: '***',
  authDomain: '***',
  databaseURL: '***',
  projectId: '***',
  storageBucket: '***',
  messagingSenderId: '***',
  appId: '***',
});

const auth = firebase.auth();
new firebaseui.auth.AuthUI(auth);
```

In order to **solve the problem** I had to import the npm build instead like so:

```js
import * as firebaseui from 'firebaseui/dist/npm';
```

After that, it started to work fine and the warnings at build time are also gone.

**Comment by wti806** [comment]
You need to import the Firebase Core SDK as follow:
```
import * as firebase from "firebase/app";
import "firebase/auth";
```

**Comment by juanmait** [comment]
@wti806 yes, I'm doing it that way. I miss that in the issue. I updated the snippet.

**Comment by juanmait** [comment]
sorry, hit the wrong btn

**Comment by juanmait** [comment]
For the core import I tryed both ways, `import * as firebase from 'firebase'` (in this case the resulting object has a `default` property) and also `import firebase from firebase` (work just fine).

**Comment by wti806** [comment]
I just tried with js-sdk v7.2.0 and firebaseui v4.2.0. I works fine for me. From the error message, it seems that FirebaseUI cannot find the js-sdk dependencies. Probably it's related to your webpack config.

**Comment by juanmait** [comment]
@wti806 Thanks, indeed seems to be a webpack config thing. I tried with the simplest config and it works. Thanks for your time!

**Comment by saviski** [comment]
I manually edited _node_modules/firebaseui/dist/esm.js_,
changed `import * as firebase from 'firebase/app';`
to `import firebase from 'firebase/app';`

and now it works, I am able to import firebaseui ES Module on my app and run this code without issues:

```js
import firebase from 'firebase/app';
import * as firebaseui from 'firebaseui';
firebase.initializeApp({ ... });
new firebaseui.auth.AuthUI(firebase.auth());
```

before it was throwing the _initializeApp is not a function_ exception running the last line.

**Comment by dwivedithedev** [comment]
> import * as firebase from "firebase/app";
> import "firebase/auth";

Why don't they write this in the main docs?! It fixed the issue I was having when implementing the same in svelteJS based webapp.
