### ISSUE TITLE
The supplied auth credential is malformed or has expired

### ISSUE THREAD

**Issue by xErik** [firebase/firebaseui-web#643]
# Setup 

  * Operating System version:  Win 10
  * Firebase UI version: 4.2.0
  * Firebase SDK version: 6.6.2
 * Development on https://localhost:4200

# Problem

Login with Twitter, Github and Facebook works flawlessly. 

After entering my password in the oAuth login popup window, Google fails with error message in Chrome UI:

`The supplied auth credential is malformed or has expired`

The browser console gives two errors:

```
POST: 400

https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=<I-DELETED-THIS>
```

```
Unhandled Promise rejection: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Function.push../node_modules/@firebase/firestore/dist/index.cjs.js.SimpleDbTransaction.open (https://localhost:4200/vendor.js:117927:43)
```

# Background

- I enabled the Google Authorization in the Firebase Console.
- I deleted the local browser storage etc. just to be sure.

**Comment by wti806** [comment]
I cannot reproduce this issue. If you can host your code somewhere, I can help debug. But I suspect it was caused by your configuration.

**Comment by xErik** [comment]
Indeed a strange error. I will open a ticket with the Firebase team.

Trying Edge, tells me `invalid syntax`:

```
HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(XHR)POST - https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=<SECRET>
```

I tried variations of my config, none is working:

```javascript
 signInOptions: [
    {
      scopes: [
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile'
      ],
      customParameters: {
        // auth_type: 'reauthenticate',
        prompt: 'select_account'
      },
      provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID
    },
...
]
```

**Comment by wti806** [comment]
I tested your configuration and it works. Did you setup the support email when you create the firebase project and enable google sign-in?

**Comment by xErik** [comment]
Yes, Google Sign-In is enabled and my email is the support email.

Days ago I changed my password, that might be a factor. That's why I used these settings to to get a "fresh login token":

```
customParameters: {
        auth_type: 'reauthenticate',
        prompt: 'select_account'
      }
```

Basically, I believe the password change bungled up my Google Account in some way.

I am giving on on this :-(

**Comment by raahimkhan** [comment]
I am also getting `[auth/invalid-credential] The supplied auth credential is malformed or has expired.` on iOS only when using Firebase auth (Google provider). Simple Google login is working fine in both Android and iOS. Firebase auth with Google provider is also working fine on Android. Just getting the error on iOS. Any leads?
