### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'AuthUI' of undefined" in 4.1.0+ 

### ISSUE THREAD

**Issue by raygesualdo** [firebase/firebaseui-web#645]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OSX 10.14
  * Browser version: Chrome 78
  * Firebase UI version: 4.1.0 & 4.2.0
  * Firebase SDK version: 7.3.0

#### Steps to reproduce:

Use the Parcel bundler with Typescript. Set up a firebaseui instance as [documented](https://github.com/firebase/firebaseui-web#starting-the-sign-in-flow). A console error will throw saying "Uncaught TypeError: Cannot read property 'AuthUI' of undefined". This issue is non-existent in v4.0.0. My suspicion is it has to do with the ESM bundle present in v4.1.0+. This issue was [observed by at least one other on a closed issue](https://github.com/firebase/firebaseui-web/issues/613#issuecomment-537367729).

#### Relevant Code:

NOTE: This issue does not present itself on stackblitz.

`js/index.ts`

```typescript
import * as firebase from 'firebase/app'
import * as firebaseui from 'firebaseui'

const firebaseConfig = {
  projectId: '************',
  databaseURL: '************',
  storageBucket: '************',
  locationId: '************',
  apiKey: '************',
  authDomain: '************',
  messagingSenderId: '************',
}

firebase.initializeApp(firebaseConfig)

const ui = new firebaseui.auth.AuthUI(firebase.auth())
```

`package.json`

```json
{
  "name": "test-app",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html"
  },
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.12.4",
    "typescript": "^3.7.2"
  },
  "dependencies": {
    "firebase": "^7.3.0",
    "firebaseui": "^4.2.0"
  }
}
```

`index.html`

```html
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Test App</title>
  </head>
  <body>
    <div>Hello world.</div>
    <script src="js/index.ts"></script>
  </body>
</html>

```

My current workaround is downgrading to v4.0.0, but I would like to be on the latest.

**Comment by wti806** [comment]
Can you try to upgrade to the latest version of FirebaseUI?  The issue should be fixed in v4.3 with this PR: https://github.com/firebase/firebaseui-web/pull/623

**Comment by raygesualdo** [comment]
Excellent! I'm away from my work computer for the week but will check on Monday. Thanks!

**Comment by raygesualdo** [comment]
Verified that this works! Thanks!
