### ISSUE TITLE
`Firebase is not defined` js error

### ISSUE THREAD

**Issue by andig** [firebase/firebaseui-web#65]
Probably stupid mistake, but using the sample page and even though `https://www.gstatic.com/firebasejs/ui/live/1.0/firebase-ui-auth.js` loads FireFox says 

    15:04:07.673 ReferenceError: firebase is not defined <anonymous>firebase.html:18

I'm not using `firebase serve` though.

**Comment by TMSCH** [comment]
You need to load the firebase.js library too, and initialize it, usually done by copy pasting the Web Snippet from the Firebase Console into your HTML page.

See [here](https://github.com/firebase/firebaseui-web#starting-the-sign-in-flow) in the `<head>` tags, you have to include the snippet. Please close the issue if this works for you.

**Comment by andig** [comment]
Got it. as expected- so obvious that it hurts, thanks!

**Comment by apanin** [comment]
Make sure that the firebase is being loaded before the function/configuration is being called. If you get the message that firebase is loaded after the error message it means the library is being accessed after.

<img width="645" alt="Screen Shot 2020-03-28 at 12 28 09 PM" src="https://user-images.githubusercontent.com/17930633/77828027-99ea8680-70ef-11ea-9427-b21a0e73a0c0.png">
<img width="815" alt="Screen Shot 2020-03-28 at 12 27 55 PM" src="https://user-images.githubusercontent.com/17930633/77828029-9c4ce080-70ef-11ea-87c8-7aeb46b8feab.png">

**Comment by apanin** [comment]
make sure the library is loaded before your js starts running,
I fixed this by putting the firebase configuration in a function that is called when the body is loaded.
<img width="815" alt="Screen Shot 2020-03-28 at 12 27 55 PM" src="https://user-images.githubusercontent.com/17930633/77828145-17ae9200-70f0-11ea-8b46-7980617bdd22.png">
<img width="636" alt="Screen Shot 2020-03-28 at 12 28 09 PM" src="https://user-images.githubusercontent.com/17930633/77828148-1aa98280-70f0-11ea-9505-c430dd1f5f72.png">

**Comment by ARKS-INDUSTRY** [comment]
thx man this helped me to make my project
