### ISSUE TITLE
Modal created a mask, but don't destroy it after modal is closed.

### ISSUE THREAD

**Issue by FateXRebirth** [firebase/firebaseui-web#650]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Mojave 10.14.6
  * Browser version: Chrome 78.0.3904.108 (Official Build) (64-bit)
  * Firebase UI version: 7.2.3
  * Firebase SDK version: 4.3.0

### [REQUIRED] Describe the problem

Seems like firebaseui created a Modal with a mask, but the mask left in the body of the document after user finishes his task, I mean user close the modal, I think this mask should be destroyed with modal, please let me know if I am wrong.

### Reproduce with Video:
https://drive.google.com/file/d/1OSfSeVxCCq7GHYLYkjxVBdN8JVLQoP0s/view?usp=sharing

**Comment by wti806** [comment]
Can you provide the code of how you create the FirebaseUI in your app? And also, please provide a minimal reproducible example to help us investigate. I don't think firebaseui creates any modal.

**Comment by FateXRebirth** [comment]
Thanks for your response

I use it in the react app, this how I initialize firebaseUI.

![2](https://user-images.githubusercontent.com/11188616/69517890-fea2a280-0f90-11ea-80d8-3e0115f736cb.png)

This is my configuration, nothing special.
![1](https://user-images.githubusercontent.com/11188616/69517824-cdc26d80-0f90-11ea-92b9-6cbb67f5d3c0.png)

But I guess the modal I said was created by reCAPTCHA, the modal appear as long as reCAPTCHA shows up.
![Screen Shot 2019-11-25 at 2 32 03 PM](https://user-images.githubusercontent.com/11188616/69517957-3dd0f380-0f91-11ea-9faa-d8a218cf5654.png)

**Comment by wti806** [comment]
This element is created by the google [recaptcha API ](https://developers.google.com/recaptcha) FirebaseUI depends on. Is this causing any unexpected behaviors?

**Comment by FateXRebirth** [comment]
No, I just wonder if this is bug or any situation you was not expect in the beginning, I think I can close this issue now.
