### ISSUE TITLE
4.3 not found on CDN vs gstatic

### ISSUE THREAD

**Issue by narayananl23** [firebase/firebaseui-web#651]
### [REQUIRED] Describe your environment

  * Operating System version: NA
  * Browser version: NA
  * Firebase UI version: 4.3
  * Firebase SDK version: NA

### [REQUIRED] Describe the problem
 Cound not find 4.3 version on CDN 

#### Relevant Code:
I can find 
https://cdn.firebase.com/libs/firebaseui/4.2.0/firebaseui.css
https://cdn.firebase.com/libs/firebaseui/4.2.0/firebaseui.js
404 for 
https://cdn.firebase.com/libs/firebaseui/4.3.0/firebaseui.css
https://cdn.firebase.com/libs/firebaseui/4.3.0/firebaseui.js

While lastest is in 
https://www.gstatic.com/firebasejs/ui/4.3.0/firebase-ui-auth.css 
https://www.gstatic.com/firebasejs/ui/4.3.0/firebase-ui-auth.js

What should we use 
CDN or gstatic ?

Is there any benefit for gstatic over other ?

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by bojeil-google** [comment]
Hey @narayananl23 going forward, new versions of `firebaseui-web` will only be available via `gstatic`. We are no longer releasing new binaries via `cdn.firebase.com`.

**Comment by akauppi** [comment]
@bojeil-google This can be closed, right?

**Comment by bojeil-google** [comment]
Yeah, I will close it. Thanks for the reminder.

**Comment by ewa-silly** [comment]
Hey, I don't know if there's a different github project that this  _should_ go under, but be aware that the Google AppEngine tutorial code (at least Python37 edition) still gives `cdn.firebase.com` urls for these.

**Comment by bojeil-google** [comment]
Hey @ewa-silly, thanks for notifying us. Can you provide the link to the tutorial? Is it on GitHub?

**Comment by hoedward** [comment]
This part of the GAE Python 3 Quickstart for Adding Firebase has the outdated URLs:
https://cloud.google.com/appengine/docs/standard/python3/building-app/adding-firebase
