### ISSUE TITLE
Language code is not correspond to gulpfile

### ISSUE THREAD

**Issue by FateXRebirth** [firebase/firebaseui-web#653]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Mojave 10.14.6
  * Browser version: Chrome 78.0.3904.108 (Official Build) (64-bit)
  * Firebase UI version: 7.2.3
  * Firebase SDK version: 4.3.0

### [REQUIRED] Describe the problem
I uesd the code in [LANGUAGES.md](https://github.com/firebase/firebaseui-web/blob/master/LANGUAGES.md) corresponding to my language (Chinese) to run npm script 
```javascript
npm run build build-npm-{LANGUAGE_CODE}
```

#### Steps to reproduce:

1. git clone firebaseui-web
2. npm run build build-npm-zh_tw

#### Relevant Code:
```javascript
npm run build build-npm-zh_tw
```

![Screen Shot 2019-11-28 at 2 47 53 PM](https://user-images.githubusercontent.com/11188616/69783580-c8faf500-11ee-11ea-887c-e3d5f35f6409.png)

Until I found this...
![Screen Shot 2019-11-28 at 2 53 52 PM](https://user-images.githubusercontent.com/11188616/69783656-eaf47780-11ee-11ea-9ff6-c8fbc08b4c07.png)
 
is not zh_tw, is zh-TW

**Comment by bojeil-google** [comment]
We will update the documentation to reflect this: https://github.com/firebase/firebaseui-web/pull/654
