### ISSUE TITLE
Recognize sign up from sign in

### ISSUE THREAD

**Issue by RealLankinen** [firebase/firebaseui-web#657]
I use this to sign up / sign in. Right now I only use Google but might add more later. The problem I'm trying to solve is that I want to do one thing if user sign up the first time versus sign in. I use signInSucccessWithAuthResults but seems like there is no way to recognize sign up from sign in at least in that callback. Is there some trick to test if user exists before creating it?

**Comment by bojeil-google** [comment]
`signInSucccessWithAuthResult` triggers with an object `firebaseui.auth.AuthResult` which has the same signature as [`firebase.auth.UserCredential`](https://firebase.google.com/docs/reference/js/firebase.auth.html#usercredential) which includes information on whether the user is new or existing.
