### ISSUE TITLE
Provide sign in button images.

### ISSUE THREAD

**Issue by prenna** [firebase/firebaseui-web#66]
I would like to use the sign in buttons from this. Google's button related branding documentation is excellent, but Facebook and Twitter leave a lot to be desired, and I couldn't find an approved button for GitHub. Could you please provide the buttons used as images?

**Comment by TMSCH** [comment]
Hi, we cannot provide images for these buttons. We actually don't use images, but CSS styling, only the providers icons are images (and you can find them on the respective providers' websites). You can inspect the buttons using the Web Inspector of your browser and mimick the style for your own website (or look at our [source code](https://github.com/firebase/firebaseui-web/blob/master/stylesheet/firebase-ui.css) and see how we do it).
