### ISSUE TITLE
Set Minimum Password Length Firebase Email & Password Authentication

### ISSUE THREAD

**Issue by namsor** [firebase/firebaseui-web#661]
Hi! 

Currently, Firebase will through a FirebaseAuthWeakPasswordException if the password length is less that 6. 

Could additional password rules be configured on the client side, for example if we would like to encore a minimum password length of 8 ? The IT Security team of a client is requesting this minimum password length. 

The minimum password length or custom rules could be specified in Other config options...  
ui.start('#firebaseui-auth-container', {
  signInOptions: [
    // List of OAuth providers supported.
	...
	firebase.auth.EmailAuthProvider.PROVIDER_ID 
  ],
  // Other config options...  
});

Alternatives were discussed in this Stackoverflow thread, but none seems convincing,
https://stackoverflow.com/questions/36318198/set-minimum-password-length-firebase-email-password-authentication

Thanks for considering this enhancement or suggesting an alternative approach,
Elian

**Comment by bojeil-google** [comment]
Hey @namsor, we may consider setting a client side enforcement in firebaseui via some regex. Though the risk is if the user cannot meet the regex requirements, we still need a custom error message to guide the user beyond just a message that the password is too weak.

**Comment by namsor** [comment]
Thank you, yes. The custom error message could be passed along with the regexp.

**Comment by nordknight** [comment]
I'm also interested - will the minimum password length be available for configuration?

**Comment by andrew-mikhailov-zfort** [comment]
Also, please, don't forget about password recovery. Because it should have the same rule.

**Comment by mohiyuddinshaikh** [comment]
> Hey @namsor, we may consider setting a client side enforcement in firebaseui via some regex. Though the risk is if the user cannot meet the regex requirements, we still need a custom error message to guide the user beyond just a message that the password is too weak.

What is the status on this guys?

**Comment by wildkatana** [comment]
Having some kind of built in mechanism to control password regex for firebase authentication would be amazing.

**Comment by luanlucho** [comment]
Please guys, develop this functionality. It could look somethings like these.
```js
const rules = [ 
  {
    rule: "some regex",
    message: "My error message for this rule"
  },
  {
    rule: "some other regex",
    message: "My error message for this rule"
  },
  // ... more rules
];

await firebase.auth().enforcePasswordRules(rules);
```

**Comment by weixifan** [comment]
Hi all, thanks for your input on this feature request! We are unable to promise any timeline for this, but if others also have this request, adding a +1 on this issue can help us prioritize adding this to the roadmap.

Internal tracking bug: b/188591575

**Comment by dangell7** [comment]
A merchant is blocking our registration because we cannot implement a stronger password requirement. I see the work arounds but it would be nice if this was implemented directly.

**Comment by ritenv-remo** [comment]
@weixifan just curious, do we have any new updates on b/188591575?

**Comment by skyyy777** [comment]
+1 I need this too

**Comment by matthieunelmes** [comment]
+1

**Comment by matas-itmoos** [comment]
+1 as it sounds super basic and important

**Comment by nenriquez** [comment]
+1 please add minimum strength also

**Comment by JoshMart** [comment]
+1 
6 characters is a very, very basic starting point for a password. Enabling additional rules around passwords would greatly increase peace of mind while using FirebaseUI.

**Comment by welsh11** [comment]
+1

**Comment by WONDERJEWEL** [comment]
+1

**Comment by turnonsc** [comment]
+1

**Comment by papmodern** [comment]
+1

**Comment by PolVales** [comment]
+1

**Comment by benhxy** [comment]
+1

**Comment by propkitty** [comment]
The current problem of not being able to set a set of rules for passwords is a huge issue for Firebase as far as I'm concerned. We need to be able to program regex rules into FB for our apps.

+1

**Comment by fchu** [comment]
+1

**Comment by dov212** [comment]
+1

**Comment by prameshj** [comment]
This is currently implemented on the Google Cloud Identity Platform backend -  https://cloud.google.com/identity-platform/docs/password-policy

**Comment by hampak** [comment]
+1

**Comment by lowriwyllt** [comment]
+1

**Comment by opolo** [comment]
+1

**Comment by kendra-human** [comment]
+1

**Comment by svetlana-mate** [comment]
+1

**Comment by rachelmyers** [comment]
You can do this via the admin API: https://cloud.google.com/identity-platform/docs/password-policy. We don't have plans to add this to FirebaseUI, although I can imagine something like surfacing error messages being handy. Let us know what you need as you start using this.

**Comment by smlima** [comment]
Yeah, it would be nice to surface the error through FirebaseUI. We're using FirebaseUI for authentication , and we need to meet some minimum requirements in terms of security and password strength is one of those.  So it would be nice to expose that error so that we can set the strength on identity platform , and then show the error on the mobile

**Comment by dennisbcloud** [comment]
+1
