### ISSUE TITLE
SAMLAuthProvider type missing constructor

### ISSUE THREAD

**Issue by mykter** [firebase/firebaseui-web#663]
I think the SAMLAuthProvider requires a type to be passed to it, i.e. the typings are missing this entry:
`    constructor(providerId: string);`

When trying to use it in typescript, you're currently stuck - it won't compile if you provide an ID when creating it, and it crashes if you don't provide one.

**Comment by bojeil-google** [comment]
I think this is missing in the type definitions: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L225
