### ISSUE TITLE
Sign in with Apple flow with logged in macOS or iOS causes blank white screen when user presses cancel

### ISSUE THREAD

**Issue by albertstill** [firebase/firebaseui-web#664]
When iOS or macOS is signed into an Apple account and the user is on Safari the normal web based flow does not occur, instead a native UI pop up from Apple occurs. When clicking cancel in this flow a blank white screen appears and the user is not taken back to the previous screen. To reproduce visit the official demo at https://fir-ui-demo-84a6c.firebaseapp.com with an OS signed into Apple. Below are screen shots from a macOS but iOS does the same thing.

Screen 1 - click sign in with Apple
<img width="723" alt="Screen Shot 2020-01-12 at 7 13 46 pm" src="https://user-images.githubusercontent.com/2787876/72216042-b86cc700-356f-11ea-8d23-94a49a0ac66d.png">

Screen 2 - click cancel
<img width="724" alt="Screen Shot 2020-01-12 at 7 13 55 pm" src="https://user-images.githubusercontent.com/2787876/72216045-c0c50200-356f-11ea-8181-f0861cf78621.png">

Screen 3 -  blank white screen
<img width="719" alt="Screen Shot 2020-01-12 at 7 14 03 pm" src="https://user-images.githubusercontent.com/2787876/72216048-c7537980-356f-11ea-8e07-13a021f0786f.png">

Anyone know how to fix this? It's currently blocking my webview based iOS app from getting approved on the Apple app store.

**Comment by bojeil-google** [comment]
Hey @albertstill thanks for reporting this edge case. It seems that for Safari flows where a user is signed in to the device, Apple is able to intercept the redirect to sign in with Apple ID and show the native UI. I have 2 questions:

1. If you continue sign in, does the flows succeed? Do you get signed in at the end with Firebase? I assume so, but just wanted to confirm.
2. In the cancel flow, we need a mechanism to detect the cancellation so we can redirect back to the app or close the popup. It is not clear if there is a way to detect this as the Apple native UI shown is not a standard web API.

**Comment by bojeil-google** [comment]
Hey @albertstill I forgot to update the thread but from now on, we will show a UI option to cancel if this happens so the user can recover. No need to update the version of your client. This should be automatically picked up.

**Comment by albertstill** [comment]
Fantastic thanks @bojeil-google, as a temp workaround I ended up doing a similar "back to app" button in my native UI but that's great you've sorted, I can remove the hacky code. Cheers
