### ISSUE TITLE
Sign-in with email & password silently fails if account was created using an email link

### ISSUE THREAD

**Issue by micropat** [firebase/firebaseui-web#668]
Environment:
[FirebaseUI Demo](https://fir-ui-demo-84a6c.firebaseapp.com/)

Reproduced in a local environment too:

  * Firebase UI version: 4.4.0
  * Firebase SDK version: 7.7.0

### The problem
Accounts created using the _email link_ method are not given a response when trying to log in using the _email & password_ method.

Under this condition, I'd ideally expect a "Create a password" UI with the option to continue using the _email link_ method.

#### Steps to reproduce:

1. Use FirebaseUI's [email link sign-in](https://fir-ui-demo-84a6c.firebaseapp.com/#recaptcha=normal&emailSignInMethod=emailLink) method.
2. Sign in with email (creating a new account via an email link).
3. Open the emailed link, then sign out.
5. Use FirebaseUI's [email & password sign-in](https://fir-ui-demo-84a6c.firebaseapp.com/#recaptcha=normal&emailSignInMethod=password) method.
6. Enter the email address then press Next.
6. Observe an infinite progress bar. No response. No JavaScript console errors.

**Comment by wti806** [comment]
@micropat Thanks for reporting the issue. We are currently working on a fix and it will be in the next release.

**Comment by marcus7777** [comment]
fixed in v4.5.0?

**Comment by bojeil-google** [comment]
Hey @marcus7777 this should be fixed in [v4.5.0](https://github.com/firebase/firebaseui-web/releases/tag/v4.5.0).
