### ISSUE TITLE
detect that autoUpgradeAnonymousUsers happened?

### ISSUE THREAD

**Issue by jaunt** [firebase/firebaseui-web#686]
When I use autoUpgradeAnonymousUsers, and it works without a conflict, firebase.auth().onAuthStateChanged is not called.  Is there a way I can detect this condition?  In other words, how do I know if a user was auto upgraded or not at signInSuccessWithAuthResult?

**Comment by bojeil-google** [comment]
This is expected `onAuthStateChanged` is triggered when there is a change of users. For upgrade flows, the user (and the user ID) is the same, a linked provider is added to the existing user. You could inspect the authResult object triggered in the callback "signInSuccessWithAuthResult".  `authResult.operationType` will have a value 'link'.

**Comment by jaunt** [comment]
Thank you!  I figured it was as expected, but now you've given me a way to deal with it!  The problem was that I still needed to re-log into my app with the user's real data either way, and so I needed to either hope onAuthStateChanged was called, or do the log-in manually.  Until now I couldn't think of a safe way to decide to log-in manually, since onAuthStateChanged is async.
