### ISSUE TITLE
Cannot see the dismiss button to close the error message

### ISSUE THREAD

**Issue by game-libgdx-unity** [firebase/firebaseui-web#693]
![image](https://user-images.githubusercontent.com/5079800/78746874-2881c200-7992-11ea-9587-36e1e5bbb1fe.png)

I try to login using Facebook, then I cancel it. I returned to firebase app and I saw this error message (very long) and the dismiss button is hidden.

 How can I edit the error message or how to make the dismiss button visible?

Thanks

**Comment by bojeil-google** [comment]
I am not sure how you triggered this flow. I tried it and didn't consent to Facebook. I got the expected message:
![Screen Shot 2020-04-07 at 11 32 49 PM](https://user-images.githubusercontent.com/13474811/78752063-37cc2580-7928-11ea-8ae5-231564f6796b.png)
