### ISSUE TITLE
Enable "Automatic sign in and sign out" for Google One-Tap (Google YOLO)

### ISSUE THREAD

**Issue by brunocrosier** [firebase/firebaseui-web#699]
Google One-Tap allows us to to enable [automatic sign in](https://developers.google.com/identity/one-tap/web/guides/automatic-sign-in-sign-out), however it doesn't seem like FirebaseUI allows the same.

Am I missing something? Is this possible, and if not, could it be possible?

**Comment by bojeil-google** [comment]
FirebaseUI was using a deprecated version of one-tap (no longer usable for new customers). We don't currently support the new version of that service. The old version used to support automatic sign-in via one-tap.

**Comment by brunocrosier** [comment]
Thanks for the reply!

I managed to implement this with a different workaround but it would be great if this was back in FirebaseUI!

**Comment by geekkun** [comment]
Would it be supported ever?

And what's the workaround, @brunocrosier?

**Comment by brunocrosier** [comment]
@geekkun I haven't looked into this for a while but please check out this https://github.com/brunocrosier/google-one-tap
