### ISSUE TITLE
Open source FirebaseUI-web

### ISSUE THREAD

**Issue by Tim15** [firebase/firebaseui-web#7]
I'd love to contribute to development of this widget, but the code is not in this repo. The Android and iOS code is available, but not the web code. Am I looking in the wrong place? Is there a reason why Firebase/Google would open source the Android and iOS code but not the web code?

Thanks,
Tim

**Comment by davidgilbertson** [comment]
"Currently, only the iOS and the android version are open sourced.", apparently according to this: https://github.com/firebase/firebaseui-web/issues/6

**Comment by TMSCH** [comment]
Hi Tim, we're planning to open source FirebaseUI for web soon but we haven't a precise date yet. It will be hosted on this Github repository.

**Comment by Tim15** [comment]
I'm glad you're working on it.

**Comment by pablomoralesm** [comment]
+1

**Comment by serradura** [comment]
Does anyone have any update about this thread?

**Comment by bojeil-google** [comment]
Firebaseui has been open sourced with the launch of firebaseui-web v1.0.
