### ISSUE TITLE
security change rejects login from electron

### ISSUE THREAD

**Issue by David-Asher-Bose** [firebase/firebaseui-web#712]
I'm using firebaseui-web as a login workflow with an electron app. This works great, and it's possible to lock down the browser window so that it's a secure environment for running firebaseui-web (setting BrowserWindow webPreferences nodeIntegration to false). However it seems that Google made a security change recently that rejects browsers under particular conditions. The electron web window doesn't seem to fit any of these criteria, however it is being rejected nonetheless. Does anyone know anything about these security changes, and what action that could be taken on the electron side to enable firebaseui-web again? 
Thanks,
David Asher

**Comment by bojeil-google** [comment]
Hey David, Electron is not an officially supported environment for `firebaseui-web`. What identity providers are you using in this environment?

**Comment by David-Asher-Bose** [comment]
I've had success logging in with Google, Facebook, GitHub, and Twitter. The browser is Chrome, of course, so are you saying that there is a list of Google supported Chrome environments and unsupported Chrome environments?

**Comment by bojeil-google** [comment]
I don't know how you got these providers to work in Electron environment. I don't think the Firebase Auth JS SDK supports `signInWithPopup` or `signInWithRedirect` in these environments.

**Comment by David-Asher-Bose** [comment]
A little more work and I'll open source the code, but it sure would be nice to have Google as an auth provider on this list.
