### ISSUE TITLE
Unexpected keyword const - breaks applications in older browsers that don't support the const ES6 keyword

### ISSUE THREAD

**Issue by jhades** [firebase/firebaseui-web#715]
In older browsers that only support plain ES5, like older Safari versions but still very popular in a lot of iPhone and iPad devices, we get the following error:

"Unexpected keyword 'const'. Const declarations are not supported in strict mode."

This has been tracked down to the presence of the ES6 const keyword, at the very end of the esm.js bundle on the dist folder of the firebaseui dependency:

At the end of the esm.js file we currently find:

const auth = firebaseui.auth;export { auth } ;

If we switch the const to var it fixes the issue.

  * Operating System version: IOs 8.4
  * Browser version: Safari 8
  * Firebase UI version: 4.5.0
  * Firebase SDK version: 6.1.1

**Comment by Rob-ot** [comment]
Here's an older PR with the fix for this. https://github.com/firebase/firebaseui-web/pull/701

It's extremely frustrating that this single `const` breaks support, and they seem unwilling to accept the PR.

**Comment by yuchenshi** [comment]
Fixed by #701
