### ISSUE TITLE
Can't install due to error building node-sass

### ISSUE THREAD

**Issue by InterestedInTechAndCake** [firebase/firebaseui-web#716]
* Operating System version: Debian 9
  * Browser version: n/a
  * Firebase UI version: n/a
  * Firebase SDK version: is this the version I checked out the code base at? If yes - v4.5.0

The problem:

1. git clone https://github.com/firebase/firebaseui-web.git
2. cd firebaseui-web
3. npm install firebase --save
4.
../src/binding.cpp
../src/binding.cpp: In function ‘void MakeCallback(uv_work_t*)’:
../src/binding.cpp:246:39: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is d
     ctx_w->success_callback->Call(0, 0);
                                       ^
In file included from ../src/binding.cpp:1:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/binding.cpp:254:40: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is d
     ctx_w->error_callback->Call(1, argv);
                                        ^
In file included from ../src/binding.cpp:1:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
In file included from ../src/custom_function_bridge.h:7:0,
                 from ../src/sass_context_wrapper.h:9,
                 from ../src/binding.cpp:3:
../src/callback_bridge.h: In instantiation of ‘T CallbackBridge<T, L>::operator()(std::vector<void*>) [with T = Sass_
../src/binding.cpp:19:21:   required from here
../src/callback_bridge.h:111:5: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ns]
     );
     ^

<cut similar warning messages>

binding.target.mk:131: recipe for target 'Release/obj.target/binding/src/create_string.o' failed
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory '$HOME/firebaseui-web/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit ($HOME/firebaseui-web/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.9.0-11-amd64
gyp ERR! command "/usr/bin/node" "$HOME/firebaseui-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-flags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd $HOME/firebaseui-web/node_modules/node-sass
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-osx@20190415.0.0 (node_modules/google-closure
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-osx@20190415.0.0: wantrrent: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/glob-watcher/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by thomasmburke** [comment]
Think these issues are related to https://stackoverflow.com/a/56035814/9586164. I ran into a similar error and ultimately believe it is due to node-sass not having support for node 12 until version 4.12. This repository uses and older version of node-sass as it is a dependency of gulp-sass. 

The solution for the repository owner may just be as simple as upgrading the version of gulp-sass used.

Until this repo sees an update it appears there may be two workarounds. Either downgrade to node version 10 or update the gulp-sass version in the package.json to the latest version before running `npm install` to ensure a newer version of node-sass is pulled in.

**Comment by rosalyntan** [comment]
Filed b/161813849 for internal tracking.

**Comment by BigBoulard** [comment]
any update on this?

**Comment by jhuleatt** [comment]
Fixed by #927
