### ISSUE TITLE
Proposal: improve I18N by passing through languageCode to providers

### ISSUE THREAD

**Issue by momander** [firebase/firebaseui-web#718]
### Background

The FirebaseUI localized widget (https://github.com/firebase/firebaseui-web#localized-widget) works great for a web app built in a single language. A French website can import the French widget, a Portuguese website the Portuguese widget, etc.

### Problem

Developers increasingly want to support more than one language in their web apps. To do so, they typically use one single codebase and change language dynamically. The language of the FirebaseUI localized widget is hard-coded to one particular language, so it can't be changed dynamically. This means that multi-language websites can't use FirebaseUI. (Please correct me if I'm wrong).

But regular FirebaseAuth (not using FirebaseUI) already supports setting the language dynamically for the Google, Facebook, and Twitter providers:

`firebase.auth().languageCode = 'pt';`

### Proposal

It would be very helpful if a developer could set `languageCode` in FirebaseUI, and FirebaseUI simply passed this through to the providers:

```
ui.start('#elementName', {
  signInOptions: [
    {
      provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      languageCode: 'pt',
    },
```

This would not localize the complete FirebaseUI of course, but it would still be a great help to people who use Google, Facebook or Twitter to sign in. And it would hopefully be a quicker fix than re-architecting how FirebaseUI supports languages.

### Did I miss anything?

Perhaps developers can already today combine FirebaseUI with code like

`firebase.auth().languageCode = 'pt';`

I have tried a few different ways and not managed to get it to work. If it works, it would be helpful to document how it's done.

**Comment by bojeil-google** [comment]
We already support localization and we [propagate](https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/authui.js#L512) that to the IdPs like Google.

You can use the [localized binary](https://github.com/firebase/firebaseui-web#localized-widget).

**Comment by momander** [comment]
Yes, I have seen the localized widget. To use it for my web app, which supports 40+ languages, I have to do this:

1. Install and set up Java.
1. Install and set up Python.
1. Set up build pipelines for the 40+ localized versions of the localized widget.
1. Set up conditional importing of the 40+ different version of the FirebaseUI widget.
1. Teach the above to anyone else who wishes to use my open-source project.

It would be easier to use FirebaseUI in a multi-language app if I could do this instead:

1. Set the `languageCode` parameter.

This would not replace the localized widget. It would simply provide an alternate, simpler way to apply I18N. It would hopefully be easy to implement in FirebaseUI, because it would simply pass on the `languageCode` parameter to the auth providers.

**Comment by bojeil-google** [comment]
The translations are built into the binaries (one binary per language). This is the system we use. Encoding 40+ language into one binary is not a feasible solution. This can be done using server side logic.

**Comment by momander** [comment]
Thank you for your response and sorry if I was unclear. I understand that it wouldn't work well to bake 40 languages into a single binary. That is not what I'm proposing.

I propose that a developer using FirebaseUI should be able to set `languageCode`, and that FirebaseUI should simply pass that parameter along to Google/Facebook/Twitter. That way Google/Facebook/Twitter would display their sign-in UI in the correct language, and the developer won't have to build 40 versions of the FirebaseUI binary.
