### ISSUE TITLE
Incognito tab - "This browser is not supported or 3rd party cookies and data may be disabled."

### ISSUE THREAD

**Issue by maxwell8888** [firebase/firebaseui-web#721]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.13.6
  * Browser version: Chrome 83.0.4103.61
  * Firebase UI version: 3.5.2
  * Firebase SDK version: 7.14.0

#### Relevant Code:
```
<script src="/__/firebase/7.14.0/firebase-app.js"></script>
<script src="/__/firebase/7.14.0/firebase-auth.js"></script>
<script src="/__/firebase/init.js"></script>
<script src="https://cdn.firebase.com/libs/firebaseui/3.5.2/firebaseui.js"></script>
<link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/3.5.2/firebaseui.css" />


```javascript
var uiConfig = {
  callbacks: {
    signInSuccessWithAuthResult: signInSuccessWithAuthResult,
  },
  // Will use popup for IDP Providers sign-in flow instead of the default, redirect.
  signInFlow: "popup",
  credentialHelper: firebaseui.auth.CredentialHelper.NONE,
  signInSuccessUrl: "<url-to-redirect-to-on-success>",
  signInOptions: [
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
    {
      provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
      requireDisplayName: false,
    },
  ],
  tosUrl: "<your-tos-url>",
  privacyPolicyUrl: "<your-privacy-policy-url>",
};
ui.start("#firebaseui-auth-container", uiConfig);
```

**Comment by maxwell8888** [comment]
I tried updating to the latest versions of Firebase and Firebase UI (7.15.0 and 4.5.1) and get the same message when trying to sign in (clicking "Sign in with Google" button)

**Comment by bojeil-google** [comment]
`signInWithPopup` and `signInWithRedirect` do not work when 3rd party cookies / data are disabled.

**Comment by maxwell8888** [comment]
Oh, sorry. I was pretty sure I had used incognito to test sign in on different projects. Thanks for the quick reply.

**Comment by maxwell8888** [comment]
Now that I think about it, I am positive I have previously used a Google Chrome incognito tab to test signing in via Firebaseui. Has something changed?

**Comment by bojeil-google** [comment]
It still works (I just tested it on a Mac laptop in a chrome incognito window). I assume you must have disabled 3rd party cookies and site data.

**Comment by maxwell8888** [comment]
Ah, yes that was the problem. I think Chrome 83 changed the default settings to not allow cookies in incognito. I've been having so many problems with auth over the past few weeks, this must be a big contributor to that. Thanks for helping me find the the problem!
