### ISSUE TITLE
OIDC Provider does not return the user information

### ISSUE THREAD

**Issue by ferreiro** [firebase/firebaseui-web#723]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Catalina 10.15.4 (19E287)
  * Browser version: Chrome 83.0.4103
  * Firebase UI version: latest
  * Firebase SDK version: latest

### [REQUIRED] Describe the problem

Hey guys, I'm using this library to connect users using Twitch as the OIDC provider. All the flow is working: I'm able to authorize the app, and I got a user change. However, the user information is completely empty. I don't see the email, displayName...

1. I follow these steps to [configure the provider with GCP Identity Providers](https://cloud.google.com/identity-platform/docs/web/oidc#popup):
![Screen Shot 2020-06-23 at 1 22 33 AM](https://user-images.githubusercontent.com/7242959/85344495-2094e100-b4f0-11ea-8826-fde6afbd1b1c.jpg)

2. Then I went over my React app, and setup a new provider in the following way:
```js
  uiConfig = {
    signInFlow: "popup",
    signInOptions: [
      {
        provider: "oidc.twitch",
        providerName: "Twitch",
        buttonColor: "purple",
        iconUrl: "",
        customParameters: {},
      },
      firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      firebase.auth.EmailAuthProvider.PROVIDER_ID,
    ],
    callbacks: {
      signInSuccessWithAuthResult: () => false,
    },
  };
```
3. Now I go to my UI and click on "login with Twitch". I authorize the app, and the request is resolved successfully.
4. However, when I open the console, I don't see any info for the user (except the userId).

On the contrary, I tried to directly use firebase.auth().signInWithPopup() and it returns me at least the display name, but again not the rest of the info.

What can I do? I researched your issues, as well as on Twitch API but couldn't find anything to fix it.

**Comment by bojeil-google** [comment]
Can you file an issue with [Identity Platform support](https://cloud.google.com/identity-platform/docs/support). You will need to provide information about your project and possible ID tokens for your Twitch provider. Did you try inspecting the `firebase.sign_in_attributes` claim in the ID token we issue? That normally contains the claims of the underlying IdP. It should shed some light on the issue.
