### ISSUE TITLE
Include build of localized JavaScript binaries

### ISSUE THREAD

**Issue by AndreNeves97** [firebase/firebaseui-web#726]
I need to use a localized JavaScript file for pt_br language. In my project, i can't use the files from CDN, therefore, i need to use the build from NPM. However, in NPM I don't have the localized files.

I need the NPM repository contain the localized builds

**Comment by bojeil-google** [comment]
Please read the instructions in the [README](https://github.com/firebase/firebaseui-web#building-firebaseui) on how to build the localized binary.
