### ISSUE TITLE
Oauth elements not centered

### ISSUE THREAD

**Issue by charleywright** [firebase/firebaseui-web#729]
### Describe your environment

  * Operating System version: Ubuntu 20.04 with KDE Plasma
  * Browser version: Chrome
  * Firebase UI version: ^4.5.1
  * Firebase SDK version: ^7.15.0

### Describe the problem
The "signing with" buttons aren't centered, 
![image](https://user-images.githubusercontent.com/46938699/87298484-2e8fbd80-c502-11ea-8fa7-6bab6ee43574.png)

#### Steps to reproduce:
Have a centered login form, and add a firebase UI auto container. The buttons won't be centered

**Comment by bojeil-google** [comment]
You are embedding the UI within your own container. You should be able to override the CSS styles to match yours, including any left margins. That is a better approach as we can't customize our UI to meet the requirements of every container used.
