### ISSUE TITLE
Pass email for emaillLinkSignIn

### ISSUE THREAD

**Issue by GuilhermeBCC** [firebase/firebaseui-web#734]
**Is your feature request related to a problem? Please describe.**
I need to save the email the user entered.

**Describe the solution you'd like**
Pass as a parameter in **emaillLinkSignIn** the email that the user entered.

**Additional context**
See https://firebase.google.com/docs/auth/web/email-link-auth#send_an_authentication_link_to_the_users_email_address

```javascript
firebase.auth().sendSignInLinkToEmail(email, actionCodeSettings)
  .then(function() {
    // The link was successfully sent. Inform the user.
    // Save the email locally so you don't need to ask the user for it again
    // if they open the link on the same device.
    window.localStorage.setItem('emailForSignIn', email);
  })
  .catch(function(error) {
    // Some error occurred, you can inspect the code: error.code
  });
```

**Comment by bojeil-google** [comment]
If the user finishes on the same device, the UI will not prompt for email. This is already the case. You can test it for yourself in our demo app. However, we can't pass the email in the link for security reasons.
