### ISSUE TITLE
Authentication function with firebase does not work with AT&T number in Mexico

### ISSUE THREAD

**Issue by CesarRuiz48** [firebase/firebaseui-web#735]
Any solution for my authentication messages to reach any number in Mexico using firebase and had problems putting an AT&T number does not get the verification code

**Comment by bojeil-google** [comment]
Hey @CesarRuiz48, if you are having issues with SMS message deliveries, please file a ticket with [support](https://firebase.google.com/support). They'll be able to help you out. The repo is for FirebaseUI SDK issues.
