### ISSUE TITLE
Add %DATE% and %TIME% placeholders to passwordless auth email template

### ISSUE THREAD

**Issue by ultraGentle** [firebase/firebaseui-web#742]
**Is your feature request related to a problem? Please describe.**

- The passwordless auth log-in link gets hidden in the "quoted text" section of the email if more than one login email is sent in the same day(ish).  Try it with Gmail.  
- To users, it appears that the link is missing or that the login system is broken.  
- This scenario is quite common, because a user often authenticates on a laptop and then on mobile (for example).

**Describe the solution you'd like**

- The subject line of the email should have a date- and time-stamp.  
- This would prevent messages from being lumped into the same thread, thus preventing the login link from being hidden in quoted/truncated text.  

**Describe alternatives you've considered**

- You can roll your own auth system, but that's a lot of effort to just fix a missing date/time stamp.
- An alternative to date time would be any random, unique identifier, like those sent with SMS (e.g. G-473056).

**Additional context**
The attached picture represents the entirety of the message I receive when re-sending the login link from my app.  

Just `...`.  
![authQuotedText](https://user-images.githubusercontent.com/41548755/90802201-e162f080-e2e4-11ea-84ec-b4663b0a7857.jpg)

**Comment by bojeil-google** [comment]
Hey @ultraGentle, this issue is not specific to FirebaseUI, can you file a [feature request](https://firebase.google.com/support) for it. Thanks.
