### ISSUE TITLE
AuthCredential TypeScript definition missing for GitHub accessToken

### ISSUE THREAD

**Issue by peterpeterparker** [firebase/firebaseui-web#743]
**Is your feature request related to a problem? Please describe.**
According the Firebase Github Auth [documentation](https://firebase.google.com/docs/auth/web/github-auth), the Github `accessToken` can be retrieved as following:

```
const result = await firebase.auth().signInWithPopup(provider);
const token = result.credential.accessToken;
```

Indeed this is working fine but the `firebase.auth.AuthCredential` Typescript definition, returned  as Promise from functions such as `signInWithPopup` or any other signin functions, does not contains/defines the `accessToken`.

**Describe the solution you'd like**
Define the related Typescript definition.

**Describe alternatives you've considered**
Current workaround with a cast to `any`

```
const result = await firebase.auth().signInWithCredential(cred);
console.log('Github token', (result.credential as any).accessToken);
```

**Comment by bojeil-google** [comment]
Well, they don't always return `OAuthCredential`. This is not the case for SAML providers.

**Comment by peterpeterparker** [comment]
I see. Thank you for the feedback.
