### ISSUE TITLE
Federated providers not signing in user after email/link registration

### ISSUE THREAD

**Issue by Miguelmargar** [firebase/firebaseui-web#746]
### Step 2: Describe your environment

  * FirebaseUI Web
  * Firebase/Play Services SDK version:  7.18.0
  * FirebaseUI version: 3.5.2
  * Firebase one account per email.
  
### Step 3: Describe the problem:

Once an email has been registered through the email link, if the user tries to login through a federated provider the popup redirect works well and prompts the user to sign in through an email link. The email is subsequently sent and if clicked an "uncaught I (letter I) error logs in the console. The error message is: credential failed: First argument "token" must be a valid string or a valid object. 

The other way around ie. registering through a provider first then through email link works as intended as well as registering with one provider eg. twitter then trying to sing in with another, eg. github. 

#### Steps to reproduce:

* initialise firebase, then I followed the firebaseUI docs: https://firebase.google.com/docs/auth/web/firebaseui?authuser=0

#### Observed Results:

  * "uncaught I (letter I) error logs in the console. The error message is: credential failed: First argument "token" must be a valid string or a valid object. 
  
#### Expected Results:

  * User to register as with an email/link object to be returned rather than the uncaught error as it happens when 
  * The provider account to be linked to the previous user's email/link that was registered.  
  
#### Relevant Code:
code after my initialisation for firebase:
`<script>
    var uiConfig = {
        callbacks: {
            signInSuccessWithAuthResult: function(authResult, redirectUrl) {
                // User successfully signed in.
                // Return type determines whether we continue the redirect automatically
                // or whether we leave that to developer to handle.
                // return true;
            },
            uiShown: function() {
                // The widget is rendered.
                // Hide the loader.
                document.getElementById('loader').style.display = 'none';
            },
            // signInFailure callback must be provided to handle merge conflicts which
            // occur when an existing credential is linked to an anonymous user.
            signInFailure: function(error) {
                // For merge conflicts, the error.code will be
                // 'firebaseui/anonymous-upgrade-merge-conflict'.
                if (error.code !== 'firebaseui/anonymous-upgrade-merge-conflict') {
                    return Promise.resolve();
                }
                // The credential the user tried to sign in with.
                var cred = error.credential;
                // Copy data from anonymous user to permanent user and delete anonymous
                // user.
                // ...
                // Finish sign-in after data is copied.
                return firebase.auth().signInWithCredential(cred);
            }
        },
        // Will use popup for IDP Providers sign-in flow instead of the default, redirect.
        signInFlow: 'popup',
        credentialHelper: firebaseui.auth.CredentialHelper.NONE,
        autoUpgradeAnonymousUsers: true,
        signInSuccessUrl: '/http://agrilandstaging.local',
        signInOptions: [
            // Leave the lines as is for the providers you want to offer your users.
            {
                provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
                signInMethod: firebase.auth.EmailAuthProvider.EMAIL_LINK_SIGN_IN_METHOD,
                // Allow the user the ability to complete sign-in cross device,
                // including the mobile apps specified in the ActionCodeSettings
                // object below.
                forceSameDevice: false,                
            },
            firebase.auth.GoogleAuthProvider.PROVIDER_ID,
            firebase.auth.FacebookAuthProvider.PROVIDER_ID,
            firebase.auth.TwitterAuthProvider.PROVIDER_ID,
            firebase.auth.GithubAuthProvider.PROVIDER_ID,
        ],
    };

    // Initialize the FirebaseUI Widget using Firebase.
    var ui = new firebaseui.auth.AuthUI(firebase.auth());
    ui.start('#firebaseui-auth-container', uiConfig);

    firebase.auth().onAuthStateChanged(function(user) {
        if (user) {
            console.log(user.displayName);
            console.log(user.email);
            console.log(user.photoURL);
            console.log(user.emailVerified);
            console.log(user.uid);
            user.providerData.forEach(function (profile) {
                console.log("Sign-in provider: " + profile.providerId);
                console.log("  Provider-specific UID: " + profile.uid);
                console.log("  Name: " + profile.displayName);
                console.log("  Email: " + profile.email);
                console.log("  Photo URL: " + profile.photoURL);
            });
            document.getElementById('firebaseLogout').style.display = "block";
            document.getElementById('firebaseui-auth-container').style.display = "none";
        } else {
            document.getElementById('firebaseui-auth-container').style.display = "block";
            document.getElementById('firebaseLogout').style.display = "none";
            console.log('No One Signed In At The Moment');
        }
    });

    function firebaseSignOut() {
        firebase.auth().signOut().then(function() {
            document.getElementById('firebaseLogout').style.display = "none";
            ui.start('#firebaseui-auth-container', uiConfig);
            document.getElementById('firebaseui-auth-container').style.display = "block";
            console.log('Sign Out Successfull');
        }).catch(function(error) {
            console.log('Error when signing out: ', error);
        });
    }

</script>`

**Comment by bojeil-google** [comment]
It is not clear what is happening.
Is this happening on merge conflict? eg. when you call:

`return firebase.auth().signInWithCredential(cred);`

If so, can you inspect the content of `cred`?

**Comment by Miguelmargar** [comment]
I don't think it is even getting to the signInFailure call back function. I've tried to log out the error object where the credential should be and It does not log out. 
The individual steps are as follows:
1- User clicks on the mail "sign in with email" button.
2- User gets an email with a link which correctly signs in the user.
3- User logs out correctly.
4- Same user now tries to sign in with a federated provider eg, twitter or Github.
5- Firebase recognises the same email address but now with a provider not an email link sign in. 
6- Firebase informs the user of this and asks the user to sign in with an email link:
![Screenshot 2020-09-02 at 08 39 48](https://user-images.githubusercontent.com/38430603/91948931-e453dd00-ecf7-11ea-8f90-2665bec23a42.png)
7- When the user clicks the "sign in" button an email with a link is sent and when the link is clicked, it seems that everything goes well until it pops up the website without the user being signed in and the error message showing:
![Screenshot 2020-09-02 at 08 42 33](https://user-images.githubusercontent.com/38430603/91950738-617f5200-ecf8-11ea-81a7-0eb7760bb708.png)
At this point the "loading..." div shows and not the  "#firebaseui-auth-container". Maybe I'm missing a step in between or straight after this?

Thanks for your time and help.

**Comment by bojeil-google** [comment]
I can't recreate it in our [demo app](https://fir-ui-demo-84a6c.firebaseapp.com/).

1. Sign in with email link.
2. Click generated link and sign in is successful.
3. Sign in again but with Twitter using same email.
4. Linking requirement screen shown.
5. Trigger email link sign-in.
6. On completion (link click), Twitter credential linked.
7. Sign in again with Twitter. The sign in is successful.

Note that in all cases, I am clicking the link in the same device where it is generated.

**Comment by Miguelmargar** [comment]
I've tried the the demo app and it's working well. Would I be able to have a look at the demo app's code somewhere?

**Comment by bojeil-google** [comment]
Yeah, it's open sourced: https://github.com/firebase/firebaseui-web/tree/master/demo

**Comment by Miguelmargar** [comment]
Thanks for the link!. I had a look at the code in the link and tried a few different things and the only one that I think may be the issue is:
`'credentialHelper': CLIENT_ID && CLIENT_ID != 'YOUR_OAUTH_CLIENT_ID' ?
        firebaseui.auth.CredentialHelper.GOOGLE_YOLO :
        firebaseui.auth.CredentialHelper.NONE`

Which I don't have in my code. If I remember correctly the credential helper helps with what I'm trying to achieve? When I ad the above code to my code it gives a CLIENT_ID not defined error. Do I need to set it up with google like I set up twitter and facebook providers?

**Comment by bojeil-google** [comment]
I don't think that is related to your issue. Things to consider: make sure you are using the latest firebase/auth library, could be issues in your compilation (if you are using a bundler like webpack or rollup, etc.

**Comment by Miguelmargar** [comment]
Hi Bojeil, as you said I was using the firebaseui version 3.5.2 and replaced it with version 4.6.1 and it's now working. Thank you very much for your help and guidance!

**Comment by bojeil-google** [comment]
Glad my suggestion helped you out, @Miguelmargar .
