### ISSUE TITLE
Please update the following code

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/firebaseui-web#754]
<img width="1680" alt="Screen Shot 2020-09-21 at 8 09 20 PM" src="https://user-images.githubusercontent.com/4000076/93833405-80fa0280-fc46-11ea-94ee-3c61057250be.png">

https://firebase.google.com/docs/auth/web/firebaseui - Number 4 Optional 

It should be  `signInOptions: [` so that there is no error.

**Comment by bojeil-google** [comment]
Hey @JamesVanWaza, thanks for notifying us. I have sent out an internal fix for this. It is in the review process.

**Comment by JamesVanWaza** [comment]
<img width="1374" alt="Screen Shot 2020-09-23 at 6 40 21 PM" src="https://user-images.githubusercontent.com/4000076/94078706-3efac900-fdcc-11ea-9eb8-e7993730a51e.png">

@bojeil-google also update the following it's missing a right closing bracket at the end. 

it should be 
    `if ((firebase.auth().isSignInWithEmailLink(window.location.href))) {
          ui.start('#firebaseui-auth-container', uiConfig);
      }`

**Comment by bojeil-google** [comment]
Thanks, I sent out another fix to remove the unnecessary parenthesis.

**Comment by bojeil-google** [comment]
They should all be fixed now: https://firebase.google.com/docs/auth/web/firebaseui
