### ISSUE TITLE
Cancelling Microsoft permissions renders a low level error message and does not call config signInFailure callback

### ISSUE THREAD

**Issue by shivna-2020** [firebase/firebaseui-web#755]
### [REQUIRED] Describe your environment

  * Operating System version:  Windows 10 Pro 20H2 19042.541
  * Browser version:  Chrome Version 85.0.4183.121 (Official Build) (64-bit)
  * Firebase UI version: 4.6.1
  * Firebase SDK version: 7.19.1

#### Steps to reproduce:

1. Revoke any access permissions for a Microsoft account by visiting: https://myapplications.microsoft.com/
2. Return to the FirebaseUI and click on [Sign in with Microsoft]
3. In the Microsoft Permissions requested dialog box, click on [Cancel]
4. The FirbaseUI will return to the UI screen showing the following error in the place of the buttons:
Error getting verification code from microsoft.com response: error... [Dismiss]

At this time, the expectation is that the signInFailure callback set in the uiConfig should be called.
#### Relevant Code:
        var uiConfig = {
            callbacks: {
                signInSuccessWithAuthResult: function(authResult, redirectUrl) {
                      window.location.reload();
               },
               signInFailure(error) {
                    console.log('signInFailure', error);
                    console.log(firebaseui.auth.AuthUIError);
                }
            },
            signInFlow: 'redirect',
            immediateFederatedRedirect:false,
            signInSuccessUrl: './index.html',
            credentialHelper:firebaseui.auth.CredentialHelper.NONE,
            signInOptions: [
                firebase.auth.GoogleAuthProvider.PROVIDER_ID,
                firebase.auth.EmailAuthProvider.PROVIDER_ID,
                'microsoft.com'
            ],

The signInFailure is not called for the app UI to show a human readable message to the user.

**Comment by bojeil-google** [comment]
This works as expected. We have a similar behavior for other providers when a user rejects consent. The info bar shows the error message to the user. `signInFailure` only triggers when anonymous upgrade fails.

**Comment by shivna-2020** [comment]
![permissions-cancel-screen](https://user-images.githubusercontent.com/66382980/94390531-8ee0e380-0170-11eb-81f7-a184898f98ad.png)

Understood that the signInFailure callback will not be called if the user rejects the consent. The attached screenshot shows the screen when this happens and it is not a good user experience. 

Is there any way we can stop this message being shown and show a simpler message as desired by the web app? Probably have a signInRejectedConsent callback?

**Comment by bojeil-google** [comment]
Ah I see, the error message can definitely be improved. We currently don't have any plans to surface a new callback.

**Comment by bojeil-google** [comment]
This should be fixed in [4.7.1](https://github.com/firebase/firebaseui-web/releases/tag/v4.7.1)
