### ISSUE TITLE
How to integrate sendSignInLinkToEmail() with firebaseui

### ISSUE THREAD

**Issue by willismonroe** [firebase/firebaseui-web#758]
In the Firebase auth docs they show how to save the user's e-mail locally prior to sending them an authentication link (https://firebase.google.com/docs/auth/web/email-link-auth#send_an_authentication_link_to_the_users_email_address).  

You're then able to retrieve this from the localstorage to complete the signin when the user visits the signin link (https://firebase.google.com/docs/auth/web/email-link-auth#complete_sign_in_with_the_email_link).

Firebasui seems to handle sendSignInLinkToEmail() by itself, so I'm not sure when you are supposed to save the user's e-mail locally.

Any help would be appreciated.

**Comment by bojeil-google** [comment]
FirebaseUI handles the end-to-end process for you to sign in users with email links. You just need to set up the configuration correctly as [documented](https://github.com/firebase/firebaseui-web#email-link-authentication).
