### ISSUE TITLE
signInOptions provider fullLabel ignored 

### ISSUE THREAD

**Issue by bidmii** [firebase/firebaseui-web#761]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04
  * Browser version: Chrome Version 85.0.4183.121 (Official Build) (64-bit)
  * Firebase UI version: 7.19.1
  * Firebase SDK version: 7.19.1

When configuring provider options and passing the "fullLabel" attribute I find that it is ignored and the default attributes are applied.

#### Steps to reproduce:

When initialising the UI pass custom provider options specifically "fullLabel". When passing the "fullLabel" I expect it to be rendered however what I find is the default is consistently rendered.

#### Relevant Code:

      self.state.ui.start('#firebaseui-auth-container', {
        signInOptions: [
          {
            provider: window.firebase.auth.GoogleAuthProvider.PROVIDER_ID,
            fullLabel: "Register with $providerName",
          },
        ],
        signInFlow: 'popup',
        signInSuccessUrl: 'https://www.mywebsite.com/',
        tosUrl : 'https://www.mywebsite.com/terms-of-use',
        privacyPolicyUrl: 'https://www.mywebsite.com/privacy-policy',
      });

**Comment by bidmii** [comment]
I upgraded to the newest version and the above issue was resolved.

**Comment by cvoadmin** [comment]
Thanks for the pointer :D
