### ISSUE TITLE
No "cancel" button visible in sign in when credentialHelper set to NONE

### ISSUE THREAD

**Issue by stianl** [firebase/firebaseui-web#768]
I have disabled accountchooser.com by setting credentialHelper to NONE. This removes the CANCEL button from the UI. 
I think the users should still have the option to cancel the sign in/sign up?

Version as tested 4.6.1

```js
var uiConfig = {
    credentialHelper: firebaseui.auth.CredentialHelper.NONE,
    signInOptions: [
        firebase.auth.EmailAuthProvider.PROVIDER_ID
    ],
    callbacks: {
        signInSuccessWithAuthResult: function (authResult, redirectUrl) {
            // User successfully signed in.
            // Return type determines whether we continue the redirect automatically
            // or whether we leave that to developer to handle.
            return true;
        }
    }
};

var ui = new firebaseui.auth.AuthUI(firebase.auth());

signInButton.addEventListener('click', function () {
    ui.start('#firebaseui-auth-container', uiConfig);    
});
```

![image](https://user-images.githubusercontent.com/169642/95918338-e8215780-0dab-11eb-881c-a54eb95e055e.png)

**Comment by bojeil-google** [comment]
If you are only using email provider and no other provider, the cancel button will not show as there is no other screen to go back to.

**Comment by stianl** [comment]
Ok, but it is shown if I don't include the `credentialHelper` option. I don't have anything to "go back to" in this case either...

Alas it's not doing anything except clearing the input field and sending some request to accountchooser.com.

**Comment by bojeil-google** [comment]
Yeah I think back when `accountchooser.com` was supported, going back triggered the `accountchooser.com` flow. This isn't relevant anymore.

**Comment by stianl** [comment]
Ah, I think it's starting to make some sense to me know. 😄 The default option for `credentialHelper` should not really be used at all and will go away/be changed in a later version.

Part of the problem was that I used a button to trigger the `start` function which displays the sign in form. I understand now that this is not how it is intended to be used. The `start` function should be called if the user is not signed in and I should use some other logic to hide/show the UI. Or - I could add another provider which will provide two nice buttons and then "Cancel" will make sense.

Thanks for your swift feedback, @bojeil-google!
