### ISSUE TITLE
Syntax error on example in Readme

### ISSUE THREAD

**Issue by jefferythewind** [firebase/firebaseui-web#77]
In the [example with all parameters used](https://github.com/firebase/FirebaseUI-Web#example-with-all-parameters-used) it seems there is a misplaced bracket.  Inside the `callbacks` object, the `signInSuccess` function is missing the closing bracket after `return true;` and then there is an extra bracket way down after `tosUrl`.

The way it is now, all of the uiConfig parameters are inside the `callbacks` object, which i don't think is supposed to be.

**Comment by bojeil-google** [comment]
Hey Jeffery, thanks for catching that. We will get it fixed soon.

**Comment by jefferythewind** [comment]
Awesome

**Comment by TMSCH** [comment]
Just fixed in my latest PR.

**Comment by jefferythewind** [comment]
@TMSCH unfortunately I think there is still an extra bracket after `tosUrl`:

```
    // Terms of service url.
    tosUrl: '<your-tos-url>'
    }                                       // <-- this one is extra
};
```
