### ISSUE TITLE
Incomplete type definition for signInFailure callback return value (TypeScript)

### ISSUE THREAD

**Issue by apaatsio** [firebase/firebaseui-web#770]
The [documentation](https://github.com/firebase/firebaseui-web#signinfailureerror) says that the valid return type for signInFailure callback is `Promise<void>|void` but the [type definition](https://github.com/firebase/firebaseui-web/blob/master/types/index.d.ts#L27) defines only `Promise<void>`.

### Describe your environment

  * Operating System version: Linux
  * IDE: Visual Studio Code 1.50.1
  * TypeScript: 3.9.7 
  * Firebase UI version: 4.7.0 (via react-firebaseui 4.1.0)
  * Firebase SDK version: 7.24.0

### Steps to reproduce:

Write the following code in IDE:

```typescript
const firebaseUiConfig: firebaseui.auth.Config = {
  callbacks: {
    signInFailure: (error) => {
      console.log("failure");
    },
  }
};
```

#### Expected result: 
No errors.

#### Actual result:
IDE gives error:
```
Type '(error: AuthUIError) => void' is not assignable to type '(error: AuthUIError) => Promise<void>'.
Type 'void' is not assignable to type 'Promise<void>'.ts(2322)
```

**Comment by bojeil-google** [comment]
Thanks for flagging. We will try to fix it by next release.

**Comment by Rafarel** [comment]
Is there a workaround to be able to use the callback?
My Typescript won't compile...
Thanks!

**Comment by apaatsio** [comment]
@Rafarel Just return an empty Promise

```typescript
const firebaseUiConfig: firebaseui.auth.Config = {
  callbacks: {
    signInFailure: (error) => {
      console.log("failure");
      return Promise.resolve();
    },
  }
};
```

**Comment by ckybonist** [comment]
Could we have the return type get defined as `Promise<void> | void`?

**Comment by bojeil-google** [comment]
Oops, this slipped through the cracks. Sorry about that. The fix is merged. We will push the release next week with the fix.
FYI: @xil222
