### ISSUE TITLE
Attempted import error: 'app' is not exported from 'firebase/app' (imported as 'firebase')

### ISSUE THREAD

**Issue by bhkj9999** [firebase/firebaseui-web#771]
### [REQUIRED] Describe your environment

  * Operating System version: __WSL2 Ubuntu___
  * Browser version: _Chrome 86.0.4240____
  * Firebase UI version: __4.7.0___
  * Firebase SDK version: _8.0.0____

### [REQUIRED] Describe the problem
Attempted import error: 'app' is not exported from 'firebase/app' (imported as 'firebase')

```javaScript
`According to the update log of the firebase SDK (version 8.0.0), the way to import firebase SDK should be`
import firebase from 'firebase/app' 
`instead of `
import * as firebase from 'firebase/app'
```
#### Steps to reproduce:
found when importing this package.

**Comment by bhkj9999** [comment]
by the way, under my circumstance, I found this little bug when I am upgrading my site to Next.js Version 10, don't know if this happens in other conditions or not.

**Comment by karen1au** [comment]
I installed the firebaseui bundle through yarn and is still having `import * as` in my esm.js, I already updated to this latest, what else do I need to do?

**Comment by anuradhedilshan** [comment]
Same error on Vue cli ... How can Fix It..

**Comment by bojeil-google** [comment]
This was a breaking change in the firebase-js-sdk. The fix will be released next week. For now, if you are using `firebaseui`, you may need to stick with a version older than 8.0.0.

**Comment by bojeil-google** [comment]
You can also clone the repo and build the binary if you need this urgently.

**Comment by karen1au** [comment]
oh i see, i thought it's included in the latest release, i'll wait for next week :) Thanks!

**Comment by anuradhedilshan** [comment]
thanks

**Comment by bojeil-google** [comment]
This should be now fixed in [4.7.1](https://github.com/firebase/firebaseui-web/releases/tag/v4.7.1). Please let us know if you have any issues with this.

**Comment by fares997** [comment]
Attempted import error: 'auth' is not exported from 'firebase'
help plz

**Comment by DarwinSantos** [comment]
> Error de importación intentado: 'auth' no se exporta desde 'firebase'
> ayuda por favor


First of all I am new but I had the same error, reading a little documentation from the firebase v8 is no longer used

import * as firebase from "firebase/app";
import "firebase/auth";

Currently fix the error with the following
Sorry for my English;



![image](https://user-images.githubusercontent.com/55763569/110159179-5cd74b80-7db8-11eb-89a3-5ad9f791c6a2.png)

**Comment by abhishekpatel946** [comment]
> ### [REQUIRED] Describe your environment
> * Operating System version: **WSL2 Ubuntu**_
> * Browser version: _Chrome 86.0.4240____
> * Firebase UI version: **4.7.0**_
> * Firebase SDK version: _8.0.0____
> 
> ### [REQUIRED] Describe the problem
> Attempted import error: 'app' is not exported from 'firebase/app' (imported as 'firebase')
> 
> ```js
> `According to the update log of the firebase SDK (version 8.0.0), the way to import firebase SDK should be`
> import firebase from 'firebase/app' 
> `instead of `
> import * as firebase from 'firebase/app'
> ```
> 
> #### Steps to reproduce:
> found when importing this package.

```javascript
import firebase from "firebase/app";
import "firebase/performance";
import "firebase/firestore";
import "firebase/auth";

const fireConfig = {
   ....
};

if (!firebase.apps.length) {
  firebase.initializeApp(fireConfig);
}

export const perf = firebase.performance();
export const auth = firebase.auth();
export const db = firebase.firestore();
export default firebase;
```
I did the same thing as mentioned, but no change same error received.
`./src/App.js
Attempted import error: 'auth' is not exported from 'firebase'.`

`firebase --version` 9.8.0
`firebase tools --version` 9.8..0

can you help me pls.

**Comment by lmolteni** [comment]
> > ### [REQUIRED] Describe your environment
> > 
> > * Operating System version: **WSL2 Ubuntu**_
> > * Browser version: _Chrome 86.0.4240____
> > * Firebase UI version: **4.7.0**_
> > * Firebase SDK version: _8.0.0____
> > 
> > ### [REQUIRED] Describe the problem
> > Attempted import error: 'app' is not exported from 'firebase/app' (imported as 'firebase')
> > ```js
> > `According to the update log of the firebase SDK (version 8.0.0), the way to import firebase SDK should be`
> > import firebase from 'firebase/app' 
> > `instead of `
> > import * as firebase from 'firebase/app'
> > ```
> > 
> > 
> > #### Steps to reproduce:
> > found when importing this package.
> 
> ```js
> import firebase from "firebase/app";
> import "firebase/performance";
> import "firebase/firestore";
> import "firebase/auth";
> 
> const fireConfig = {
>    ....
> };
> 
> if (!firebase.apps.length) {
>   firebase.initializeApp(fireConfig);
> }
> 
> export const perf = firebase.performance();
> export const auth = firebase.auth();
> export const db = firebase.firestore();
> export default firebase;
> ```
> 
> I did the same thing as mentioned, but no change same error received.
> `./src/App.js Attempted import error: 'auth' is not exported from 'firebase'.`
> 
> `firebase --version` 9.8.0
> `firebase tools --version` 9.8..0
> 
> can you help me pls.

Did you solved it? I am having the same issue

**Comment by mendrik** [comment]
having same issue with firebase 9.0.0-beta.1
"Attempted import error: 'firebase/app' does not contain a default export (imported as 'firebase')."

when I try to import firebaseui/dist/firebaseui I get the following import:
![image](https://user-images.githubusercontent.com/160805/117586267-cd377b80-b11f-11eb-9a26-f63c61fd8b70.png)

**Comment by Arifur-rahman14** [comment]
same issue....how to solve it?
"Attempted import error: 'initializeApp' is not exported from 'firebase/app' (imported as 'firebase')."

**Comment by abhishekpatel946** [comment]
> > > ### [REQUIRED] Describe your environment
> > > 
> > > * Operating System version: **WSL2 Ubuntu**_
> > > * Browser version: _Chrome 86.0.4240____
> > > * Firebase UI version: **4.7.0**_
> > > * Firebase SDK version: _8.0.0____
> > > 
> > > ### [REQUIRED] Describe the problem
> > > Attempted import error: 'app' is not exported from 'firebase/app' (imported as 'firebase')
> > > ```js
> > > `According to the update log of the firebase SDK (version 8.0.0), the way to import firebase SDK should be`
> > > import firebase from 'firebase/app' 
> > > `instead of `
> > > import * as firebase from 'firebase/app'
> > > ```
> > > 
> > > 
> > > #### Steps to reproduce:
> > > found when importing this package.
> > 
> > 
> > ```js
> > import firebase from "firebase/app";
> > import "firebase/performance";
> > import "firebase/firestore";
> > import "firebase/auth";
> > 
> > const fireConfig = {
> >    ....
> > };
> > 
> > if (!firebase.apps.length) {
> >   firebase.initializeApp(fireConfig);
> > }
> > 
> > export const perf = firebase.performance();
> > export const auth = firebase.auth();
> > export const db = firebase.firestore();
> > export default firebase;
> > ```
> > 
> > 
> > I did the same thing as mentioned, but no change same error received.
> > `./src/App.js Attempted import error: 'auth' is not exported from 'firebase'.`
> > `firebase --version` 9.8.0
> > `firebase tools --version` 9.8..0
> > can you help me pls.
> 
> Did you solved it? I am having the same issue

Yes I change the version of firebase to little bit older and it will work very well for me.
`    "firebase": "^7.24.0",`
If you change your firebase version with above then it will works.

**Comment by lmolteni** [comment]
Hi, can i ask you how to put 2 search results boxes in the same component??

Its for a marketplace. I want to see products and shops in those boxes.
My <ais-instantsearch [config]="config">  is the same fort both, the only
difference i set to distinguish them is setting the distinct parameter to
true or false in the config box:

<ais-configure
*ngIf="query.length <= 0"
[searchParameters]="{
hitsPerPage: 50,
distinct: true,
index: 'posts'
}"
></ais-configure>

But that work when i have a TAB, thaht hides or show different searches but
i dont know how to do that in the same component.

Thanks

I am attaching you an image of what i nedd to do.

Thanks
