### ISSUE TITLE
"updateCurrentUser failed" error on screen, after using 4.7.1 via ES module import

### ISSUE THREAD

**Issue by akauppi** [firebase/firebaseui-web#776]
### Describe your environment

  * Operating System version: macOS 
  * Browser version: Chrome 85
  * Firebase UI version: 4.7.1
  * Firebase SDK version: 8.0.0

### Describe the problem

The ability to `import` as ES module in 4.7.1 is something I have been looking forward to. Bringing it in in my application, I found two problems. This issue describes the more crucial one, which I don't understand and can not find a way around.

After changing my code to use `import` instead of loading via the globals, and signing in with Google account, I see this:

![image](https://user-images.githubusercontent.com/1297734/97973343-98dcae80-1dce-11eb-99f3-efa58cd4c420.png)

I have no idea, where it comes from.

#### Steps to reproduce:

1. Clone https://github.com/akauppi/GroundLevel-es-firebase-app
2. Set up a Firebase project to work against (please read the README, until you can `npm run dev:online`).
3. `npm run dev:online`

Open the browser at http://localhost:3001 and try Google sign-in.

Expected: one should get to the app
Actual: the above error is shown

#### Relevant Code:

Unfortunately, I don't have a minimum reproducing project available. Merely scouting, if other are also seeing this.

**Comment by samhorlbeck** [comment]
Thanks for reaching out--

Is there anything that's logged to the JS console (like a stack trace for example)?

**Comment by akauppi** [comment]
@samhorlbeck I'll have a look for a stack trace. Is there something I should use on the FirebaseUI side, to enable one?

**Comment by bojeil-google** [comment]
The error you are receiving is related to the core [Auth library](https://github.com/firebase/firebase-js-sdk/blob/86971662ccb39ed56dfed6406417dc155e4c2fc2/packages/auth/src/args.js#L384). I would investigate there first.

**Comment by bojeil-google** [comment]
A quick search in your repo seems that you are creating [wrappers or new references](https://github.com/akauppi/GroundLevel-es-firebase-app/blob/832dc7249fd2571f8457220cc1131b1b2a700c18/src/auth/userRef.js#L26) of the user. I suspect that is making the check fail.

**Comment by akauppi** [comment]
So you are saying this is not occurring with others. 

@bojeil-google The wrapping code should not affect Firebase in any way. It has worked before, the only change was bringing ’firebaseui’ via ES import, instead of via globals (`window.firebase` and `window.firebaseui`).

**Comment by bojeil-google** [comment]
The issue is unlikely to be related to firebaseui as I explained in my first comment.

We have not seen any other reports of this issue.

Try changing your [auth import](https://github.com/akauppi/GroundLevel-es-firebase-app/blob/08df866eec89e56db3d4536fa45700cbd6ae8b17/src/pages/SignIn.vue#L38) from `import '@firebase/auth'` to `import 'firebase/auth';`. That worked for us and this matches the firebase guidelines.

**Comment by akauppi** [comment]
I saw your first comment (and appreciate the help). I am simply reporting that importing Firebase and FirebaseUI as browser-native ES modules does not currently work. To me, it does not play a huge role whether the reason is in the auth, the FirebaseUI or their mutual bridging.

>Try changing your auth import from import '@firebase/auth' to import 'firebase/auth';. That worked for us and this matches the firebase guidelines.

That's a good point. I tried it, but it makes no difference. In fact, the latter is just a redirect to the former:

```
$ cat node_modules/firebase/auth/dist/index.esm.js
import '@firebase/auth';
//# sourceMappingURL=index.esm.js.map
```

I'll come back to this, eventually. For a couple of weeks, I likely have other work to do.

**Comment by Scino** [comment]
I have the same problem, in localhost only, using npm [nuxtjs/firebase](https://firebase.nuxtjs.org/service-options/auth) with npm firebase and npm firebaseui.
```
"@nuxtjs/firebase": "^7.1.1",
"firebase": "^8.0.2",
"firebaseui": "^4.7.1",
```
In production it perfectly works.

**Comment by akauppi** [comment]
Have now time to look into this.

@bojeil-google Thank you for your comments.

>We have not seen any other reports of this issue.

I did find the issue discussed in #536 (Dec 2018 - May 2019). 

>Try changing your auth import from import '@firebase/auth' to import 'firebase/auth';. That worked for us and this matches the firebase guidelines.

I did. It doesn't change anything.

**Comment by akauppi** [comment]
Did not find a way to make FirebaseUI live with ES modules.

Instead, wrote my own authentication components which is available as a web component. If anyone is interested, you find it [here](https://github.com/akauppi/aside-keys).

**Comment by beardsleym** [comment]
Same, local not working. Production seems fine.

`"@nuxtjs/firebase": "^7.5.0",
    "firebase": "^8.3.1",
    "firebaseui": "^4.8.0",`

**Comment by boosh** [comment]
I had this problem too. It turned out I had two `package.json` files, one in my repo root, and one in my 'app' directory. Since most of my other app dependencies were in the `package.json` file in my `app` directory, I reinstalled firebase and firebaseui in that directory and deleted `package.json`, `package-lock.json` and `node_modules` from my root directory. This library is now working (with ES6 imports).

**Comment by jmargolisvt** [comment]
I recently updated to firebase 8, and related deps including firebaseui 4.8.1 (I have tried several versions, they all give me this error).  It loads a login box, but when trying to enter creds or create a new user, I get this error:

> updateCurrentUser failed: First argument "user" must be an instance of Firebase User or null.

How can I restore the auth functionality?

firebase.js
```
import firebase from 'firebase/firebase';
import '@firebase/firestore';
import { FIREBASE_CONFIG } from '../keys';

const config = FIREBASE_CONFIG;

export const firebaseApp = firebase.initializeApp(config);
export const db = firebaseApp.firestore();
```

/store/index.js (abbreviated)
```
import firebase from 'firebase/firebase';
import * as firebaseui from 'firebaseui';
import '@firebase/firestore';

// This is our firebaseui configuration object
const uiConfig = ({
	signInSuccessUrl: '',
	signInOptions: [
		firebase.auth.EmailAuthProvider.PROVIDER_ID,
	],
	callbacks: {
		signInSuccessWithAuthResult: authResult => {
			store.dispatch(login(authResult));
		},
	},
});

// This sets up firebaseui
const ui = new firebaseui.auth.AuthUI(firebase.auth());

// This adds firebaseui to the page
export const startFirebaseUI = elementId => {
	ui.start(elementId, uiConfig);
};
```

I have tried solutions suggested in these discussions, but they are not working for me.
https://github.com/firebase/firebaseui-web/issues/536
https://github.com/firebase/firebaseui-web/issues/776

I'm seeing what looks like a valid auth response in the console too.  Here is the `verifyPassword` response:
```
{
  "kind": "identitytoolkit#VerifyPasswordResponse",
  "localId": "VgZWszYv8cYDJLQsIr3YzwcZJ4s1",
  "email": "user@gmail.com",
  "displayName": "My User",
  "idToken": "<<a_long_token>>",
  "registered": true,
  "refreshToken": "<<another_token>>",
  "expiresIn": "3600"
}
```
Here is the getAccountInfo response:
```
{
  "kind": "identitytoolkit#GetAccountInfoResponse",
  "users": [
    {
      "localId": "VgZWszYv8cYDJLQsIr3YzwcZJ4s1",
      "email": "user@gmail.com",
      "displayName": "Me",
      "passwordHash": "<<a hash>>",
      "emailVerified": false,
      "passwordUpdatedAt": 1561313504412,
      "providerUserInfo": [
        {
          "providerId": "password",
          "displayName": "Me",
          "federatedId": "user@gmail.com",
          "email": "user@gmail.com",
          "rawId": "user@gmail.com"
        }
      ],
      "validSince": "1561313504",
      "lastLoginAt": "1627418219738",
      "createdAt": "1561313504412",
      "lastRefreshAt": "2021-07-27T20:36:59.738Z"
    }
  ]
}

```

**Comment by akauppi** [comment]
@jmargolisvt Do you absolutely need to be using FirebaseUI, in your project?

I was surprised that it's not necessary for simple (in my case, Google) social sign-in. As marked in my Jan 28th comment, I then moved away from FirebaseUI. While it may be useful, I think the code base is way too complicated - for example, I don't remember I ever got it to compile on my machine. That's a litmus test for any open source software.

If you need FirebaseUI, I'll be interested to see what responses you get.
