### ISSUE TITLE
Add support for Auth emulator via useEmulator

### ISSUE THREAD

**Issue by c5n8** [firebase/firebaseui-web#778]
**Is your feature request related to a problem? Please describe.**
UI still connect to project server when using auth emulator.

**Describe the solution you'd like**
A way to connect UI to auth emulator.

**Describe alternatives you've considered**
I have modified default auth instance to use emulator, but still failed to make UI use emulator.

**Additional context**
[Related Documentation](https://firebase.google.com/docs/emulator-suite/connect_auth)

**Comment by akauppi** [comment]
This should have been obvious. Could Firebase teams please have a post-mortem about why such information leaks through, and releases are not in sync?

Then again, none of the Changelogs likely state that we should expect firebaseui to be compatible with the auth emulation, do they?

**Comment by samhorlbeck** [comment]
Hi @c5n8 thanks for raising this! We are aware of the issue and we are investigating (b/165671830).

**Comment by samhorlbeck** [comment]
@akauppi -- We released the Auth Emulator BETA just last week. We're really excited about the emulator and we wanted to get it into the hands of customers as quickly as we could, knowing how valuable it can be to a  safe development workflow!🙂 We're currently working on ensuring that the Auth emulator works with FirebaseUI; it has a slightly different release schedule, and releases aren't always aligned with other Firebase SDKs.

**Comment by bojeil-google** [comment]
FirebaseUI cannot currently support the Auth emulator as it creates an internal Auth instance which does not propagate the emulator settings.

**Comment by akauppi** [comment]
@samhorlbeck just a slight nod. I meant no harm. Somehow the mention that Auth Emulator was only beta has escaped me.

**Comment by samhorlbeck** [comment]
@akauppi no worries, that's how I spell "BETA," not meant as emphasis :)

**Comment by jmcdl** [comment]
It's not explicit in the original comment, but am I correct in thinking that @c5n8 is referring to the fact that the useEmulator() method suggested in the linked docs (copied below) appears to be undefined? 

At least when I try to use it in my React app I get a 'useEmulator is not a function' error from webpack.

`firebase.auth().useEmulator('http://localhost:9099/');`

**Comment by samhorlbeck** [comment]
@jmcdl this is a different issue: Firebase UI for Auth does not currently honor the call to `firebase.auth().useEmulator()` though the function is defined properly on `firebase.auth()`. It sounds like you may be using an older version of the SDK that does not have the `useEmulator()` function (it was added quite recently, as in the last month or two, at least for Auth).

If you're still having the issue, please file a bug with the [firebase-js-sdk repo](https://github.com/firebase/firebase-js-sdk).

**Comment by jmcdl** [comment]
@samhorlbeck thank you, you were correct that I wasn't using the latest version of the firebase sdk. Updating the SDK has resolved the error.

**Comment by horizon89** [comment]
Great that I'm not the only being in need of this. Any idea when this might be resolved? Thank you so much for the work that you do. Greatly appreciated.

**Comment by bojeil-google** [comment]
Hey folks, in order to support the emulator in firebaseui, the emulator settings need to be copied from the external auth instance into the temporary internal one.

This can be done [after initialization](https://github.com/firebase/firebaseui-web/blob/7844a2e6cec9c38e59e09459ce3e6dcfddb69406/javascript/widgets/authui.js#L123) of the internal instance.

However, the missing piece is that we need to get the emulator settings from the provided Auth instance and I don't believe that a [getter](https://github.com/firebase/firebase-js-sdk/blob/ddb7993dd7b2fbb1d3c8119b14994782e40373ce/packages/auth/src/auth.js#L354) for this is [exposed](https://github.com/firebase/firebase-js-sdk/blob/ddb7993dd7b2fbb1d3c8119b14994782e40373ce/packages/auth/src/exports_auth.js#L200) yet.

**Comment by cupcakearmy** [comment]
Docs should be more clear. I immagined it would simply work as in the docs. There should be a warning about this here: https://firebase.google.com/docs/emulator-suite/connect_auth

Hope the feature is here soon :)

**Comment by benomatis** [comment]
@cupcakearmy I might be missing something, but I believe what was meant above is that `useEmulator` is not currently working specifically in `firebaseui` (mind the `ui` at the end of the word), which is why this issue is logged here. The linked doc is generally about firebase emulator for auth; I have not tested, but I'm assuming that if you set up auth yourself (NOT using `firebaseui`), you'll probably be able to get it working.

**Comment by cupcakearmy** [comment]
@benomatis yes. Without the UI the Auth emulation works. It's just not mentioned anywhere. So a little temporal warning would be very helpful :)

**Comment by benomatis** [comment]
@cupcakearmy If anywhere, it should probably be mentioned in firebaseui's docs, not the main firebase docs; it's basically a separate product.

**Comment by cupcakearmy** [comment]
Sure. Just somewhere where it's obvious :)

**Comment by ajonp** [comment]
Whew thought I was losing my mind!!

**Comment by QaDeS** [comment]
> FirebaseUI cannot currently readily support the Auth emulator as it creates an internal Auth instance which does not propagate the emulator settings.

Needed this to work now, so I removed the creation of the internal Auth instance just to see what breaks. Nothing did – for all I can say – so I was wondering what this mechanism is/was actually meant for?

Cleaning up to create a pull request in the meanwhile :)

**Comment by brianrodri** [comment]
Spent some time digging through [firebase-js-sdk/packages/auth/src/auth.js](https://github.com/firebase/firebase-js-sdk/blob/c9f379cf7ef2c5938512a45b63008bbb135926ed/packages/auth/src/auth.js) and found that `firebase.auth.Auth` has a `getEmulatorConfig` function ([source](https://github.com/firebase/firebase-js-sdk/blob/c9f379cf7ef2c5938512a45b63008bbb135926ed/packages/auth/src/auth.js#L355-L360)):
```javascript
/**
 * @return {?fireauth.constants.EmulatorSettings}
 */
fireauth.Auth.prototype.getEmulatorConfig = function() {
  return this.emulatorConfig_;
}
```

The `emulatorConfig_` appears to be a simple object with a `url` property ([source](https://github.com/firebase/firebase-js-sdk/blob/c9f379cf7ef2c5938512a45b63008bbb135926ed/packages/auth/src/auth.js#L311-L312)):
```javascript
// Persist the config.
this.emulatorConfig_ = { url };
```

---

Could we fix this issue by copying the `getEmulatorConfig()` value into the internal auth instance?

Assuming #774 is pointing at the right location, maybe after these lines: https://github.com/firebase/firebaseui-web/blob/6525220b5dccdac769692592b79f392aef08ed1b/javascript/widgets/authui.js#L136-L138

We can add:
```javascript
// Change emulator settings to respect the existing configuration.
if (this.tempAuth_.useEmulator && auth.getEmulatorConfig) {
  this.tempAuth_.useEmulator(auth.getEmulatorConfig().url);
}
```

**Comment by bojeil-google** [comment]
Yes `getEmulatorConfig` needs to be [exposed](https://github.com/firebase/firebase-js-sdk/blob/c9f379cf7ef2c5938512a45b63008bbb135926ed/packages/auth/src/exports_auth.js) so it can be call in firebaseui.

**Comment by jQrgen** [comment]
+1, need a fix for this ASAP or stop using this lib

**Comment by cupcakearmy** [comment]
@bojeil-google do you know if there is an estimated ETA on this?

**Comment by bojeil-google** [comment]
@samhorlbeck is currently working on it.

**Comment by chetbox** [comment]
I believe it should now be possible to get the emulator settings with the latest Firebase SDK: https://firebase.google.com/support/release-notes/js#version_824_-_january_21_2021

**Comment by benomatis** [comment]
Looks like it's been added here as well, but not yet released: https://github.com/firebase/firebaseui-web/commit/bb65d4914f95015cc4cc74a6aae3d3358ad37895

**Comment by interactive-web-dev** [comment]
Any approximate ETA on the release date? I'm unfamiliar with how frequently they occur.

**Comment by bojeil-google** [comment]
We are working on it. We discovered another unrelated [issue](https://github.com/firebase/firebaseui-web/issues/806) in the process of the release and we may have to delay the release until the bug is fixed. You can expect this to be out sometime this week or next week.

**Comment by bojeil-google** [comment]
Emulator support should now be available in the latest FirebaseUI-web release.

**Comment by antoinedc** [comment]
I'm still having issues with this. It looks like some requests are sent to the emulator and some are not.
For example, `https://www.googleapis.com/identitytoolkit/v3/relyingparty/createAuthUri?key=xxx` is not proxied through the emulator, same with the signin/signup process requests.

Here is my code:
```javascript
firebase.initializeApp(FIREBASE_CONFIG, 'debug');
var auth = firebase.auth()
auth.useEmulator("http://localhost:9099")
var ui = new firebaseui.auth.AuthUI(auth);
ui.start('#firebaseui-auth-container', {
    signInSuccessUrl: '/transactions',
    signInOptions: [
        {
            provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
            requireDisplayName: false
        }
    ]
});
```

`FIREBASE_CONFIG` contains a dummy apiKey and projectId.

However, if I proceed to login with a live api key and a production account, and then check for `currentUser()`, it seems to go through the emulator: `http://localhost:9099/www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo?key=xxx`, and it (obviously) fails with a 400 USER_NOT_FOUND.
