### ISSUE TITLE
Demo login (redirect or popup) fails

### ISSUE THREAD

**Issue by FunMiles** [firebase/firebaseui-web#779]
I tried to use firebaseui to add a nicer login to my app than what I had done on my own after hitting some issues with iOS pop-up based login from installed PWA fail.
I tried the [demo page with redirect-based login ](https://fir-ui-demo-84a6c.firebaseapp.com/widget#recaptcha=normal&emailSignInMethod=emailLink) and found that it actually fails.

#### Steps to reproduce:
  - Open the demo page ( https://fir-ui-demo-84a6c.firebaseapp.com/widget#recaptcha=normal&emailSignInMethod=emailLink ) in a fresh incognito chrome window. 
  - Chose the login with Google. 
  - Enter email then password on the next page
  - The result is a failed login.

PS: I tried with the popup method and the result is the same.
PPS: Apple login fails in the same way. Anonymous login does succeed.

In visual form, here is what I have:
FirebaseUI login page:
<img width="781" alt="Screen Shot 2020-11-06 at 7 23 54 AM" src="https://user-images.githubusercontent.com/7741038/98377873-92cf1380-2002-11eb-826c-2a0cbfa2cfbf.png">
Redirect for Google login:
<img width="660" alt="Screen Shot 2020-11-06 at 7 25 09 AM" src="https://user-images.githubusercontent.com/7741038/98378013-b98d4a00-2002-11eb-92a0-2695d8c9c885.png">
Result after login:
<img width="665" alt="Screen Shot 2020-11-06 at 7 26 11 AM" src="https://user-images.githubusercontent.com/7741038/98378051-c316b200-2002-11eb-9bf4-8d6c2bffd2f3.png">

**Comment by bojeil-google** [comment]
Hey @FunMiles, the iOS issue seems related to this [known issue](https://github.com/firebase/firebase-js-sdk/issues/77) regarding home screen apps.
For Chrome incognito, [recent versions](https://github.com/firebase/firebase-js-sdk/issues/3004) now disable 3P cookies. Popup sign in is now fixed and should work but redirect sign-in is still a work-in-progress. Note that popup sign-in is not supported in the demo app. (we open the app in a popup but still use redirect flow).
However, popup sign-in won't work for home screen apps.

As these issues are not related to `firebaseui`, I will close it here and you can track in the `firebase-js-sdk` repo.

**Comment by FunMiles** [comment]
Thanks @bojeil-google 
I did see that the incognito was indeed an issue as in some later experiment, however so far, I am not getting the pop up version to do the login properly either. I get a very similar screen to the one above without being given a login interface. I will move my questions to that known issue that you linked.

**Comment by FunMiles** [comment]
Thanks @bojeil-google 
I did see that the incognito was indeed an issue as in some later experiment, however so far, I am not getting the pop up version to do the login properly either. I get a very similar screen to the one above without ever being given a login interface. I cann ot move my questions to that known issue that you linked, since it's limited to current collaborators. It claims it has been fixed but it is not working for me. Is there a demo code that works for a PWA installed in the home-screen on iOS?

**Comment by bojeil-google** [comment]
You can't test signInWithPopup using our demo app in Chrome incognito. Our demo app uses redirect flow. The `popup` selection just opens the sign-in UI window in a popup but sign in is still done via redirect. You have to tweak the demo app to test `signInWithPopup` in incognito by passing the `{signInFlow: 'popup'}` in the UI config.

Unfortunately, I haven't kept track of PWA status for home-screen apps in iOS. Some folks claim redirect flows were working in newer versions but I don't know the latest on that. However, popup will not work in this case.

**Comment by FunMiles** [comment]
Here is some new results @bojeil-google. This might be helpful for anyone who finds this thread.
Contrary to what I found in some other threads, the popup method does NOT work as a `signInFLow` when my PWA is installed on the home screen under iOS. However the redirect method does work. My issue before with the redirect failing was linked with the `npx serve` command that was not serving the home `index.html` when trying to reload a page. The redirect would essentially fail when coming back.
Now my PWA is working as expected for me. 
Would posting an example and my `Node.js/express` based server be useful?

**Comment by bojeil-google** [comment]
Thanks for sharing your findings @FunMiles.

That matches my original understanding regarding PWAs with respect to only redirect flows working in that environment.

If you have a public GitHub repo with an example, feel free to share your link in this thread.
