### ISSUE TITLE
Examples `Unnecessarily quoted property`

### ISSUE THREAD

**Issue by rstormsf** [firebase/firebaseui-web#78]
Is there any solid reason to use quoted properties in examples?

Example:

```
http://eslint.org/docs/rules/quote-props  Unnecessarily quoted property 'signInOptions' found
```

**Comment by TMSCH** [comment]
There's none in that case indeed, thanks for pointing this out. Just fixed.

**Comment by TMSCH** [comment]
Ah my bad, thanks for catching this! I fixed it.
