### ISSUE TITLE
Password UI: user should have to type twice to catch typos

### ISSUE THREAD

**Issue by garyo** [firebase/firebaseui-web#787]
**Is your feature request related to a problem? Please describe.**
The problem is that users often mistype their (hidden) password when first creating their account, and then they are locked out unless they reset it.

**Describe the solution you'd like**
When creating an email/password account, the UI should show two password fields, and require that they match. (This could be optional of course.) The second (confirming) password field would only be shown for new accounts, naturally.

**Describe alternatives you've considered**
Stop using FirebaseUI and roll my own... but FirebaseUI is great!

**Comment by bojeil-google** [comment]
Hey @garyo, we have followed the MDL design pattern. Instead of typing another password for confirmation, we allow users to toggle visibility of the password. This allows developers to toggle visibility to confirm the password without having to type it again which is not ideal for mobile devices.
