### ISSUE TITLE
How to set the language of provider's popup login panel?

### ISSUE THREAD

**Issue by JoJo562** [firebase/firebaseui-web#788]
I am adding the Firebaseui feature to a website.
The website can change different languages.
When clicking the provider such as Facebook, Google, etc, it popup a login panel.
I want to control the content language for the provider's popup login panel.
Is there any feature that can do it?

**Comment by bojeil-google** [comment]
Hey @JoJo562, the language code will be propagated to the federated provider (popup or redirect) when using the localized binary. The instructions for localization are available here:

- Localized [CDN](https://github.com/firebase/firebaseui-web#localized-widget)
- Localized build via [npm](https://github.com/firebase/firebaseui-web#building-firebaseui)

**Comment by JoJo562** [comment]
I try that Google and Facebook are okay, but Apple login also is English when I use "https://www.gstatic.com/firebasejs/ui/4.6.0/firebase-ui-auth__zh_tw.js". Kindly check.

**Comment by bojeil-google** [comment]
I think at the time of launch, Apple didn't publicly document their support for location. It seems that the custom parameter they use is `locale`. I think we can support that.

**Comment by bojeil-google** [comment]
Hmm, we actually already support that in the [core sdk](https://github.com/firebase/firebase-js-sdk/blob/b662f8c0a9890cbdcf53cce7fe01c2a8a52d3d2d/packages/auth/src/idp.js#L137). I tested firebaseui localization in `fr`. However, `zh_tw` does not seem to be supported by Apple sign-in. Perhaps Apple uses a different code for it.

**Comment by JoJo562** [comment]
What localization code I can use?

I tested firebaseui localization in `fr`. it is also not work for Facebook.

**Comment by bojeil-google** [comment]
I documented the steps above. It is likely you are not using it correctly.

**Comment by JoJo562** [comment]
It is work that set up the following code in the `signInOptions` for Facebook and Apple:
`
customParameters: {
                locale: "zh-TW"
            }
`

It solved. Thank you!

**Comment by bojeil-google** [comment]
Ok, glad you solved it @JoJo562 .
