### ISSUE TITLE
'name' is jwt token still not set after signInSuccessWithAuthResult is called

### ISSUE THREAD

**Issue by fchu** [firebase/firebaseui-web#793]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.7 (19H15)
  * Browser version: Version 1.17.75 Chromium: 87.0.4280.88 (Official Build) (x86_64)
  * Firebase UI version: 7.22.0
  * Firebase SDK version: 4.6.1

#### Steps to reproduce:
  1. Display Firebase UI
  1. Have user sign in with email+password, prompting for a First + Last name too, say "Johnny Appleseed"
  1. Redirect to a logged-in page
  1. In the Firebase 'firebaseAuth.onAuthStateChanged' success callback, do the following:
    1. Read user.displayName in the client: it correctly says "Johnny Appleseed"
    1. Set the jwt to user.getIdToken(); [*]
    1. Call the server.
    1. In server, decode the jwt.
    1. Read the field "name" from the decoded jwt.

#### Expected
name is equal to "Johnny Appleseed"

#### Observed
name is absent from the claims.
logging out and logging in again fixes the claim around "name".
Alternatively, in step [*] above, if force is passed as a parameter, name is correctly set on the jwt. 

#### Explanation
At this point the only rational explanation I have is that the trick used by firebaseUI highlighted in this [comment](https://github.com/firebase/firebase-functions/issues/95#issuecomment-325303062) doesn't update the id token automatically, resulting in a jwt being out of sync with what the client see. Recommendation would be to ensure that this token is correctly set as well before triggering onAuthStateChanged

**Comment by bojeil-google** [comment]
This is not a firebaseui issue. We don't force token update on profile update. You can call `user.getIdToken(true)` after sign-in and that should solve it.
