### ISSUE TITLE
firebase.auth.[ThirdPartyAuth] does not exist on type '() => Auth'. 

### ISSUE THREAD

**Issue by dwidjaja945** [firebase/firebaseui-web#796]
### Environment

  * Operating System version: macOS Big Sur 11.1
  * Browser version: FireFox 84.0.1
  * Firebase UI version: 4.7.1
  * Firebase SDK version: 8.2.1
  * React: 17.0.1
  * Typescript: 4.1.3

### Problem
When creating config for `firebaseui`, `firebase.auth.GoogleAuthProvider` or property off of `auth` does not exist. 
I did not test directly with a ReactJS project, but I would hypothesize that it would work as so far, it seems to be a type issue.

Error:
<img width="814" alt="Screen Shot 2020-12-31 at 2 34 47 PM" src="https://user-images.githubusercontent.com/33010823/103427353-5e488580-4b75-11eb-9e31-01cf86a32349.png">

<img width="361" alt="Screen Shot 2020-12-31 at 2 36 13 PM" src="https://user-images.githubusercontent.com/33010823/103427378-8a640680-4b75-11eb-98be-2367264748f8.png">

What is odd is that I do not get any type errors in my text editor.

#### Steps to reproduce:
I followed the steps on the firebaseui docs, but I imported the modules rather than require.

```
import firebase from 'firebase';
import firebaseui from 'firebaseui';
```

I also have my firebase app configured in a separate file:
<img width="616" alt="Screen Shot 2020-12-31 at 2 41 35 PM" src="https://user-images.githubusercontent.com/33010823/103427518-61904100-4b76-11eb-9250-39c594fe4500.png">

When debugging, I do not see the values of the AuthProviders directly on the `auth` property, but I can view them if I dig into the `firebase.firebase_.auth`

**Comment by bojeil-google** [comment]
Hey @dwidjaja945 you seem to provide conflicting snippets on how you import `firebase`, are you importing it as follows?
```
import firebase from 'firebase/app';
import 'firebase/auth';
import * as firebaseui from 'firebaseui';
```

**Comment by dwidjaja945** [comment]
Hi @bojeil-google , Thanks for getting back to me. I managed to fix my issue. I created the config, but my app wasn't initializing it. But yes, by importing how you demonstrated was how I ended up importing and it now works~

If anyone runs into the same issue, my solution was to create a `FirebaseContext` which would provide the initialized firebase instance to the rest of the app.

```
const config = {...};
const FirebaseContext = React.createContext();
const FirebaseProvider = (props): JSX.Element => {
    // ...
    const firebaseApp = firebase.initializeApp(config);
    return (
        <FirebaseContext.Provider value={{firebase: firebaseApp}}>
            {props.children}
        </FirebaseContext.Provider>
    );
};
```
As long as the component I was working on was within this provider, `firebase.auth[ThirdPartyAuth]`would be properly defined.

**Comment by bojeil-google** [comment]
Thanks @dwidjaja945.
