### ISSUE TITLE
Firebaseui-web does not do automatic account linking

### ISSUE THREAD

**Issue by ssijak** [firebase/firebaseui-web#798]
### [REQUIRED] Describe your environment

  * Operating System version: all
  * Browser version: all
  * Firebase UI version: 4.1.0
  * Firebase SDK version: 8.2.1

Firebaseui-web does not do automatic account linking, it just prompts me to log in with the provider I logged in in the first place. So even if I am logged in with for example Google, then show the firebaseui and click the Sign in with Twitter button (same emails), it does not link the account but prompts me to log in with Google, and when I do, the account is still not linked. I see in several places in the docs that linking is mentioned, and by Google devs in the issues that this should work, but for me, it does not and I do not see a way to configure this?

**Comment by bojeil-google** [comment]
Hey @ssijak, this is how auto-linking works.

- Create account with google using email A
- Sign in with unverified provider (Twitter) using email A
- Auth service detects existing account with Google
- Verify the same use owns google account
- Prompt use to sign in with google using the same email A
- Link Twitter credential to the account
- The user can now sign in using either provider for the email A.

It is possible that when you sign in with Google, you switch to a different email. When that happens, the linking will not occur.

**Comment by bojeil-google** [comment]
Thanks for sharing your thoughts and glad this worked for you. For the most of it, we haven't heard any complaints about the messaging but we will take your suggestion on clarifying it into account.
