### ISSUE TITLE
Ability to add pattern, min, and max attributes to input fields 

### ISSUE THREAD

**Issue by andrewpat24** [firebase/firebaseui-web#799]
**Is your feature request related to a problem? Please describe.**

The phone number and verification code input fields could use a little more customization.

It would be nice if we could write our own input masks or patterns. Instead of phone numbers looking like this: 0987654321, they can look like this: (098) 765-4321. It would also be nice so we could limit the inputs to only numbers, because we can put letters in the verification or phone number fields. 

Additionally, you can enter more than 6 numbers into the verification code input field, even though an error does pop up automatically if you write in more than 6 numbers, it would be nice if we can limit the maximum number of characters in the verification code field. 

**Describe the solution you'd like**
I'd like the ability to inject our own input mask patterns, min and max characters, and input types into the input fields as additional parameters. 

**Describe alternatives you've considered**
Overriding css doesn't allow you to set an input mask or limit the input. 
https://stackoverflow.com/questions/13484291/how-to-limit-input-text-length-using-css3

**Comment by strom2357** [comment]
Hey @andrewpat24 ,  thanks for bringing this up.  Since this isn’t a request we hear too often we’re not able to prioritize making this change on our side, but another workaround could be to modify these input elements with custom js code or, if you’d like, to fork this repo and make a change there.
