### ISSUE TITLE
Missing information of localized build for Typescript users. 

### ISSUE THREAD

**Issue by ferrywlto** [firebase/firebaseui-web#815]
In our project we are using **Typescript** with **Vue** and need to support **Traditional Chinese** language (`zh-TW`) locale. Since Typescript requires type checking to work. Dynamically create and append script tag to load the localized version is not an option. Therefore we need to pull the repo and build by our own. Following the `README.md` doesn't work for us, with `firebaseui__zh_tw.js` and `npm__zh_tw.js`, the UI were still in **English** (`en`), when inspected the element was still look like this:

<pre>
&lt;div id="firebase-auth-container" lang="en"&gt;
</pre> 

After a few hours of trial and error we find that `esm.js` was the file we actually needed to be localized. However the `README.md` didn't mention we can instead build the localized version of `esm.js` via `yarn build build-esm-zh-tw` as well. I think this information will help both the new user of **firebaseui** and **TypeScript** a lot.

Would the repo owner mind I do a PR to update the `README.md` with steps on how I successfully build, import and use the localized version?

Below is my successful screenshot:
![image](https://user-images.githubusercontent.com/8111089/107602080-75de5800-6c63-11eb-8eaa-90933afcedbc.png)
![image](https://user-images.githubusercontent.com/8111089/107602118-7c6ccf80-6c63-11eb-86c4-ae7c90f2d6d4.png)

**Comment by bojeil-google** [comment]
Thanks, @ferrywlto, feel free to send a PR to update the `README` file with the additional instructions.

**Comment by brayce1996** [comment]
I follow [the removed instruction](https://github.com/firebase/firebaseui-web/pull/816/commits/5a6cbccd235b38dbea78aa16f8e62432c7a57b8a)
It works! Thanks a lot @ferrywlto !
