### ISSUE TITLE
Is there  Sign Up using Email/Password option avvailable ?

### ISSUE THREAD

**Issue by udithv** [firebase/firebaseui-web#817]
I noticed there is only a signin option available for the email/password. it would be  nice to have a signup option available to the user when they are logging in. 

I propose a Signup with email and password button be available in the UI. which the users can use to signup.

**Comment by bojeil-google** [comment]
This is a duplicate of https://github.com/firebase/firebaseui-web/issues/665#issuecomment-754835197
