### ISSUE TITLE
images/buffer.svg CSS dependency

### ISSUE THREAD

**Issue by adriancretu** [firebase/firebaseui-web#82]
While the user is logging in, there is a period of time before the final redirect, where the Firebase UI component does not render anything, assumingly finalizing the authentication.

During this time a request is made by the browser for the "images/buffer.svg?embed" resource. After some digging, I saw that it's referenced only in the minified build of firebase-ui.css, as some mask for a material design element (maybe a loading state?).

Is this a known issue?

**Comment by andlcool** [comment]
also noticed the same behaviour.

**Comment by 8enmann** [comment]
Ping

**Comment by timothyasp** [comment]
Looks like it's from the [material-design-lite](https://github.com/google/material-design-lite) library from google.  

https://github.com/google/material-design-lite/blob/mdl-1.x/src/images/buffer.svg

**Comment by ishandutta2007** [comment]
This is what I get:

GET http://localhost:4200/images/buffer.svg?embed 404 (Not Found)
![screen shot 2017-11-27 at 4 10 47 am](https://user-images.githubusercontent.com/2527354/33245104-3310a1b2-d329-11e7-926c-e97d1b4b5590.png)

**Comment by thapeloseema** [comment]
Did anyone get a work-around for this issue ?

**Comment by kdubau** [comment]
ping? anyone on the firebase team?

**Comment by MuizNadeem** [comment]
I no longer see this error in the console after commenting URL reference in firebaseui.css file. Am not sure if this is allowed under the license though.

@supports (-webkit-appearance:none) {
    .mdl-progress:not(.mdl-progress--indeterminate):not(.mdl-progress--indeterminate)>.auxbar,
    .mdl-progress:not(.mdl-progress__indeterminate):not(.mdl-progress__indeterminate)>.auxbar {
        background-image: linear-gradient(to right, rgba(255, 255, 255, .7), rgba(255, 255, 255, .7)), linear-gradient(to right, #3f51b5, #3f51b5);

        /* mask: url(/images/buffer.svg?embed) */

    }
}

**Comment by MidnightWonderer** [comment]
A year passed! I just open a pull request addressing this issue.  
https://github.com/firebase/firebaseui-web/pull/457  
Hope you guys are still there.  
MDC is quite ready now Google discontinued MDL for quite some time.  
Hope there is a plan to migrate.

**Comment by nicolasgarnier** [comment]
CL was merged!
