### ISSUE TITLE
CDN error - firebaseui is not defined

### ISSUE THREAD

**Issue by michaelkostal** [firebase/firebaseui-web#824]
With the basic firebase and firebaseui configs, I get this error when only including the following:

```
<script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-app.js"></script>
<!-- SDKs for Firebase products 
    https://firebase.google.com/docs/web/setup#available-libraries -->   
<script src="https://www.gstatic.com/firebasejs/ui/4.7.3/firebase-ui-auth.js"></script>
```

However, everything works as intended when I add the following firebaseui.js (from another tutorial) 

```
<script src="https://cdn.firebase.com/libs/firebaseui/3.5.2/firebaseui.js"></script>
```

Is there an issue with the script, or the documentation? Should I need to include firebaseui.js?

**Comment by bojeil-google** [comment]
`cdn.firebase.com` is no longer used in FirebaseUI. Please switch to the `gstatic` one. The `README` file should provide more clarity on this.

**Comment by michaelkostal** [comment]
Thank you. The readme doesn't include a cdn reference to firebaseui.js, only firebase-ui-auth.js.

Without firebaseui.js the authentication script fails.

**Comment by michaelkostal** [comment]
Sorry about that, I was conflating firebase-auth and firebase-ui-auth
