### ISSUE TITLE
npm install fails with ENOENT when "rename dialog-polyfill"

### ISSUE THREAD

**Issue by Cyclodex** [firebase/firebaseui-web#830]
### Describe your environment

  * Operating System version: Windows 10 Pro Version 2004
  * Browser version: doen't matter its CLI
  * Firebase UI version: 4.8.0
  * Firebase SDK version: 8.3.1
  * Node: v14.15.1
  * NPM: 6.14.8

### Describe the problem

Fresh/clean  setup
Can't install firebaseui with `npm install firebaseui`, fails 

#### Steps to reproduce:
When installing firebaseui with `npm install firebaseui --save` the install process stopped with following output:

```
PS D:\webproject> npm install firebaseui --save
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\webproject\node_modules\jest-haste-map\node_modules\fsevents' -> 'D:\webproject\node_modules\jest-haste-map\node_modules\.fsevents.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\webproject\node_modules\watchpack-chokidar2\node_modules\fsevents' -> 'D:\webproject\node_modules\watchpack-chokidar2\node_modules\.fsevents.DELETE'

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path D:\webproject\node_modules\dialog-polyfill
npm ERR! dest D:\webproject\node_modules\.dialog-polyfill.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\webproject\node_modules\dialog-polyfill' -> 'D:\webproject\node_modules\.dialog-polyfill.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### Analysing

Checking my `node_modules`, there is no such `dialog-polyfill`, checking also with `npm ls`.
Why does it want to rename it / remove it when it is not there?

### Temporary solution

When it wants to rename something, lets put it there first :)

* I installed this package `npm install dialog-polyfill`.
* Then I installed firebaseui
* Now it worked - because it probably renamed this projects...

But why? :)

### How to fix the problem
Should the install maybe check before if it should really rename this project, when it is not existing

**Comment by yuchenshi** [comment]
I cannot reproduce this on my end. This looks like an issue with `npm` though. Please file a bug with `npm` and include `npm-debug.log`.
