### ISSUE TITLE
Microsoft - Support "accounts in this organizational directory only" 

### ISSUE THREAD

**Issue by p8952** [firebase/firebaseui-web#833]
When using Microsoft for Authentication, I need support limiting Authentication to a single Organizational Directory

According to the Documentation this is done via setting "accounts in this organizational directory only" when registering the application: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

However when this is set and Firebase UI is used an error is raised:

```
error_description=AADSTS50194: Application 'adef8cd0-ebfa-48e7-b86e-969c5422daf1'(APP-NAME) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
```

This seems to be a known issue, although the workaround documented here no longer seems to work: https://stackoverflow.com/questions/55807677/microsoft-single-tenant-authentication-with-firebase

The only way to make Authentication work is to set "accounts in any organizational directory" when when registering the application, however when this is done I can see no way of determining which Organizational Directory the Authenticated User is from

1) Is there a way to only allow Authentication from a single Organizational Directory?

2) If not, is there a way of determining which Organizational Directory the Authenticated User is from, so I can use an allow-list at the App level to control access?

**Comment by bojeil-google** [comment]
As far as I know the solution documented [here](https://firebase.google.com/docs/auth/web/microsoft-oauth#handle_the_sign-in_flow_with_the_firebase_sdk) is the way to sign in from a particular Azure AD tenant.

```
provider.setCustomParameters({
  // Optional "tenant" parameter in case you are using an Azure AD tenant.
  // eg. '8eaef023-2b34-4da1-9baa-8bc8c9d6a490' or 'contoso.onmicrosoft.com'
  // or "common" for tenant-independent tokens.
  // The default value is "common".
  tenant: 'TENANT_ID'
})
```

You would need to pass in FirebaseUI via:
```
ui.start('#firebaseui-auth-container', {
  signInOptions: [
    {
      provider: 'microsoft.com',
      providerName: 'Microsoft',
      customParameters: {
        tenant: 'TENANT_ID'
      }
    }
  ]
});
```

If this doesn't work, please reach out to [Firebase support](https://firebase.google.com/support).

**Comment by p8952** [comment]
Thanks @bojeil-google, I was just setting tenant directly under signInOptions, not under customParameters, that does work

**Comment by bojeil-google** [comment]
Cool, glad it worked and thanks for confirming.
