### ISSUE TITLE
How to catch 'auth/admin-restricted-operation' after disable 'sign-up' at Identity Platform

### ISSUE THREAD

**Issue by eosca** [firebase/firebaseui-web#841]
Hello, following the docs ('Configure Email Provider' section) I unchecked 'Enable create (sign-up)' checkbox (Identity Platform - Settings - User actions) in order to disallow users the sign-up action. 

Everything ok, users can not sign-up. But I'd want to catch the error to avoid the default popup (message: 'This operation is restricted to administrators only.  Dismiss')... Google Cloud Identity Platform [docs](https://cloud.google.com/identity-platform/docs/concepts-manage-users?authuser=1&_ga=2.2653363.-2010310589.1618683759#user_self-service) indicates that:

"_If an end-user attempts to create or delete an account within your system, the Identity Platform service will return an error code: auth/admin-restricted-operation for Web API calls, or ERROR_ADMIN_RESTRICTED_OPERATION for Android and iOS. You should gracefully handle the error on your front-end by asking the user to take the appropriate actions for your service._"

But I do not know if I could catch this error using firebaseui... and change the default popup. The try catch in my code is catching nothing at all...

```
try {

      let ui = firebaseui.auth.AuthUI.getInstance()
      if (!ui) {
        ui = new firebaseui.auth.AuthUI(this.$fb.auth())
      }
      ui.start('#firebaseui-auth-container', uiConfig)
      if (ui.isPendingRedirect()) {
        ui.start('#firebaseui-auth-container', uiConfig)
      }
    } catch (error) {
      console.error('AuthV2 - error:', error)
    }
```
I suppose I have to catch that error in other place... Any indication? Thanks!

**Comment by bojeil-google** [comment]
Hey @eosca, you cannot catch the error. We currently handle the error by popping up the info bar and then stop it from propagation. Can you provide more information on how you want to handle the error?

Have you considered using `disableSignUp.status` and setting that to `true` for [email providers](https://github.com/firebase/firebaseui-web#configure-email-provider)? This will show a dedicated error screen and you can provide additional customization (Admin contact email and help link).

**Comment by eosca** [comment]
Hello @bojeil-google, thanks for your response.

I want to handle the error in order to indicate the user that he can not access because only users with an account can access. And indicate (redirect) him that the right way to sign-up is in other section (because I need more information about the user that only email and password for the nature of the app, I collect that info with a form and then I create the user with cloud function and admin sdk). 

I am using `disableSignUp.status` with the first sign-in option (email and password), but I also have Google provider sign-in option and in this case there is no `disableSignUp.status`, the option I chose to disallow users sign-up was to activate Google Cloud Identity Platform and uncheck 'Enable create (sign-up)'  (following the docs indications).

And now users can not sign-up (in the sign-in section), as I wanted, but users need a feedback to indicate them what happens (_you can not access because you don't have an account_) and what to do (_you have to go to sign-up section in order to get an account_). If they try to sign-up from option 1 (email and password), `disableSignUp` property  allows me to indicate an `adminEmail` and `helpLink` to show users the right way to sign-up. But option 2 (Google provider) shows a default popup with the message 'This operation is restricted to administrators only. Dismiss'... and this is an unfriendly message for the user... I am trying to catch this error in order to indicate the user that he does not have an account and the right way to get one.

Thanks for your help!

**Comment by bojeil-google** [comment]
Thanks for explaining, @eosca. It's a valid use case. We'll investigate a solution for this. Exposing the error is one option but we would then need to figure out which other errors to expose and which we don't (based on whether the error is recoverable or not and that can be subjective). Maybe we can find a similar solution to `disableSignUp.status` for other providers.

**Comment by VicSmith** [comment]
> Thanks for explaining, @eosca. It's a valid use case. We'll investigate a solution for this. Exposing the error is one option but we would then need to figure out which other errors to expose and which we don't (based on whether the error is recoverable or not and that can be subjective). Maybe we can find a similar solution to `disableSignUp.status` for other providers.


**THANK YOU**
@bojeil-google :  I am currently using `disableSignUp.status` for email and am really grateful that that was put in recently.
My usecase is very similar to @eosca ...  Any way to disableSignUp.status for all other providers in addition to email would really help.   

Here is my Usecase:

1. Sales Page has sign up form requiring email address and credit card.
2. Once credit card clears, use Firebase Admin SDK to set up an account ( this solution is pay to play ).
3. After the user logs in the first time, when session timeout happens, I redirect to the Firebase UI page for EXISTING users only to log-in.
4. All Account matches are done on email address.
5. Currently if someone signs-in using other providers other than email and there is no subscription match on the email... I send them an email with a notice that they don't have a subscription.  I would like to eliminate this confusion.

**Comment by xil222** [comment]
There is a new feature in recent release v4.8.1 adding a field adminRestrictedOperation in Uiconfig which can meet this requirement:
```
var uiConfig = {
        ...
        'signInOptions': [
          {
            provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
            // Required to enable ID token credentials for this provider.
            clientId: CLIENT_ID
          },
          {
            provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
            signInMethod: getEmailSignInMethod(),
            disableSignUp: {
              status: getDisableSignUpStatus()
            }
          },
        ],
        ...
        'adminRestrictedOperation': {
          status: getAdminRestrictedOperationStatus()
        }
      };
```
