### ISSUE TITLE
Firebase-ui-auth suddenly fails with generic 'network error'

### ISSUE THREAD

**Issue by mogwely** [firebase/firebaseui-web#844]
### [REQUIRED] Describe your environment

  * Operating System version: mac OS 10.14.3
  * Browser version: chrome 90.0.4430.93
  * Firebase UI version: 4.8.0
  * Firebase SDK version: 8.4.1

### [REQUIRED] Describe the problem
Im using Firebase-ui-auth on my website with google sign in and it fails for a lot of my users with a generic 'Network Error'.
Upon clicking the 'sign in with google' button, the sign in popup appears but it's blank. It stays on loading for some seconds then it disappears (looks like it times out). 
This is a screenshot of the failing request on the console network tab:
<img width="1127" alt="Screenshot 2021-04-28 at 16 08 41" src="https://user-images.githubusercontent.com/6021722/116418377-5efbda80-a83c-11eb-912d-2a03ad864e31.png">

Some users would report that it won't work for them then a few days later the problem resolves on its own, then happens again for other users. Inconsistent behavior and doesn't follow a pattern.
Now suddenly I could reproduce the problem on my testing machine without changing anything.
Strange enough this error disappears if i connected through a vpn or mobile internet, but on wifi I will always get this error.
My internet connection is fast and stable. Same error is happening to thousands of users with stable internet connections.
Navigator.online is true. Please help as this is on production.

This is the error stack:

```
  Uncaught Error: Network Error @  iframewrapper.js:124
-- | -- | -- | --
  | setTimeout (async) |   |  
  | se | @ | nexttick.js:33
  | (anonymous) | @ | promise.js:1269
  | le | @ | run.js:124
  | Promise.then (async) |   |  
  | ie | @ | run.js:55
  | ue | @ | run.js:34
  | Ne | @ | promise.js:1029
  | ke | @ | promise.js:921
  | (anonymous) | @ | promise.js:185
  | (anonymous) | @ | iframewrapper.js:124
  | setTimeout (async) |   |  
  | (anonymous) | @ | iframewrapper.js:123
  | (anonymous) | @ | cb=gapi.loaded_0:253
  | e.lr | @ | cb=gapi.loaded_0:218
  | Rk | @ | cb=gapi.loaded_0:221
  | Mk | @ | cb=gapi.loaded_0:221
  | _.xk.Yt | @ | cb=gapi.loaded_0:221
  | wk | @ | cb=gapi.loaded_0:213
  | Promise.then (async) |   |  
  | rk | @ | cb=gapi.loaded_0:213
  | _.vk | @ | cb=gapi.loaded_0:213
  | Nk | @ | cb=gapi.loaded_0:220
  | _.xk.Zg | @ | cb=gapi.loaded_0:219
  | (anonymous) | @ | cb=gapi.loaded_0:214
  | _.Nm.open | @ | cb=gapi.loaded_0:288
  | (anonymous) | @ | iframewrapper.js:138
  | fe | @ | promise.js:163
  | (anonymous) | @ | iframewrapper.js:111
  | e.g | @ | promise.js:826
  | Ce | @ | promise.js:1166
  | Oe | @ | promise.js:1140
  | t.gc | @ | promise.js:1111
  | le | @ | run.js:124
  | Promise.then (async) |   |  
  | ie | @ | run.js:55
  | ue | @ | run.js:34
  | Ne | @ | promise.js:1029
  | ke | @ | promise.js:921
  | (anonymous) | @ | promise.js:167
  | (anonymous) | @ | api.js?onload=__iframefcb368185:15
  | fa | @ | api.js?onload=__iframefcb368185:8
  | A | @ | api.js?onload=__iframefcb368185:15
  | r.<computed> | @ | api.js?onload=__iframefcb368185:15
  | x.<computed> | @ | api.js?onload=__iframefcb368185:15
  | (anonymous) | @ | cb=gapi.loaded_0:1
```

#### Relevant Code:

```
const firebaseUI = new firebaseui.auth.AuthUI(firebase.auth());
const firebaseUiConfig = {
  callbacks: {
    signInSuccessWithAuthResult: function (authResult, redirectUrl) {
      var userIsNew = authResult.additionalUserInfo.isNewUser;
      if(userIsNew){
        addUserToFirebase();
      }
      return false;
    },
    uiShown: () => {
      document.querySelector('#loader').style.display = 'none';
    },
  },
  signInFlow: 'popup',
  signInSuccessUrl: 'signup.html',
    signInOptions: [
        {
            provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
            customParameters: {
                prompt: 'select_account'
            }
        }
    ],
  credentialHelper: firebaseui.auth.CredentialHelper.NONE,
};
firebaseUI.start('#firebaseui-auth-container', firebaseUiConfig);
```

**Comment by rachelmyers** [comment]
Despite the quality of your connection, based on this description, this does seem like a network problem rather than a problem in the library. I'm closing this issue for now. If you can provide steps to reliably reproduce this problem on a stable internet connection, please reopen and provide steps to reproduce. We welcome community contributions via Pull Requests if you'd like to improve the library's network fault tolerance or error messaging.

**Comment by mogwely** [comment]
@rachelmyers why would you close the ticket? it's not solved.
As you can see in the network tab screenshot, all the other requests succeed without a problem, except for the iframe request. The internet connection is stable and this issue is not affecting one machine, it's affecting thousands of users in different locations. How am I supposed to give you steps to reproduce the problem if the problem does not follow any pattern and fails with a generic error message.
If all network requests to firebase, and to other services, pass 100% without a problem except for this 1 request, then why would you assume a problem with the internet connection? Clearly that is a bug that throws a 'network error' while the underlying cause is unrelated.

**Comment by kalpthakkar** [comment]
I am too facing the same issue :(
I am using the iframe and javascript addeventListner method with it.
I have observed that when I am only keeping iframe, all auth services are working properly (with event listener commented) but when I uncomment it, the problem again starts showing up.

Uncaught Error: Network Error at iframewrapper.js:124
