### ISSUE TITLE
API-created user can't sign in with email link if disableSignUp status true

### ISSUE THREAD

**Issue by kenara** [firebase/firebaseui-web#848]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20
  * Browser version: Latest Chrome, Firefox
  * Firebase UI version: 4.0.8
  * Firebase SDK version: 8.2.9

#### Steps to reproduce:

I created a user with the Firebase Admin Python module 3.2.1 like so:
`auth.create_user(email=email, display_name=name, photo_url=profile_image_url)`

A user is created but when attempting to sign in is presented with a message,
`newuser@example.com is not authorized to view the requested page.`

A similarly-created user, if given a password, can sign in but is prompted for the password. 
However, I wish to use email link sign-in.

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem

        signInOptions: [
          {
            provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
            signInMethod: firebase.auth.EmailAuthProvider.EMAIL_LINK_SIGN_IN_METHOD,
            disableSignUp: {
              status: true,
              adminEmail: '',
              helpLink: 'https://example.com/welcome'
            },
          },
        ],

```

**Comment by bojeil-google** [comment]
When you create a user with just an email, the user is not considered an email link user. The email user has to sign in with email link first. Unfortunately, there is no way to label the user as email link on creation via the admin SDK.

We use `fetchSignInMethodsForEmail` API in FirebaseUI to check if the email is associated with a sign in method. If not, we consider the user new and disable sign up. When we call this with the user's email in this case, I believe it will not return any results. We need to confirm this.

Assigning to @xil222 to investigate.

**Comment by xil222** [comment]
Hi @kenara, could you try 
auth.create_user(email=email, emailVerified=true, display_name=name, photo_url=profile_image_url)
notice: do not provide password parameter.

Here is the explanation:
emailPassword and emailLink are two different methods although they have same providerId, 
If you set up password parameter(that is for sign up emailPassword method), when you click sign in with email in FirebaseUI and entering the email, it would be recognized as an emailPassword(and proceed if you enable this method in signInOptions).
 
From what I know, if we manually signup an account with emailLink using Firebase SDK library, we need to verify it through a email link.

In Firebase admin library, I think the rules that emailLink needs to be verified may still apply,
Therefore, setting emailVerified to true could help in this case.

Let me know if that is not working.

**Comment by kenara** [comment]
Hi @xil222, sadly, that did not work. 

This is the resulting user after adding emailVerified:

```
{
  "uid": "zEcuOW2vR2abcdYS1V4FodoNTz0I3",
  "email": "newuser2@example.com",
  "emailVerified": true,
  "displayName": "newuser2",
  "photoURL": "https://letters.noticeable.io/N15.png",
  "disabled": false,
  "metadata": {
    "lastSignInTime": null,
    "creationTime": "Fri, 14 May 2021 07:59:51 GMT"
  },
  "tokensValidAfterTime": "Fri, 14 May 2021 07:59:51 GMT",
  "providerData": []
}
```
and here is a 'good' user that I added after commenting out `disableSignUp`:

```
{
  "uid": "YNQgh0MeNKabcd513bo09v4VpiF2",
  "email": "newuser3@example.com",
  "emailVerified": true,
  "photoURL": "https://letters.noticeable.io/N7.png",
  "disabled": false,
  "metadata": {
    "lastSignInTime": "Fri, 14 May 2021 08:10:06 GMT",
    "creationTime": "Fri, 14 May 2021 08:10:06 GMT"
  },
  "tokensValidAfterTime": "Fri, 14 May 2021 08:10:06 GMT",
  "providerData": [
    {
      "uid": "newuser3@example.com",
      "email": "newuser3@example.com",
      "photoURL": "https://letters.noticeable.io/N7.png",
      "providerId": "password"
    }
  ]
}
```
The good user has complete `providerData` and a `lastSignInTime`. Strangely, `providerId` is "password" even though email link was used.

Would there be a way to update the user with a cloud function to make whatever change the system needs to allow the user to sign in as an email link user?

**Comment by kenara** [comment]
Well, I found a solution that works for me but it is a workaround.

I already have a cloud function to notify users that their account has been created. 

So I added,

```
  var actionCodeSettings = {
    url: 'https://example.com/welcome',
    handleCodeInApp: true,
  };  

  const link =  await admin.auth().generateSignInWithEmailLink(user.email, actionCodeSettings);

```

to the function, and they now get a link to complete their account setup. 

In my implementation, '/welcome' is just an alias for home page but landing there opens the `firebaseui-auth-container` where the message "Confirm your email to complete sign in" is shown. It's a quite natural flow.

I hesitate to say that this issue is a bug. I think my use case for `disableSignUp` is typical. We respond to requests and send out invites; then create the accounts with custom claims and JWTs that need to be added individually server-side. Finally, we need to advise users that their account is ready. Perhaps an improved version of this approach, published as sample code, could be added somewhere in the doc.

**Comment by xil222** [comment]
Glad you found the solution and thanks for your feedback. @kenara 

For one question above, can we add `emailLink` to the `signInMethods` array?
Yes, we can add emailLink to signInMethods, see the snippet in the link: https://github.com/firebase/firebaseui-web#email-link-authentication

Since `disableSignUp` config is used to disable user from signing up on their own, we usually use the Firebase Admin library to createUsers when setting `disableSignUp.status` to true, and we could say the `disableSignUp` config is designed to be compatible with Firebase Admin Library.

For your suggestion of updating the doc, it could be a little confusing to developers if directly put `generateSignInWithEmailLink()` into README.md since that is Firebase Admin API. We would consider adding information/links about Firebase Admin Library next to the `disableSignUp` config to let developers know they're related in README.md instead.

**Comment by kenara** [comment]
> The reason that your API-created user was not allowed to sign in, I think that only applied for emailLink provider(requires a verified user) which requires a link verification process, but not for password(in your 2nd comment, 2nd case).

This is the case that resulted in an unexpected behavior, and that will affect anyone who, like me, creates a user through the API and limits sign-in method to email link only. The developer needs to know that `generateSignInWithEmailLink()` will be required for the user to log in until this is changed. It's not enough to simply inform the user that their account has been created - they need the link!

**Comment by xil222** [comment]
Hey @kenara ,
I think what you said make sense, but to this point:

> `generateSignInWithEmailLink()` will be required for the user to log in until this is changed.

is unrelated to FirebaseUI but Firebase Admin SDK, so it is not reasonable to add notice for Firebase Admin SDK inside FirebaseUI Readme.
From your description, the factor affects your development Firebase Admin SDK [document](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth-1) may not indicate the information you need. Therefore, I would recommend go to that link click **send feedback** in the top right.
