### ISSUE TITLE
hash prop is lost during the redirect from accountchooser

### ISSUE THREAD

**Issue by rstormsf** [firebase/firebaseui-web#85]
when I use hash mode for my SPA app, my hash route is lost during the redirect to accountchooser
https://www.accountchooser.com/redirect.html#localhost:8080
then it comes back as http://localhost:8080/?mode=select#/

while ideally it would preserve hash route so my SPA won't be broken

**Comment by rstormsf** [comment]
here is some workaround that I used in my project. 
https://github.com/rstormsf/friendsmap/blob/master/src/router.js#L8

**Comment by mhuebert** [comment]
Similarly, query params are also lost.
eg/
`my-app.com/register?specialRequiredCode=123`
-> AccountChooser ->
`my-app.com/register?mode=select`

**Comment by bojeil-google** [comment]
In the config, add the following parameter:
widgetUrl: 'https://my-app.com/register?specialRequiredCode=123'

After redirect from accountchooser.com back to app, you will be redirected to:
https://my-app.com/register?specialRequiredCode=123&mode=select

**Comment by bojeil-google** [comment]
This should be fixed in 2.0.0:  https://github.com/firebase/firebaseui-web/releases/tag/v2.0.0
