### ISSUE TITLE
Auth.onCustomClaimsChange - to  immediately react for customClaims changes on web site.

### ISSUE THREAD

**Issue by pumanitro** [firebase/firebaseui-web#854]
**Is your feature request related to a problem? Please describe.**
I would like to immediately react to changing the access level of already logged-in users in a shared environment.
Shared environment means other users can disable access to given resources for me and I would like to block this access with customClaims, but them are refreshed at maximum 1h.

**Describe the solution you'd like**
Auth.onCustomClaimsChange - new observer which let me react to changes in custom claims from frontend side to manage user access immediately.

**Describe alternatives you've considered**
1.  I would need to retrieve new customClaims every time I do any action in my big application to see if I have access to it which uses tons of internet resources for big app and big amount of users.
2. Retrieve new customCalims in 5 min. loop to have only 5 min. window period for stolen session etc. which is still not significant. (`currentUser.getIdToken(true)`)
3. Do not access Firestore/Storage directly from Frontend but create additional backend proxy.

**Comment by bojeil-google** [comment]
Hey @pumanitro, FirebaseUI is more focused on providing a drop-in UI for sign-in built on top of the core JS sdk. This capability is better suited for a cloud function (ideally server side), independent of UI. I would suggest you file a [feature request](https://firebase.google.com/support) for it.

**Comment by patryk-janik-ellipsis** [comment]
@bojeil-google but how I could react on customClaimChanges even on cloud function. I could not find any support for this functionality in the API doc.

**Comment by bojeil-google** [comment]
Hey @patryk-janik-ellipsis, the cloud function to trigger on claims changes doesn't exist yet. I am saying that ideally, that would be the best way to support it (via a cloud function).
