### ISSUE TITLE
Setting `signInOptions.disableSignUp.status = true` for `GoogleAuthProvider` still allows new users to register.

### ISSUE THREAD

**Issue by davidbielik** [firebase/firebaseui-web#859]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.4
  * Browser version: Chrome 91
  * Firebase UI version: 4.8.0
  * Firebase SDK version: 8.6.8

### [REQUIRED] Describe the problem

Setting `signInOptions.disableSignUp.status = true` for `GoogleAuthProvider` does not work as expected and still allows new users to register.

#### Steps to reproduce:

1. Initialize using the following signInOptions:

```
signInOptions: [
    {
      provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      scopes: ["https://www.googleapis.com/auth/userinfo.email"],
      disableSignUp: {
        status: true,
      },
    }
]
```

2. Try to sign up via Google with a new account

#### Relevant Code:

Expected: New users can not sign up with this provider set to disabled

Actual: New users can sign up and create new account with this provider.

Note: the option does work as expected with email provider.

**Comment by xil222** [comment]
The disableSignUp config only supports for email provider [https://github.com/firebase/firebaseui-web#configure-email-provider](url).
For your case there're 2 options:
1. If you want to disable users signing up for all providers, you can try FirebaseUI version v4.8.1, set 
adminRestrictedOperation field status [https://github.com/firebase/firebaseui-web#configuration](url), you can see that in an example of [demoApp](https://fir-ui-demo-84a6c.firebaseapp.com/).
Basically by setting up adminRestrictedOperation field in uiConfig [https://github.com/firebase/firebaseui-web/blob/04fbd80ace683f769dccee797758ad9a9209179d/demo/public/widget.html#L72](url), you can control users to sign up.
2. If you only want to disable Google SignUp meanwhile allow other providers for example, Email/Password for signing up. This require take much more work. You can try out blocking function: First, setting up cloud function for turn downing specific requests you want to reject, then in GCP dashboard go to Identity Platform -> Settings  -> Triggers -> BeforeCreate, attach the Cloud Function to BeforeCreate, more reference in [https://cloud.google.com/identity-platform/docs/blocking-functions](url)

**Comment by davidbielik** [comment]
Thanks @xil222 very helpful response!

Can I convert this to a feature request, then?

**Comment by xil222** [comment]
@davidbielik Lmk if the new feature can solve your problem.

**Comment by davidbielik** [comment]
@xil222 I see in the docs it mentions:

> When sign-up is disabled in the project settings, this should be set to `true`. Setting this to `true` without disabling sign-up in the project settings will not have any effect.

Where would I find this project setting? I've searched all the firebase settings and don't see anything like this.

**Comment by xil222** [comment]
@davidbielik 
![Screen Shot 2021-07-16 at 1 10 01 PM](https://user-images.githubusercontent.com/22864922/126003534-21a9d1b6-aa21-4704-9ef0-7636d7904bd4.png)

**Comment by davidbielik** [comment]
Thanks @xil222 looks like this feature is beyond a simple Firebase integration (it's a separate API I need to enable). If that's the case, it might be worth clarifying the conditions to use it in the docs.

**Comment by xil222** [comment]
@davidbielik Thanks for the advice, we'll make it more clear in the doc.

**Comment by xil222** [comment]
this has been fixed in:
https://github.com/firebase/firebaseui-web/pull/871
