### ISSUE TITLE
CSS appears not to be compiled correctly

### ISSUE THREAD

**Issue by gmaslov** [firebase/firebaseui-web#86]
`firebase-ui.css` contains some statements like `@def BLACK_ALPHA_12 [...]`. Those def statements remain in the compiled `dist/firebaseui.css` shipped with the firebaseui-1.0.0 NPM module, and don't actually work correctly when served to a browser (latest Chrome on Linux).

Workaround was to compile firebase-ui.css myself using closure-stylesheets.jar before running the firebaseui-web build.

(Apologies if I've made a silly mistake here; not very familiar with CSS stuff. But the current compiled CSS does produce warnings from Chrome and invisible input-box text unless I do this.)

**Comment by channing-google** [comment]
Fixed in 2.0.0
