### ISSUE TITLE
Facing export error of firestore from firebase/app

### ISSUE THREAD

**Issue by Jassi10000** [firebase/firebaseui-web#864]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase UI version: _____
  * Firebase SDK version: _____

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

I have integrated the firebase in a react project , but am facing an error which goes like :

``` Attempted import error: 'firestore' is not exported from 'firebase/app' (imported as 'firebase'). ```

Can you pls tell how should I deal with this  ?

**Comment by bojeil-google** [comment]
Hey @Jassi10000 your error does not appear to be related to FirebaseUI-web. For Firestore issues, please use the [firebase-js-sdk](https://github.com/firebase/firebase-js-sdk) repo and provide more information on how to reproduce the issue.
