### ISSUE TITLE
Trigger Verification email upon registration?

### ISSUE THREAD

**Issue by MrVentzi** [firebase/firebaseui-web#865]
Seems a few different code snippets laying around but not quite clear what the proper way to do it is.

We are using the firebaseUI with gcip-iap.

Currently we have a blocking cloud function to check the email domains.

```
const gcipCloudFunctions = require('gcip-cloud-functions');

const authClient = new gcipCloudFunctions.Auth();

exports.beforeCreate = authClient.functions().beforeCreateHandler((user, context) => {
  //Get allowed domains list
  var allowedDomains = process.env.ALLOWED_DOMAINS;
  //Get the domain from user's email
  var emailArr = user.email.split("@");
  var domain = emailArr[1];


  //Check if the domain of the email signing up is allowed
  if (allowedDomains.indexOf(domain) === -1) {
    //Throw a bad request if domain is not found
    console.log("INFO: Domain " + domain + " NOT ALLOWED!");
    console.log("INFO: Account creation denied for: " + user.email);
    throw new gcipCloudFunctions.https.HttpsError('invalid-argument', `Unauthorized`);
  }
});
```
Which works nicely, however, anyone can just register with a domain from the "allowed" list as there is no email verification sent... 

If we then end up adding a blocking function that will check if they are verified, then we can be sure that the user's email belongs to them.

e.g. 

```
const gcipCloudFunctions = require('gcip-cloud-functions');

const authClient = new gcipCloudFunctions.Auth();

exports.beforeSignIn = authClient.functions().beforeSignInHandler((user, context) => {
  if (user.email && !user.emailVerified) {
    console.log("INFO: Sign in blocked. " + user.email + " email not verified.")
    throw new gcipCloudFunctions.https.HttpsError(
      'invalid-argument', `Email needs to be verified before access is granted.`);
   }
 });
```

However, the problem is, how do we trigger the default verification email that can be sent by Firebase and using the default template from https://console.firebase.google.com/u/0/project/project-name/authentication/emails.

The snippet here is a bit confusing as it is using the admin sdk and impossible to debug in the cloud function? https://cloud.google.com/identity-platform/docs/blocking-functions#requiring_email_verification_on_registration

Some people online say that the verification email needs to be triggered from the client side, is that true?

```
           beforeSignInSuccess: (user) => {
                // Do additional processing on user before sign-in is
                // complete.
                user.sendEmailVerification()
                .then(() => {
                    // Email verification sent!
                    // ...
                });
                return Promise.resolve(user);
```
We can send it through the client, but feels weird. What is the best way to do it?

Any help would be greatly appreciated and apologies if not the correct repo to raise this. Thanks

**Comment by bojeil-google** [comment]
Hey @MrVentzi, this is not the right repo for these kind of inquiries but I will answer your question.

You can use the client SDK to send the email. You would need to sign in the user with a custom token (`signInWithCustomToken`) in the blocking function, and then trigger the email verification (`user.sendEmailVerification()`). Or you can use the Admin SDK and [generate the email link](https://firebase.google.com/docs/auth/admin/email-action-links#generate_email_verification_link) and send it on your own. The latter is recommended here as the former is designed for client side usage.
