### ISSUE TITLE
New user sign up fails with message: "This operation is restricted to administrators only"

### ISSUE THREAD

**Issue by bgirschig** [firebase/firebaseui-web#872]
## Environment
Debian GNU/Linux rodete
Google chrome 92.0.4515.131
Firebase 8.8.1
Firebase SDK 8.8.1 (?)
Firebase UI 4.8.1

#### Steps to reproduce:
- Create a firebase project
- Enable authentication methods 'email' and 'google'
- Register a new web app in firebase, and replace the `firebaseConfig` object in the code below with the real `firebaseConfig` object
- Add `localhost` as an authorized domain (same issue happens on a normal domain, but this is easier to test)
- Open the code below in a browser
- Try to login

#### What happens:
The login process looks like it's going to work, but then fails with the following message:
![image](https://user-images.githubusercontent.com/6248734/128559974-d5a02a34-0312-474d-b1ee-d4c71641a7f6.png)

There are no errors in the console or in the network requests.

Note: This used to work, so there are some users already in the firebase users list
These can sign-in fine. The issue seems to only affect new users signing up

#### Relevant Code:

```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <div id="firebaseui-auth-container"></div>

  <script src="https://www.gstatic.com/firebasejs/8.8.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.8.1/firebase-auth.js"></script>  
  <script src="https://www.gstatic.com/firebasejs/ui/4.8.1/firebase-ui-auth.js"></script>
  <link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/4.8.1/firebase-ui-auth.css" />

  <script>
    const firebaseConfig = {
      apiKey: '', // API_KEY
      authDomain: '', // AUTH_DOMAIN
      databaseURL: '', // DATABASE_URL
      projectId: '', // PROJECT_ID
      storageBucket: '', // STORAGE_BUCKET
      messagingSenderId: '', // MESSAGING_SENDER_ID
      appId: '', // APP_ID
    };
    firebase.initializeApp(firebaseConfig);

    const ui = new firebaseui.auth.AuthUI(firebase.auth());
    ui.start('#firebaseui-auth-container', {
      signInOptions: [
        firebase.auth.GoogleAuthProvider.PROVIDER_ID,
        firebase.auth.EmailAuthProvider.PROVIDER_ID,
      ],
      signInSuccessUrl: 'http://localhost:8080/welcome.html'
    });
  </script>
</body>
</html>
```

**Comment by xil222** [comment]
Hi @bgirschig,
Are you asking about 1. How to fix new users not able to sign up. 2. What can we do to improve error message?
If asking about 1, since I have no information about your project, probably dont have a straight answer.
If asking about 2:

Since you are using FirebaseUI version v4.8.1, you can try out setting adminRestrictedOperation field status in configuration:
see [from](https://github.com/firebase/firebaseui-web#configuration)
basically by setting up adminRestrictedOperation field in uiConfig for example:

```
var uiConfig = {
        ...
        'signInOptions': [
          {
            provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
            // Required to enable ID token credentials for this provider.
            clientId: CLIENT_ID
          },
          {
            provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
            signInMethod: getEmailSignInMethod(),
            disableSignUp: {
              status: getDisableSignUpStatus()
            }
          },
        ],
        ...
        'adminRestrictedOperation': {
          status: getAdminRestrictedOperationStatus()
        }
      };
```

Then you can configure a more informative error page instructing users to operations to sign up.
similar response in [#859](https://github.com/firebase/firebaseui-web/issues/859)

**Comment by bojeil-google** [comment]
I think @bgirschig it looks like you disabled new user sign up. This is why you are seeing this error.

**Comment by bgirschig** [comment]
Thank you both for your answers.
I was looking for a "enable/disable user signup option" in the firebase console, but it was in the gcloud console (Identity platform)

I'm so sorry for the spam...
Again, thank you both for the fast response
