### ISSUE TITLE
Signing in with duplicate email when only one provider specified

### ISSUE THREAD

**Issue by nikcheerla** [firebase/firebaseui-web#880]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS Big Sur, 11.2
  * Browser version: Google Chrome 91
  * Firebase UI version: 5.0.0
  * Firebase SDK version: 8.1.0

#### Steps to reproduce:
Create a firebase UI object with signInOptions equal to just the EmailAuthProvider provider, and try to login with an email that has already been used by another provider (i.e Google provider). Strangely enough, when you login with that email, it doesn't show the UI that you normally see when you reuse emails, i.e the below UI:

<img width="300" alt="Screen Shot 2021-09-14 at 12 36 11 PM" src="https://user-images.githubusercontent.com/7505423/133385002-ccb6c89a-8d57-4d4a-8e69-fc4c51ca8ca8.png">

instead the FirebaseUI object just disappears completely and nothing is shown. I don't see any callback or way to handle this case, aside from specifying multiple providers which I would like to avoid. How do I fix this?

#### Relevant Code:

```javascript
const firebaseUIConfig = {
    signInFlow: "popup",
    signInOptions: [firebase.auth.EmailAuthProvider.PROVIDER_ID],
    callbacks: {
      // Avoid redirects after sign-in.
      signInSuccessWithAuthResult: () => false,
      signInFailure: async (error: firebaseui.auth.AuthUIError) => {
        console.warn("[login-window] ERROR" + error);
      },
    },
  };
var ui = new firebaseui.auth.AuthUI(firebase.auth());
ui.start('#firebaseui-auth-container', uiConfig);
```

to create a firebaseUI object with just one provider.

**Comment by bojeil-google** [comment]
On success, `signInSuccessWithAuthResult` callback is triggered. It doesn't do anything in your case (based on your snippet). You need to tell it what to do on successful sign in, or supply a sign in success URL.

**Comment by nikcheerla** [comment]
@bojeil-google I get that, I intentionally made the code simple to show as an MVP but we do do something when we sign in successfully (specifically we move past the login page). Edited the snippet to reflect this. The issue is that when you sign in with a "duplicate email" that was used by a different provider such as the GoogleProvider, you don't get a signInSuccess callback OR a signInFailure callback, the widget just silently disappears. We have no way to detect these cases and tell our users to sign in with a different email.

**Comment by bojeil-google** [comment]
I don't understand what you mean. Usually, the user is notified that they have an existing account and need to sign in with Google. Once they sign in with Google, the sign in flow is completed and the `signInSuccessWithAuthResult ` callback is triggered.

**Comment by nikcheerla** [comment]
@bojeil-google Yup, usually that happens. For some reason, it doesn't happen if you only specify a single provider (the EmailAuthProvider), and the FirebaseUI widget just disappears with no error.
