### ISSUE TITLE
Issue Redirect user to another page after login 

### ISSUE THREAD

**Issue by zakblacki** [firebase/firebaseui-web#888]
It's a silly question, but I'd like to redirect user to another page after login instead of reloading page how do I achieve this in app.js
without losing user auth

**Comment by zakblacki** [comment]
Any follow on up on this please ?

**Comment by bojeil-google** [comment]
Hey @zakblacki please check the [README](https://github.com/firebase/firebaseui-web). The documentation provides multiple snippets on this. You can use the `signInSuccessWithAuthResult` callback or just use `signInSuccessUrl`. This action will take place on sign in success.

If you need to run some async function before redirecting, you can just return false to prevent the premature redirect before the operation finishes. You also have to wait for the promise to resolve before you close the window. After that resolves, you can explicitly do the redirect.
