### ISSUE TITLE
Login with Biometrics

### ISSUE THREAD

**Issue by danijorda1** [firebase/firebaseui-web#890]
Hi guys,

Nowadays Security is a must for most Fintech Applications. Most of them have embeded many security steps suchs as 2FA and/or biomentrics checks for login.

Would it be possible to embed a Biometric login feature within your UI Flow? i.e. when Users sign up ask them if they'd like to make the process quicker next time and ask for fingreprint or face recognition sign up. 

Any time users try to login again they can do it easily with finger print/face recognition.

Thanks.

Daniel

**Comment by bojeil-google** [comment]
Hey @danijorda1, feel free to file an official [feature request](https://firebase.google.com/support) for this. FIDO 2.0 would be the right vehicle for this.

**Comment by jhuleatt** [comment]
FirebaseUI can't implement this functionality unless Firebase Authentication supports it. Current open public feature requests:

- https://firebase.uservoice.com/forums/948424-general/suggestions/46647016-support-authentication-with-passkeys
- https://firebase.uservoice.com/forums/948424-general/suggestions/46591561-webauthn-integration-for-authentication
