### ISSUE TITLE
Support for Firebase Session Cookies 

### ISSUE THREAD

**Issue by treeder** [firebase/firebaseui-web#893]
Looks like the Firebase JS lib has cookie support now: https://firebase.google.com/docs/auth/admin/manage-cookies

Any plans to support that?

**Comment by bojeil-google** [comment]
Hey @treeder the way these session cookies typically work is you sign in with FirebaseUI or any other custom UI mechanism using the Firebase Auth client SDK, using no client side persistence and then pass the ID token to your server where you exchange it for longer lives session cookies. You can still use FirebaseUI with that. So you can use this feature now already.

**Comment by masibw** [comment]
Hi, it is true that we can use `signInSuccessWithAuthResult` to describe the process after authentication, but it does not accept Promise. So I think you can't send the token to the server and wait for the cookie to come back.

Is there a better way?
