### ISSUE TITLE
Upgraded to firebaseui 6 and now anon user delete is acting differently

### ISSUE THREAD

**Issue by jaunt** [firebase/firebaseui-web#900]
* Browser version: Chrome Version 95.0.4638.69 
  * Firebase UI version: 6.0
  * Firebase SDK version: 9.2 Compatibilty Mode

This is in regards to handling anonymous-upgrade-merge-conflict.

Before I updated to 6, I was on firebaseui 5.0 and firebase 8.x.  Deleting the anon user as shown in the code below silently did so, and the new user was logged in successfully.

After updating to 6.0 and 9.2, when that anonymousUser.delete() is called, it actually logs out the new user, triggering my entire sign-out logic.  I.e.  onAuthStateChanged is called with user==null

Is this expected behaviour?  If so I'm not sure how I can delete the unneeded anon user in this case.

```
           signInFailure: (error) => {
                // For merge conflicts, the error.code will be
                // 'firebaseui/anonymous-upgrade-merge-conflict'.
                if (
                  error.code != "firebaseui/anonymous-upgrade-merge-conflict"
                ) {
                  return Promise.resolve();
                }

                // The credential the user tried to sign in with.
                let cred = error.credential;
                let anonymousUser = firebase.auth().currentUser;
                let newUser;

                return firebase
                  .auth()
                  .signInWithCredential(cred)
                  .then(function (data) {
                    newUser = data.user;
                    me.signInComplete(newUser, {
                      upgraded: false,
                      merged: true,
                    });
                    anonymousUser.delete(); // causes new user to be signed out!
                  })
```

**Comment by xil222** [comment]
There isn't change in the callback logic, I'll take a look to see if there is logic changes in Firebase compat library

**Comment by xil222** [comment]
Hey @jaunt could you also file a bug here [firebase-js-sdk](https://github.com/firebase/firebase-js-sdk/issues)? Looks like above example is more related to usage of Firebase web sdk.

**Comment by jaunt** [comment]
@xil222 Ok will do.  Thanks for looking at this!

**Comment by jaunt** [comment]
Hi @xil222, so I opened a bug at firebase-js-sdk and it was eventually closed saying I should be using linkWithCredential.  It doesn't make sense to me, but anyway if it is correct, I guess the firebase-ui example I copied from needs to be updated?  Here is the explanation:

https://github.com/firebase/firebase-js-sdk/issues/5705

**Comment by xil222** [comment]
ok, sure. thanks for pointing that out!

**Comment by xil222** [comment]
@jaunt Are you still having the problem? Looks like the link you sent me is closed. I can try take a look later if not fixed.
As you said `LinkedWithCredential` isn't supposed to be there if `autoUpgradeAnonymousUsers` set to true.

**Comment by jaunt** [comment]
@xil222 I haven't had time to verify that the anon users are being deleted without the delete command, but at least removing it no longer logs my current user out!  Will let you know if I see anything strange.  Thanks for the help.
