### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by bilalsoomro** [firebase/firebaseui-web#91]
Hi, I am trying to run the demo but hitting an error. I am on windows 10 and ran my cmd program as administrator. Don't think I have missed a step so some help would be appreciated. Thanks!

Here are the steps I followed....
1) Cloned the repo
2) Ran "npm install" in the root.
3) Ran "npm build" in the root
3) Made a copy of the sameple-config.js in the /demo/public folder and renamed it to config.js with my own firebase config settings which I got when I clicked web setup in my project's firebase console.
4) Went back to root folder and ran "npm run demo"

This is when I hit the error. Here is the npm-debug log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'demo' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'predemo', 'demo', 'postdemo' ]
5 info lifecycle firebaseui@0.0.0~predemo: firebaseui@0.0.0
6 silly lifecycle firebaseui@0.0.0~predemo: no script for predemo, continuing
7 info lifecycle firebaseui@0.0.0~demo: firebaseui@0.0.0
8 verbose lifecycle firebaseui@0.0.0~demo: unsafe-perm in lifecycle true
9 verbose lifecycle firebaseui@0.0.0~demo: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\sunny\Downloads\firebaseui-web-master\node_modules\.bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GitExtensions\;C:\Android\sdk;C:\Android\sdk\platform-tools;C:\Android\sdk\tools;C:\OpenSSL\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Git\bin;C:\Python27;C:\Program Files\nodejs\;C:\Users\sunny\AppData\Local\Microsoft\WindowsApps;C:\Users\sunny\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle firebaseui@0.0.0~demo: CWD: C:\Users\sunny\Downloads\firebaseui-web-master
11 silly lifecycle firebaseui@0.0.0~demo: Args: [ '/d /s /c', 'npm run build && ./buildtools/run_demo.sh' ]
12 silly lifecycle firebaseui@0.0.0~demo: Returned: code: 1  signal: null
13 info lifecycle firebaseui@0.0.0~demo: Failed to exec demo script
14 verbose stack Error: firebaseui@0.0.0 demo: `npm run build && ./buildtools/run_demo.sh`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid firebaseui@0.0.0
16 verbose cwd C:\Users\sunny\Downloads\firebaseui-web-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "demo"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error firebaseui@0.0.0 demo: `npm run build && ./buildtools/run_demo.sh`
22 error Exit status 1
23 error Failed at the firebaseui@0.0.0 demo script 'npm run build && ./buildtools/run_demo.sh'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the firebaseui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && ./buildtools/run_demo.sh
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs firebaseui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls firebaseui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jalajc** [comment]
I suspect its pertaining to node/npm rather than firebase-ui.
You may want to search over line 21 error code. Just a guess, permission to
directory or assigned port could be issue.

**Comment by TMSCH** [comment]
Hi @sunny061,
We currently do not support building FirebaseUI under Windows. Several scripts that are required only run on Unix platforms, i.e. Mac OS or Linux.
Sorry for the inconvenience.

**Comment by sunny061** [comment]
Hi @TMSCH ,
Oh. Looking at the "run_demo.sh" script, I see it is just copying the dist folder that is generated by "npm run build"  to the /demo/public which I did manually and kind of got it working although the CSS seemed a bit off for some reason. But thanks for the info anyway.

**Comment by xgeoff** [comment]
I'm on a mac and I got the exact same error. I'll see if I can build it and copy it manually.

**Comment by TMSCH** [comment]
Hi @xgeoff, I'm sorry you had a bad experience. Is there any chance you could provide the logs displayed when the `npm run build` command fails? That would be very helpful for us.

Many of the node modules we require are meant to compile the source in the most efficient way possible which adds overhead in development environment installation, but provides great benefits once deployed. There's also a few dependencies meant for testing.

The `node_modules` may contain a lot more folders, but these are indirect dependencies that we do not control.

**Comment by danialhr** [comment]
I have to same problem with xgeoff.

Unable to npm run demo. 

This fails npm run build && ./buildtools/run_demo.sh

btw i was told to do 
npm ERR!  Please include the following file with any support request:
npm ERR!     /Users/danialharis/.npm/_logs/2017-03-08T03_08_37_686Z-debug.log

how am i able to access the log to share it?

**Comment by bradparks** [comment]
This can also pop up if you haven't run

Run "npm install" in the root of the project!

**Comment by nicolasgarnier** [comment]
Closing since this is a bit old. Please if you are facing such issue make open a new issue and provide as much details as possible especially what's written in the console.

And yes, make sure to run `npm install` :)
