### ISSUE TITLE
Support switching Google identities

### ISSUE THREAD

**Issue by LDMFD** [firebase/firebaseui-web#919]
**Is your feature request related to a problem? Please describe.**

When multiple Google identities are authenticated in the same browser session, and one of them has been used to sign into the developer's app, there is no way to choose a different identity for a subsequent login of the app.

The work-around is to navigate to google.com, go to the profile menu, and click "Sign out". This is non-obvious to the user, and takes them away from the app, increasing attrition.

**Describe the solution you'd like**

When multiple Google identities are present in the session, but none are logged into the app, the popup should always show, rather than defaulting to the previously used.

**Describe alternatives you've considered**

**Additional context**

Repro steps:

1. Sign in to two different Google accounts at once (for example, sign in to Gmail, then in the same tab sign in to a second Gmail account).
2. Go to the demo app https://fir-ui-demo-84a6c.firebaseapp.com/
3. Click "Sign in with Google", sign in
4. Realize that you used the wrong Google account.
3. Click "Sign out"
5. Click "Sign in with Google"
6. Notice that you have no way of choosing a different Google account.

**Comment by lisajian** [comment]
Hi, thanks for filing this issue! We are unable to promise any timeline for this, but if others also have this issue, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: [b/217763383](https://b.corp.google.com/issues/217763383))

**Comment by sam-gc** [comment]
I'm unable to reproduce this. When I sign out and click "Sign in with Google" again, I am prompted to select an account as expected. What browser are you seeing this in?

**Comment by LDMFD** [comment]
Agreed, I'm also unable to repro. Will close, and re-open if I can repro again. Thanks for looking at this!
