### ISSUE TITLE
'X-Frame-Options' set to 'DENY' ?

### ISSUE THREAD

**Issue by ahsan87** [firebase/firebaseui-web#92]
I am seeing the following error while trying to login.

Refused to display 'https://www.facebook.com/login.php?skip_api_login=1&api_key=<apikey>_&display=page&locale=en_US&logger_id=<someid>' in a frame because it set 'X-Frame-Options' to 'DENY'.

Any idea what is going on ?

**Comment by ahsan87** [comment]
This happens if I am not logged in to facebook from the browser.

**Comment by TMSCH** [comment]
Hi @ahsan87,

Could you be more specific? When does the error happen, at which point in the flow, what are you using to sign-in? Can you also provide the full stack trace?

Thanks

**Comment by bojeil-google** [comment]
Hey @ahsan87 are you trying to embed firebaseUI in an iframe? If so that will not work. Please provide more details.

**Comment by ahsan87** [comment]
Apparently, due to a domain hosting change, https://... was no longer working and it had to be www.... This caused the issue to manifest. I assume an error page or something similar should have been shown and  it had a iframe deny in its header ?

Anyways, closing this. Thanks.
