### ISSUE TITLE
This issue does not have all the information required by the template.  Looks like you forgot to fill out some sections.  Please update the issue with more information.

### ISSUE THREAD

**Issue by mvdpas** [firebase/firebaseui-web#933]
This issue does not have all the information required by the template.  Looks like you forgot to fill out some sections.  Please update the issue with more information.

_Originally posted by @google-oss-bot in https://github.com/firebase/firebase-tools/issues/4246#issuecomment-1057940110_

**Comment by mvdpas** [comment]
Na het installeren van de firebase CLI en het init commando, liep ik vast bij het deployen, waarschijnlijk van mijn project augustus-vine-141617.
De error was een waarde (((https://github.com/firebase/firebase-tools/issues/4246)))

Fout functies pre-implementeren fout opdracht beëindigd met een niet-nul exit-code 1

Ik weet niet wat dit betekend en wil graag firebase deployen., kan iemand helpen?? 
Bedankt Mark

**Comment by mvdpas** [comment]
Na het installeren van de firebase CLI en het init commando, liep ik vast bij het deployen, waarschijnlijk van mijn project augustus-vine-141617.
De fout was:  "

Fout functies pre-implementeren fout begonnen met een niet-nul exit-code 1     "

Ik weet niet wat dit bedoeld en wil graag firebase deployen., kan iemand helpen??
Bedankt Mark

**Comment by annzimmer** [comment]
This seems like a user error - you can reach out to https://firebase.google.com/support
