### ISSUE TITLE
signInSuccessWithAuthResult is not called on Mac ios

### ISSUE THREAD

**Issue by imseppl** [firebase/firebaseui-web#934]
### [REQUIRED] Describe your environment

  * Operating System version: iPadOS 15,3,1
  * Browser version: Safari 15,3,1
  * Firebase UI version: 6.0.1
  * Firebase SDK version: web only

### [REQUIRED] Describe the problem

signInSuccessWithAuthResult is not called with the following code. The same code works on all other operating systems and web browsers except for Mac.

#### Steps to reproduce:

After log in, the signInSuccessWithAuthResult is not called 

#### Relevant Code:

// FirebaseUI config.
var uiConfig = {
	signInSuccessUrl: 'https://www.hamburgermap.com/auth/firebase/callback',
	signInOptions: [
	  // Leave the lines as is for the providers you want to offer your users.
	  firebase.auth.GoogleAuthProvider.PROVIDER_ID
	],
	callbacks:{
		signInSuccessWithAuthResult: function(authResult, redirectUrl) {
		  // Process result. This will not trigger on merge conflicts.
		  // On success redirect to signInSuccessUrl.
		  alert("Loggedin"); //this is never called
		  return true; //return true to redirect to signInSuccessUrl
		},
		signInFailure: function(error) {
			// Some unrecoverable error occurred during sign-in.
			// Return a promise when error handling is completed and FirebaseUI
			// will reset, clearing any UI. This commonly occurs for error code
			// 'firebaseui/anonymous-upgrade-merge-conflict' when merge conflict
			// occurs. Check below for more details on this.
			//return handleUIError(error);
			alert("Sign in failed: " + error);
		},
		uiShown: function() {
			// The widget is rendered.
		}
	},
	// tosUrl and privacyPolicyUrl accept either url string or a callback
	// function.
	// Terms of service url/callback.
	tosUrl: 'https://www.hamburgermap.com/terms',
	// Privacy policy url/callback.
	privacyPolicyUrl: function() {
	  window.location.assign('https://www.hamburgermap.com/privacy');
	}
};

// Initialize the FirebaseUI Widget using Firebase.
var ui = new firebaseui.auth.AuthUI(firebase.auth());
// The start method will wait until the DOM is loaded.
ui.start('#firebaseui-auth-container', uiConfig);

**Comment by imseppl** [comment]
Full code is here: https://www.hamburgermap.com/login

**Comment by sargison** [comment]
Same issue here.  Tried to two weeks to upgrade many components to see if this solves.  The callback uiShown is being called.  signInSuccessWithAuthResult is not being called and nor is signInFailure.

Works in Safari - just doesn't work on iOS Native App on phone or Xcode iPhone emulator.

**Comment by sargison** [comment]
I fixed this issue implementing a version of: https://harryherskowitz.com/2021/08/23/firebase-capacitor.html

let auth
  if (Capacitor.isNativePlatform()) {
    auth = initializeAuth(app, {
      persistence: indexedDBLocalPersistence
    })
  } else {
    auth = getAuth()
  }
  return auth

**Comment by jahertor** [comment]
> I fixed this issue implementing a version of: https://harryherskowitz.com/2021/08/23/firebase-capacitor.html
> 
> let auth if (Capacitor.isNativePlatform()) { auth = initializeAuth(app, { persistence: indexedDBLocalPersistence }) } else { auth = getAuth() } return auth

Okay, this workaround works, but now the flow on Android ends redirecting to "http://localhost/login" on a new tab, so it can't be opened in the app itself. In Safari iOS it ends on "about:blank", no idea where it attempts to redirect. I tried to change the `signInSuccessUrl` to some internal deep link, but the redirect doesn't change.

**Comment by rejhgadellaa** [comment]
I just ran into the same issue as the OP. Both Sign in with Google and Apple options do not work in Safari on macOS (13.1) and iOS (16.2). Not native/capacitor apps, I'm seeing this in the browser, across multiple projects. After I sign in / approve the oauth, the Firebase UI just sits there and does nothing.

I am 100% sure my configs worked fine in the past, so not sure something changed and "we're doing it wrong" or that firebaseui login has been broken for *every single Safari user* (which, on iOS, probably means *every single iPhone user* because all browsers on iOS are required to use the WebKit-engine) since *March 2022* ?? 😬

@jamesdaniels, I see you're assigned to this ticket. Could you please have a look / provide us with an update?

Example: https://bsl-web-app.rejh.nl

Relevant config:

```javascript
{
    callbacks: {
      signInSuccessWithAuthResult: () => true,
    },
    signInFlow: 'redirect',
    signInOptions:[
      firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      // ...
    ],
    signInSuccessUrl: location.href,
}
```

**Comment by rejhgadellaa** [comment]
Just a quick workaround for anyone coming across this: It seems like `signInFlow: 'redirect'` is broken in Safari. Change it to `'popup'` and it seems to work just fine:

```javascript
{
    callbacks: {
      signInSuccessWithAuthResult: () => true,
    },
    signInFlow: 'popup', // <<===== this works
    signInOptions:[
      firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      // ...
    ],
    signInSuccessUrl: location.href,
}
```

You could possibly do some browser detection and only do popup for Safari:

```javascript
{
  signInFlow: isSafari() ? 'popup' : 'redirect',
}
```

**Comment by alexmingoia** [comment]
The workaround doesn't work for me. I woke up to angry customer saying login doesn't work. I haven't changed the code in months. Tried upgrading libraries, still doesn't work.

`signInSuccessWithAuthResult` is no longer called after successful sign-in with Google and redirect. I'm using Safari, 9.13.0 firebase-app-compat and firebase-auth-compat, and 6.0.2 of firebase-ui. Error callbacks are not called with. authStateChanged is called with null for user object.

**Comment by Chuiantw1212** [comment]
I downgraded modules to legacy versions to make it worked.
`    "firebase": "^7.24.0",
    "firebaseui": "^4.8.1",`

**Comment by jhuleatt** [comment]
We believe this was resolved https://github.com/firebase/firebaseui-web/issues/977#issuecomment-1316084766

 firebase-ui 6.0.2 has been published on npm - https://www.npmjs.com/package/firebaseui
