### ISSUE TITLE
clarify script inclusion

### ISSUE THREAD

**Issue by arpowers** [firebase/firebaseui-web#94]
Hey there, 
Just getting started playing with this... however there is a conflict... Firebase core recommends including the init script in the footer after HTML... while you guys recommend including the UI script AFTER the init script in the header. 

Does this mean we should move the init script to the header? 

Should we move the UI JS to the footer, and keep the css in head? Confusing.

**Comment by bojeil-google** [comment]
Hey @arpowers. FirebaseUI for web doesn't have an official policy on this.
