### ISSUE TITLE
Login with email/password in IPAD save as home screen does not show keyboard to enter email address

### ISSUE THREAD

**Issue by shivna-2020** [firebase/firebaseui-web#941]
### [REQUIRED] Describe your environment

  * Operating System version:  IOS 15.4 in IPAD
  * Browser version:  Page https://fir-ui-demo-84a6c.firebaseapp.com/ added to Home Screen using Safari
  * Firebase UI version:  6.0.1  and version used in https://fir-ui-demo-84a6c.firebaseapp.com/
  * Firebase SDK version:  9.6.8 and version used in https://fir-ui-demo-84a6c.firebaseapp.com/

#### Steps to reproduce:

1. Visit  https://fir-ui-demo-84a6c.firebaseapp.com/ using Safari in IPAD with IOS version 15.4.
2. Touch on Share icon and then [Add to Home Screen]
3. Launch the FirebaseuiDemo icon added to the home screen
4. Touch [Sign in with email] red button
5. Sign in with email box is shown to to enter Email. No keyboard is shown to enter the email address.
6. Reboot the IPAD. Try step 3, the keyboard may show up if you are lucky!

![firebase-ui-web-no-keyboard-in-ios](https://user-images.githubusercontent.com/66382980/158589789-5d431276-a0d1-4e60-b79e-18a9a15a862d.png)

**Comment by peterfriese** [comment]
Hello - I was able to reproduce this by connecting a physical keyboard to my iPad (resp. using Apple's new Universal Control to use my computer's keyboard as a virtual keyboard connected to the iPad). This seems to be independent of whether you are in FirebaseUI's email field or in any other input field: the on-screen keyboard even doesn't show up when putting the cursor into the browser's address bar.

You can bring back the on-screen keyboard by tapping on the input control that appears at the bottom of the screen when you place the cursor in an input field. Then, tap on the language selector on the left hand side, and choose "Show Keyboard" from the pop-up menu.
