### ISSUE TITLE
Unable to login with Apple Sign In

### ISSUE THREAD

**Issue by santiimageen** [firebase/firebaseui-web#943]
Hi!
I am trying to offer Apple Sign In in my app but I am getting 400 error in the call to https://identitytoolkit.googleapis.com/v1/accounts:signInWithIdp with the message of "invalid client".
I have reviewed many times all the parameters (service ID, key, etc), both in Firebase console and Apple Developer Console and I am pretty sure that they are all right.
You can reproduce the problem going to https://app.imageen.net and trying to login with an apple account.
Could you give me a tip of what am I doing wrong, please?
Thanks!

**Comment by kachuuuu** [comment]
same. solved?

**Comment by sam-gc** [comment]
@santiimageen there may be a problem with the configuration for your app. Please contact [Firebase Support](https://firebase.google.com/support) directly so they can assist you with your project in particular
