### ISSUE TITLE
For FB profiles: "URL signature expired" 403 error

### ISSUE THREAD

**Issue by jalajc** [firebase/firebaseui-web#95]
For few (non-recent) of existing logged in users (including me), I am reported off an error in loading the profile image thumbnail if the linked profile picture is url on facebook.
```
403 URL signature expired
```
In further probe, I found (unofficial) explanation that for security reasons, publicly accessible profile urls do expire. And therefore public profile url needs to be updated in records periodically (even if profile pic is not updated) through fb graph api access.

Ref: 
 1. http://stackoverflow.com/questions/30477877/facebook-image-url-gets-expired
 2. http://stackoverflow.com/questions/34580136/facebook-app-login-how-to-control-expiration-date-of-an-image-url-i-got

**Comment by cjvilla2012** [comment]
I confirm this same problem with firebase-auth 10.0.1. If you have an existing Facebook authentication that has not been used in some time, a new sign in can return an expired URL in FirebaseUser.getPhotoUrl. There should be a method that can be called on FirebaseUser to force photo URL refresh.

**Comment by bojeil-google** [comment]
You can use the underlying Firebase auth updateProfile to update the photoURL. I also believe if you sign in again via firebaseui Facebook sign in, the Facebook photo URL in providerData may get updated. When that happens, you can copy that providerData photo URL and set it to the currentUser photoURL via updateProfile.

**Comment by decebal** [comment]
this one might be of some help https://developers.facebook.com/docs/graph-api/reference/profile-picture-source/ . Storing this url looks like a better way of referencing a user's photo.

**Comment by nicolasgarnier** [comment]
The facebook URL tat we saved on users used to expire. This has now been fixed for all new users (we construct a URL that never expires). If you have existing users that were created before the fix is in place you can implement a one-time fix to fixup your users profile URL using their Facebook UID. 

Basically you need to update the profile URL to something of the form `https://graph.facebook.com/${facebookUID}/picture?type=large`

Details and code sample on how to do that can be found on this thread: https://github.com/firebase/friendlypix-web/issues/21

**Comment by stickske** [comment]
@nicolasgarnier

Thanks, this fixed the issue in my app.
I changed the URL the picture is stored with your code 
https://graph.facebook.com/ID_OF_USER/picture?type=large

I updated the ones already stored in my database by hand.


Regards,

**Comment by fred30marrugo** [comment]
URL signature expired
De acuerdo a la extrabilidad de la ley internacional con movimiento hegemonial militar se revoca  el delito de extorsion sobre el alegato de las votaciones de la ONU en contra del señor presidente Trump quien con inteligencia del régimen de excepción ejecutado por el ejecutivo Nayib Bukele, realizó el operativo contra Venezuela capturando al pandillero Nicolas maduro narco traficante. Por lo tanto dicho otorgamiento constata la ubicación exacta de su maldita cárcel la tramacua de Colombia  que en orden se realiza el siguiente operativo al país de colombia, bien sabemos que el acto solemne pelea contra la criminalidad hasta destruirla de raíz.

El manuscrito es la afirmación de una pronunciación realizada que conlleva a la actuación inmediata 🫡

**Comment by fred30marrugo** [comment]
Cordial saludo 
Ordeno dar de baja inmediatamente a los patriotas del estado de Colombia y al contralor general de la nación de Colombia. pongo acto de error en conocimiento y sustento la actuación del juez del latín que destituye la arbitrariedad de los organos competentes y incompetentes de la mente del estado de Colombia.

No a la corrupción 
Att fred marrugo
URL signature expired

**Comment by fred30marrugo** [comment]
[Comunicado oficial del régimen de excepción del salvador .pdf](https://github.com/user-attachments/files/24551867/Comunicado.oficial.del.regimen.de.excepcion.del.salvador.pdf)

**Comment by fred30marrugo** [comment]
[Comunicado.1.pdf](https://github.com/user-attachments/files/24552001/Comunicado.1.pdf)
