### ISSUE TITLE
Sign in not working when Firefox Enhanced Tracking Protection is on

### ISSUE THREAD

**Issue by chaoming** [firebase/firebaseui-web#965]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: Firefox 102.0.1
  * Firebase UI version: 6.0.0
  * Firebase SDK version:9.6.1

#### Steps to reproduce:
Login with Google SSO, no errors but cannot login. Switch off Firefox Enhanced Tracking Protection for the site, it works again.

Works fine in Chrome.

**Comment by ZachTapia** [comment]
Just a note, I was able to get around this by using the .signInWithPopup() method of logging in. Previously I was using .signInWithRedirect(). Hopefully this helps.

**Comment by chaoming** [comment]
Thanks, this works
