### ISSUE TITLE
internal error occur 

### ISSUE THREAD

**Issue by zirho** [firebase/firebaseui-web#97]
Hello, 

I found a bug or an error.

I could successfully log in by just refresh the page (or the component) and try again.

How to reproduce

1. use mobile device (I used android & chrome)

2. open chrome incognito tab or other browser's privacy mode. (this is to make sure there's no cookie or session)

3. go to https://fir-ui-demo-84a6c.firebaseapp.com/

4. click facebook login. 

5. don't login, just tap 'back button' on your phone.

6. click google login.

7. internal error occur 

![image](https://cloud.githubusercontent.com/assets/1251296/22176238/880a8646-dfba-11e6-8f9b-9aad85c9ebf6.png)

**Comment by TMSCH** [comment]
Hi @zirho,
Thanks for bringing this to our attention! We will look into it.

**Comment by mahmoudfelfel** [comment]
I'm using firebase-ui web, and many users have reported the same issue, any idea how can I fix it?

**Comment by mahmoudfelfel** [comment]
If it helps, most of the users who reported the issue were using safari or chrome on iOS 10

**Comment by bojeil-google** [comment]
We are working on a fix for @zirho's issue. We were able to replicate in android chrome.

**Comment by bojeil-google** [comment]
Hey @zirho, I forgot to update the thread. The issue you were encountering should have been fixed more than a week ago. It should be fixed automatically (a reload should be enough).

**Comment by zirho** [comment]
Hey @bojeil-google. 

cool! Let me poke around a little bit more.
I really appreciate your work.

**Comment by bojeil-google** [comment]
Hey @zirho we fixed another issue that could have potentially been causing this in version 4.0.0. Check the thread: https://github.com/firebase/firebaseui-web/issues/98
