### ISSUE TITLE
ERROR: No Firebase App '[DEFAULT]' has been created. Using Firebae UI CDN

### ISSUE THREAD

**Issue by tuberelevant2** [firebase/firebaseui-web#980]
I'm new to JS. I'm using CDN (<script> tags method) to install FirebaseUI. But I always get the following error:
Uncaught FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app-compat/no-app).
    at s (firebaseNamespaceCore.ts:102:27)
    at Object.e [as auth] (firebaseNamespaceCore.ts:153:31)
    at firebase.html:50:52
![image](https://user-images.githubusercontent.com/104287304/195652529-1209cb44-2050-4dac-9455-941897d14d41.png)

Here's my entire Code. I have only a single HTML file in VS Code. 
`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Sample FirebaseUI App</title>
    <script src="https://www.gstatic.com/firebasejs/9.1.3/firebase-app-compat.js"></script>
    <script src="https://www.gstatic.com/firebasejs/9.1.3/firebase-auth-compat.js"></script>
  
    <script type="module">
      // Import the functions you need from the SDKs you need
      import { initializeApp } from "https://www.gstatic.com/firebasejs/9.12.1/firebase-app.js";
      import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.12.1/firebase-analytics.js";
      // TODO: Add SDKs for Firebase products that you want to use
      // https://firebase.google.com/docs/web/setup#available-libraries
    
      // Your web app's Firebase configuration
      // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    const firebaseConfig = {
        apiKey: "xxx",
        authDomain: "xxx",
        projectId: "xxx",
        storageBucket: "xxx",
        messagingSenderId: "xxx",
        appId: "xxx",
        measurementId: "xxx"
    };
    
      // Initialize Firebase
    const app = initializeApp(firebaseConfig);
    const analytics = getAnalytics(app);
    </script>
    <script src="https://www.gstatic.com/firebasejs/ui/6.0.1/firebase-ui-auth.js"></script>
    <link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/6.0.1/firebase-ui-auth.css" />
    <script type="text/javascript">
      // FirebaseUI config.
      var uiConfig = {
        signInSuccessUrl: 'https://www.syllabuzz.in/',
        // tosUrl and privacyPolicyUrl accept either url string or a callback
        // function.
        // Terms of service url/callback.
        tosUrl: 'https://www.syllabuzz.in/',
        // Privacy policy url/callback.
        privacyPolicyUrl: function() {
          window.location.assign('https://www.syllabuzz.in/');
        }
      };

      // Initialize the FirebaseUI Widget using Firebase.
      var ui = new firebaseui.auth.AuthUI(firebase.auth());
      // The start method will wait until the DOM is loaded.
      ui.start('#firebaseui-auth-container', {
         signInOptions: [
           firebase.auth.PhoneAuthProvider.PROVIDER_ID
         ],
      // Other config options...
      });
    </script>
  </head>
  <body>
    
    <h1>Welcome to My Awesome App</h1>
    <div id="firebaseui-auth-container"></div>
  </body>
</html>
`

I am getting the analytics in my Firebase dashboard. But it says app is not defined. I tried `console.log(app)` and found that it works just below cont declaration but doesn't work  in the line `var ui = new firebaseui.auth.AuthUI(firebase.auth());` It shows error when it's reading `auth()`
I hope you just have to copy/paste this code to replicate the issue.
Thanks in advance.

**Comment by Jerit3787** [comment]
Hi,
Firebase v9 Modular is still not supported in this release of Firebase UI. Please use Firebase v9 Compat instead. :)
